### ISSUE TITLE
Error!

### ISSUE THREAD

**Issue by bubundas17** [r0oth3x49/udemy-dl#1]
Error in Python 3.6 windows 10 and windows server 2016

![screenshot_20170503100721](https://cloud.githubusercontent.com/assets/26280146/25648330/54851dee-2fe8-11e7-8d63-127d97ec0183.png)

**Comment by r0oth3x49** [comment]
@bubundas17 Currently its only compatible with Python 2.7 Soon 'll make it work on both python 2.x and 3.x, till then you have to install Python 2.7 to use this utility and it is also mention in README.md..
