### ISSUE TITLE
Unable to extract login-form form

### ISSUE THREAD

**Issue by Feelav** [r0oth3x49/udemy-dl#101]
Hello, I got this error after I tried to download a course.
![error-udemy-dl](https://user-images.githubusercontent.com/34603115/36115689-22de7100-1034-11e8-9d9a-d28d1c0b3006.jpg)

I double checked my login and password. Any recommendations please?

**Comment by DazzaB73** [comment]
I can confirm this behaviour too.  I was able to download one of my courses yesterday morning (2018-02-11) but was unable to download another course yesterday afternoon.

**Comment by r0oth3x49** [comment]
@Feelav,@DazzaB73 check issue #98 i have already discussed the solution to this.
