### ISSUE TITLE
udemy-dl.py can not login, error  "Unable to extract login-form form"

### ISSUE THREAD

**Issue by pppedrillo** [r0oth3x49/udemy-dl#107]
__                               ____
   __  ______/ /__  ____ ___  __  __      ____/ / /
  / / / / __  / _ \/ __ `__ \/ / / /_____/ __  / /
 / /_/ / /_/ /  __/ / / / / / /_/ /_____/ /_/ / /
 \__,_/\__,_/\___/_/ /_/ /_/\__, /      \__,_/_/
                           /____/
                                 Version : 0.3
                                 Author  : Nasir khan(r0ot h3x49)
                                 Visit   : https://github.com/r0oth3x49

[*] : Downloading webpage..
[*] : Extracting course information..
[*] : Downloading 'D:\'
[*] : Trying to login as (*******@blahblah.com)...
[-] Unable to extract login-form form
Traceback (most recent call last):
  File ".\udemy-dl.py", line 936, in <module>
    main()
  File ".\udemy-dl.py", line 852, in main
    udemy.ExtractAndDownload(path=outto)
  File ".\udemy-dl.py", line 303, in ExtractAndDownload
    self.login()
  File ".\udemy-dl.py", line 40, in login
    extract_info.login(self.username, self.password)
  File "D:\Temp\udemy-dl-py-r00t\udemy\_extractor.py", line 147, in login
    login_form      = self._fill_login_form(login_popup, username, password)
  File "D:\Temp\udemy-dl-py-r00t\udemy\_extractor.py", line 98, in _fill_login_form
    login_form = self._form_hidden_inputs('login-form', webpage)
  File "D:\Temp\udemy-dl-py-r00t\udemy\_extractor.py", line 88, in _form_hidden_inputs
    return _hidden_inputs(form)
  File "D:\Temp\udemy-dl-py-r00t\udemy\_utils.py", line 80, in _hidden_inputs
    html = re.sub(r'', '', html)
  File "C:\Program Files (x86)\Python\Python36-32\lib\re.py", line 191, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object

**Comment by Pheinte** [comment]
Same problem here :/

**Comment by r0oth3x49** [comment]
@pppedrillo ,@Pheinte check #98 , #100 .

**Comment by ronkiwest** [comment]
Not Working after 1 hour or after several days - same problem as hamidgh83.What to do?

**Comment by pppedrillo** [comment]
> What to do?

Ask @r0oth3x49 to fix this not just link with another (random) issue and close

**Comment by ronkiwest** [comment]
@pppedrillo This is the same issue bugging a lot of users ( and they are reporting it in many threads) so obviously r0oth3x49 knows this and already fixed it - no point tagging him while he was busy fixing it.

**Comment by ssarwar92** [comment]
Hi I am getting the issue as below 👍 
[-] Unable to extract login-form form

**Comment by enankobh** [comment]
I am getting this error (tried several times) with the updated code "Udemy Says : 403 Forbidden retry after few minutes ..." @r0oth3x49 can you please provide the solution.
