### ISSUE TITLE
Files with "?" or special chars in Windows (Bash)

### ISSUE THREAD

**Issue by oscarinom** [r0oth3x49/udemy-dl#11]
udemy-dl can't save or load files with "?" or special characters in their video names

Can you take a look into this pls ?

**Comment by r0oth3x49** [comment]
@oscarinom thanks for the report. actually windows have  reserve  characters such as <>/\?:"* which we are not allowed to use in file naming thats why udemy-dl is just replacing that with _ to download file normally.
for more details you can check this link.
[Naming Files, Paths, and Namespaces (Windows) - MSDN - Microsoft](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx)
let me know if i 'm not getting your point.

**Comment by oscarinom** [comment]
Oh, well sorry about the delay of my reply.

But more specific, in every video that have a "?" I'm having this (obv, can't continue downloading)

Using Bash for Windows 10
![image](https://user-images.githubusercontent.com/7976341/31954444-fabeaf02-b8bb-11e7-9a79-6870856744c8.png)
