### ISSUE TITLE
Password Error

### ISSUE THREAD

**Issue by serhattsnmz** [r0oth3x49/udemy-dl#112]
I have capitalized letters in my password such as "D", "A", "C"...
When I write my password, It doesn't get these chracters.

**Comment by r0oth3x49** [comment]
@serhattsnmz i will fix this ASAP.

**Comment by r0oth3x49** [comment]
@serhattsnmz can you please verfity this fix works for you?

**Comment by serhattsnmz** [comment]
Works for me. Thanks.
