### ISSUE TITLE
Can't download

### ISSUE THREAD

**Issue by ipkpjersi** [r0oth3x49/udemy-dl#117]
Hi,

Hold on, before you close this issue because it's a duplicate or it's been solved, I must inform you that is not the case.

I downloaded the latest code from the master branch which includes your latest commit 13 hours ago and I still get an error.

Here's the error: ![](https://i.imgur.com/7XWllNL.png)

**Comment by hxor** [comment]
![capture](https://user-images.githubusercontent.com/18319373/36337728-078040ec-13d0-11e8-8efe-544aca68f9fc.PNG)
Same as me. this error is unable to extract form login. 
i hope fix this ASAP

**Comment by r0oth3x49** [comment]
@ipkpjersi , @hxor did you try to install **requests[security]** or **pyOpenSSL** separately?

## *sudo -H pip install requests[security] --upgrade*
or 
## *sudo -H pip install pyOpenSSL --upgrade*

@ipkpjersi  **did you tried of one of these solutions  ( **[#110](https://github.com/r0oth3x49/udemy-dl/issues/110#issuecomment-366187456), [#98](https://github.com/r0oth3x49/udemy-dl/issues/98#issuecomment-365200934), [#98](https://github.com/r0oth3x49/udemy-dl/issues/98#issuecomment-366187397), [#113](https://github.com/r0oth3x49/udemy-dl/issues/113#issuecomment-366234478)** )**

if any one of these works for you let me know.

**Comment by ipkpjersi** [comment]
I tried the first command: `sudo -H pip install requests[security] --upgrade` and it worked great, seems my dependencies were out of date. You can close this now if you want. Thanks!

**Comment by hxor** [comment]
how about windows user ?

**Comment by r0oth3x49** [comment]
@hxor did you even tried to install before asking this question?
