### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by SiteDesignUSA** [r0oth3x49/udemy-dl#118]
I've tried running this on a CentOS system with all the dependencies installed. Python v2.66

Here's the error:

```
  File "udemy-dl.py", line 57
    return {k: v for k, v in ((k, self.clean_dict(v)) for k, v in udemy_dict.items()) if v}
                   ^
SyntaxError: invalid syntax
```

Thanks

**Comment by r0oth3x49** [comment]
@SiteDesignUSA i can give you a suggestion to upgrade your python version this might be syntax issue with py2.6 i have only tested this against >= 2.7.xx
