### ISSUE TITLE
Multiple Line Problem

### ISSUE THREAD

**Issue by serhattsnmz** [r0oth3x49/udemy-dl#119]
![02](https://user-images.githubusercontent.com/20886290/36345977-5c49732a-1446-11e8-85c4-5220b7219bd9.png)
![01](https://user-images.githubusercontent.com/20886290/36345978-5c7910ee-1446-11e8-82bb-da76065ea36d.png)

Before that, the downloading line was one line. But now, these are multiple lines.
What is the problem? 
( Linux Mint - 18.3 / Both python2.7 and python3.6 )

**Comment by r0oth3x49** [comment]
@serhattsnmz this is not the problem simply increase the columns of terminal problem will be solved.
have a look.
![screenshot from 2018-02-17 21-57-41](https://user-images.githubusercontent.com/11024397/36348863-c62e28b8-149a-11e8-9855-85dbc4668aa7.png)
![screenshot from 2018-02-17 21-57-51](https://user-images.githubusercontent.com/11024397/36348865-cac67e7a-149a-11e8-9c9b-f53679c41059.png)
