### ISSUE TITLE
Slow downloading speed

### ISSUE THREAD

**Issue by ameerhamza619** [r0oth3x49/udemy-dl#120]
![image](https://user-images.githubusercontent.com/26673662/36348996-5998a260-149e-11e8-89ab-d452ca992acd.png)

I am facing slow download speed issue as shown in the image above. It is not the problem with my internet speed, as I am able to download the same file with 100 kB/s with IDM.

**Comment by r0oth3x49** [comment]
@ameerhamza619 this is not an issue but a network problem may be. you can save links to download using IDM or any other downloader you like.
