### ISSUE TITLE
Connection error : make sure your internet connection is working.

### ISSUE THREAD

**Issue by hxor** [r0oth3x49/udemy-dl#121]
I've try #117 and #44 but still not work. any idea ?
![screen shot 2018-02-19 at 4 37 07 pm](https://user-images.githubusercontent.com/18319373/36371019-6d474b72-1593-11e8-9573-88c266afbdc7.png)

![screen shot 2018-02-19 at 4 41 43 pm](https://user-images.githubusercontent.com/18319373/36371150-d33232b2-1593-11e8-9fca-de2d920a490b.png)

**Comment by r0oth3x49** [comment]
@hxor which OS r u using?
