### ISSUE TITLE
Unable to extract login-form form

### ISSUE THREAD

**Issue by helenyau0** [r0oth3x49/udemy-dl#122]
I have upgraded all the other modules, but when entering `sudo pip install requests[security] --upgrade` I'm getting this error.
![screen shot 2018-02-19 at 10 19 07 am](https://user-images.githubusercontent.com/22210582/36392108-873b684a-155e-11e8-83d3-ecbfaa07a2d5.png)

**Comment by r0oth3x49** [comment]
@helenyau0 have a look at issue [#117](https://github.com/r0oth3x49/udemy-dl/issues/117#issuecomment-366421627). which OS r u using?

**Comment by helenyau0** [comment]
@r0oth3x49 I'm using mac. I've tried entering both commands `sudo -H pip install requests[security] --upgrade` and  `sudo -H pip install pyOpenSSL --upgrade` and I'm still getting errors

**Comment by r0oth3x49** [comment]
@helenyau0 the error shows some kind of permissions error why don't you switch to root & then try installing the? don't install six. try below commands.
 - sudo -H pip install unidecode --upgrade
 - sudo -H pip install requests --upgrade
 - sudo -H pip install colorama --upgrade
 - sudo -H pip install pyOpenSSL --upgrade

if your current user is root then don't use sudo -H only pip install will do the work for you.

**Comment by helenyau0** [comment]
I'm having trouble installing pyOpenSSL. It has something to do with six that I'm unsure about. 
![screen shot 2018-02-19 at 12 42 57 pm](https://user-images.githubusercontent.com/22210582/36396342-79990850-1572-11e8-8bc6-98ffca282d63.png)

**Comment by helenyau0** [comment]
I tried the command `sudo -H pip install pyOpenSSL --upgrade --ignore-installed six` which fixed the install error but when attempting to login using udemy-dl, I am still getting the same login error.

**Comment by helenyau0** [comment]
@r0oth3x49 switching to root then installing dependencies also didn't work...

**Comment by r0oth3x49** [comment]
@helenyau0 did you tried udemy-dl with python3 may be it works. because for me on MAC it works fine. i cannot reproduce the error.

**Comment by helenyau0** [comment]
@r0oth3x49 I've been using python3 to download the courses. The program worked fine for me up until I disconnected from wifi one day while downloading a course.

**Comment by helenyau0** [comment]
@r0oth3x49 I solved the error. I was not specifying which python version to use in pip. If using python3 then module installs using pip should be specified as pip3. I switched to root then updated all modules using pip3 instead of pip

**Comment by r0oth3x49** [comment]
@helenyau0 great so i 'm going to close it now.

**Comment by tylerforesthauser** [comment]
Hello,

Unfortunately I'm running into this same issue and I've seen _ALL_ the issues opened with this problem and have tried all of the solutions I could find. I am running macOS 10.13.3. I've tried using the already-installed Python 2.7.10 and Python 2.7.14 & Python 3.6.4 both installed via Homebrew. None have worked. I've tried making sure all of the requirements are installed and up to date (using the respective pip, pip2 and pip3) with no success. 

```
$ python3 udemy-dl.py -u xxx@xxxxxx -p xxxxxx https://www.udemy.com/the-complete-nodejs-developer-course-2/ -r 1080 -o "~/Downloads/The Complete Node.js Developer Course (2nd Edition)"

              __                               ____  
   __  ______/ /__  ____ ___  __  __      ____/ / /  
  / / / / __  / _ \/ __ `__ \/ / / /_____/ __  / /   
 / /_/ / /_/ /  __/ / / / / / /_/ /_____/ /_/ / /    
 \__,_/\__,_/\___/_/ /_/ /_/\__, /      \__,_/_/     
                           /____/
                                 Version : 0.3
                                 Author  : Nasir khan(r0ot h3x49)
                                 Visit   : https://github.com/r0oth3x49


[*] : Downloading webpage..
[*] : Extracting course information..
[*] : Downloading 'the complete nodejs developer course 2'.
[*] : Trying to login as (xxx@xxxxxx)...
[-] Unable to extract login-form form
Traceback (most recent call last):
  File "udemy-dl.py", line 936, in <module>
    main()
  File "udemy-dl.py", line 868, in main
    udemy.ExtractAndDownload(path=outto, quality=res)
  File "udemy-dl.py", line 303, in ExtractAndDownload
    self.login()
  File "udemy-dl.py", line 40, in login
    extract_info.login(self.username, self.password)
  File "/Users/user/Downloads/udemy-dl/udemy/_extractor.py", line 147, in login
    login_form      = self._fill_login_form(login_popup, username, password)
  File "/Users/user/Downloads/udemy-dl/udemy/_extractor.py", line 98, in _fill_login_form
    login_form = self._form_hidden_inputs('login-form', webpage)
  File "/Users/user/Downloads/udemy-dl/udemy/_extractor.py", line 88, in _form_hidden_inputs
    return _hidden_inputs(form)
  File "/Users/user/Downloads/udemy-dl/udemy/_utils.py", line 80, in _hidden_inputs
    html = re.sub(r'<!--(?:(?!<!--).)*-->', '', html)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/re.py", line 191, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
```

Any help with this would HUGELY appreciated.

**Comment by tylerforesthauser** [comment]
Installed pip3 modules:

```
asn1crypto (0.24.0)
certifi (2018.1.18)
cffi (1.11.4)
chardet (3.0.4)
colorama (0.3.9)
cryptography (2.1.4)
idna (2.6)
ndg-httpsclient (0.4.4)
pip (9.0.1)
pyasn1 (0.4.2)
pycparser (2.18)
pyOpenSSL (17.5.0)
requests (2.18.4)
setuptools (36.5.0)
six (1.11.0)
termcolor (1.1.0)
Unidecode (1.0.22)
urllib3 (1.22)
wheel (0.30.0)
```

**Comment by helenyau0** [comment]
@tylerforesthauser hm... I fixed the error when I switched to root then updated only these dependencies: 
- sudo -H pip install unidecode --upgrade
- sudo -H pip install requests --upgrade
- sudo -H pip install colorama --upgrade
- sudo -H pip install pyOpenSSL --upgrade

Have you done this already?

**Comment by tylerforesthauser** [comment]
@helenyau0 Yes, unfortunately I have, with no luck.

```
$ sudo -H pip3 install unidecode --upgrade
Requirement already up-to-date: unidecode in /usr/local/lib/python3.6/site-packages
$ sudo -H pip3 install requests --upgrade
Requirement already up-to-date: requests in /usr/local/lib/python3.6/site-packages
Requirement already up-to-date: urllib3<1.23,>=1.21.1 in /usr/local/lib/python3.6/site-packages (from requests)
Requirement already up-to-date: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.6/site-packages (from requests)
Requirement already up-to-date: idna<2.7,>=2.5 in /usr/local/lib/python3.6/site-packages (from requests)
Requirement already up-to-date: certifi>=2017.4.17 in /usr/local/lib/python3.6/site-packages (from requests)
$ sudo -H pip3 install colorama --upgrade
Requirement already up-to-date: colorama in /usr/local/lib/python3.6/site-packages
$ sudo -H pip3 install pyOpenSSL --upgrade
Requirement already up-to-date: pyOpenSSL in /usr/local/lib/python3.6/site-packages
Requirement already up-to-date: cryptography>=2.1.4 in /usr/local/lib/python3.6/site-packages (from pyOpenSSL)
Requirement already up-to-date: six>=1.5.2 in /usr/local/lib/python3.6/site-packages (from pyOpenSSL)
Requirement already up-to-date: idna>=2.1 in /usr/local/lib/python3.6/site-packages (from cryptography>=2.1.4->pyOpenSSL)
Requirement already up-to-date: cffi>=1.7; platform_python_implementation != "PyPy" in /usr/local/lib/python3.6/site-packages (from cryptography>=2.1.4->pyOpenSSL)
Requirement already up-to-date: asn1crypto>=0.21.0 in /usr/local/lib/python3.6/site-packages (from cryptography>=2.1.4->pyOpenSSL)
Requirement already up-to-date: pycparser in /usr/local/lib/python3.6/site-packages (from cffi>=1.7; platform_python_implementation != "PyPy"->cryptography>=2.1.4->pyOpenSSL)
```

**Comment by hxor** [comment]
I think this package need update or some fix.
Because I've trying with this instructor but still error.
using python3 in windows machine.

**Comment by ssarwar92** [comment]
Hi,
i am having all updated component 

pip install unidecode --upgrade
 pip install requests --upgrade
 pip install colorama --upgrade
pip install pyOpenSSL --upgrade

still i am getting error from few days as below 👍 

[-] Unable to extract login-form form

any one can help me here please.
