### ISSUE TITLE
Username and password

### ISSUE THREAD

**Issue by desarrollador2Navsat** [r0oth3x49/udemy-dl#123]
![sin titulo](https://user-images.githubusercontent.com/19977793/36395568-68f74428-157f-11e8-8b35-5ae4a87885cc.png)

Hi, I'm getting this error. My username and pass are both correct.

**Comment by r0oth3x49** [comment]
@desarrollador2Navsat did you cloned the most recent version? explain a bit more write complete command you are using.

**Comment by desarrollador2Navsat** [comment]
Sure, I'm using 


python udemy-dl.py -u user@domain.com -p p4ssw0rd COURSE_URL

like 

python udemy-dl.py -u bayron.picado@navsat.com -p ******** https://www.udemy.com/xamarin-forms-espanol/

and using the most recent option.

Thankyou!

**Comment by r0oth3x49** [comment]
@desarrollador2Navsat how can i reproduce this error.

**Comment by desarrollador2Navsat** [comment]
I don't know, the answer is: the username, password and course url are required. Is like I don't write them in console.

**Comment by r0oth3x49** [comment]
@desarrollador2Navsat have a look at issue #81 , i don't know what can be the problem so no fix for that until unless i cannot reproduce.
