### ISSUE TITLE
Not able to Download from Udemy (My Internet Connection is working fine)

### ISSUE THREAD

**Issue by nadeemkhan123** [r0oth3x49/udemy-dl#124]
[root@server udemy-dl]# python udemy-dl.py https://www.udemy.com/the-complete-jenkins-course-for-developers-and-devops/

              __                               ____
   __  ______/ /__  ____ ___  __  __      ____/ / /
  / / / / __  / _ \/ __ `__ \/ / / /_____/ __  / /
 / /_/ / /_/ /  __/ / / / / / /_/ /_____/ /_/ / /
 \__,_/\__,_/\___/_/ /_/ /_/\__, /      \__,_/_/
                           /____/
                                 Version : 0.3
                                 Author  : Nasir khan(r0ot h3x49)
                                 Visit   : https://github.com/r0oth3x49

[*] : Username : __________@gmail.com
[*] : Password : ************
[*] : Downloading webpage..
[*] : Extracting course information..
[*] : Downloading 'the complete jenkins course for developers and devops'.
[*] : Trying to login as (________@gmail.com)...
From cffi callback <function _verify_callback at 0x25b7a28>:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/OpenSSL/SSL.py", line 313, in wrapper
    _lib.X509_up_ref(x509)
AttributeError: 'module' object has no attribute 'X509_up_ref'
[-] : Connection error : make sure your internet connection is working.

**Comment by r0oth3x49** [comment]
@nadeemkhan123 you should install requirements properly. the error cause because of ssl. so you should either install/upgrade **requests[security]** or **pyOpenSSL**
