### ISSUE TITLE
Umlauts in filenames

### ISSUE THREAD

**Issue by NoMoreUsernamesAvailable** [r0oth3x49/udemy-dl#127]
Hi! Unfortunately all umlauts from the german language (ÄÖÜäöüß) gets "normalized" (=erased). Many of the lecture titles are harder to read because of this. Would it be possible to add umlauts to the allowed characters?

I tried this for a quick workaround: changing the `unicodedata.normalize` method in _sanitize.py from 'NFKC' to 'NFKD'. At least this gives me U instead of Ü or o instead of ö. But not an ideal result. Adding the umlauts to the `SLUG_OK` variable did not help at all.

Best regards

**Comment by r0oth3x49** [comment]
@NoMoreUsernamesAvailable currently i 'm working on new release i will look into that in next release.
