### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode characters in position 51-52

### ISSUE THREAD

**Issue by bharathgrk** [r0oth3x49/udemy-dl#13]
I'm having an issue while downloading the course [iOS 11 & Swift 4 - The Complete iOS App Development Bootcamp](https://www.udemy.com/ios-11-app-development-bootcamp/). The download stopped with the following error message: 

> Traceback (most recent call last):
  File "udemy-dl.py", line 646, in <module>
    main()
  File "udemy-dl.py", line 496, in main
    udemy.ExtractAndDownload(path=outto, quality=res, default=True)
  File "udemy-dl.py", line 356, in ExtractAndDownload
    f.write("[+] -- name {}\n[+] -- Visit {}\n".format(lecture_name, _url))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 51-52: ordinal not in range(128)

Running on python version 2.7.14 and macOS Sierra 10.12.6

Can you please look into it?

**Comment by r0oth3x49** [comment]
@bharathgrk thanks for trying this out. first of all can you please make sure you have an updated repo of udemy-dl and then try again the same course and post the Screenshot here. currently i don't have macOS Sierra i 'm using macOS Mavericks on which i have already tested and it works fine. BTW sorry for the late response. i will soon update the repo.

**Comment by jdsantiagojr** [comment]
Running into same issue on macOS Sierra 10.13 in docker container. Was trying to download ethereum-dapp course at 720p.

**Comment by bharathgrk** [comment]
Cloned the repo using the git clone command in your readme file and tried the download again with the same result. Attaching the screenshot below. Thanks for responding.

![screen shot 2017-10-31 at 12 21 01](https://user-images.githubusercontent.com/9738122/32210934-40ef4124-be36-11e7-9daa-9bc26ac32dde.png)

**Comment by selenafa** [comment]
```diff
diff --git a/udemy-dl.py b/udemy-dl.py
index cd9af9a..4ce9258 100644
--- a/udemy-dl.py
+++ b/udemy-dl.py
@@ -353,7 +353,7 @@ class UdemyDownload:
                         _external_links = "links-to-visit.txt"
                         print (fc + sd + "\n[" + fm + sb + "*" + fc + sd + "] : " + fg + sd + "Saving external links to file : {}".format(_external_links))
                         f = open(_external_links, "a")
 -                        f.write("[+] -- name {}\n[+] -- Visit {}\n".format(lecture_name, _url))
+                        f.write("[+] -- name {}\n[+] -- Visit {}\n".format(lecture_name, _url.encode("utf-8").strip()))
                         f.close()
                         print (fc + sd + "[" + fm + sb + "*" + fc + sd + "] : " + fg + sd + "Saved successfully..")
                     elif _url:

@@ -173,7 +173,7 @@ class UdemyDownload:
                         
                    if _url:
                        with open("%s.txt" % (course), "a") as f:
-                           f.write("[+] -- name : %s\n[+] -- link : %s\n" % (lecture_name, _url))
+                           f.write("[+] -- name : %s\n[+] -- link : %s\n" % (lecture_name, _url.encode("utf-8").strip()))
                            f.close()
            print (fc + sd + "[" + fm + sb + "+" + fc + sd + "] : " + fg + sd + "Saved successfully.")
                             

```
here is the solution of the problem.
note : I tested this and works well it can be merged

**Comment by r0oth3x49** [comment]
@bharathgrk as i said i 'm working on new release which has the patch for this error as well. sorry for the late response.

**Comment by selanium** [comment]
sorry r0oth3x49 can we speak in another place? like skype or telegram or yahoo. thanks

**Comment by r0oth3x49** [comment]
@selanium you can add me on fb. [r0oth3x49](https://www.facebook.com/r0oth3x49)

**Comment by r0oth3x49** [comment]
@bharathgrk issue is fixed now in new version.

**Comment by bharathgrk** [comment]
@r0oth3x49 new version worked like a charm, thanks for the fix.
