### ISSUE TITLE
Request the download of "Quiz or Quizzies" files

### ISSUE THREAD

**Issue by YaNgO15** [r0oth3x49/udemy-dl#135]
Hello Nazir,

Hello, the script udemy-dl-master seems great and almost complete, but I come to request a new function that I've seen in another script (udemy-dl-windows) that differentiates it, and is to download the files called "Quiz" of each course or section of course, and I would like it to be renamed in an orderly manner and not in an external folder, here I send you a screenshot.

Thanks!
![2](https://user-images.githubusercontent.com/34865634/36888215-84353d58-1dc2-11e8-86b6-ed5090b16201.png)

**Comment by r0oth3x49** [comment]
@YaNgO15 downloading quizzes is out of scope. i didn't added this intentionally. the course videos and other materials are enough to learn. You can take quizzes on the bases of that learning. so i 'm closing this now.

**Comment by YaNgO15** [comment]
Thank you very much for responding, it was a suggestion to add that add-on to the script.

**Comment by r0oth3x49** [comment]
@YaNgO15 thanks for your suggestion.
