### ISSUE TITLE
Error downloading file after pause.

### ISSUE THREAD

**Issue by Drovosek01** [r0oth3x49/udemy-dl#139]
During boot I pressed the left mouse button to put the download on pause. After ~ 10 minutes I pressed the space bar on the keyboard to continue downloading. But the file on which the pause was not downloaded completely. I opened it in the Explorer and there looked its size and the size was smaller than it should be. Also this video is not peremahival.

PS I just deleted the file and restarted the download and the problem was solved, but not all guess to do or not everyone will see that the file is not completely downloaded.

![image](https://user-images.githubusercontent.com/29478700/37052309-fed44458-2189-11e8-92db-e57e4f36f7ec.png)

**Comment by r0oth3x49** [comment]
@Drovosek01 i cannot i reproduce BTW, this is not the way to pause video if really want to pause simple terminate the session and when you run again the script will start from the same point. i m closing this is invalid.
