### ISSUE TITLE
Error No such file or directory

### ISSUE THREAD

**Issue by Drovosek01** [r0oth3x49/udemy-dl#140]
These errors occur during the course download process. I'm using the latest version of your program.

![image](https://user-images.githubusercontent.com/29478700/37053099-542eacca-218c-11e8-9ee6-d815e7c14c80.png)

**Comment by r0oth3x49** [comment]
@Drovosek01 i cannot explain the error which is already discussed so many times on windows you will face all the time same problem if the path is longer then specified path convention. read on Microsoft for that or check the older issues. closing this as dupliacte
