### ISSUE TITLE
Getting Below Mentioned Error

### ISSUE THREAD

**Issue by thedtech** [r0oth3x49/udemy-dl#144]
Microsoft Windows [Version 10.0.16299.248]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Users\Deepak>udemy-dl.py -u ********* -p ********** https://www.udemy.com/the-python-bible -o "C:\Users\Deepak\Desktop\Udemy"

              __                               ____
   __  ______/ /__  ____ ___  __  __      ____/ / /
  / / / / __  / _ \/ __ `__ \/ / / /_____/ __  / /
 / /_/ / /_/ /  __/ / / / / / /_/ /_____/ /_/ / /
 \__,_/\__,_/\___/_/ /_/ /_/\__, /      \__,_/_/
                           /____/
                                 Version : 0.4
                                 Author  : Nasir Khan (r0ot h3x49)
                                 Github  : https://github.com/r0oth3x49

usage: udemy-dl.py [-h] [-v] [-u] [-p] [-o] [-q] [-c] [-l] [--chapter-start]
                   [--chapter-end] [--lecture-start] [--lecture-end] [--save]
                   [--info] [--cache] [--sub-only] [--skip-sub]
                   course
udemy-dl.py: error: the following arguments are required: course

C:\Users\Deepak>

**Comment by r0oth3x49** [comment]
@thedtech i cannot reproduce works fine for me
