### ISSUE TITLE
"[-] Unable to extract course idation .." error

### ISSUE THREAD

**Issue by mandrivnyk133** [r0oth3x49/udemy-dl#145]
[+] : Logged in successfully.
[-] Unable to extract course idation .."

That is what I get when I try to download this course:
https://www.udemy.com/complete-guide-to-tensorflow-for-deep-learning-with-python/
I tried other courses, as well as free one, but the result was the same.

**Comment by r0oth3x49** [comment]
@mandrivnyk133 will fix this ASAP

**Comment by mandrivnyk133** [comment]
Thank you!

**Comment by AnkitVashist11** [comment]
[-] Unable to extract course idation .. 
  
Getting this error while trying to download course from udemy in ubuntu 14.04 
Can Anyone help?
