### ISSUE TITLE
How to use or How to download by using this script

### ISSUE THREAD

**Issue by vikasnewports** [r0oth3x49/udemy-dl#148]
Sorry for very basic question
how can I download the course (already joined/subscribed)
I have windows 10 and already installed python 3
already installed IntelliJ Community version (as IDE)
I tried to download by launching Windows Power Shell but error

**Comment by r0oth3x49** [comment]
@vikasnewports the very basic usage is.
- simply launch the power shell or cmd in the root directory of udemy where `udemy-dl.py` is.
- now run the command billow to download course.
- `python udemy-dl.py -u YOUR_EMAIL_HERE -p YOUR_PASSWORD  COURSE_URL`
**Example** 
```
python udemy-dl.py -u abc@gmail.com -p abcpass https://www.udemy.com/learn-ruby-on-rails-from-scratch
```
rest you can check.
  - ### [Usage](https://github.com/r0oth3x49/udemy-dl#usage)
