### ISSUE TITLE
Anaconda installation post install script fails

### ISSUE THREAD

**Issue by katiyarsahil** [r0oth3x49/udemy-dl#151]
I am trying to reinstall anaconda 64 bit on Windows and the installations works right till the end but it fails executing the post install script and returns a Winerror 2: File not found error The system cannot find the file specified.
However, If i check the LIb folder in Anaconda3 folder, i see the files _nsis.py and subprocess.py which the installer says are missing.
Ignoring the error results in no anaconda navigator in the start menu but anaconda promt is available for some reason.

I tried installing Miniconda too but am facing the same issue.

Kindly help 

![image](https://user-images.githubusercontent.com/26725671/37366590-80af2e0c-26c6-11e8-8668-17db6b4cef81.png)

**Comment by r0oth3x49** [comment]
@katiyarsahil what the hack is going on man, this is invalid issue i don't even know what you are talking about.

**Comment by katiyarsahil** [comment]
Hi Nasir,

My Apologies for posting my request on your board. This was my first time
using Github and was not aware of the correct way to use it when I posted
that. Would pay more attention moving forward now when i know how to
utilize the platform.

Again, sorry for the inconvenience I caused.

Thank you
