### ISSUE TITLE
Not download course

### ISSUE THREAD

**Issue by sudamar** [r0oth3x49/udemy-dl#152]
I try MANY TIMES to download my course from completed url(https://www.udemy.com/XXXXXX/learn/v3/overview), but failed:

[INFO-835] Downloading to: 
_

**> [INFO-107] Trying to log in ...
> Traceback (most recent call last):
>   File "/usr/local/bin/udemy-dl", line 7, in <module>
>     main()
>   File "/usr/local/lib/python2.7/dist-packages/udemy_dl/udemy_dl.py", line 837, in main
>     udemy_dl(username, password, link, lecture_start, lecture_end, save_links, safe_file_names, just_list, output_dest)
>   File "/usr/local/lib/python2.7/dist-packages/udemy_dl/udemy_dl.py", line 658, in udemy_dl
>     login(username, password)
>   File "/usr/local/lib/python2.7/dist-packages/udemy_dl/udemy_dl.py", line 109, in login
>     csrf_token = get_csrf_token()
>   File "/usr/local/lib/python2.7/dist-packages/udemy_dl/udemy_dl.py", line 102, in get_csrf_token
>     return match.group(1)
> AttributeError: 'NoneType' object has no attribute 'group'**

I am using Ubuntu LTS in VPS. When i try to download from simple url ( https://www.udemy.com/XXXXXX/):

**> 
> [INFO-107] Trying to log in ...
> [INFO-137] Login success.
> [ERROR-166] Course id not found!**

What do I need to do?
_

**Comment by r0oth3x49** [comment]
@sudamar you are using a package at Python's Repository which is not the same as this one so either clone this repository and try to download or better to report to the original developer of python's repository.
