### ISSUE TITLE
No Name of the video appears while saving

### ISSUE THREAD

**Issue by RuthlessRuler** [r0oth3x49/udemy-dl#154]
Well, earlier, the name of the video or the subtitle used to be there, but with latest version, only the video lecture names are saved. 

Also, if i use arguments like  --save --skip-sub, then the the skipi-sub is ignored by the program.

**Comment by r0oth3x49** [comment]
@RuthlessRuler can you please explain a bit more i 'm not getting your point?

**Comment by RuthlessRuler** [comment]
Yeah, i remeber it clearly, and i just saw that you added the compatability for aria2c, but then in the end, how the files are gonna be renamed to match with the course since the videos dont have any file name, why dont add that file name append so that even videos filename gets predefined. 

Like having a txt file with name which was it downloaded on one side, and the name it has to be renamed toon other side separated with comma.
This name can also be extracted from Subtitles(If the lectures have). 
Eg: 
Web1080p.mp4, INtroduction.mp4
WebHD_1080.mp4, Hello World.mp4

IDK if there are more ways to define but please add, as each video files download with same file name with .1 to .xx in aria2c, only the subtitles get the file name

**Comment by r0oth3x49** [comment]
@RuthlessRuler will w8 for more suggestion from others. closing the issue.
