### ISSUE TITLE
Unable to Execute Python commands in Windows Server 2012 R2

### ISSUE THREAD

**Issue by MrEhsanEllahi** [r0oth3x49/udemy-dl#156]
I have installed python36 on windows server 2012 R2 and also add paths to system properties to access python. But when I try to execute python commands in windows CMD, it invokes python interpreter. While in Windows 8.1, its working fine. 

![img_20180317_112551](https://user-images.githubusercontent.com/37433424/37552635-1ed13064-29db-11e8-875d-4ffaed851411.jpg)

And one more thing, I did try to execute the command in python interpreter but it instead of executing that it invokes another python interpreter window. following is the command.
import subprocess as sp 
sp.call('pip install -r requirements.txt)

![img_20180317_112533](https://user-images.githubusercontent.com/37433424/37552609-9c1f5d80-29da-11e8-9fb7-78c2682b4fcf.jpg)

**Comment by Jaffar-Hussain** [comment]
first give path to scripts folder  then 
py -m pip install tkinter
* Replace tkinter with your module or package..

**Comment by tofanelli** [comment]
and, one more thing, open your terminal as administrator.... windows server version enforces too much the security, specially on terminals

**Comment by r0oth3x49** [comment]
@MrEhsanEllahi i didn't tested with `Windows Server 2012 R2`. and this issue is more related to OS than this repository. so i 'm closing this and hoping that @tofanelli suggestion worked for you.
