### ISSUE TITLE
unable to extract login-form

### ISSUE THREAD

**Issue by GhaziXX** [r0oth3x49/udemy-dl#157]
after upgrading to the latest version i encountred this problem
![command prompt](https://user-images.githubusercontent.com/24620184/37561034-8ab89ab0-2a44-11e8-82fb-bba67fef1bfc.png)

**Comment by GhaziXX** [comment]
ok I solved this problem by referring to an older post but now I am getting this error 
![command prompt_2](https://user-images.githubusercontent.com/24620184/37561135-3b7da53c-2a47-11e8-87f6-dd6303b38fd0.png)

**Comment by r0oth3x49** [comment]
@GhaziXX i cannot reproduce or may be you are not using the recent update. #145 .
