### ISSUE TITLE
Connection error : make sure your internet connection is working.

### ISSUE THREAD

**Issue by dodyrosjidi** [r0oth3x49/udemy-dl#16]
Hi,
I was install all requirement on my Mac Sierra, but when i try to execute command "python udemy-dl.py -u EMAIL -p PASSWORD https://www.udemy.com/COURENAME", show this error : 
Connection error : make sure your internet connection is working
What happen?
Any solution?

Thanks

**Comment by r0oth3x49** [comment]
@dodyrosjidi this is not an error, try with super user (root) i have tested this with super user it works fine.

**Comment by dodyrosjidi** [comment]
i try duso su like this

Dodys-MacBook-Air:~ dodyrosjidi$ sudo su
Password:
sh-3.2# cd /volumes/data/udemy/udemy-dl
sh-3.2# python udemy-dl.py -u USERNAME -p PASSWORD https://www.udemy.com/learning-yii-2/learn/v4/

              __                               ____  
   __  ______/ /__  ____ ___  __  __      ____/ / /  
  / / / / __  / _ \/ __ `__ \/ / / /_____/ __  / /   
 / /_/ / /_/ /  __/ / / / / / /_/ /_____/ /_/ / /    
 \__,_/\__,_/\___/_/ /_/ /_/\__, /      \__,_/_/     
                           /____/
                                 Version : 0.2
                                 Author  : Nasir khan(r0ot h3x49)
                                 Visit   : https://github.com/r0oth3x49


[*] : Downloading webpage..
[*] : Extracting course information..
[*] : Downloading 'v4'.
[-] : Connection error : make sure your internet connection is working.


Still doesnt work

**Comment by r0oth3x49** [comment]
@dodyrosjidi do not use "/learn/v4/overview" in the course url.

try like this.
python udemy-dl.py -u USERNAME -p PASSWORD https://www.udemy.com/learning-yii-2

let me know if you still face the problem

**Comment by r0oth3x49** [comment]
@dodyrosjidi here is a quick fix for you if you are using python2.
pip install requests[security]

then try downloading your course it will work fine i just checked.

**Comment by coozgan** [comment]
was this solved? I seem to be having the same problem with mac

**Comment by r0oth3x49** [comment]
@coozgan yes it is fixed now i have added a solution into **README** in Requirements section.

**Comment by jnicol** [comment]
In my case I ran into the "make sure your internet connection is working" error on OS X Sierra when using OS X's python2 version, even after installing the required dependencies. Instead, I installed python via Homebrew (brew install python) per http://docs.python-guide.org/en/latest/starting/install/osx/, and after that I had no problems using udemy-dl.
