### ISSUE TITLE
[ERROR-166] Course id not found!

### ISSUE THREAD

**Issue by mariesheilag** [r0oth3x49/udemy-dl#160]
Hi @r0oth3x49 , i also encountered "Course id not found" issue. I tried the URL with /learn/v4/*. Can you please advise on what should I do?

**Comment by r0oth3x49** [comment]
hey @mariesheilag , First of all a bit confuse about date it `29-June-2019` here. are you here from paste :rofl: 
![Capture](https://user-images.githubusercontent.com/11024397/60365747-06bade00-9a03-11e9-8722-8a6cf73d00e8.PNG)

which method you used to authenticate?
  - email/pass or cookies based?
