### ISSUE TITLE
Feature Req: Can we download all the supplementary assets?

### ISSUE THREAD

**Issue by HaoweiCh** [r0oth3x49/udemy-dl#162]
I wanna write a tool to manage all the information related to the course, but unfortunately `youtube-dl` is not support this and the resume feature is bad...

and I wrote a demo to download a whole course into one place(archive), and with the ability to download assets,. 

I really the project you created,, and can I party in?

glad to contact you.

**Comment by r0oth3x49** [comment]
@Chaaang this utility already have a feature to download all available supplementary assets. BTW i 'm unable to get what you want say can you please explain a bit more? what problem actually you are facing with this utility.

**Comment by Rithic3** [comment]
@r0oth3x49 can you like make a video on how to use this program? i very new to all this and i have no idea how to get it even started

**Comment by Chaaang** [comment]
I'll check this utility deeply, and by the way, if this utility can installed by `pip` is a really great.

also , add this to homebrew... 

thanks...

**Comment by r0oth3x49** [comment]
@Rithic3 i will add a comprehensive video for the usage of this tool soon Insha Allah.

**Comment by tofanelli** [comment]
@Chaaang .... please take a look in this comment [here](https://github.com/r0oth3x49/udemy-dl/issues/141#issuecomment-373727754)
