### ISSUE TITLE
"Course id not found!" Crashing on retry

### ISSUE THREAD

**Issue by ram619** [r0oth3x49/udemy-dl#163]
Hi,
I am getting following errors

1. Login is successful but gives the error
> Trying to log in ...
 Login success.
 **Course id not found!**

2. On multiple retries the script start **crashing** 

>  Trying to log in ...
 Exception
Traceback (most recent call last):
  File "udemy_dl.py", line 976, in <module>
  File "udemy_dl.py", line 971, in main
  File "udemy_dl.py", line 766, in udemy_dl
  File "udemy_dl.py", line 156, in login
  File "udemy_dl.py", line 150, in get_csrf_token
AttributeError: 'NoneType' object has no attribute 'group'
Failed to execute script udemy_dl

It was working fine till couple of weeks back.
I tried re-downloading the courses which I have earlier successfully downloaded, it gives same error.

Following are the links that I have tried, these are free courses
[https://www.udemy.com/blockchain-cryptocurrency-course-101-for-absolute-beginners](url)
[https://www.udemy.com/java-tutorial/](url)

**Issue reproduced multiple times**

_Python 2.7
udemy-dl-windows-2.1.3
Windows 7 Professional_

Thanks!

**Comment by r0oth3x49** [comment]
@ram619 check issue #152
