### ISSUE TITLE
Can't download

### ISSUE THREAD

**Issue by ipkpjersi** [r0oth3x49/udemy-dl#164]
Hi,

Whenever I attempt to download videos with either of my two Internet connections, I get an error. Normally if I switch Internet connections, this type of error goes away but not the last 2 days which makes me think this is an actual error. When I go to udemy, there is no captcha or anything like that so I definitely think this is an actual error.

Here is the error:
![](https://i.imgur.com/4wdN0fF.png)

**Comment by r0oth3x49** [comment]
@ipkpjersi you should upgrade to recent commit.
