### ISSUE TITLE
Unable to extract course idation ..

### ISSUE THREAD

**Issue by rahulnautiyal** [r0oth3x49/udemy-dl#166]
__  ______/ /__  ____ ___  __  __      ____/ / /
  / / / / __  / _ \/ __ `__ \/ / / /_____/ __  / /
 / /_/ / /_/ /  __/ / / / / / /_/ /_____/ /_/ / /
 \__,_/\__,_/\___/_/ /_/ /_/\__, /      \__,_/_/
                           /____/
                                 Version : 0.4
                                 Author  : Nasir Khan (r0ot h3x49)
                                 Github  : https://github.com/r0oth3x49

[*] : Trying to login as (abc@xyz.com)...
[+] : Logged in successfully.
[-] Unable to extract course idation ..

**Comment by r0oth3x49** [comment]
@rahulnautiyal this is already fixed check this issue #145

**Comment by rahulnautiyal** [comment]
But i have the latest code, i took it yesterday itself, with my credentials i am able to download where as from my friends credentials i am not able to download videos.

**Comment by la9una** [comment]
Not work for me.

`
[*] : Trying to login as (mymailxxx@gmail.com)...
[+] : Logged in successfully.
[-] Unable to extract course idation .. 
`
. udemy-dl version : 0.4
- Python 2.7.12
- Install pyOpenSSL from source (also from pip)
. Ubuntu 16.04 LTS

**Comment by arindam89** [comment]
Same here.

**Comment by Ogromny** [comment]
Same here too

**Comment by ronkiwest** [comment]
Same error.

**Comment by Kronosneko** [comment]
Same error still happening today at November 9 2018 after installing pyOpenSSL

**Comment by ronkiwest** [comment]
@Kronosneko  Install everything from scratch with the latest versions - python,pip,requirments,udemy-dl then logout of udemy , clear browser cache , login back to udemy.Should work ok after that - make sure to wait 3-5 minutes between downloads.
