### ISSUE TITLE
"course id not found"

### ISSUE THREAD

**Issue by bamacanuck** [r0oth3x49/udemy-dl#169]
I used the udemy-dl utility many months ago, with success, and I thank you for this.

Tonight, seeking to use it again, I've found I'm unable to download course materials. I keep getting the same message, noting that the course id can't be found. I've tried this with several of the many courses I've acquired, over time.

**Comment by r0oth3x49** [comment]
@bamacanuck i will check & fix ASAP.

**Comment by maxnnina** [comment]
I am having the same issue as bamacanuck.
[ERROR-166] Course id not found!

**Comment by r0oth3x49** [comment]
@maxnnina you are not using this repo but the one on python repo. so either report the bug to original author or use this one.

**Comment by maxnnina** [comment]
@r0oth3x49  So sorry for the mistake!  I am still very much a newbie.  I cloned your repo and it is working perfectly.  Thank you so much!!

**Comment by bamacanuck** [comment]
I (also) feel compelled to extend my apology. I have used udemy-dl with success, several times, since last contributing to this discussion.

thanks
