### ISSUE TITLE
Problem about download Resources

### ISSUE THREAD

**Issue by selanium** [r0oth3x49/udemy-dl#17]
Hi, there is 2 problem about resources and links.

**first is that you can download only 1x resource link `links-to-visit` from every chapter.** I mean if there is 5x chapter, and every chapter has 8 lecture I can see only the last lecture link. so I cant download lecture 1 - 7 links or resources. and it is possible that every lecture has more than 2-3x resource link

**second problem is about Quizzes.** this part is not work too

also it is good to add them in another folder. I find an working example here. both problems that I explain above are working here.
`https://github.com/madmax2/udemy-dl-windows`

but my knowledge is low in python. I will try to add it in future but it is hard for me :)

**Comment by r0oth3x49** [comment]
@selanium i will look into these problems thanks for the report+suggestions. currently i 'm closing this issue.

**Comment by selanium** [comment]
I find another bug too, it is same with **first issue** but a little more detail.
sometimes I see duplicate links in text file. forexample 2x from the same link

**Comment by r0oth3x49** [comment]
@selanium this is not the bug it gets all the external links and adds it to the file to visit no matter it the same external link is present with each video it will append that in a file.
