### ISSUE TITLE
Unable to extract course idation

### ISSUE THREAD

**Issue by harishpal2090** [r0oth3x49/udemy-dl#170]
HI All,
i am receiving the below error message while using the script to download the Udemy content.
i have read all the previous given article about the error message and i am using latest GIt repo. however still encountering with the same error message. Will appreciate your help.
![error-message](https://user-images.githubusercontent.com/12540336/38654641-0452bac0-3e2e-11e8-93a7-3328ab5b8f2e.jpg)

**Comment by thesalah1212** [comment]
may you check the url you have put in in wrong way

**Comment by r0oth3x49** [comment]
@harishpal2090 i cannot reproduce the error.
