### ISSUE TITLE
Caption format issues

### ISSUE THREAD

**Issue by thesalah1212** [r0oth3x49/udemy-dl#171]
when I was trying to download some courses from udemy  I notice that some courses's captions have an error in its syntax of srt 

for example in this course udemy.com/animationselling the caption file is like this 
**so it doesn't open by vlc**
![image](https://user-images.githubusercontent.com/13509687/38703699-a2baac76-3eac-11e8-9a4e-6943341b6649.png)

notice that all videos in this course captions aren't working

**Comment by r0oth3x49** [comment]
what is wrong with caption and it will be great if you can share the course url.

**Comment by thesalah1212** [comment]
http://udemy.com/animationselling

**Comment by r0oth3x49** [comment]
@thesalah1212 i don't have this course in my account so i cannot test against this course but i have tested against many others and i didn't get any starting point from 0 so i will wait for more reports for now i 'm closing this.
