### ISSUE TITLE
KeyError: 'lectures_count' when downloading a course

### ISSUE THREAD

**Issue by saexfer** [r0oth3x49/udemy-dl#176]
The course is: https://www.udemy.com/integrando-docker-a-su-infraestrucutra-y-servicios/
I have been able to download other courses but not this one. Please help me.

[+] : Logged in successfully.
[*] : Downloaded course information .. (done)
Traceback (most recent call last):
  File "udemy-dl.py", line 1201, in <module>
    main()
  File "udemy-dl.py", line 1053, in main
    udemy.course_list_down(chapter_number=options.chapter, lecture_number=options.lecture)
  File "udemy-dl.py", line 125, in course_list_down
    course = udemy.course(self.url, self.username, self.password)
  File "/opt/udemy-dl/udemy/_udemy.py", line 37, in course
    return Udemy(url, username, password, basic, callback)
  File "/opt/udemy-dl/udemy/_internal.py", line 44, in __init__
    super(InternUdemyCourse, self).__init__(*args, **kwargs)
  File "/opt/udemy-dl/udemy/_shared.py", line 61, in __init__
    self._fetch_course()
  File "/opt/udemy-dl/udemy/_internal.py", line 61, in _fetch_course
    self._chapters          =       [InternUdemyChapter(z) for z in self._info['chapters']]
  File "/opt/udemy-dl/udemy/_internal.py", line 79, in __init__
    self._lectures_count    = chapter['lectures_count']
KeyError: 'lectures_count'

**Comment by r0oth3x49** [comment]
@saexfer clone the most recent version on github and then try to download if you still face the error then i might need your account to test against this course because i don't have this course in my account.

**Comment by otakucore** [comment]
I get that error with this course:
https://www.udemy.com/press-release-how-to/learn/v4/content

**Comment by faridyarkhan** [comment]
This issue can be fixed by adding below snippet at line 83 of udemy/_internal.py . Remeber to replace line 83 with this. I would like to check in this snippet but I am still new to git hub

if 'lectures_count' in chapter.keys() :
            self._lectures_count    = chapter['lectures_count']
        else :
            self._lectures_count    = 0
