### ISSUE TITLE
ImportError: No module named colorama

### ISSUE THREAD

**Issue by afedulov** [r0oth3x49/udemy-dl#182]
After successfully installing dependencies with 
`sudo pip install -r requirements.txt
`
Running 
`sudo python udemy-dl.py ...`
Throws **ImportError: No module named colorama** exception.
MacOS 10.12.6

Would appreciate any advice on how to fix this.

**Comment by r0oth3x49** [comment]
@afedulov try to install each module separately with pip.

sudo pip install modulename --upgrade

**Comment by afedulov** [comment]
I had to do `sudo pip uninstall colorama` to globally remove it and then do `pip install --user colorama` to install it into a home folder, where it could be detected by udemy-dl

**Comment by alexander-tampier** [comment]
```
sudo -H pip install requests --upgrade
sudo -H pip install colorama --upgrade
sudo -H pip install unidecode --upgrade
sudo -H pip install six --upgrade
sudo -H pip install requests[security] --upgrade
sudo -H python udemy-dl.py -u <EMAIL> -p <PASSWORD> <URL>
```

worked for me :) with `python3` it did not work i also used `python`

**Comment by jsonify** [comment]
I found that @alexander-tampier had the best solution and that worked great for me.

**Comment by rhodesgod01** [comment]
> ```
> sudo -H pip install requests --upgrade
> sudo -H pip install colorama --upgrade
> sudo -H pip install unidecode --upgrade
> sudo -H pip install six --upgrade
> sudo -H pip install requests[security] --upgrade
> sudo -H python udemy-dl.py -u <EMAIL> -p <PASSWORD> <URL>
> ```
> worked for me :) with `python3` it did not work i also used `python`

Well Done. Worked for me this way.
thank you.

**Comment by tifDev** [comment]
Where do the files go after downloading? I cant find them in Ubuntu...

**Comment by Drwalcore** [comment]
@tifDev - in the same folder where You have udemy-dl.py

**Comment by r0oth3x49** [comment]
thank @alexander-tampier for guidance.

> 
> 
> Where do the files go after downloading? I cant find them in Ubuntu...

are you sure you can't find? udemy-dl is not doing any kind of magic for the rest of people it works fine and for me as well but still i will try to reproduce and fix



> 
> 
> @tifDev - I see that You have opened #325 and further conversation should be written up there.

thanks for pointing out. opening so many related issue will make delay in solving because of so may duplicates.

sorry for the very late reply guys.

**Comment by mindsx** [comment]
The easiest solution to your problem is to run

$ pip install --upgrade --user awscli

as this will make sure you have all needed dependencies.

**Comment by r0oth3x49** [comment]
@mindsx are you a bot trying to comment on every issue and suggesting the same solution every where

**Comment by mindsx** [comment]
No I'm not a bot. I just want to help people that have the same issue

вс, 2 Фев 2020, 9:53 Nasir Khan <notifications@github.com>:
