### ISSUE TITLE
Only found chapter, videos not found

### ISSUE THREAD

**Issue by kamalhm** [r0oth3x49/udemy-dl#183]
Is this because of udemy update? or is it because of my pc?

windows 10, python 3.6

**Comment by r0oth3x49** [comment]
already fixed check : #179

**Comment by kamalhm** [comment]
but where is the updated release? I dont see any upgrade from 0.4

**Comment by r0oth3x49** [comment]
@kamalhm you should check commits instead version upgrade.

**Comment by kamalhm** [comment]
I see, thank you, sorry for bothering you i'm still new to github :D
