### ISSUE TITLE
[-] Unable to extract login-form form

### ISSUE THREAD

**Issue by jskarulis** [r0oth3x49/udemy-dl#184]
Getting error after downloading several courses.
The error occurs immediately after the output statement that is Trying to login

[*] : Trying to login as (        )...
[-] Unable to extract login-form form

**Comment by sinusjz** [comment]
I'm also having this exact problem.
It was working fine until few days ago.

**Comment by r0oth3x49** [comment]
@jskarulis , @sinusjz you should wait before retrying to download another course because udemy detects attempts as bot. try after few minutes this will wok fine.

**Comment by r0oth3x49** [comment]
@TonioGela i have tested this solution and changing user agent works but not always and you can check the previous commits for solving this problem was a simple change of user agent.

**Comment by TonioGela** [comment]
It couldn't have been so easy obviously. Maybe it's something else in the header, and maybe trying to decompile the android app can be useful. But maybe it's simply not worthy when you could just wait some minutes and retry. In the worst case the control is made server side per user and there's simply a datasize over time limit.

**Comment by r0oth3x49** [comment]
@jskarulis for now i 'm going to close this issue as the current solution to tackle this problem is to wait for few minutes and then try to download.

**Comment by adriannx** [comment]
That's what I did, I've tried every hour and I get the same message.

Or maybe udemy banned my IP?

**Comment by adriannx** [comment]
@r0oth3x49 
That's what I did, I've tried every hour and I get the same message.

Or maybe udemy banned my IP?

**Comment by markusmaresch** [comment]
Getting the same message immediately without any prior downloads

**Comment by markusmaresch** [comment]
Waiting helps. Logging in with a browser at the same time also appears to help.
