### ISSUE TITLE
problem 

### ISSUE THREAD

**Issue by sagarsamrat3956** [r0oth3x49/udemy-dl#188]
when i download the subtile of the video it downloads the first video subtitle and remaining video subtitle shows the error like this : 

Traceback (most recent call last):
  File "udemy-dl.py", line 1201, in <module>
    main()
  File "udemy-dl.py", line 1034, in main
    udemy.course_download(caption_only=options.caption_only, path=options.output)
  File "udemy-dl.py", line 433, in course_download
    self.download_captions_only(lecture_subtitles=lecture_subtitles, lecture_assets=lecture_assets, filepath=filepath)
  File "udemy-dl.py", line 373, in download_captions_only
    self.download_subtitles(lecture_subtitles=lecture_subtitles, filepath=filepath)
  File "udemy-dl.py", line 347, in download_subtitles
    self.convert(filename=filename)
  File "C:\Users\Back Benchers\Desktop\udemy-dl-master\udemy\_vtt2srt.py", line 141, in convert
    _start, _end  = line.split(' --> ')
ValueError: not enough values to unpack (expected 2, got 1)

please fix my issue !!! i will be more thankful .

**Comment by r0oth3x49** [comment]
@sagarsamrat3956 details required for the next time i will not facilitate such kind of issues i will soon add a reporting critera. you should explain completely instead simply showing the error you are facing.

what was the course, course url, and other details etc.

**Comment by sagarsamrat3956** [comment]
this course:
https://www.udemy.com/complete-intensive-english-course-for-beginners/

**Comment by sagarsamrat3956** [comment]
but the other course subtitle download successfully but this course
subtitle why :
https://www.udemy.com/complete-intensive-english-course-for-beginners/learn/v4/content

**Comment by r0oth3x49** [comment]
@sagarsamrat3956 i i don't have this course in my account so i cannot test against this one. if you really want me to solve this issue for you, You can [email](mailto:nasir251292@gmail.com) me your credentials and once the bug is resolved i will let you know.

the other solution to this is, you can simply skip the subtitle for that perticular chapter or lecture.

**Comment by sagarsamrat3956** [comment]
sorry it is personal so i can't . anyway thank u so much !!!!
