### ISSUE TITLE
0 lecture found

### ISSUE THREAD

**Issue by RuthCollins** [r0oth3x49/udemy-dl#190]
I tried to download my course but I got this feedback: "0 lecture(s) found.
[*] : Course 'the-web-developer-bootcamp'.
[+] : Chapter(s) (39).
[*] : Lecture(s) (0).

[*] : Downloading chapter : (1 of 39)
[+] : Chapter (01 Introduction to this Course)
[*] : Found (0) lectures ...

[*] : Downloading chapter : (2 of 39)
[+] : Chapter (02 Introduction to Front End Development)
[*] : Found (0) lectures ...

[*] : Downloading chapter : (3 of 39)
[+] : Chapter (03 Introduction to HTML)
[*] : Found (0) lectures ...

[*] : Downloading chapter : (4 of 39)
[+] : Chapter (04 Intermediate HTML)
[*] : Found (0) lectures ...

[*] : Downloading chapter : (5 of 39)
[+] : Chapter (05 Introduction to CSS)
[*] : Found (0) lectures ...

[*] : Downloading chapter : (6 of 39)
[+] : Chapter (06 Intermediate CSS)
[*] : Found (0) lectures ...

[*] : Downloading chapter : (7 of 39)
[+] : Chapter (07 Bootstrap)
[*] : Found (0) lectures ...

[*] : Downloading chapter : (8 of 39)
[+] : Chapter (08 Introduction to JavaScript)
[*] : Found (0) lectures ...

[*] : Downloading chapter : (9 of 39)
[+] : Chapter (09 Javascript Basics Control Flow)
[*] : Found (0) lectures ...

[*] : Downloading chapter : (10 of 39)
[+] : Chapter (10 Javascript Basics Functions)
[*] : Found (0) lectures ...

**Comment by Redlava60** [comment]
Reclone the udemy dl git and it will work well.

**Comment by linneudm** [comment]
This issue is solved. #189

**Comment by r0oth3x49** [comment]
@RuthCollins you should follow the guideline  before creating and issue otherwise i will directly close the issue without resolving as **follow-reporting-guideline** label.
