### ISSUE TITLE
udemy lecture

### ISSUE THREAD

**Issue by jaan143** [r0oth3x49/udemy-dl#191]
hello i am getting error on lecture 052's asset file so i want to start downloading from lecture 53
and i wam using this command but its giving me error on lecture 52's asset file

D:\Downloads\dlmster\uddl.py -o 'D:\contents\New folder' -u *****@***.com -p ***** --skip-sub --lecture-start 53 https://www.udemy.com/growthhacking****/

please help me to solve it

**Comment by r0oth3x49** [comment]
@jaan143 i have already given a help under the Usage how you can use. check the [Usage](https://github.com/r0oth3x49/udemy-dl#usage)
