### ISSUE TITLE
Unable to extract course idation

### ISSUE THREAD

**Issue by lynecker** [r0oth3x49/udemy-dl#193]
:red_circle: This issue have been up again :red_circle:
maybe some udemy system update make this issue up again i think.
any chance to fix that? 
thank's

I have test with linux and windows, the both got same error.

**Comment by r0oth3x49** [comment]
@lynecker thank for the report. recently i was discussing this error on [comment](https://github.com/r0oth3x49/udemy-dl/issues/184#issuecomment-385164513) please take and look and let me know if you still face the error.

and one more request please do follow the [Issue Reporting Guideline](https://github.com/r0oth3x49/udemy-dl#issue-reporting-guideline)
