### ISSUE TITLE
udemy lecture error

### ISSUE THREAD

**Issue by jaan143** [r0oth3x49/udemy-dl#194]
actually my command is working fine but its not downloading start from spesific lecture
still i am getting this error

i want to skip lecture's 52 asset which i giving me error to download so i want to start downloading from lecture 53 and i am using these commands and all commands are start downloading from first lecture

D:\Downloads\dlmster\uddl.py -o 'D:\contents\New folder' -u ****@y.com -p ***** --skip-sub --lecture-start 053 --lecture-end 088 https://www.udemy.com/growthhacking/

here i used other command also
D:\Downloads\dlmster\uddl.py -o 'D:\contents\New folder' -u ****y.com -p **** --skip-sub -c 06 -l 053 --lecture-end 088 https://www.udemy.com/growthhacking/

i just need to clarify that which command i need to use to start lecture from 53

**Comment by jaan143** [comment]
@r0oth3x49  if you cannot help then why to open this project just close it and take bed rest
first read github rules

**Comment by r0oth3x49** [comment]
@jaan143 brother if you are not comfortable with using this utility you can go for any one else did i bound you to use this.

**Comment by jaan143** [comment]
@r0oth3x49  i used old udemy-dl nishad's project and i know little bit about python thats 
he closed this project thats why i am using this one i just want to clear which command i need to use for downloading start from lecture 053 and you didnt help
i read all usage and i tried one by one but its start downloading from first lecture

**Comment by jaan143** [comment]
@r0oth3x49  how much time it will take you to give example ? less than 30 seconds

**Comment by jaan143** [comment]
bro sorry if i take your time
its important to add lecture end option also ?
if i just use only lecture start option and it will not finish auto on lecture end ?

**Comment by r0oth3x49** [comment]
@jaan143 lets start from scratch. 
 - delete the old udemy-dl
 - download/clone again from here on github (remember this repository cannot be installed via pip)
 - change to the root directly where udemy-dl.py is.
 - then run the commands.
 - pip install -r requirements.txt
 - python udemy-dl.py COURSE_URL --chapter 6 --lecture-start 2 or 3 where ever you wish to start with.
 - once chapter 6 is downloaded run the below command.
 - python udemy-dl.py COURSE_URL --chapter-start 7
 - this will download all chapters starting from 7

**Comment by jaan143** [comment]
@r0oth3x49 bro these are done
download/clone again from here on github (remember this repository cannot be installed via pip)
pip install -r requirements.txt

but how to change root directly
change to the root directly where udemy-dl.py is.

**Comment by r0oth3x49** [comment]
@jaan143 [here](https://github.com/r0oth3x49/udemy-dl/issues/141#issuecomment-373727754) is more better explaination of using via cmd by @tofanelli bro.

**Comment by jaan143** [comment]
@r0oth3x49  bro this command is not working 
---chapter-start 5 --chapter-end 11 https://www.udemy.com/new-manager-training/

i want to download chapter 5 to chapter 11
for this what is exactly command ?
