### ISSUE TITLE
Unable to extract login-form form

### ISSUE THREAD

**Issue by Wayne-Mather** [r0oth3x49/udemy-dl#197]
Hi,

Is anyone else getting this issue?

I am running Version 0.4 (commit 59ba1efb5f3e227ab2d563bb964479af125d6794) under python3 (3.6.5) on Fedora 27 x64.

This is on every single course I have tried it on.

**Comment by emekaorjiani** [comment]
Am also getting the same issue [-] Unable to extract login-form form

**Comment by r0oth3x49** [comment]
@Wayne-Mather did you check this #184 i already have discussed the solution. thanks for the explaining the issue you are facing you should also check if the issue is discussed or not...

**Comment by Wayne-Mather** [comment]
@r0oth3x49 - I got it after upgrading to the latest commit and running my scripts probably 2 months after they were last run. I can confirm that after waiting over night, the downloads are working again as expected.

And normally I do search first but as I saw no open tickets I asked this question. You are correct in that I should have looked at closed tickets as well. 

I wonder if you could capture this error and say "please try again in x minutes"?

**Comment by r0oth3x49** [comment]
@Wayne-Mather that is a great suggestion thank you, i will work on this ASAP & i really appreciate, thanks man for following Issue Reporting guideline, this helps a lot.
