### ISSUE TITLE
cannot download due to html?

### ISSUE THREAD

**Issue by githubnewbee1** [r0oth3x49/udemy-dl#199]
[INFO-884] Downloading to: D:\My Videos\eLearning_Videos\Download

[INFO-127] Trying to log in ...
[INFO-157] Login success.
[INFO-189] Found course id: 555462

Getting course data: 2.44% [--------------------] [CRITICAL-428] Cannot download lecture "Introduction to Multivariate Analysis (MVA) Course": "u'view_html'"
Getting course data: 98.78% [====================] [CRITICAL-428] Cannot download lecture "SIMSEM Package Simulation Capabilities (part 1)": "u'view_html'"

Or is it just me?

**Comment by thava** [comment]
I am facing same issue with udemy dl.
udemy-dl --version
udemy-dl 0.2.1
