### ISSUE TITLE
Resource Bug

### ISSUE THREAD

**Issue by selanium** [r0oth3x49/udemy-dl#20]
Hi, thanks for the new version it work well and caption futures too, just there is one error that I post it in another issue,

ok lets say current issue about this topic
`https://github.com/r0oth3x49/udemy-dl/issues/17`
about this problem, it is again same but now it is a little changed, there is no .txt file like before. but the same problem about lectures is still bug
lets say we have 3 chapter and 4lecture in chapter 1

```
chapter 1:
        lecture a:
             download file 1;
             download file 2;
             download file 3;
       lecture b:
       lecture c:
       lecture d:
chapter 2:
     .....................
chapter 3:
     ......................
```

with starting the program it will download only and just **download file 3**, and download 2 and download 1 are skipped.

**Comment by r0oth3x49** [comment]
@selanium which course are you downloading.

**Comment by selanium** [comment]
it is same, for all courses, just find a course with with more than 1x ( I mean 2, 3 , 4 ,5, ...) in one lecture only.

> in this case it **works** perfect, and it downloads in this way, lecture a.mp4 + download file 1 + b.mp4 + download file 2 + c.mp4 + download file 3 + d.mp4 ( this one dosent have resource :D ), then jump chapter 2 and do the same, then jump chapter 3 and do the same.

```
chapter 1:
        lecture a:
             download file 1;
       lecture b:
             download file 2;
       lecture c:
             download file 3;
       lecture d:
chapter 2:
     .....................
chapter 3:
     ......................
```

> but in this case **not work**, how it works in this case?
> start chapter 1, download a.mp4 + download file 3.mp4 ( here we lost download 1 + download 2 ) + b.mp4 + download file 5 ( here we lost download file 4 )  + c.mp4 ( here we don't have any resource to download :D ) + d.mp4 + download file 6

```
chapter 1:
        lecture a:
             download file 1;
             download file 2;
             download file 3;
       lecture b:
             download file 4;
             download file 5;
       lecture c:
       lecture d:
             download file 6;
chapter 2:
     .....................
chapter 3:
     ......................
```

so every lecture with more than 1x ( 2,3,4,...) we have only the last one, so if we have **3** downloable file we can download only **download file 3**
if we have 4, only I can download ,**download file 4**
only case that it works is 1 downloadble file, so it downloads the 1 file and works well:D
I try my best to explain it well wish you understand. about the course you can test it on any course you want it is same in alls

my personal idea about this as developer ( beginner:D)
I guess we read download file1, then jump to download file 2, then download file 3 and if we have 3. we save only last one . it look like before the 3 ( 2 and 1 , are overwritten without saving )

**Comment by r0oth3x49** [comment]
@selanium which course are you downloading?
