### ISSUE TITLE
Error Traceback (most recent call last):

### ISSUE THREAD

**Issue by Murtadhajfadhil** [r0oth3x49/udemy-dl#202]
I'm using the below arguments to download this course https://www.udemy.com/java-the-complete-java-developer-course

python udemy-dl.py -u *********@outlook.com -p ******** --skip-sub https://www.udemy.com/java-the-complete-java-developer-course

and after the lecture number 025 I'm getting this error:

Traceback (most recent call last):
  File "udemy-dl.py", line 1201, in <module>
    main()
  File "udemy-dl.py", line 1193, in main
    udemy.course_download(skip_captions=options.skip_captions, path=options.outp                                                                                                    ut, quality=options.quality)
  File "udemy-dl.py", line 447, in course_download
    self.download_lectures_only(lecture_best=lecture_best, lecture_title=lecture                                                                                                    _title, inner_index=inner_index, lectures_count=lectures_count, lecture_assets=l                                                                                                    ecture_assets, filepath=filepath)
  File "udemy-dl.py", line 381, in download_lectures_only
    self.download_assets(lecture_assets=lecture_assets, filepath=filepath)
  File "udemy-dl.py", line 309, in download_assets
    assets.download(filepath=filepath, quiet=True, callback=self.show_progress)
  File "E:\udemy\udemy-dl\udemy\_shared.py", line 538, in download
    return self._write_external_links(filepath)
  File "E:\udemy\udemy-dl\udemy\_shared.py", line 470, in _write_external_links
    with open('{}.txt'.format(filename), 'a', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\udemy\\udemy-dl\\ja                                                                                                    va-the-complete-java-developer-course\\05 Java Tutorial Expressions Statements C                                                                                                    ode blocks Methods and more\\025 Source-Code-Java-Tutorial-Expressions-Statement                                                                                                    s-Code-blocks-Methods-and-more-Statements-Whitespace-and-Intentation-Code-Organi                                                                                                    zation-.txt'

![screenshot_20180514133750](https://user-images.githubusercontent.com/24244733/39992617-094054a4-577c-11e8-9c4b-f40ef367d1e5.png)

**Comment by r0oth3x49** [comment]
@Murtadhajfadhil you check [this](https://msdn.microsoft.com/en-us/library/aa365247(VS.85).aspx#maxpath) or [this one](https://stackoverflow.com/questions/1880321/why-does-the-260-character-path-length-limit-exist-in-windows).
