### ISSUE TITLE
Unable to extract course idation

### ISSUE THREAD

**Issue by adriannx** [r0oth3x49/udemy-dl#203]
Maybe some udemy system update make this issue up again i think.
any chance to fix that?

Regards!

**Comment by r0oth3x49** [comment]
@adriannx you should wait and then retry after few minutes. take a look at issue #184 .

**Comment by adriannx** [comment]
@r0oth3x49 Hello,  I just confirmed, udemy bans the IP.
I used VPN and when changing my IP I was able to download the course.

Regards!

**Comment by r0oth3x49** [comment]
@adriannx udemy detects many attemps as bot so its to download courses with time interval let say 3 to 5 minutes so that it does not block you.
