### ISSUE TITLE
Failed to Loin

### ISSUE THREAD

**Issue by griffen62** [r0oth3x49/udemy-dl#211]
Windows 10
Python 3.6.5
latest udemy-dl as of 13:36 EST 23 May 18

Similar issue to #201 - typing password creates multiple asterisks, then fails to login.

1. Power shell or CMD
2. run the application:
     python udemy-dl.py https://www.udemy.com/cisco-ccna-icnd2-200-105-complete-course-sims-and-gns3/learn/v4/overview
3. type username
4. type password, returns '**' for every character i type, then fails. 

To play around I made my password on udemy very simple, to test if python was just double typing my characters, still nothing.

**Comment by r0oth3x49** [comment]
@griffen62 thanks for the report i will try to reproduce on Windows-10 with Python 3.6.5 against latest `master` in git & will get back to you ASAP.
