### ISSUE TITLE
Unable to extract course idation and login-form form

### ISSUE THREAD

**Issue by thedtech** [r0oth3x49/udemy-dl#212]
Hey there, 
                 While downloading a course these two errors are coming, (which I think are recent) :

**1. Unable to extract course idation**

[+] : Logged in successfully.
[-] Unable to extract course idation ..

**2. Unable to extract login-form form**

[*] : Trying to login as (xxxxxx@gmail.com)...
[-] Unable to extract login-form form

Please see through them.
Thank You.

**Comment by r0oth3x49** [comment]
@thedtech check #184 its already discussed so i 'm closing the issue and please do follow issue reporting guieline

**Comment by r0oth3x49** [comment]
@thedtech after certain interval didn't that worked for you, you have to wait atleast 3 to 4 minutes to retry downloading, as we have discussed in #184 that waiting for few minutes and resuming the download works for almost every one out there even for me i face the above error so many times but then i wait for atleast 5 to 10 minute to resume downloading and it works fine..

**Comment by thedtech** [comment]
@r0oth3x49 Actually that is the real problem bro, this error came for me yesterday and till them I am waiting. Waited for 5 minutes even for 1 hour but nothing is happening.I will again try today, hope it works.

**Comment by thedtech** [comment]
@r0oth3x49 Hey Bro, I tried everything on my current environment **(Windows 10 X64 April 2018)** but nothing working. Now I am trying to do the same on **(Ubuntu 18.04 LTS Desktop)** installed on vmware (Virtual Environment) but I am getting error **Command Not Found** while executing the script.I have Python 3.6.5 installed and PIP/Modules are also installed.

Can you please instruct me If I am missing anything. Please!

Thank You!!!

**Comment by r0oth3x49** [comment]
@thedtech sorry for the late response. can you please verify that you are using this utility instead the one at Python's Repository. remember this **cannot** be installed via `pip` so you have to clone udemy-dl from here. one more suggestion is to use cookie based authentication mechanism. steps to use cookie based authentication are below.

- login to your udemy account via browser
- Once you are logged in goto the course you want to download and right click on page look for option **Inspect Element** & click on that option.
- Click on **Network Tab** Menu in **Inspect Element** and then click on **XHR** option.
![capture](https://user-images.githubusercontent.com/11024397/40576215-72f58642-610b-11e8-8437-6d14cd321fe2.PNG)

- Refresh the page you will see some requests in Network tab right click on any one of them and goto **Copy** & then **Copy Request Headers**.
![untitled](https://user-images.githubusercontent.com/11024397/40576218-78c746be-610b-11e8-8980-e238932b6481.png)

- Save the Copied Request Headers to text file (let say cookies.txt) under the root directory of udemy-dl where **udemy-dl.py** is.
- Now run the below command.
   python COURSE_URL -k file_name_where_you_save_request_headers.txt
- Done this will download the course for you.
- this guide is created using Firefox browser for other i hope will be the same process.

**Comment by TheAlexPorter** [comment]
This solved the issue of not being able to find the id. Thanks @r0oth3x49 !

**Comment by shoio** [comment]
It didn't work for me :(
Any tips?

[*] : Trying to login using cookies ...
Traceback (most recent call last):
  File "udemy-dl.py", line 1443, in <module>
    main()
  File "udemy-dl.py", line 1102, in main
    udemy.course_download(path=options.output, quality=options.quality, unsafe=options.unsafe)
  File "udemy-dl.py", line 436, in course_download
    course = udemy.course(url=self.url, username=self.username, password=self.password, cookies=self.cookies)
  File "/home/jj/Udemy/udemy-dl-master/udemy/_udemy.py", line 38, in course
    return Udemy(url, username, password, cookies, basic, callback)
  File "/home/jj/Udemy/udemy-dl-master/udemy/_internal.py", line 44, in __init__
    super(InternUdemyCourse, self).__init__(*args, **kwargs)
  File "/home/jj/Udemy/udemy-dl-master/udemy/_shared.py", line 62, in __init__
    self._fetch_course()
  File "/home/jj/Udemy/udemy-dl-master/udemy/_internal.py", line 52, in _fetch_course
    auth = self._login(cookies=self._cookies)
  File "/home/jj/Udemy/udemy-dl-master/udemy/_extract.py", line 101, in _login
    self._cookies = self._extract_cookie_string(raw_cookies=cookies)
  File "/home/jj/Udemy/udemy-dl-master/udemy/_extract.py", line 87, in _extract_cookie_string
    cookie_parser.load(cookie_string.group('cookie'))
AttributeError: 'NoneType' object has no attribute 'group'
