### ISSUE TITLE
Downloading is being paused and pending so long

### ISSUE THREAD

**Issue by k0th31** [r0oth3x49/udemy-dl#215]
When I download the following course, 2 issues are observed.
(1) Sometimes, video cannot skip (i,e not complete video)
(2) Downloading in some lectures is pending so long. There is no auto re-downloading after a few minutes. (It is suggested, it should automatically re-download after a specific perioud)
My internet is good. 50 Mbps.

https://www.udemy.com/accent-reduction/learn/v4/overview

**Comment by r0oth3x49** [comment]
@k0th31 i don't have access to this course but i will try to reproduce with any other course & fix it ASAP. i would appreciate if you follow the complete issue reporting guideline.

**Comment by r0oth3x49** [comment]
**Update**

@k0th31 sorry for the very late response. 
About this issue it is more related to `urllib/urllib2`  than the udemy-dl so for now i 'm going to close the issue, & will do some research on work around i have found many of them but need to test and once i get time i will test and deploy the solution.

for now the solution is to terminate script and re-run against the same course if it halts between downloads.
