### ISSUE TITLE
When I typed a character in the password field, it shown that I typed two characters

### ISSUE THREAD

**Issue by kamalhm** [r0oth3x49/udemy-dl#222]
Which make me failed to login, and I can only download using the -email and -password option

this happened using cmd, on windows 10 64 bit 1803

when using bash, the password that I typed is displayed in cleartext

**Comment by r0oth3x49** [comment]
@kamalhm take a look at issue #201 . there are other ways as well which you can use,
example.
  - caching your credentials (`--cache`)
  - or using cookies based auth ('--cookies/-k')
