### ISSUE TITLE
subtitle problem

### ISSUE THREAD

**Issue by zacksleo** [r0oth3x49/udemy-dl#223]
I download the subtitle on mac os, but found the english srt file is not correct.

There is no deadline for the Timeline. Subtitle for other language is correct.

## Cmd

```
python3 udemy-dl.py https://www.udemy.com/illustrator-cc-masterclass/ --sub-only
```

## Result 

```
1
00:00:00,000 -->
Adobe Illustrator is the industry standard

2
00:00:00,000 -->
vector graphics application

3
00:00:05,520 -->
that let's you create logos, icons, sketches,

4
00:00:05,520 -->
typography and complex illustrations
```

## Courses

[illustrator-cc-masterclass](https://www.udemy.com/illustrator-cc-masterclass)

## Files if can help

[001 Why learn Illustrator.zip](https://github.com/r0oth3x49/udemy-dl/files/2084201/001.Why.learn.Illustrator.zip)

**Comment by r0oth3x49** [comment]
@zacksleo it would be great if you take a look at [issue reporting guideline](https://github.com/r0oth3x49/udemy-dl#issue-reporting-guideline)

**Comment by zacksleo** [comment]
Maybe there is some problem when transforming from vtt to srt. So I downloaded the vvt and put it in the attachment.

**Comment by zacksleo** [comment]
In this subtitle , there is a string after the timestamp `line:93%`, maybe this is the problem.

`001 Why learn Illustrator.vtt.vtt`
```
WEBVTT

00:00:00.000 --> 00:00:04.900 line:93%
Adobe Illustrator is the industry standard
vector graphics application

00:00:05.520 --> 00:00:11.140 line:93%
that let's you create logos, icons, sketches,
typography and complex illustrations
.....
```

**Comment by r0oth3x49** [comment]
@zacksleo i will take a look & try to fix this ASAP
