### ISSUE TITLE
Issue while running requirements.txt

### ISSUE THREAD

**Issue by PallavAg** [r0oth3x49/udemy-dl#227]
When running the command 
`pip install -r requirements.txt`

I get the error
`OSError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/colorama-0.3.9.dist-info`

If it helps, i'm running MacOS Mojave but I doubt it should make a difference. Anyone got a fix?

**Comment by zacksleo** [comment]
> Seems like you don't have permission to the Python folder. Try sudo chown -R $USER /Library/Python/2.7

https://github.com/sindresorhus/weechat-notification-center/issues/1

**Comment by r0oth3x49** [comment]
@PallavAg try run with `sudo -H pip install -r requirements.txt` this will install the requirements for you.
