### ISSUE TITLE
Unable to extract course idation

### ISSUE THREAD

**Issue by 7ang** [r0oth3x49/udemy-dl#230]
Unable to extract course idation 
It seems a common problem, every course will trigger this problem

![pic](https://user-images.githubusercontent.com/15152796/41324289-56b7aef4-6ee6-11e8-8a46-e3d33639e452.jpg)

**Comment by r0oth3x49** [comment]
@7ang you should wait for atleast 5 to 10 minutes between downloading the courses. udemy detects attempts. if you are getting this error wait for few minutes and then try again this will work

or if this is not the case then upgrade all the requirements.

- upgrade requests[security] or pyopenssl

**Comment by 7ang** [comment]
Thanks for replying

I have tried what you advise
(I just have one course,so there is no time between courses downloading,and had upgrade the requirements) 
 however it didn't work just like before

**Comment by 7ang** [comment]
If I use cookie to login, what should I do? which cookie is right?

**Comment by 7ang** [comment]
If I use cookie to login, what should I do? which cookie is right?

**Comment by 7ang** [comment]
If I use cookie to login, what should I do? which cookie is right?


![cookie](https://user-images.githubusercontent.com/15152796/41327500-52512740-6ef6-11e8-8c04-801a7c657053.PNG)

**Comment by adriannx** [comment]
EDIT: I got a solution, just update to the latest version of python

RegarsS!

**Comment by 7ang** [comment]
which version of python will work @adriannx , thx

**Comment by r0oth3x49** [comment]
@7ang what i mean by
> you should wait for atleast 5 to 10 minutes between downloading the courses.
is to download course if you get the error such as
 - Unable to extract login-form form
 - Unable to extract course idation

that means you are continuously trying to download the course without any wait which udemy server is blocking. take a look at these issues #193 #203  #184 .

The other solution is to change your user agent that works but not all the time.

**About cookies:**
You need to provide all of them in other words simply copy any of the Authenticated Request Headers.

*Note* :- `I will be using Firefox in the below steps for extraction of cookies`
Steps. 
 - Login to your udemy account via browser.
 - Once you are logged in right click on page the search for option called **Inspect Element** and click on that.
 - Under that look for **Network Tab** and click on that. Under that **Network Tab** click on Requests type **XHR** .
 - Now click on **My Courses** in the Udemy navbar and refresh the page you will see some requests under **Network Tab**.
 - Right click on any of the Requests which is links to **udemy.com**. Simply copy **Request Headers** and save to text file. done you are good to go for downloading.

![untitled](https://user-images.githubusercontent.com/11024397/41338818-b1d6b886-6f0c-11e8-8fd0-0d21f32d1bf2.png)

**Comment by r0oth3x49** [comment]
@7ang i 'm closing the issue and hoping that every thing is clear now.

**Comment by adriannx** [comment]
@7ang I'm using the last version 2.7
