### ISSUE TITLE
do not download the courses

### ISSUE THREAD

**Issue by HotzLincoln** [r0oth3x49/udemy-dl#231]
As it is in the picture enter as I read in the description I log in and there is left or I have to wait for the previous version to load the first one I created at the touch I just had to load or I have to do something else to load it because it does not work
![udemy](https://user-images.githubusercontent.com/23439638/41366276-2fabd298-6f01-11e8-9452-ae3870b0bd64.png)

**Comment by r0oth3x49** [comment]
@HotzLincoln why don't you use cmd/powershell instead.

**Comment by HotzLincoln** [comment]
Thanks for cmd works well I thought that I only had to use git, as I do not surf the console a lot but now I thank you very much greetings from Peru
