### ISSUE TITLE
Udemy connection not reset after download of a video course

### ISSUE THREAD

**Issue by accorreia123** [r0oth3x49/udemy-dl#236]
After downloading successfully a course, and trying immediately download the next course, I get the error exemplified in the image. Only after several minutes, I am able to initiate the next download. 
It seems that the connection with the udemy site is maintained open and, only when the site kills it, a connection for the download of a new course is allowed.

![img](https://user-images.githubusercontent.com/10086579/41713004-e3b34260-7543-11e8-8f29-9fb377e799dd.png)

**Comment by r0oth3x49** [comment]
@accorreia123 this not because of udemy site is maintaining the connection as open. the reason for this is udemy detects attemps as robot and stops you, so you need to wait for few minutes to download the next one. take a look at in #184 . i 'm closing this as duplicate.

**Comment by accorreia123** [comment]
@r0oth3x49 Thanks for your reply.
I suggest to include a parameter in udemy-dl, in order that it could have the following behavior: pause for a moment (say 2 minutes) and automatically try it again until the course content is made available by udemy.
