### ISSUE TITLE
Downloading is very slow now .....!! please fix this

### ISSUE THREAD

**Issue by vivekpanchal** [r0oth3x49/udemy-dl#238]
last year when I use udemy-dl it was blazing fast and I downloaded the whole course in around 3 hours I guess, now I have put a course to download around 5 pm its now 9 pm and its still hasn't reached halfway through.
please fix this it takes too much time to download course now. I am getting 20mbps speed still its really slow

**Comment by r0oth3x49** [comment]
@vivekpanchal udemy-dl also have an option with switch `--save` through which you can save links to download using external programs such as `curl` etc. but i will try to fix this issue as i get free time

**Comment by r0oth3x49** [comment]
@vivekpanchal i 'm closing this issue and will w8 for other to report / suggestion for now the downloading part is okay.
