### ISSUE TITLE
Spanish Characters Support

### ISSUE THREAD

**Issue by Chlitzxer** [r0oth3x49/udemy-dl#24]
Hi first thanks for this magnificent script it would be nice to add support for Spanish characters like "á, é, í, ó, ú, ñ".

A good example is "https://www.udemy.com/universidad-java-especialista-en-java-desde-cero-a-master/" the files are coming for example` "019 Lecci n_ Variables en Java" instead of "Lección Variables en Java", same problem with the folder structure, comes "03 Fundamentos Java_ Instalaci n de JDK de Java y Herramientas" instead of "Fundamentos Java Instalación de JDK de Java y Herramientas".
`
Another change that would be great is replacing the character:`"_" for "-" (with an space for example "03 Fundamentos Java_ Instalaci n de JDK de Java y Herramientas" to "Fundamentos Java - Instalación de JDK de Java y Herramientas") when ":" is present in titles and video/attachments descriptions.
`
Thanks in advance, regards!

**Comment by r0oth3x49** [comment]
@Chlitzxer thanks for the suggestion. i will try to add this as soon as possible

**Comment by Chlitzxer** [comment]
@r0oth3x49 Thanks for your time and effort!

**Comment by Chlitzxer** [comment]
Hi @r0oth3x49 do you have any update? Regards!

**Comment by r0oth3x49** [comment]
@Chlitzxer i will update the code at weekend.

**Comment by Chlitzxer** [comment]
@r0oth3x49 Thanks! Another solution if is easier for you will be replace "á, é, í, ó, ú, ñ" for "a, e, i, o, u, n" at least that would be better than a blank space...

**Comment by r0oth3x49** [comment]
@Chlitzxer this solution looks great. can you please PM me the complete list of Spanish character on FB. so that according to above solution i can translate?

**Comment by Chlitzxer** [comment]
@r0oth3x49 The best place to check would be `http://www.columbia.edu/~fdc/misc/teclas.html` is not that long :) also I believe somebody opened a ticket for an issue with videos and files containing the symbol "?" in Spanish we also use "¿" to open a question...

The replacement for the letters on the link above would be "a, e, i, o, u, n" if is easier for you we are capable of reading no matter if the "tildes" are not on the letter :)

**Comment by r0oth3x49** [comment]
@Chlitzxer added feature you can check. i am closing the issue now.

**Comment by tofanelli** [comment]
hey @r0oth3x49 .... i used to have this same punctuation issue when I was using udemy-dl from Nishad, and to avoid the blank space instead the character, i used to used a DOS command called [chcp](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-xp/bb490874(v=technet.10)) and this change the console code page...

So, for me, to download courses in Brazilian Portuguese, i used 'chcp 860', so Udemy-dl recognize the code page and download using the right word. But, this is not working to use with yours, even if I enable the code page 65001 (UTF-8)...


any ideas? 

PS: There is a few more code pages [here](https://ss64.com/nt/chcp.html), if you may want to try them accordingly...

**Comment by Chlitzxer** [comment]
@r0oth3x49 The problem continues after the many updates that you did to the script :(

**Comment by tofanelli** [comment]
@Chlitzxer did you used the --unsafe flag?
