### ISSUE TITLE
General question 

### ISSUE THREAD

**Issue by leovarmak** [r0oth3x49/udemy-dl#242]
Hey,

Is this like a Udemy ripper that downloads course from Udemy or using this one can download courses that the user has already purchased?

**Comment by r0oth3x49** [comment]
@leovarmak did this repository looks like some kind 0-day or N-day? if not then you can only download courses, you already have paid for.

**Comment by leovarmak** [comment]
Looks like I pissed you off.  Sorry man

**Comment by r0oth3x49** [comment]
@leovarmak no man.
