### ISSUE TITLE
download only practice files related

### ISSUE THREAD

**Issue by yeguangteng** [r0oth3x49/udemy-dl#243]
First of all, thank you. Can you set up to download only practice files related, do not download video.

**Comment by yeguangteng** [comment]
Only download the practice file related, can you?

**Comment by r0oth3x49** [comment]
@yeguangteng currently there is no option but with `--sub-only` it also downloads the practice files. i will consider this as future enhancement. for now i 'm closing this issue

**Comment by yeguangteng** [comment]
谢谢您的回复，只下载练习文件确实很重要，等待你的改进。

**Comment by yeguangteng** [comment]
hank you for your reply. It's really important to just download the practice file and wait for your improvement.

**Comment by yeguangteng** [comment]
Thank you for your reply. It's really important to just download the practice file and wait for your improvement.

**Comment by r0oth3x49** [comment]
@yeguangteng soon will add this options any other suggestions are also welcome.
