### ISSUE TITLE
addition line break in the subtitle file

### ISSUE THREAD

**Issue by xXxsomebodyoncetoldmexXx** [r0oth3x49/udemy-dl#244]
There is a bug (i guess so) that  happen when i download the courses. it's automatically adding these line break at the end of each line in the subtitle files (the .srt files). Normally the srt file should look like this (when open with notepad):

````
1
00:00:00,141 --> 00:00:02,841
Thank you very much for taking this course.

2
00:00:03,005 --> 00:00:06,133
There are two basic
reasons to take this course.
````
but when i open it with other editor (Sublime text, etc) it turn out to be like this (when open with sublime):

````
1

00:00:00,141 --> 00:00:02,841

Thank you very much for taking this course.



2

00:00:03,005 --> 00:00:06,133

There are two basic

reasons to take this course.

````
Because of this those video player (window media, movie & tv,...) can not load the subtitle for the video.
If need i can also send you the file i download with udemy-downloader.
If this problem only happen to me can you suggest any solution so i can fix it? cause i have like dozens of course that also have this problem, i don't want to spend all day and night deleting line like a maniac :((

**Comment by r0oth3x49** [comment]
@xXxsomebodyoncetoldmexXx this not a bug but a default behavior of code which i have written for conversion. i have tested with `VLC player` and it works fine but i will check with these Players too & fix.

**Comment by xXxsomebodyoncetoldmexXx** [comment]
ok. let's me download the vlc player and test it out quick, thank you very much

**Comment by xXxsomebodyoncetoldmexXx** [comment]
well, one problem close another one open, now the subtitle is upside down :/
the subtitle should be showing this:
````
Hello there
General Kenobi
````
instead it giving me this:
````
General Kenobi
Hello there
````
here you can see an image, in which the subtitle are upside down 
![image](https://user-images.githubusercontent.com/31753655/42111997-8b731bce-7c10-11e8-926b-1f48976d4485.png)
