### ISSUE TITLE
problem in udemy Q & A section

### ISSUE THREAD

**Issue by sagarsamrat1** [r0oth3x49/udemy-dl#245]
is their any option available to download udemy Q & A section(Question and answer) also ?? how i can download all the udemy Question and answer section which i enrolled it in ??

**Comment by r0oth3x49** [comment]
@sagarsamrat1 currently no option to download Q & A section i will check if possible i will consider this as future enhancement.

**Comment by sagarsamrat1** [comment]
i wish u'll make it soon anyway thanks 4 ur word. :)
