### ISSUE TITLE
Missing chars on captions

### ISSUE THREAD

**Issue by tofanelli** [r0oth3x49/udemy-dl#247]
Hey @r0oth3x49 ... how's going? Hope fine

question.... I downloaded a course last week and noticed this
`prximas horas antes de comear.`

this sentence is missing 2 character, where it should be like
`próximas horas antes de começar`

Even if I use unsafe flag, it doesn't work...  just to let you know this =)

cheers =)

**Comment by r0oth3x49** [comment]
@tofanelli reason is --unsafe flag is for file names only not for file content will take a look at this.

**Comment by tofanelli** [comment]
Yeah @r0oth3x49 .... i know, but i just tried in case it could might work.... idk =).... 

thanks =)

**Comment by r0oth3x49** [comment]
@tofanelli added a fix for this try and let me know if it still miss the characters
