### ISSUE TITLE
What if i want the .vtt files for the Subtitle

### ISSUE THREAD

**Issue by BlacboyTheVirus** [r0oth3x49/udemy-dl#252]
Good day. 
What a great and useful script you have here.
What if i want the files for the subtitle as .vtt?

Can it be done?

Thanks.

**Comment by r0oth3x49** [comment]
@BlacboyTheVirus if you are asking about an option then there is currently no option available via command line but you can comment out line number 46,47,48,49 and 59, 60, 61, 62 in _vtt2srt.py file. this way udemy-dl will not delete the vtt files

**Comment by BlacboyTheVirus** [comment]
Thanks man. You the bomb.

**Comment by r0oth3x49** [comment]
@BlacboyTheVirus i 'm going to close this issue as future enhancement, and will add option to save vtt as well.
