### ISSUE TITLE
[-] Unable to extract login-form form

### ISSUE THREAD

**Issue by amilcarnetto** [r0oth3x49/udemy-dl#256]
Some courses, maybe with very long urls, don't download, like: https://www.udemy.com/data-science-deep-learning-in-theano-tensorflow/learn/v4/ and https://www.udemy.com/work-from-home-earn-income-by-building-websites-no-coding/learn/v4/

**Comment by akshayd29** [comment]
Getting the same error for https://www.udemy.com/kafka-connect/learn/v4/content

**Comment by Pvybhav** [comment]
I am also facing issue "[-] Unable to extract login-form form"

**Comment by r0oth3x49** [comment]
@amilcarnetto take a look at #184 i already have discuss this so many times and many issues.

**Comment by amilcarnetto** [comment]
many, many thanks @r0oth3x49 you work is great!
