### ISSUE TITLE
trouble logging into Account . password field taking to char but i am putting one char

### ISSUE THREAD

**Issue by vivekpanchal** [r0oth3x49/udemy-dl#259]
i am putting my password but the password field is taking two characters  i Dont know why i am putting up the correct password still  it show failed !!!  please fix this issue with the password

**Comment by sagarsamrat1** [comment]
same issue.

**Comment by r0oth3x49** [comment]
@vivekpanchal need more details. because i cannot reproduce.

**Comment by vivekpanchal** [comment]
@r0oth3x49  The field which takes password its printing 2 character but I am typing 1 characters, I am typing the exact password but can't log in to that in there might be some problem with the password field please have a look at it.

**Comment by sagarsamrat1** [comment]
same problem 4 me

**Comment by r0oth3x49** [comment]
@sagarsamrat1 , @vivekpanchal  i cannot reproduce. BTW there are more ways which also can be used to login instead, 

- cookie based
- configuration based
- direct using -u -p with course url.

why don't you try out that. 

and please take a look at old issues i have discussed and closed many issues reported the same. i cannot reproduce. also please take a look at issue reporting guideline in README.md

**Comment by sagarsamrat1** [comment]
yes you are correct :). i forgot that !!

**Comment by sagarsamrat1** [comment]
@vivekpanchal you can do it in another way, it can solved the problem. like this:
python udemy-dl.py <url> -u <udemyemailid> -p <udemypassword> and hit enter.
it will fix :).
