### ISSUE TITLE
Can I set up to download only the practice files? Very need, I hope you.

### ISSUE THREAD

**Issue by yeguangteng** [r0oth3x49/udemy-dl#263]
Can I set up to download only the practice files? Very need, I hope you.

**Comment by r0oth3x49** [comment]
@yeguangteng currently there is no option to download specifically assets/practice files as i already discussed in this [issue](https://github.com/r0oth3x49/udemy-dl/issues/243) created by you

You can download them with subtitles only option `--sub-only` with this option udemy-dl will only download subtitles and practice files.
