### ISSUE TITLE
practice test as flash file

### ISSUE THREAD

**Issue by sohaibsalih** [r0oth3x49/udemy-dl#264]
Hi would you please let me know how I can download Udemy question course I mean the practice test from Udemy I deal with paython trick but it's only for downloading vedio courses I need to download questions course practice test from Udemy thanks?

**Comment by r0oth3x49** [comment]
@sohaibsalih 'm not getting your point can you explain a bit more. what i understand is, You want download quizzes in a course as well 'm i right?

if yes then downloading quizzes is out of scope, and udemy-dl don't have an option to download one.

**Comment by sohaibsalih** [comment]
I mean Udemy Practice Test some Udemy course dose not  contain any video lecture its just Practice Test with answer  pleas check ((https://support.udemy.com/hc/en-us/articles/231954647-Practice-Test-FAQs))

I need to download it as flash format or any if its  out of scope please guide me to another tool

**Comment by r0oth3x49** [comment]
@sohaibsalih these are certification test and this is out of scope. you can search on Github for similar programs like this that might have support for this. closing the issue.
