### ISSUE TITLE
It was working all fine but this happen after last pull!

### ISSUE THREAD

**Issue by annata83** [r0oth3x49/udemy-dl#277]
Hi, I usually pull updates from Git projects to stay updated. Today I pull From here and after that, the error message show as Below. I did remove and git clone from scratch with same results.

Traceback (most recent call last):
  File "udemy-dl.py", line 7, in <module>
    import udemy
  File "/home/niko/udemy-dl/udemy/__init__.py", line 32, in <module>
    from ._udemy import course
  File "/home/niko/udemy-dl/udemy/_udemy.py", line 26, in <module>
    from ._internal import InternUdemyCourse as Udemy
  File "/home/niko/udemy-dl/udemy/_internal.py", line 30, in <module>
    from ._extract import Udemy
  File "/home/niko/udemy-dl/udemy/_extract.py", line 48, in <module>
    from ._sanitize import (
  File "/home/niko/udemy-dl/udemy/_sanitize.py", line 10, in <module>
    from unidecode import unidecode
ModuleNotFoundError: No module named 'unidecode'

Here is the course Url: https://www.udemy.com/the-complete-internet-security-privacy-course-volume-1/learn/v4/content

I am running Inside Manjaro KDE 17.1.12 with Python 3.7.0.
Comand use to download: 
python udemy-dl.py https://www.udemy.com/the-complete-internet-security-privacy-course-volume-1/learn/v4/content

**Comment by r0oth3x49** [comment]
@annata83 did you installed all the requirements because the issue you are facing is clearly stats that you haven't installed the requirements to run this utility.

clone and then install the requirements before running. 

***Remember :- this utility cannot be installed via pip***
### Example
- pip install -r requirements.txt
### OR
- pip install unidecode six requests

**Comment by u1k-arsh** [comment]
@annata83 found simplest solution. Put the installed unidecode dir to the repo folder. Worked for me!
