### ISSUE TITLE
Download stops if a file listed in the course information does not exist

### ISSUE THREAD

**Issue by EddyVos** [r0oth3x49/udemy-dl#280]
Using Windows 10 with Python 3.6.2 and the master download (18 september 2018)  of the udemy-dl application.

URL trying to download is 
https://www.udemy.com/java-the-complete-java-developer-course/learn/v4/overview

```
Traceback (most recent call last):
  File "udemy-dl.py", line 1441, in <module>
    main()
  File "udemy-dl.py", line 1437, in main
    udemy.course_download(path=options.output, quality=options.quality, unsafe=options.unsafe)
  File "udemy-dl.py", line 511, in course_download
    self.download_lectures_and_captions(lecture_best=lecture_best, lecture_title=lecture_title, inner_index=inner_index, lectures_count=lectures_count, lecture_subtitles=lecture_subtitles, lecture_assets=lecture_assets, filepath=filepath, unsafe=unsafe)
  File "udemy-dl.py", line 429, in download_lectures_and_captions
    self.download_assets(lecture_assets=lecture_assets, filepath=filepath, unsafe=unsafe)
  File "udemy-dl.py", line 338, in download_assets
    assets.download(filepath=filepath, unsafe=unsafe, quiet=True, callback=self.show_progress)
  File "D:\tools\udemy-dl-new\udemy-dl-master\udemy\_shared.py", line 594, in download
    return self._write_external_links(filepath)
  File "D:\tools\udemy-dl-new\udemy-dl-master\udemy\_shared.py", line 512, in _write_external_links
    with open('{}.txt'.format(filename), 'a', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\UDL\\01\\java-the-complete-java-developer-course\\05 Java Tutorial Expressions Statements Code blocks Methods and more\\025 Source-Code-Java-Tutorial-Expressions-Statements-Code-blocks-Methods-and-more-Statements-Whitespace-and-Intentation-Code-Organization-.txt'
```

**Comment by r0oth3x49** [comment]
@EddyVos thanks for using this utility. the reason you are facing this error is because by default windows allows 260 characters in path. 
- Max Path length of the current file is 261.
but you can disable the path limit in windows 10. 
python3 asks to disable path limit while installing.
take a look at this article [disable path limit](https://aatayyab.wordpress.com/2016/12/25/install-programming-language-python-for-windows-10-64-bit/)

**Comment by tofanelli** [comment]
@EddyVos another thing you can do, and better, is to mover udemy-dl to a root folder, like

`D:\tools\udemy-dl`

instead of 

`D:\tools\udemy-dl-new\udemy-dl-master\`

**Comment by EddyVos** [comment]
Thanks all!
Reinstalled python with the option to disable the file length. Did not notice that one after installing the first time. 
I managed to download my course.

**Comment by r0oth3x49** [comment]
@tofanelli thanks for the alternate solution. @EddyVos now the path problem is fixed for you so i 'm going to close this issue.
