### ISSUE TITLE
Problem with audio mp3

### ISSUE THREAD

**Issue by oskippy** [r0oth3x49/udemy-dl#289]
Hello,

I have issues with audio contents with mp3  datas.

i become all the time this message  doesn't matter if i'm in unsafe modus  or not

Traceback (most recent call last):
  File "udemy-dl.py", line 1441, in <module>
    main()
  File "udemy-dl.py", line 1437, in main
    udemy.course_download(path=options.output, quality=options.quality, unsafe=o
ptions.unsafe)
  File "udemy-dl.py", line 502, in course_download
    dimension = int(lecture_streams[index].dimention[1])
ValueError: invalid literal for int() with base 10: 'Audio'

the text is in this form

Bonus - Audio Version For Your Ipod or Smartphone
34. AUDIO: Introduction 4:02
35. AUDIO: Regret#1 Revealed! 2:00
36. AUDIO: How to discover your true purpose in life 17:01
37. AUDIO: how to discover what your values are & how to live by them 3:33
38. AUDIO: how to create an action plan for your life 3:40

Thanks for you great work !

Regards

**Comment by r0oth3x49** [comment]
@oskippy thanks for using this utility. it will be great if you follow the [Issue Reporting Guideline](https://github.com/r0oth3x49/udemy-dl#issue-reporting-guideline) and to resolve the issue i might request your credentials if needed (in case i don't have the course for fixing purpose).

**Comment by oskippy** [comment]
Hi the course is https://www.udemy.com/be-your-own-hero/learn/v4/overview

Thanks

**Comment by oskippy** [comment]
Hello,

i put 2 print in the code 

line 502 print ('lecture_streams', lecture_streams[index], lecture_streams[index].dimention)
line 513 print ("lecture_best", lecture_best)

i have as output :

[*] : Lecture(s) : (1 of 24)
[*] : Downloading (034 AUDIO Introduction)
[*] : Lecture : '034 AUDIO Introduction' (download skipped).
[-] : Reason : [Errno 2] No such file or directory: 'c:\\temp\\udemy-dl-master\\be-your-own-hero\\08 Bonus - Audio Version For Your Ipod or Smartphone\\034 AUDIO Introduction.audio/mp3.part'
lecture_streams video:audio/mp3@256xAudio ('256', 'Audio')
lecture_best video:audio/mp3@256xAudio

[*] : Lecture(s) : (2 of 24)
[*] : Downloading (035 AUDIO Regret1 Revealed)
[*] : Lecture : '035 AUDIO Regret1 Revealed' (download skipped).
[-] : Reason : [Errno 2] No such file or directory: 'c:\\temp\\udemy-dl-master\\be-your-own-hero\\08 Bonus - Audio Version For Your Ipod or Smartphone\\035 AUDIO Regret1 Revealed.audio/mp3.part'
lecture_streams video:audio/mp3@256xAudio ('256', 'Audio')
lecture_best video:audio/mp3@256xAudio

i think the problem is the / 

Hope this help.

Regards

**Comment by r0oth3x49** [comment]
@oskippy i will try to reproduce and fix ASAP against course --> `https://www.udemy.com/golden-lies-the-ultimate-guide-for-the-creative-soul/learn/v4/content`.

**Comment by oskippy** [comment]
Ok thanks hope the little modifications helps
