### ISSUE TITLE
Error: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9

### ISSUE THREAD

**Issue by VuNguyen102** [r0oth3x49/udemy-dl#291]
Hi,

I have an issues when I try to download a lecture of chapter from udemy. Could you please help to look and advise me how to fix it?
![image](https://user-images.githubusercontent.com/17152694/47642617-b0f41480-db9b-11e8-8b38-cda004874bc2.png)

Many Thanks,
Tony

**Comment by VuNguyen102** [comment]
This is the link for your reference: 
https://www.udemy.com/learn-linux-in-5-days/
The error appeared from chapter 5.

**Comment by r0oth3x49** [comment]
@VuNguyen102 i will try to reproduce and fix ASAP.

**Comment by VuNguyen102** [comment]
@r0oth3x49 I have tried with flag --unsafe however still the same result.

**Comment by r0oth3x49** [comment]
@VuNguyen102 i don't have this course, So to be able to resolve this issue i might need your credentials, if you are okay with that you can [email me](mailto:nasir251292@gmail.com) your credentials.
