### ISSUE TITLE
"Unable to extract course idation" error

### ISSUE THREAD

**Issue by pppedrillo** [r0oth3x49/udemy-dl#299]
Just picked up the latest sources and now getting an error

                                Version : 0.5
                                 Author  : Nasir Khan (r0ot h3x49)
                                 Github  : https://github.com/r0oth3x49

[*] : Trying to login as (termoblad69@mail.ru)...
[+] : Logged in successfully.
[-] Unable to extract course idation ..

**Comment by ioanvapi** [comment]
The same here on Windows 10. Running with python 2.7.13. I've just started to download one course. No previous download. I've tried both login and logout from udemy in chrome.

**Comment by scavdar** [comment]
I have same problem on MacOS.

**Comment by r0oth3x49** [comment]
@pppedrillo , @ioanvapi , @scavdar  please take a look at #295 i already have fixed the issue.

**Comment by pppedrillo** [comment]
Waiting and re-login in the browser did not help me. Still unable to download course :(

**Comment by postacik** [comment]
Waiting and relogin unfortunately does not work me, either.

[*] : Trying to login as (xxxxx@yahoo.com)...
[+] : Logged in successfully.
[-] Unable to extract course idation ..

**Comment by ioanvapi** [comment]
Thank you @postacik. You are right. It worked after adding the slash at the end.

**Comment by khansaad** [comment]
Hi @r0oth3x49 

I'm experiencing the same issue. I have downloaded the latest version.
and I'm running the following script: 
python udemy-dl.py https://xxxx.udemy.com/spring-hibernate-tutorial/learn/v4/overview -u abcd@xxxx.com -p pass

![udemy](https://user-images.githubusercontent.com/11271971/48265738-47092400-e453-11e8-9510-02c2710b2714.JPG)

**Comment by pppedrillo** [comment]
Thanks @postacik ! It works with trailing slash !

**Comment by ashokdey** [comment]
Take the latest pull and it's working awesome. This issue bothered me since last 7 days. I took the latest pull today and everything is working as usual.
