### ISSUE TITLE
Skipped. Expected quality not found!

### ISSUE THREAD

**Issue by raymestalez** [r0oth3x49/udemy-dl#30]
Hi there! I'm getting an error:

```
[CRITICAL-238] Skipped. Expected quality not found!
```

On different courses. I've tried to add the `-q` flag, but the same error.

Can you help me out?

**Comment by Chlitzxer** [comment]
@raymestalez you are not using this script you must be sing udemy-dl from python repository,  to fix that install aria2c but again you are using the wrong script...

**Comment by raymestalez** [comment]
You're right, cloned script from this repo, installed dependencies, and everything works! Awesome! Thank you very much for this excellent project!
