### ISSUE TITLE
403 Forbidden retry after few minutes ...

### ISSUE THREAD

**Issue by TheBaby5** [r0oth3x49/udemy-dl#302]
[*] : Trying to login as (*********@gmail.com)...
[-] : Udemy Says : 403 Forbidden retry after few minutes ...

**Comment by r0oth3x49** [comment]
@TheBaby5 this error only occurs when, either you are not waiting for few minutes or your SSL is outdated. i cannot reproduce this.

try upgrading packaged manually using pip. specially the installed by `requests[security]`
