### ISSUE TITLE
Udemy Says : 403 Forbidden retry after few minutes

### ISSUE THREAD

**Issue by gopal032** [r0oth3x49/udemy-dl#306]
Issue number 298 is closed but this is still an issue for so many members. Pls see the comments from users. I too am facing the same issue. Updated everything and even for the first download I get the error.

[*] : Trying to login as (gopal.nayak@*****.com)...
[-] : Udemy Says : 403 Forbidden retry after few minutes ...

**Comment by gopal032** [comment]
It works with latest update. So closing it.

**Comment by kaungdev** [comment]
it's occurring again

**Comment by tangzhiyin** [comment]
![9TF%X8H% 4TJ_4557AQTAPY](https://user-images.githubusercontent.com/38394543/55847940-f1f64900-5b7d-11e9-89c3-c04afdbf044f.png)

I use the way to solve the 400 problem,but this problem I can`t solve it
