### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 20: ordinal not in range(128)

### ISSUE THREAD

**Issue by raul93611** [r0oth3x49/udemy-dl#308]
OS: Ubuntu 18
python 2
The lastest version udemy-dl
![captura de pantalla de 2018-11-26 10-31-40](https://user-images.githubusercontent.com/27871832/49020331-9004ec00-f166-11e8-8785-c43c547d995d.png)
I tried with all my courses but I have the same error.

**Comment by raul93611** [comment]
I solved my problem:
First: Set 'UTF-8' like default.
`import sys
reload(sys)
sys.setdefaultencoding('utf8')`

Second: Use `encode()` instead of `str()`

I don't know if someone else got this problem.

**Comment by r0oth3x49** [comment]
@raul93611 there is already a switch available `--unsafe` check README **Features**

**Comment by raul93611** [comment]
I tried the `--unsafe` , but I got the same error.

**Comment by r0oth3x49** [comment]
i think with latest pull this should not be the case. but still i would love to reproduce and fix. are you using unicode characters in your directories because the course name seems okay to me. what was your complete command
