### ISSUE TITLE
403 Unauthorized

### ISSUE THREAD

**Issue by Keweb** [r0oth3x49/udemy-dl#309]
hello, im already download new udemy-dl but still error with me, i use windows 10 google crome with my browser

![capture](https://user-images.githubusercontent.com/18476093/49035176-f6cde800-f1ee-11e8-9f9c-acab640c2a75.PNG)

and 

im using --upgrade to but not work

**Comment by mnovak20** [comment]
Having the same issue, been seeing the `[-] Unable to extract login-form form` for a while so upgraded udemy-dl but now I'm consistently seeing the 403 error.

**Comment by Keweb** [comment]
> Having the same issue, been seeing the `[-] Unable to extract login-form form` error for a while so upgraded udemy-dl but now I'm consistently seeing the 403 error.

im waiting sir :D @r0oth3x49

**Comment by jlfrank312** [comment]
Just chiming in to say that it's still working for me, using the cookie method.

**Comment by 4ngeluxpunk** [comment]
The same thing happens to me the error of cookies, before it was only to some detailed courses, now it comes out in all you can not download anything.

**"Udemy Says : 403 Unauthorized, it seems your cookie based session got expired ..."**
![error udemy](https://user-images.githubusercontent.com/22511504/49050797-16dfb600-f1b3-11e8-9742-281839ae013a.png)

**Comment by mnovak20** [comment]
@jlfrank312 you're right I didn't see the part about cookies in the readme. 
Creating a cookies.txt and adding the -k flag with the file name worked for me. 
It'll be annoying to have to update the cookie but at least it works.

**Comment by 4ngeluxpunk** [comment]
@mnovak20 o @jlfrank312 Dear have a source where you can get the cookies and use them, or what cookies have been placed for them to work. Greetings.

**Comment by mnovak20** [comment]
@4ngeluxpunk 
towards the middle of the readme.md you'll see
```
Extracting Cookies / Request Headers
Login to your udemy account via browser.
Once you are logged in right click on page the search for option called Inspect Element and click on that.
Under that look for Network Tab and click on that. Under that Network Tab click on Requests type XHR .
Now click on My Courses in the Udemy navbar and refresh the page you will see some requests under Network Tab.
Right click on request links to udemy.com/api-2.0/. Simply copy Request Headers and save to text file.
The above guide is for Firefox users. Chrome Users can follow guide by @lamlephamngoc.
Done run the udemy-dl against that text file it will start downloading the course.
```
I'm on Chrome so I followed the instructions in the guide by @lamlephamngoc. 

In my case

- I copied the headers as cURL from a call to udemy from Chrome.
- Pasted that in a cookies.txt file that I created and moved said file to the dl-udemy directory.
- Then called ` python udemy-dl.py [course url] -k cookies.txt` and the download began without the 403 error.

**Comment by tofanelli** [comment]
@mnovak20 ... and where is this guide??

**Comment by mnovak20** [comment]
@tofanelli look in the readme...https://github.com/r0oth3x49/udemy-dl#extracting-cookies--request-headers

**Comment by r0oth3x49** [comment]
> 
> 
> hello, im already download new udemy-dl but still error with me, i use windows 10 google crome with my browser
> 
> ![capture](https://user-images.githubusercontent.com/18476093/49035176-f6cde800-f1ee-11e8-9f9c-acab640c2a75.PNG)
> 
> and
> 
> im using --upgrade to but not work

already fixed will push in evening.

**Comment by r0oth3x49** [comment]
> 
> 
> The cookie method doesn't work every time for me....

whats the errror?

**Comment by landerover** [comment]
I've tried both with cookie and classic login but not work.
With classic login I riceved 403 and with cookie "Udemy Says : 400 Bad Request retry after few minutes ..."

**Comment by khansaad** [comment]
Thanks @mnovak20 , it's working by adding the cookies part.

**Comment by pedroricardo** [comment]
For those who still have doubts

1 Login to your udemy account via browser.
2 Once you are logged in right click on page the search for option called Inspect Element and click on that.
3 Under that look for Network Tab and click on that. Under that Network Tab click on Requests type XHR .
4 Now click on My Courses in the Udemy navbar and refresh the page you will see some requests under Network Tab.
5 Right click on request links to udemy.com/api-2.0/. Simply copy Request Headers and save to text file.
https://imgur.com/a/PvLPtEY
6  Then paste inside the `cookies.txt` file and save
7 At the end execute the command `python udemy-dl.py [course url] -k cookies.txt`

**Comment by tofanelli** [comment]
@pedroricardo and for those who use Chrome on Windows, which option is the right one?

![image](https://user-images.githubusercontent.com/5512922/49105904-e9554400-f268-11e8-84f6-a5bb0ae9c3c0.png)

**Comment by r0oth3x49** [comment]
@tofanelli either copy as cURL (cmd) or (bash) both will work.

**Comment by tofanelli** [comment]
There is no need anymore for using cookies =).... @r0oth3x49 nailed once again and its working flawlessly now =)

Thanks again man =)
