### ISSUE TITLE
The argument --names does not generate a list of course readings, as it should.

### ISSUE THREAD

**Issue by oijm17** [r0oth3x49/udemy-dl#315]
The argument  --names download the course files normally, but you should only generate a file with the names of each reading and chapter of the course. It is not like this?

This is my command: 
sudo python udemy-dl.py -u EMAIL -p PASSWORD --unsafe https://www.udemy.com/curso-completo-de-hacking-etico/learn/v4/t/lecture/7392860?start=0 -q 1080 --names

**Comment by r0oth3x49** [comment]
@oijm17 i will try to reproduce and fix ASAP.

**Comment by oijm17** [comment]
Thank you very much, now and generate the list, but again I found an inconvenient: What happens is the same as the previous example. of the course. Here is a fragment of the content of the text file that generated the script:

> 001 Presentation
> 001 Presentation
> 002 Objectives and organization of the course.
> 003 Key points for a better use of the course
> 004 Definitions and basic terms.
> 005 Introduction to the module
> 006 Basic notions
> 007 Using Mailinator and how to evade controls
> 008 attack vectors
> 009 Security devices
> 010 methodologies
> 010 methodologies
> 010 methodologies
> 010 methodologies
> 010 methodologies
> 011 Introduction of the module
> 011 Introduction of the module
> 011 Introduction of the module
> 012 Main Distributions of Ethical Hacking
> 012 Main Distributions of Ethical Hacking
> 013 Main vulnerable distributions
> 013 Main vulnerable distributions
> 013 Main vulnerable distributions
> 013 Main vulnerable distributions
> 013 Main vulnerable distributions
> 013 Main vulnerable distributions
