### ISSUE TITLE
@oijm17 i will try to reproduce and fix ASAP.

### ISSUE THREAD

**Issue by oijm17** [r0oth3x49/udemy-dl#316]
**Edit**
- this command will not output the names to stdout / terminal, but will save the names to a file.
![capture](https://user-images.githubusercontent.com/11024397/49694915-3a8ffc80-fbb4-11e8-9efc-082236c51d51.PNG)

_Originally posted by @r0oth3x49 in https://github.com/r0oth3x49/udemy-dl/issues/315#issuecomment-445518630_

Thank you very much, now and generate the list, but again I found an inconvenient: What happens is the same as the previous example. of the course. Here is a fragment of the content of the text file that generated the script:

> 001 Presentation
> 001 Presentation
> 002 Objectives and organization of the course.
> 003 Key points for a better use of the course
> 004 Definitions and basic terms.
> 005 Introduction to the module
> 006 Basic notions
> 007 Using Mailinator and how to evade controls
> 008 attack vectors
> 009 Security devices
> 010 methodologies
> 010 methodologies
> 010 methodologies
> 010 methodologies
> 010 methodologies
> 011 Introduction of the module
> 011 Introduction of the module
> 011 Introduction of the module
> 012 Main Distributions of Ethical Hacking
> 012 Main Distributions of Ethical Hacking
> 013 Main vulnerable distributions
> 013 Main vulnerable distributions
> 013 Main vulnerable distributions
> 013 Main vulnerable distributions
> 013 Main vulnerable distributions
> 013 Main vulnerable distributions

**Comment by r0oth3x49** [comment]
@oijm17 again i cannot reproduce for me it works fine i might need your account to reproduce or else i will close the issue because you want get the names only and for you now it is serving the purpose.
![1128_4971](https://user-images.githubusercontent.com/11024397/49995245-642e9680-ffad-11e8-91e4-9c05e9e445ce.png)
