### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by progamerz** [r0oth3x49/udemy-dl#32]
Course: [https://www.udemy.com/complete-android-developer-course/](url)
Operating System: Windows 7
Ran the .bat as administrator

https://i.imgur.com/e1csUKx.png

**Comment by r0oth3x49** [comment]
@progamerz this is not the issue i think th problem is windows don't allow filename length greater then 255 chars.
read here.
`https://stackoverflow.com/questions/265769/maximum-filename-length-in-ntfs-windows-xp-and-windows-vista`

**Comment by progamerz** [comment]
Ok ill try it now thanks :)

**Comment by progamerz** [comment]
@r0oth3x49 working well now thanks after using "E:\courses"
