### ISSUE TITLE
Getting course id not found 

### ISSUE THREAD

**Issue by sukheja-varun** [r0oth3x49/udemy-dl#320]
Unable to download the tutorial 

I am using below cmd:
python3 udemy-dl.py https://www.udemy.com/ionic-4-crash-course-with-heartstone-api-angular/ -q 720

[+] : Logged in successfully.
[-] : Downloading course information, course id not found .. (failed)
[i] : It seems either you are not enrolled or you have to visit the course atleast once while you are logged in.
[*] : Trying to logout now...
[+] : Logged out successfully.

**Comment by jaan143** [comment]
@sukheja-varun  how to fix this issue
i am facing this issue also evan i visited that course in browser also but again getting this error
