### ISSUE TITLE
any update on 1080p downloads?

### ISSUE THREAD

**Issue by rando4201** [r0oth3x49/udemy-dl#323]
udemy-dl is only letting me download 720p, youtube-dl allowed to do so but its broken(403 unauthorised) from a month or so.
i can see this in future-enhancement from a year but can we expect this anytime soon?

**Comment by r0oth3x49** [comment]
@rando4201 i will take a look at that, actually i dint get that much time, busy in some projects.but i will probably take a look at this feature on coming weekend.

**Comment by iZero7** [comment]
+2
