### ISSUE TITLE
Fails to download archived courses

### ISSUE THREAD

**Issue by rpgrca** [r0oth3x49/udemy-dl#324]
The program failed to download a course that has been archived. Temporarily unarchiving it made it possible to proceed.

```
[*] : Trying to login using cookies ...
[+] : Logged in successfully.
[-] : Downloading course information, course id not found .. (failed)
[i] : It seems either you are not enrolled or you have to visit the course atleast once while you are logged in.
[*] : Trying to logout now...
[+] : Logged out successfully.
```

**Comment by r0oth3x49** [comment]
> 
> 
> The program failed to download a course that has been archived. Temporarily unarchiving it made it possible to proceed.
> 
> ```
> [*] : Trying to login using cookies ...
> [+] : Logged in successfully.
> [-] : Downloading course information, course id not found .. (failed)
> [i] : It seems either you are not enrolled or you have to visit the course atleast once while you are logged in.
> [*] : Trying to logout now...
> [+] : Logged out successfully.
> ```

you can see the error gives the guide to which is `you have to visit the course atleast once while you are logged in`, But i will try to reproduce and fix ASAP.

sorry for late response.
