### ISSUE TITLE
Downloading on flaky connections -- getting stuck

### ISSUE THREAD

**Issue by smart-lemon** [r0oth3x49/udemy-dl#329]
This is similar to #84 

Sometimes on a poor internet connection the download gets stuck. I'm not able to reproduce it regularly but it happens from time to time  

Platform Mac OS x 10.12.5  
Python - 3.7
 
By the way I implemented a time-out mechanism that skips the download after 25 minutes of waiting  as a last ditch attempt to solve it using interuptingcow 

Please check my fork and let me know your feedback : 
https://github.com/smart-lemon/udemy-dl/commits/master 

(Ideally it would be nice to have a back-off retry implementation for this ..

Thanks for developing this tool 💯

**Comment by r0oth3x49** [comment]
@smart-lemon i will check this and implement in next version the timeout mechanism as well.
