### ISSUE TITLE
400 bad request

### ISSUE THREAD

**Issue by dawar302** [r0oth3x49/udemy-dl#342]

**Comment by felipe-negri** [comment]
i have bad request to with the course link https://www.udemy.com/curso-de-desenvolvimento-android-oreo

**Comment by zdocker** [comment]
I have same problem

**Comment by sarahsga** [comment]
same problem

![Screen Shot 2019-03-14 at 10 14 40](https://user-images.githubusercontent.com/10798986/54332891-0825ed80-4642-11e9-8544-4d7775dfeb1c.png)

**Comment by aderaHenry** [comment]
The login step is failing. I'm getting the same message

**Comment by r0oth3x49** [comment]
let keep this conversation in one place #341 . i 'm looking into the issue. closing this
