### ISSUE TITLE
Download doesn't work for udemy business

### ISSUE THREAD

**Issue by Marcel-Lambacher** [r0oth3x49/udemy-dl#35]
I've tried to use your tool with udemy for business, but the download doesn't work. This is caused by the hardcoded udemy url in your source code. Also if you want to use udemy business, you've adjust the login scrf regex pattern.

Overall the changes to get your tool working with udemy business is pretty simple.
I would offer myself to develop this feature. Are you interested in this?

**Comment by r0oth3x49** [comment]
@Marcel-Lambacher this is out of scope because i don't have any business account for udemy that's why it only works for default udemy.

**Comment by jman69** [comment]
@Marcel-Lambacher I would love to see this feature. Would you be willing to fork this project and make the necessary changes even if they don't get merged back into this project? Thanks

**Comment by Marcel-Lambacher** [comment]
Hello Jman69,

unfortunately I'll not contribute or fork this software anymore. Overall there are some more issues in this software, so I made the decission to write an own version of this udemy downloader. If you're interessted you're welcome to visit my profile. There is a project called "UdemyDownloader". At this moment, the software is far away to be finish. I guess you can use it for downloading in about 2 Months.

**Comment by r0oth3x49** [comment]
@Marcel-Lambacher sorry if you mind my words. @jman69 i have tested the latest `repo` against one of udemy business account and it is working fine now for me & for many friends as well.

**Comment by jman69** [comment]
@r0oth3x49 using the latest repo the error is `You are not enrolled in this course Udemy Says : Resource not found..`. I don't think the repo as is supports the necessary differences in the URLs for Business accounts, and how the login form is different from the generic www.udemy.com one. It needs to support the form and csrf token format on business URLs like https://trial.udemy.com/organization/login/. Thanks for trying

**Comment by r0oth3x49** [comment]
**@jman69 it means it logs you in successfully or i am wrong?**
Here is what you get when you download a course from udemy business correct me if i am wrong?
![untitled](https://user-images.githubusercontent.com/11024397/33805534-4cb4b5dc-dddc-11e7-96b0-357901f871d2.png)

it means in your account you did not enrolled in this particular course so simply go to the course URL and enroll your self then try to download. I did the same and have a look i 'm using udemy business.
![untitled11](https://user-images.githubusercontent.com/11024397/33805540-76a2f49e-dddc-11e7-8ae9-3d9eb2bc9234.png)

**Comment by jman69** [comment]
@r0oth3x49 it works when the URL has /learn/v4 at the end of it it. Just the plain URL without that I get the error that I'm not enrolled.

**Comment by r0oth3x49** [comment]
@jman69 i just tested the way you said `works when URL has /learn/v4` seems magical :P . i am looking whats going on. but the fact is, it works for you now on your business account am i right?

**Comment by jman69** [comment]
@r0oth3x49 yes it works with the /learn/v4 URL on a busienss account nicely. Thanks for keeping working on this! hope you find the issue with the other URL!

**Comment by r0oth3x49** [comment]
@jman69 always welcome. enjoy your learning 👍 and thanks for using this utility.

**Comment by ankitwebs** [comment]
I think there has been some updates in Udemy for business authentication. The steps above are not working now and the error I'm getting is "Failed to login"

**Comment by raviswp** [comment]
Hi @r0oth3x49
Can you please answer the above comment by @antustephen , I am also looking for the same. Please reply earliest

**Comment by r0oth3x49** [comment]
> 
> 
> Will it work if the corporate udemy URL like "http://xylearning.udemy.com" redirects to SSO authentication page "https://accessidp.idaas.xy.net/idp/SSO.saml" andthen gets redirected back to udemy page. What should we be doing to login and download the course

No. you should be using cookie based method instead.

- once you authenticate using browser and redirected back to the udemy course then extract the cookies to file and use that cookie to download a course

**Comment by r0oth3x49** [comment]
> 
> 
> Hi @r0oth3x49
> Can you please answer the above comment by @antustephen , I am also looking for the same. Please reply earliest

as i said you should be using cookie based method instead
