### ISSUE TITLE
Issue Downloading Since Latest Udemy Update

### ISSUE THREAD

**Issue by Labeyoo** [r0oth3x49/udemy-dl#351]
I can't download courses since the implementation of new interface...

I used to download using -k Cookies method

But it no longer works

![Capture](https://user-images.githubusercontent.com/48537907/54837438-c8dc4a00-4c9c-11e9-9f0d-f3f3d0788c8d.JPG)

**Comment by r0oth3x49** [comment]
@Labeyoo it works fine for me i cannot reproduce. take a look at screen shot below
![Capture](https://user-images.githubusercontent.com/11024397/54840460-f05c0280-4cee-11e9-8917-b6155446836c.PNG)

**Comment by ps-feng** [comment]
I could reproduce an error with this stacktrace on Windows 10 with cookies extraced via Chrome (`Copy as cURL(cmd)`):
```
Traceback (most recent call last):
  File ".\udemy-dl.py", line 1432, in <module>
    main()
  File ".\udemy-dl.py", line 1091, in main
    udemy.course_download(path=options.output, quality=options.quality, unsafe=options.unsafe)
  File ".\udemy-dl.py", line 425, in course_download
    course = udemy.course(url=self.url, username=self.username, password=self.password, cookies=self.cookies)
  File "C:\Users\chess\git\udemy-dl\udemy\_udemy.py", line 38, in course
    return Udemy(url, username, password, cookies, basic, callback)
  File "C:\Users\chess\git\udemy-dl\udemy\_internal.py", line 44, in __init__
    super(InternUdemyCourse, self).__init__(*args, **kwargs)
  File "C:\Users\chess\git\udemy-dl\udemy\_shared.py", line 63, in __init__
    self._fetch_course()
  File "C:\Users\chess\git\udemy-dl\udemy\_internal.py", line 52, in _fetch_course
    auth = self._login(cookies=self._cookies)
  File "C:\Users\chess\git\udemy-dl\udemy\_extract.py", line 107, in _login
    self._session._session.cookies.update(self._cookies)
AttributeError: 'NoneType' object has no attribute '_session'
```
I tried manually replacing the access token value in line 106 (`self._session = auth.authenticate(access_token=access_token, client_id=client_id)`) and it worked, so I guess there's some problem with the parser.

**Comment by brundidge** [comment]
How to login with cookie for <i><b>Chrome</b></i> Users with only 4 steps:
1) Make sure you are <b>already logged in</b>, <b>right click</b> anywhere on the Udemy webpage and click <b>"Inspect"</b> or use shorcut button "F12"

![1](https://user-images.githubusercontent.com/48912654/55044304-ac8c3480-5031-11e9-8a65-683d5e4d9b14.jpg)

2) Choose "Application" tab on the top, then choose "Cookies" on the left, what we need here are values of <b>access_token</b> and <b>client_id</b>. You can type into <b>Filter</b> to find exactly what you need. Double click and copy those values.

![2](https://user-images.githubusercontent.com/48912654/55044592-d7c35380-5032-11e9-965d-f7a8e88c1ea5.jpg)

3) Create a <b>".txt"</b> file inside udemy-dl folder, name it whatever you want

![3](https://user-images.githubusercontent.com/48912654/55044710-4ef8e780-5033-11e9-8285-98c68335304e.jpg)

4) Edit the file you just created, copy and paste this line, change <b>yourAccessToken</b> and <b>yourClientId</b> with values from <b>step 2</b>. Save the file.

`Cookie: access_token=yourAccessToken client_id=yourClientId`

![4](https://user-images.githubusercontent.com/48912654/55044958-173e6f80-5034-11e9-9ec7-7ea4ee4b661f.png)

5) Use the code below to download with cookie, replace <b>courseURL</b> with link of your course, <b>fileTXT</b> with the name of your txt file from <b>step 3</b>

`python udemy-dl.py courseURL -k fileTXT`

![5](https://user-images.githubusercontent.com/48912654/55045546-042c9f00-5036-11e9-92f5-a6c5b9e3dddc.png)
