### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by brundidge** [r0oth3x49/udemy-dl#356]
Happen only with this course, i tried 2 other courses and it worked fine.

OS: Windows 10 1809 (build 17763.379)
Course URL: https://www.udemy.com/react-redux
Steps:
- Used command : udemy-dl.py https://www.udemy.com/react-redux -k cookies.txt --skip-sub
- Wait a few seconds and : 502 Bad Gateway ...

![1](https://user-images.githubusercontent.com/48912654/54930976-20362080-4f10-11e9-921a-5fa95db86619.png)

I tried to make a request manually

![2](https://user-images.githubusercontent.com/48912654/54931040-38a63b00-4f10-11e9-99b1-a95acba3128e.PNG)

**Comment by brundidge** [comment]
I'm able to download the course successfully

![3](https://user-images.githubusercontent.com/48912654/54931337-b79b7380-4f10-11e9-8480-8c7004b2556a.png)

What's happening ?
If the response size from "Downloading course information..." exceeds 3MB, you get "502 Bad Gateway"
Why 3MB ? I tried to change "&page_size=10000" to "&page_size=400" in the request, and i got 200 OK status code and the response size is about 3,01MB, it shows 502 then change to 200 OK right away.

Of course i tried 401, 402, ... 500, 1000 but i only got 502 status code.

In the request, i see ", caption" and i got response with caption field (url, language,...) in it's body.
Then i tried to make a request for caption only to a specific lecture, i got response with size about 13KB.
If a course have about 400 lectures like this course => 13 * 400 = ~5MB
Then i don't have any space in response body for lectures (lectures url, 720p, 1080p,...)

So i deleted that ", caption" in request url, and now the response size is ~1MB and i got 200 OK status code, i can download the course without any problem.

But this fix is not for someone who need *auto subtitle*.

- Fix :
I see that @r0oth3x49 already have a function extract_large_course_content which handle large courses. But extract_course_json didn't know where to go if it got status code "502" so i make some changes. I can download subtitle using this fix.

**Comment by lmyEsther** [comment]
@brundidge please, give me the steps to follow to solve this issue. 
I have the same error.

**Comment by brundidge** [comment]
@lmyEsther You can clone my fork : https://github.com/brundidge/udemy-dl

**Comment by lmyEsther** [comment]
Issue resolved! You are awesome!!! Thanks you! :nerd_face: :+1:
