### ISSUE TITLE
@diogoab @r0oth3x49  Udemy Says : 400 Bad Request ['Oops, something went wrong.muc2'] ...

### ISSUE THREAD

**Issue by bhooshanmore** [r0oth3x49/udemy-dl#358]
@diogoab @r0oth3x49  I am getting the same error 

![udemy](https://user-images.githubusercontent.com/14997154/54465029-357db300-478a-11e9-981c-b49b9863f6ae.png)

_Originally posted by @danielotieno in https://github.com/r0oth3x49/udemy-dl/issues/303#issuecomment-473458906_

**Comment by jokumar** [comment]
I am getting the same error . I took the pull now and still the same error .

**Comment by brundidge** [comment]
Use cookie to login : https://github.com/r0oth3x49/udemy-dl/issues/341
