### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by luloproductions** [r0oth3x49/udemy-dl#365]
Hi there.

When I try to download a Udemy course it is saying "SyntaxError: invalid syntax."
This was working before I updated to OS High Sierra but is now giving me this error.

MacBook-Pro-de-Joe:LGC Website Joe$ cd /Users/Joe/Desktop/WEBSITE\ BUILDING/TUTORIALS/UDEMY\ VIDEOS
MacBook-Pro-de-Joe:UDEMY VIDEOS Joe$ python3
Python 3.7.2 (v3.7.2:9a3ffc0492, Dec 24 2018, 02:44:43) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> python3 udemy-dl.py https://www.udemy.com/bootstrap-4-from-scratch-with-5-projects/ 
  File "<stdin>", line 1
    python3 udemy-dl.py https://www.udemy.com/bootstrap-4-from-scratch-with-5-projects/ 
                ^
SyntaxError: invalid syntax
>>> 

Would appreciate some help with this, thanks a lot.

Joe

**Comment by brundidge** [comment]
looks like your problem is you're running `python3 udemy-dl.py` from within the Python interpreter.

i mean, don't run `python3` before you run `python3 udemy-dl.py`. Just open terminal and run `python3 udemy-dl.py courseURL` right away.

**Comment by r0oth3x49** [comment]
@luloproductions its a command line tool, check out some tuts on how to run python code on terminal

**Comment by luloproductions** [comment]
> looks like your problem is you're running `python3 udemy-dl.py` from within the Python interpreter.
> 
> i mean, don't run `python3` before you run `python3 udemy-dl.py`. Just open terminal and run `python3 udemy-dl.py courseURL` right away.

Thanks brundidge!
