### ISSUE TITLE
403 Forbidden You do not have permission to perform this action. 

### ISSUE THREAD

**Issue by Carlosx7** [r0oth3x49/udemy-dl#366]
I find udemy had changed course link today. When I used udemy-dl with cookies login in then get the error message Udemy Says : 403 Forbidden You do not have permission to perform this action. Please give me help , bro.
![屏幕快照 2019-04-03 下午1 46 31](https://user-images.githubusercontent.com/3402621/55455809-a55bbc80-5617-11e9-8393-0ca4d7b1795f.png)

**Comment by brundidge** [comment]
I think access_token in your cookie file is broken, like you deleted a character by mistake. Try to create cookie file again.

**Comment by Carlosx7** [comment]
It works.Thanks so much.

**Comment by r0oth3x49** [comment]
@brundidge thank you for quick response.
