### ISSUE TITLE
udemy-dl doesn't care about client_id value in cookie file

### ISSUE THREAD

**Issue by brundidge** [r0oth3x49/udemy-dl#367]
#363 

If i make a cookie file with `access_token=myAccessToken client_id=hellothere`. Even though i put `hellothere` (yeah, really) inside `client_id` value. Login and download still fine without problems.

But the problem is if my cookie file with only `access_token=myAccessToken` without `client_id`. udemy-dl will throw an error.

I mean, we can put anything inside `client_id` and everything is fine. Then why we still need to provide it inside cookie file.

**Comment by abmadani** [comment]
@brundidge Hello there, 

If you follow those steps, it will works. 
https://github.com/r0oth3x49/udemy-dl#extracting-cookies--request-headers

**Comment by r0oth3x49** [comment]
@brundidge i 'm closing the issue the client id is being used in cookies in udemy headers but i think not a big impact if i don't use so i will consider the changes in next version for now i 'm closing the issue.
