### ISSUE TITLE
Cannot Run on MacOSX Sierra using Python 2.7

### ISSUE THREAD

**Issue by zdharmawan** [r0oth3x49/udemy-dl#37]
Hi there,

I've cloned your repo, then I did `pip install -r requirements.txt`.
But, when actually calling why do I get this:

`Traceback (most recent call last):
  File "udemy-dl.py", line 7, in <module>
    import udemy
  File "/Users/310176470/Workspace/udemy-dl/udemy/__init__.py", line 6, in <module>
    from ._downloader import Downloader
  File "/Users/310176470/Workspace/udemy-dl/udemy/_downloader.py", line 8, in <module>
    from .colorized import *
  File "/Users/310176470/Workspace/udemy-dl/udemy/colorized/__init__.py", line 1, in <module>
    from .Output import *
  File "/Users/310176470/Workspace/udemy-dl/udemy/colorized/Output.py", line 1, in <module>
    from colorama import init,Fore,Back,Style
ImportError: No module named colorama`

Thanks
Zul

**Comment by r0oth3x49** [comment]
@zdharmawan thanks for the report. did you try to install menually? does the OS has both Python3 and Python2? if yes then try with Python3 or first install python-pip for Python2 then install using that. the error clearly says that some how your default python version don't have that module installed.

**Comment by zdharmawan** [comment]
Hi @r0oth3x49 

Thanks for the tips. If I use python3, it's now working fine. So, if you have two installations (python3 and python (2.7)). It seems that the `colorama` package is not detected that it's installed.

Regards,
Zul

**Comment by r0oth3x49** [comment]
@zdharmawan when you run the program against some course using Python2 it will only use libs of Python2 not Python3 and this is the default behavior of any script. & when you install using `pip install -r requirements.txt` it will install libs for the default Python-pip not for both.

so there is no way you can in between of running switch to another python version. i have tested against both but before that i have installed libs for both `py2 & py3`. 

Thanks for using this utility it works for you i m closing the issue now.

**Comment by shubz007** [comment]
I am getting error like this  ;- No module named "m3u8" 
but I already have installed all the requirements.
Please help ....
