### ISSUE TITLE
issues with names when using -save

### ISSUE THREAD

**Issue by iZero7** [r0oth3x49/udemy-dl#370]
when using the -save command and using its file in a download manager, the filename is saved as webHD_720.mp4 instead of real name.

is there a way to later rename it to real name?

**Comment by r0oth3x49** [comment]
@iZero7 no there is no way available currently but will check the solutions if any till then i think youtube-dl offers renaming but don't know if it works with udemy renaming.

**Comment by iZero7** [comment]
is it possible to make a script that could use file from --names command which renames and arranges the files back in order?
