### ISSUE TITLE
FileNotFound exception

### ISSUE THREAD

**Issue by talhashoaib** [r0oth3x49/udemy-dl#372]
```
Traceback (most recent call last):
  File "udemy-dl.py", line 1432, in <module>
    main()
  File "udemy-dl.py", line 1091, in main
    udemy.course_download(path=options.output, quality=options.quality, unsafe=options.unsafe)
  File "udemy-dl.py", line 500, in course_download
    self.download_lectures_and_captions(lecture_best=lecture_best, lecture_title=lecture_title, inner_index=inner_index, lectures_count=lectures_count, lecture_subtitles=lecture_subtitles, lecture_assets=lecture_assets, filepath=filepath, unsafe=unsafe)
  File "udemy-dl.py", line 418, in download_lectures_and_captions
    self.download_assets(lecture_assets=lecture_assets, filepath=filepath, unsafe=unsafe)
  File "udemy-dl.py", line 327, in download_assets
    assets.download(filepath=filepath, unsafe=unsafe, quiet=True, callback=self.show_progress)
  File "/Documents/personal/tutorials/udemy-dl/udemy/_shared.py", line 590, in download
    return self._write_external_links(filepath, unsafe=unsafe)
  File "/Documents/personal/tutorials/udemy-dl/udemy/_shared.py", line 519, in _write_external_links
    except (OSError, Exception, UnicodeDecodeError, FileNotFoundError) as e:
NameError: global name 'FileNotFoundError' is not defined
```

**Comment by brundidge** [comment]
Can you provide more info about your problem?
I have this error on Windows but it works fine on MacOS 10.14

Python version? Course cause this error? What version of your MacOS? What command you used?

**Comment by talhashoaib** [comment]
@brundidge Thank you for your reply. 

Mac version: 10.14.2
python version: Python 2.7.16

python udemy-dl.py -u <my-email> -p <my-password> https://www.udemy.com/professional-rails-5-development-course/learn/v4/overview -q 720 --cookie=cookie.txt

**Comment by talhashoaib** [comment]
It was working fine until few lectures btw.

**Comment by doctor-henry** [comment]
I redownloaded udemy-dl and the problem has gone away.

**Comment by brundidge** [comment]
I have same problem with the course you provide: https://www.udemy.com/professional-rails-5-development-course/

But on Windows 10, Python 2.7.16

Error occurs at chapter 15 and around lecture 161

![a](https://user-images.githubusercontent.com/48912654/56674734-08d28a80-66aa-11e9-824d-aa3ab8bb0508.png)

And at the time error happen, i have a blank txt file without anything inside.

![b](https://user-images.githubusercontent.com/48912654/56674747-125bf280-66aa-11e9-821d-8b8a26a792e1.png)

It says 'FindNotFoundError' is not defined but i think it's not same problem about long path like i have with another course. This course overall have short names, and i can open that 0KB txt with Notepad normally (which i can't if it's something relative to long path on Windows)

**Comment by r0oth3x49** [comment]
@brundidge here is the problem, FileNotFound exception does not exists and once i remove the code works fine.

**Comment by brundidge** [comment]
@r0oth3x49 in #375, right now udemy-dl with Python 3 already lost that file if it understand what FileNotFound is, if we replace it with more general exception, error with catch but i'm afraid the file will be gone like in Python 3

**Comment by brundidge** [comment]
@r0oth3x49 In #375, if a person install Python 3 on Windows without 'Disable path length limit', the text file that cause error, will disappear. I'm afraid that it'll happen on Python 2 too if you replace FileNotFoundError with more general exception, error will be catch but file will be gone.

**Comment by brundidge** [comment]
@r0oth3x49 That fix is the reason causes file lost, not a fix, it just says: "Hey error, go away". I told you in comment above, and take a look at my comment here please : https://github.com/r0oth3x49/udemy-dl/pull/375#issuecomment-487261506
