### ISSUE TITLE
Udemy-dl install in Ubuntu

### ISSUE THREAD

**Issue by 4ngeluxpunk** [r0oth3x49/udemy-dl#374]
Hello dear, a query open a manual of installation of udemy-dl for ubuntu or what steps I must follow to use it with Ubuntu.

Thank you.

**Comment by brundidge** [comment]
1) Clone udemy-dl, open your terminal in udemy-dl folder, run command:
`pip install -r requirements.txt`
2) Follow: https://github.com/r0oth3x49/udemy-dl#extracting-cookies--request-headers to get your cookie file.
3) Use command to download:
`python udemy-dl.py yourCourseURL -k cookie.txt`
Note: <b>cookie.txt</b> is your cookie file name
