### ISSUE TITLE
I have this error: Udemy Says : 400 Bad Request Oops, something went wrong.

### ISSUE THREAD

**Issue by IsraelDCastro** [r0oth3x49/udemy-dl#376]
I tried with different versions of python, downloaded the files again, and with the cookies, nothing worked

**Comment by lukmanulhakimd** [comment]
+1 
got the same issue, it worked fine before

**Comment by brundidge** [comment]
At this moment you can't login with username and password, it'll cause 400 Bad Request

Can you provide more info about the problem?

What OS you're using? Windows, Mac, Linux,... and what version of OS? Win 10, Mac 10.14, Ubuntu,...
What course url did you try to download?
What command did you use to download? full command please
What guide did you follow to create cookie file ?

**Comment by IsraelDCastro** [comment]
I use a Macbook Pro version 10.14.4, i have the lastest version of python, the command that I used: 

> `python udemy-dl.py course_url`

With the cookies : `python udemy-dl.py course_url -k cookie.txt`

Bofere I updated the files It worked very good, but after it stopped working

**Comment by brundidge** [comment]
Open Terminal in your udemy-dl folder and try command `git pull` so you can have the lastest version of udemy-dl. Or you can clone udemy-dl from github again.

Try follow this guide to create a cookie file like the one i'm using : https://github.com/r0oth3x49/udemy-dl/issues/351#issuecomment-476936783

And you should provide the course url that you're having issue too.

**Comment by IsraelDCastro** [comment]
@brundidge Thanks a lot, It's work with the cookies guide.
