### ISSUE TITLE
could you help to fix this? thanks!

### ISSUE THREAD

**Issue by jiushibushuo** [r0oth3x49/udemy-dl#379]
[+] : Logged in successfully.
[*] : Downloading course information .. -Traceback (most recent call last):
  File "udemy-dl.py", line 1442, in <module>
    main()
  File "udemy-dl.py", line 1281, in main
    udemy.course_download(path=options.output, quality=options.quality, unsafe=options.unsafe)
  File "udemy-dl.py", line 436, in course_download
    course = udemy.course(url=self.url, username=self.username, password=self.password, cookies=self.cookies)
  File "/home/esir/udemydl/udemy/_udemy.py", line 38, in course
    return Udemy(url, username, password, cookies, basic, callback)
  File "/home/esir/udemydl/udemy/_internal.py", line 44, in __init__
    super(InternUdemyCourse, self).__init__(*args, **kwargs)
  File "/home/esir/udemydl/udemy/_shared.py", line 62, in __init__
    self._fetch_course()
  File "/home/esir/udemydl/udemy/_internal.py", line 56, in _fetch_course
    self._info              =       self._real_extract(self._url)
  File "/home/esir/udemydl/udemy/_extract.py", line 467, in _real_extract
    'subtitles' : self._extract_subtitles(tracks),
  File "/home/esir/udemydl/udemy/_extract.py", line 256, in _extract_subtitles
    lang = track.get('language') or track.get('srclang') or track.get('label') or track['locale'].get('locale').split('_')[0]
KeyError: 'locale'

**Comment by brundidge** [comment]
Your udemy-dl is old
Use command `git pull` to download lastest version of udemy-dl

**Comment by jiushibushuo** [comment]
> Your udemy-dl is old
> Use command `git pull` to download lastest version of udemy-dl

I downloaded the version 0.5, so I got the output above, and after clone the code, I got this:


[*] : Username : myemail.com
[*] : Password : *********
[*] : Trying to login as (myemail.com)...
[-] : Udemy Says : 400 Bad Request Oops, something went wrong. ...

**Comment by brundidge** [comment]
login with username and password is not avalible at this moment. You can cookie to login. Follow the guide here : https://github.com/r0oth3x49/udemy-dl/issues/351#issuecomment-476936783

**Comment by jiushibushuo** [comment]
> login with username and password is not avalible at this moment. You can use cookie to login. Follow the guide here : [#351 (comment)](https://github.com/r0oth3x49/udemy-dl/issues/351#issuecomment-476936783)

thank you very much! It works! and the speed so fast... cause I ran it on google cloud.

But I now am worrying they might ban me  for doing this...

**Comment by r0oth3x49** [comment]
@brundidge thanks for the quick support
