### ISSUE TITLE
video quality

### ISSUE THREAD

**Issue by JesusGarrido** [r0oth3x49/udemy-dl#38]
Hi, I can not download the videos.
What do I do wrong?
I do not understand how the argument for video quality should be written.
I have verified that the videos are at 720.
Thank you very much.

[INFO-835] Downloading to: C:\
[INFO-107] Trying to log in ...
[INFO-137] Login success.
[INFO-169] Found course id: 1145678
Getting course data: 0.87% [--------------------] [CRITICAL-238] Skipped. Expected quality not found!
Getting course data: 2.17% [--------------------] [CRITICAL-238] Skipped. Expected quality not found!
Getting course data: 3.48% [=-------------------] [CRITICAL-238] Skipped. Expected quality not found!
Getting course data: 4.35% [=-------------------] [CRITICAL-238] Skipped. Expected quality not found!
Getting course data: 4.78% [=-------------------] [CRITICAL-238] Skipped. Expected quality not found!
Getting course data: 5.22% [=-------------------] [CRITICAL-238] Skipped. Expected quality not found

**Comment by coozgan** [comment]
you might want to try take a look at this bro. [Skipped. Expected quality not found! #30](https://github.com/r0oth3x49/udemy-dl/issues/30)

**Comment by r0oth3x49** [comment]
@coozgan thanks for your help. @JesusGarrido you are not using this repo so this error does not belongs to this you must have a look at issue mention by @coozgan. so i am closing the issue

**Comment by JesusGarrido** [comment]
I'm sorry, I do not understand what happens. I downloaded the repository from this link ...
http://r0oth3x49.herokuapp.com/download-udemy-courses-using-udemy-dl/

**Comment by r0oth3x49** [comment]
@JesusGarrido sorry i think i haven't updated the repo direct download link over there lemme update that.
