### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\u200b'

### ISSUE THREAD

**Issue by brundidge** [r0oth3x49/udemy-dl#380]
Course: https://www.udemy.com/professional-rails-5-development-course/
Python: 2.7.16
OS: Windows 10 1809
Error occurs at :
 + Chapter: 15 Rails  JavaScript
  ++ Lecture: 161 Sortable-JS-Code-updated-.txt

What happen in that file?

It contains this char `\u200b` (ZERO WIDTH SPACE) at the end.

![1](https://user-images.githubusercontent.com/48912654/56858881-4ddc1280-6971-11e9-9b75-0a792becd9cb.png)

But why this cause error? Because `unsafe` checker always set to False. So it fall into 'ascii' encoder with only 128 english characters, and it wonders what on earth `\u200b` is.
That's why it raise : UnicodeEncodeError

![2](https://user-images.githubusercontent.com/48912654/56858883-546a8a00-6971-11e9-9210-ee652ff5210f.png)

By delete that checker (i don't know why we need that checker there by the way). Everything is working now. I manage to download all the file listed in `--save` command of udemy-dl.

![3](https://user-images.githubusercontent.com/48912654/56858884-592f3e00-6971-11e9-8e47-65f05c4e6e6f.png)

**Comment by r0oth3x49** [comment]
@brundidge did you tried to use `--unsafe` flag?
