### ISSUE TITLE
 decodedbytes = self.decode(data, self.errors)

### ISSUE THREAD

**Issue by devopsdymyr** [r0oth3x49/udemy-dl#385]
![Screenshot from 2019-05-05 10-23-35](https://user-images.githubusercontent.com/41105507/57188655-34623a00-6f20-11e9-9832-099d2ef07140.png)

while downloading course got above error

**Comment by r0oth3x49** [comment]
@devopsdymyr can you please follow the [issue reporting guideline](https://github.com/r0oth3x49/udemy-dl#issue-reporting-guideline).

**Comment by devopsdymyr** [comment]
i have followed as per guideline which started downloading after some videos downloaded getting error.
![Screenshot from 2019-05-07 18-47-16](https://user-images.githubusercontent.com/41105507/57302421-c45adc00-70f8-11e9-8df9-8a562bdd1747.png)

**Comment by r0oth3x49** [comment]
@devopsdymyr you got it wrong, i mean the issue you are reporting doesn't have enough information which i 'm asking for, That's why i said follow the issue reporting guideline.

- How can i reproduce (steps to reproduce)?
- Course URL?
- You can share your cookies file with me to reproduce instead of sharing credentials. So that i can fix the issue ASAP.

**Comment by MartinPee** [comment]
Hi, I installed python, added to the path, added all neccesary requirements, but I have this problem. I am not sure if I should open new issue, so I am writing here, correct me if I am wrong. I search for resolution, but found nothing applicable. I would be thankful if you would help me. I got this problem when I want to log in. 

![image](https://user-images.githubusercontent.com/41447988/57485228-6ae6de80-72ab-11e9-9bcb-cc914736a1b6.png)

**Comment by tr01** [comment]
Hi
Also meet same problem yesterday. Before I downloaded this course, but I meet this problem from yesterday with all my courses. I do not know how to share with you cookies. Sorry for my bad english. URL as sample of my courses what I want download:
https://www.udemy.com/share/100yjuB0IaeV1aRn4=/
https://www.udemy.com/share/1000ceB0IaeV1aRn4=/

![udemy-dl-master](https://user-images.githubusercontent.com/50469275/57495397-43c2f800-7311-11e9-958d-bb65f9659db2.JPG)

**Comment by r0oth3x49** [comment]
@tr01 , @MartinPee i have fixed the issue you guys are facing pull the updates. and use cookie based method if you see 403 forbidden

**Comment by MartinPee** [comment]
For me it works. Thanks a lot. Cheers :)

**Comment by 01ttouch** [comment]
@MartinPee you mean login with username and password or cookie ? or you're seeing a nicer error message tell you login with cookie

**Comment by MartinPee** [comment]
Yes, login with username and password. No message login with coocki. It works as it should.

**Comment by 01ttouch** [comment]
@MartinPee you're using my fix or you just pull the new commit from this repo?

**Comment by MartinPee** [comment]
I just changed the code in the mentioned line/udemy instead odf host/,
didnt download the whole repo.

sob., 11.05.2019, 03:33 użytkownik Anja Koenig <notifications@github.com>
napisał:

**Comment by 01ttouch** [comment]
@r0oth3x49 you see, he says it work, maybe you clone my fork with wrong branch or something that made you fail.

**Comment by r0oth3x49** [comment]
@r0oth3x49 that's not a permanent fix, i have said this earlier to the other guy as well that it blocks you after certain tries and people will start creating issues which are discussed so many times.

**Comment by 01ttouch** [comment]
@r0oth3x49 https://github.com/r0oth3x49/udemy-dl/pull/386, no it doesn't block, i tried 30 times in a row, 1 -> 3 seconds between each try and no fail whatsoever.

**Comment by r0oth3x49** [comment]
it does in my case, its not for a single user if i can face the others would do also at some point.

**Comment by 01ttouch** [comment]
@r0oth3x49 the point is now it fail 100% if you don't change at all.

**Comment by r0oth3x49** [comment]
@01ttouch have updated the code according to your patch. thanks for that.
