### ISSUE TITLE
README.md - Extracting Cookies / Request Headers is unclear

### ISSUE THREAD

**Issue by morkeltry** [r0oth3x49/udemy-dl#389]
>  Now click on My Courses in the Udemy navbar and refresh the page you will see some requests under Network Tab.
> Right click on request links to udemy.com/api-2.0/. Simply copy Request Headers and save to text file.

These instructions really are not clear.
I would suggest to improve  "Right click on request links to udemy.com/api-2.0/" to specify which request link to udemy.com/api-2.0/ -  if any one is OK, then specify that.
"Simply copy Request Headers and save to text file.": there are Request Headers displayed lower down in Dev Tools. To specify that you can save the headers via the right click context menu: "Right click on... and select 'Copy Request Headers' from the context menu".
"and save to text file." -> "The headers are now in the clipboard. Paste them into a text file and save it to the udemy-dl directory"

So far so good?

Now the next point I cannot suggest a phrasing for as I could not work out what the instruction is trying to do.
"Done run the udemy-dl against that text file it will start downloading the course."

What does it mean to run udemy-dl "against" a text file?
I cannot see any option to use a text file as parameters to udemy-dl .

**Comment by 01ttouch** [comment]
😋 Simple 5 steps login with cookie for <b>Firefox</b> users

1) Make sure you already <b>logged in</b>. Right click anywhere on the udemy website and choose <b>Inspect Element</b> or you can press shortcut button <b>F12</b>

![firefox1](https://user-images.githubusercontent.com/50474221/57639465-81d54b80-759f-11e9-89a3-491cc9f9b573.png)


2) Choose <b>Storage</b> tab, then choose <b>Cookies</b> -> `https://www.udemy.com` on the left.

On the right, type into filter: <b>access_token</b>, double click and copy the value inside <b>Value</b> box.

![firefox2](https://user-images.githubusercontent.com/50474221/57639484-8994f000-759f-11e9-814d-d432a7aac8b5.png)


3) Create a text (<b>.txt</b>) file inside your <b>udemy-dl</b> folder, name it whatever you want.

![firefox4](https://user-images.githubusercontent.com/50474221/57639493-91549480-759f-11e9-910c-61b106da836d.png)


4) Open the text (<b>.txt</b>) file you just created. Add the line below to it, replace <b>yourAccessToken</b> with the value in <b>Step 2</b> and save the file.

`access_token=yourAccessToken`

![firefox3](https://user-images.githubusercontent.com/50474221/57639489-8d287700-759f-11e9-855b-ed4717ff51cd.png)


5) Use the command below to login and download with cookie. Replace <b>courseUrl</b> with your course url, <b>cookie.txt</b> with the name of file you created in <b>Step 3</b>

`python udemy-dl.py courseUrl -k cookie.txt`

![firefox5](https://user-images.githubusercontent.com/50474221/57639507-974a7580-759f-11e9-94c1-3ffd86d89356.png)

**Comment by r0oth3x49** [comment]
> 
> 
> > Now click on My Courses in the Udemy navbar and refresh the page you will see some requests under Network Tab.
> > Right click on request links to udemy.com/api-2.0/. Simply copy Request Headers and save to text file.
> 
> These instructions really are not clear.
> I would suggest to improve "Right click on request links to udemy.com/api-2.0/" to specify which request link to udemy.com/api-2.0/ - if any one is OK, then specify that.
> "Simply copy Request Headers and save to text file.": there are Request Headers displayed lower down in Dev Tools. To specify that you can save the headers via the right click context menu: "Right click on... and select 'Copy Request Headers' from the context menu".
> "and save to text file." -> "The headers are now in the clipboard. Paste them into a text file and save it to the udemy-dl directory"
> 
> So far so good?
> 
> Now the next point I cannot suggest a phrasing for as I could not work out what the instruction is trying to do.
> "Done run the udemy-dl against that text file it will start downloading the course."
> 
> What does it mean to run udemy-dl "against" a text file?
> I cannot see any option to use a text file as parameters to udemy-dl .
thanks @01ttouch , lets wait for @morkeltry reply if he still face problem in understanding.
did you get the idea from above explanation by @01ttouch ?

**Comment by 01ttouch** [comment]
### ![chrome](https://user-images.githubusercontent.com/50474221/57762579-49448780-76ef-11e9-8ebe-20ab6c7a01c1.png) Simple 5 steps login with cookie for Chrome users


1) Make sure you already <b>logged in</b>. Right click anywhere on the udemy website and choose <b>Inspect</b> or you can press shortcut button <b>F12</b>

![chrome1](https://user-images.githubusercontent.com/50474221/57762231-a2f88200-76ee-11e9-9f2a-236ce45c532b.png)


2) Choose <b>Application</b> tab, then choose <b>Cookies</b> -> `https://www.udemy.com` on the left.

On the right, type into filter: <b>access_token</b>, double click and copy the value inside <b>Value</b> box.

![chrome2](https://user-images.githubusercontent.com/50474221/57762361-e6eb8700-76ee-11e9-954f-e75dfe0cab5d.png)


3) Create a text (<b>.txt</b>) file inside your <b>udemy-dl</b> folder, name it whatever you want.

![chrome3](https://user-images.githubusercontent.com/50474221/57762408-fcf94780-76ee-11e9-8e99-404aa21b353d.png)


4) Open the text (<b>.txt</b>) file you just created. Add the line below to it, replace <b>yourAccessToken</b> with the value in <b>Step 2</b> and save the file.

`access_token=yourAccessToken`

![chrome4](https://user-images.githubusercontent.com/50474221/57762712-8741ab80-76ef-11e9-8221-987e3a7e9ccb.png)


5) Use the command below to login and download with cookie. Replace <b>courseUrl</b> with your course url, <b>cookie.txt</b> with the name of file you created in <b>Step 3</b>

`python udemy-dl.py courseUrl -k cookie.txt`

![chrome5](https://user-images.githubusercontent.com/50474221/57762791-a4767a00-76ef-11e9-92ae-c07374cc10ed.png)

**Comment by AboShayeb** [comment]
Does it rip off any course or do I have to own it?

**Comment by tavitooo** [comment]
Ey Its only for course you buy! not for download any courses in Udemy!!. :(

**Comment by tavitooo** [comment]
> Does it rip off any course or do I have to own it?

Only Own it... :(

**Comment by sidx64** [comment]
Considering how cheap the courses are, I dont see why the sad face :P

**Comment by noorbala7418** [comment]
thank you.it was great!

**Comment by dlwhittenbury** [comment]
Thank you, it worked perfectly.

**Comment by Raqibur-Rahman** [comment]
It says "python: can't open file 'udemy-dl.py': [Errno 2] No such file or directory"
I never use python before,I have installed it .
Now, what should I do?

**Comment by noorbala7418** [comment]
you should go to udemy-dl directory.with command ' ls ' you can see script on the terminal.then you can run udemy-dl.py with this command:
python udemy-dl link -k cookieFile.txt

**Comment by S-Tangg** [comment]
hi, get this warning: It seems either you are not enrolled or you have to visit the course atleast once while you are logged in.
But I am sure I have logged in and also visit the course already, any tips?

**Comment by r0oth3x49** [comment]
> 
> 
> hi, get this warning: It seems either you are not enrolled or you have to visit the course atleast once while you are logged in.
> But I am sure I have logged in and also visit the course already, any tips?

@S-Tangg did you manage to download course other than the one you are facing the error?

**Comment by matthewmerks** [comment]
Can confirm this works.  Followed this now after receiving a 403 and access_token cleared the error and allowed downloads to resume.

**Comment by gkpavan** [comment]
Is it legal to download udemy business courses?

**Comment by gkpavan** [comment]
Hi,
Did anybody downloaded the Udemy business enrolled course using this git.

**Comment by dillagr** [comment]
> Hi,
> Did anybody downloaded the Udemy business enrolled course using this git.

yes, it works

**Comment by Pedro1Torres** [comment]
Unable to find access_key solution not working on chrome?

**Comment by noorbala7418** [comment]
access_token is true not access_key !

**Comment by noorbala7418** [comment]
> Unable to find access_key solution not working on chrome?
access_token is true not access_key !

**Comment by osazemeu** [comment]
@Pedro1Torres just tried it now... It works on chrome.

**Comment by Raqibur-Rahman** [comment]
> you should go to udemy-dl directory.with command ' ls ' you can see script on the terminal.then you can run udemy-dl.py with this command:
> python udemy-dl link -k cookieFile.txt

Sorry,I didn't understand.Will you please say it again?

**Comment by SuSSan143** [comment]
> ### ![chrome](https://user-images.githubusercontent.com/50474221/57762579-49448780-76ef-11e9-8ebe-20ab6c7a01c1.png) Simple 5 steps login with cookie for Chrome users
> 1. Make sure you already logged in. Right click anywhere on the udemy website and choose Inspect or you can press shortcut button F12
> 
> ![chrome1](https://user-images.githubusercontent.com/50474221/57762231-a2f88200-76ee-11e9-9f2a-236ce45c532b.png)
> 
> 1. Choose Application tab, then choose Cookies -> `https://www.udemy.com` on the left.
> 
> On the right, type into filter: access_token, double click and copy the value inside Value box.
> 
> ![chrome2](https://user-images.githubusercontent.com/50474221/57762361-e6eb8700-76ee-11e9-954f-e75dfe0cab5d.png)
> 
> 1. Create a text (.txt) file inside your udemy-dl folder, name it whatever you want.
> 
> ![chrome3](https://user-images.githubusercontent.com/50474221/57762408-fcf94780-76ee-11e9-8e99-404aa21b353d.png)
> 
> 1. Open the text (.txt) file you just created. Add the line below to it, replace yourAccessToken with the value in Step 2 and save the file.
> 
> `access_token=yourAccessToken`
> 
> ![chrome4](https://user-images.githubusercontent.com/50474221/57762712-8741ab80-76ef-11e9-8221-987e3a7e9ccb.png)
> 
> 1. Use the command below to login and download with cookie. Replace courseUrl with your course url, cookie.txt with the name of file you created in Step 3
> 
> `python udemy-dl.py courseUrl -k cookie.txt`
> 
> ![chrome5](https://user-images.githubusercontent.com/50474221/57762791-a4767a00-76ef-11e9-92ae-c07374cc10ed.png)
I am using termux to download udemy video. How to login using cookies here

**Comment by azmatsiddique** [comment]
thank you soo much

**Comment by Ocolus1** [comment]
Thank you so much It worked

**Comment by waldens** [comment]
Note that encoding of `cookie.txt` must be ANSI. On non-latin's system, default encoding of new created `.txt` files may be UTF8, took me a little to troubleshoot.

**Comment by shubham0804** [comment]
In the cookies it says that the access_token expires in about a month. Would a new access token have to be entered in udemy-dl when the current one expires?

**Comment by r0oth3x49** [comment]
> 
> 
> In the cookies it says that the access_token expires in about a month. Would a new access token have to be entered in udemy-dl when the current one expires?

definitely you should if you want udemy-dl to work.

**Comment by magheralex** [comment]
[*] : Trying to login using cookies ...
[+] : Logged in successfully.
[-] : Udemy Says : 403 Forbidden You should use cookie base method to authenticate or try again in few minutes ...

**Comment by ahmet-soner** [comment]
Traceback (most recent call last):
  File "C:\Users\MYSTIC\Desktop\udemy-dl-master\udemy-dl-master\dersindir.py", line 1
    python https://www.udemy.com/course/assembly-kapsaml-egitimi-ile-uzmanlga-dogru/learn/lecture/19879416#overview -k prsk.txt
           ^
SyntaxError: invalid syntax

******************************************************************
what is the solution?
prgfiles@gmail.com

**Comment by riteshbehera857** [comment]
where will be the files saved after being downloaded

**Comment by kaptX** [comment]
Trying to login using session cookie
[i] : Logged in successfully.
[-] : Udemy Says: 403 Forbidden on https://www.udemy.com...........................

Is there a solution for this? I used this like two months ago and now it's not working.

**Comment by bhantsi** [comment]
Ok I got four errors as shown in the screenshot below 
![udemy-dl](https://user-images.githubusercontent.com/26586086/121071573-0408bc00-c7c8-11eb-8b98-e6eab3f0a56e.png)

**Comment by ISYHACK** [comment]
![gali udemy hack hata](https://user-images.githubusercontent.com/85744564/121686656-25202400-caca-11eb-9165-d5e4e256e265.PNG)

**Comment by ghost** [comment]
sadece bedava olanları indirebiliyor !? 
![koyy](https://user-images.githubusercontent.com/85744564/121727308-675e5b00-caf4-11eb-928d-3210b1d31445.PNG)

**Comment by ghost** [comment]
> Tamam, aşağıdaki ekran görüntüsünde gösterildiği gibi dört hata aldım
> ![udemy-dl](https://user-images.githubusercontent.com/26586086/121071573-0408bc00-c7c8-11eb-8b98-e6eab3f0a56e.png)

hala çözemediysen ve çözemeyenler için onu python3 ile çalıştırman gerekiyor

**Comment by abedevjs** [comment]
> Ok I got four errors as shown in the screenshot below
> ![udemy-dl](https://user-images.githubusercontent.com/26586086/121071573-0408bc00-c7c8-11eb-8b98-e6eab3f0a56e.png)

you have to install the requirements.txt first

**Comment by ghost** [comment]
The id of the course can be found on this site. Can we tell udemy-dl that it should use this id?
https://www.infognu.com/udemy-course-date-finder

**Comment by VelkanLynd** [comment]
Hi, when i iuse
python udemy-dl.py -k cookies.txt URL
get this error
Traceback (most recent call last):
  File "C:\Apps\udemy-dl\udemy-dl.py", line 660, in <module>
    main()
  File "C:\Apps\udemy-dl\udemy-dl.py", line 559, in main
    f_in = open(args.cookies)
FileNotFoundError: [Errno 2] No such file or directory: 'cookies.txt'

**Comment by ghost** [comment]
> Merhaba,
> python udemy-dl.py -k cookie.txt URL'sini kullandığımda
> bu hatayı alıyorum Geri
> İzleme (en son çağrı son):
> Dosya "C:\Apps\udemy-dl\udemy-dl.py", satır 660,
> main()
> Dosya "C:\Apps\udemy-dl\udemy-dl.py", satır 559, ana
> f_in = open(args.cookies) içinde
> FileNotFoundError: [Errno 2] Böyle bir dosya veya dizin yok: 'cookies.txt '

Hepsinin bir çözümü var ama benim senden önceki yanıtımda dediğim olmazsa hiçbir anlamı yok!,ve zaten udemydeki kursları indirmek için normal programlar var bu kadar uğraşmaya gerek yok (benim dediğim olmadığı sürece) çünkü bu zımbırtı sadece satın aldığımız kursları indirebiliyor benim dediğim olmadıgı sürece bir anlamı yok!!

**Comment by abedevjs** [comment]
> Hi, when i iuse
.....

try this python udemy-dl.py -k cookies

**Comment by ghost** [comment]
All of them have a solution, but it doesn't make any sense unless I said in my previous answer!, and there are already normal programs to download courses on udemy, no need to try so hard (as I said.

**Comment by sounroy** [comment]
> you should go to udemy-dl directory.with command ' ls ' you can see script on the terminal.then you can run udemy-dl.py with this command:
> python udemy-dl link -k cookieFile.txt

I am getting the following
usage: udemy-dl [-h] [-u USERNAME] [-p PASSWORD] [--lecture-start LECTURE_START] [--lecture-end LECTURE_END]
                [-o OUTPUT] [-d {aria2c,axel,httpie,curl}] [--use-ffmpeg] [-q VIDEO_QUALITY] [-s] [--safe-file-names]
                [-l] [--debug] [-v]
                link
udemy-dl: error: unrecognized arguments

**Comment by ghost** [comment]
Course ID can be found on this site. Can we tell udemy-dl to use this ID?
https://www.infognu.com/udemy-course-date-finder
