### ISSUE TITLE
MacOSX: Not able to use relative path symbol (~)

### ISSUE THREAD

**Issue by zdharmawan** [r0oth3x49/udemy-dl#39]
Hi there,

It seems that in MacOSX (Sierra), if I specify the output location (using -o option). When I use tilde to indicate my home directory (for example instead of `/Users/me/download`, I just specify as `~/download`), it will just create that as a directory as tilde (~).

Regards,
Zul

**Comment by r0oth3x49** [comment]
@zdharmawan thanks for using the utility. it is clearly mention in README that you have to provide a full path not relative.

**Comment by zdharmawan** [comment]
Ok @r0oth3x49. I might be able to submit a pull request, if I have time and if you don't mind.

**Comment by r0oth3x49** [comment]
@zdharmawan thanks for this report. can you please verify now it is working fine or not

**Comment by zdharmawan** [comment]
@r0oth3x49 It's working fine if I use absolute path. Thanks. I will close this.
