### ISSUE TITLE
"Draft" Course

### ISSUE THREAD

**Issue by johndoe1969** [r0oth3x49/udemy-dl#391]
There are courses that I purchased which have the following disclaimer at the top of the page:
"Warning: This course has not yet been approved by Udemy's Quality Review team and does not currently offer a Certificate of Completion."

![Screenshot from 2019-05-13 21-00-13](https://user-images.githubusercontent.com/50086425/57663491-34b6a100-75c2-11e9-912f-5ce06d58e8ed.png)

The URL for one of them is https://www.udemy.com/draft/12831/
Course Title is The US Constitution: A Biography

udemy-dl returned the following when I tried to download this course:
"Downloading course information, course id not found .. (failed)
[i] : It seems either you are not enrolled or you have to visit the course atleast once while you are logged in.
[*] : Trying to logout now...
[+] : Logged out successfully."

It appears that the "draft" url throws off udemy-dl.

Is there a way around this?

**Comment by r0oth3x49** [comment]
@johndoe1969 will check & fix ASAP.

**Comment by johndoe1969** [comment]
Just emailed you cookies file
