### ISSUE TITLE
Udemy Says : 403 Forbidden You should use cookie base method to authenticate or try again in few minutes ...

### ISSUE THREAD

**Issue by vipksmosar** [r0oth3x49/udemy-dl#395]
Hello, downloaded today the last repository udemy-dl and when I try to download got an error: "Udemy Says : 403 Forbidden You should use cookie base method to authenticate or try again in few minutes ..."
Tried on 2 and 3 versions of python, the result is identical.
Please tell me how I can solve this problem?
![error](https://user-images.githubusercontent.com/22061392/57827521-bcfe9700-77b8-11e9-9332-52f214f55e29.PNG)

**Comment by 01ttouch** [comment]
You can follow this guide to login
https://github.com/r0oth3x49/udemy-dl#how-to-login-with-cookie

**Comment by vipksmosar** [comment]
Thanks - it worked!

**Comment by Rigel772** [comment]
Hello there, I am following the guide and still getting same error...
[*] : Trying to login using cookies ...
[+] : Logged in successfully.
[-] : Udemy Says : 403 Forbidden You should use cookie base method to authenticate or try again in few minutes ...

**Comment by kumarnipun** [comment]
How to use cookie base method to authenticate

**Comment by itssreenath** [comment]
1. Create cookies.txt file in udemy downloader folder. 
2. Copy access token and paste in cookies.txt file as mentioned in url https://github.com/r0oth3x49/udemy-dl/issues/389
3. Run using the below command in anaconda prompt
python udemy-dl.py -u <<email-id -p>> <<password>> <<course-url>> -k cookies.txt
