### ISSUE TITLE
ModuleNotFoundError: No module named 'colorama'

### ISSUE THREAD

**Issue by sean1245780** [r0oth3x49/udemy-dl#396]
After downloading with pip install colorama == 0.4.1 command I had tough time dealing and importing the colorama library into PyCharm. Although, importing into the python interpreter is still working. Why is it so? I am using interpreter v3.7.2 on windows 10.
By trying to import colorama in PyCharm, an exception rises: 
ModuleNotFoundError: No module named 'colorama'
Any suggestions?

**Comment by 01ttouch** [comment]
i installed requirements with command : `pip install -r requirements.txt` and PyCharm detects it well. In <b>File</b> (at the top left corner) -> <b>Settings</b>, please check your project interpreter, see the picture below.

![pycharm](https://user-images.githubusercontent.com/50474221/57867248-52694d80-77f0-11e9-9acb-e4646699c587.png)

**Comment by r0oth3x49** [comment]
@sean1245780 why are you struggling use the udemy-dl inside PyCharm when its a command line utility, are you planing to  modify the code or you want to use this inside some sort of project.

you don't need to use PyCharm if you want to run udemy-dl.

PS:
don't mind just asking.

**Comment by 01ttouch** [comment]
@r0oth3x49 fact: pycharm downloads 10 times faster, it's like a horse vs a turtle

**Comment by r0oth3x49** [comment]
> 
> 
> @r0oth3x49 fact: pycharm downloads 10 times faster, it's like a horse vs a turtle

strange although on both the code is same.

**Comment by mindsx** [comment]
The easiest solution to your problem is to run

$ pip install --upgrade --user awscli

as this will make sure you have all needed dependencies.
