### ISSUE TITLE
 Udemy Says : 403 Forbidden You should use cookie base method to authenticate or try again in few minutes ...

### ISSUE THREAD

**Issue by stryd3r** [r0oth3x49/udemy-dl#397]
When running  'python udemy-dl.py course_url', after inserting user credentials is returning ' Udemy Says : 403 Forbidden You should use cookie base method to authenticate or try again in few minutes ...' . Do you plan to tackle this somehow?
Thanks,
Adrian

**Comment by 01ttouch** [comment]
You can follow this guide to login with cookie : https://github.com/r0oth3x49/udemy-dl#how-to-login-with-cookie

**Comment by 01ttouch** [comment]
@r0oth3x49 told you, udemy changed, now it will fail 100%, wait few minutes or not it still fail.

**Comment by r0oth3x49** [comment]
@stryd3r thanks for using the utility, this issue is discussed so many times, the reason you are seeing the above error msg is because udemy detects login attempts as robot which then throws the above error.
so i would recommend to use cookie based authentication instead because for the above error there is no permanent solution available yet.

**Comment by mateoCordoba** [comment]
thank you

**Comment by srvr007** [comment]
> @stryd3r thanks for using the utility, this issue is discussed so many times, the reason you are seeing the above error msg is because udemy detects login attempts as robot which then throws the above error.
> so i would recommend to use cookie based authentication instead because for the above error there is no permanent solution available yet.

Hi, I am using the cookie auth method and I receive 'Udemy returned HTTP Code 403: Forbidden'. No mention of 'try again later' or anything else.

**Comment by hdineth** [comment]
> @stryd3r thanks for using the utility, this issue is discussed so many times, the reason you are seeing the above error msg is because udemy detects login attempts as robot which then throws the above error.
> so i would recommend to use cookie based authentication instead because for the above error there is no permanent solution available yet.

I'm getting above mentioned error even with cookie based method. This was experienced today. Cookie based  method was working fine until today.
Command I used:
`python udemy-dl.py https://udemy.com/course/<course-name> -k /path-to/cookies.txt --sub-lang en --cache -o /<download-path>`

**Comment by hdineth** [comment]
> > @stryd3r thanks for using the utility, this issue is discussed so many times, the reason you are seeing the above error msg is because udemy detects login attempts as robot which then throws the above error.
> > so i would recommend to use cookie based authentication instead because for the above error there is no permanent solution available yet.
> 
> Hi, I am using the cookie auth method and I receive 'Udemy returned HTTP Code 403: Forbidden'. No mention of 'try again later' or anything else.

Try Logging out and logging again. Make sure you are pointing correct cookies.txt file which contains below format inside:
`access_token=2FsV8RZ20HeqQfrdgtyn5ucp42InZjsTLykTkx`
