### ISSUE TITLE
No module named colorama

### ISSUE THREAD

**Issue by Jcorban1890** [r0oth3x49/udemy-dl#399]
So, Ive been trying to run this file for quite some time, I have gotten a ton of help, but none seem to work. When i drag the openme.py file into a command prompt file and enter, it says no module named colorama. After tryiny to install colorama with various commands, unistalling it, reinstalling it all multiple times, nothing has worked. Even weirder, when i try to use the command pip install colorama, it says i have it, but when i run the file after it says i dont have it. Any help would be appreciated.  ![image](https://user-images.githubusercontent.com/42871935/58387286-e8ac2900-7fd1-11e9-9dbd-e395715a80c2.png)

**Comment by r0oth3x49** [comment]
@Jcorban1890 take a look it works fine for me in both Python versions.
![Capture](https://user-images.githubusercontent.com/11024397/58401830-4a26d300-8078-11e9-8afd-1460fdf13399.PNG)

if you are facing problem then you can directly download lib from 
https://pypi.org/project/colorama/
and then use `python setup.py install`
to install the module.

**Comment by ErroR-fixed** [comment]
![Screenshot from 2020-02-22 14-54-11](https://user-images.githubusercontent.com/60101359/75089468-14d7e480-5527-11ea-91e6-76299a9851a2.png)
solve need

**Comment by bvrulez** [comment]
you need to install the things in requirements.txt as mentioned in the main page.

**Comment by helenou** [comment]
Easy way with pip : 

`pip3 install -r requirements.txt`

But weirdly for me I had to install one of the listed dependency after done this way
