### ISSUE TITLE
No google login

### ISSUE THREAD

**Issue by DanielAlcon** [r0oth3x49/udemy-dl#404]
I have tried to download a course, but since I'm registered with my google account, I can't login with it from the tool to download the videos

**Comment by M-Dahab** [comment]
@DanielAlcon check these guides [here](https://github.com/r0oth3x49/udemy-dl#how-to-login-with-cookie), you can login with a cookie in your case.

**Comment by r0oth3x49** [comment]
> 
> 
> @DanielAlcon check these guides [here](https://github.com/r0oth3x49/udemy-dl#how-to-login-with-cookie), you can login with a cookie in your case.

thank you @M-Dahab . @DanielAlcon  yes you can login with cookies instead
