### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by hazy254** [r0oth3x49/udemy-dl#405]
![Capture_1](https://user-images.githubusercontent.com/20756564/59606594-37089f80-911a-11e9-9654-9a24c2f3487a.PNG)

Get constant segmentation fault when trying to download. Same result for Windows command line but with no error message. Execution just stops.

**Comment by r0oth3x49** [comment]
@hazy254 i can't reproduce for me it works fine on all, windows, linux , osx. are you using the recent repo if not pull the recent one and you can try login using your email password instead of cookie it also works.

**Comment by hazy254** [comment]
Still get the same segmentation fault even using email with the latest repo. Might just be a problem with my local machine.

**Comment by r0oth3x49** [comment]
> 
> 
> Still get the same segmentation fault even using email with the latest repo. Might just be a problem with my local machine.

may be because i tried on almost all machines i have in vm / host but i can't reproduce the error and for me it works flawlessly.

**Comment by hazy254** [comment]
> may be because i tried on almost all machines i have in vm / host but i can't reproduce the error and for me it works flawlessly.

Yep. Guess it is my own machine that's the problem. Used to work before.
