### ISSUE TITLE
Flag for log for erros

### ISSUE THREAD

**Issue by tofanelli** [r0oth3x49/udemy-dl#409]
hey @r0oth3x49 

quick question for a new feature... maybe =)...

yesterday I was downloading a video, and I looked into the console just for checking and I noticed a few videos didn't downloaded due my connection, but the script was still running and started few lectures later.... 

so, the feature would be to enable a log file when any kind of error occurred, to prevent myself to think I have downloaded the whole course but it didn't....

What you think?? =)

Cheers =)

**Comment by r0oth3x49** [comment]
@tofanelli already have a plan to implement this :)

**Comment by tofanelli** [comment]
Superb!! waiting for it =)
