### ISSUE TITLE
Parse restricted characters before saving to file 

### ISSUE THREAD

**Issue by trung674** [r0oth3x49/udemy-dl#41]
Hi,

When I download video `043 App - Is It Prime?` in ` Swift 4 Deep Dive` from the course [Complete IOS11 Development Course](complete-ios-11-developer-course/), the script crashed. On Window, the following characters `\ / : * ? " < > |` cannot be used in filename so I guess the character `?` in the video name is the cause.

I wonder if we could parse those characters into ASCII strings (or something else) before saving to disk?

Thanks

**Comment by r0oth3x49** [comment]
@trung674 did you cloned the latest version i wonder why are you facing this error although the script already contain fix for this.
