### ISSUE TITLE
Add proxy support -- I saw many  proxy request had been closed

### ISSUE THREAD

**Issue by tlsalex** [r0oth3x49/udemy-dl#410]
This tool is so good, however , I hope this tool can use proxy for network communication.

Without proxy support , I almost can not connect to udemy to download course ,or just very slowly.

**Comment by r0oth3x49** [comment]
@tlsalex considering this for next version so closing the issue without any issue :P

**Comment by waldens** [comment]
Bump this issue to get more attention. my pc can get 3MB/s+ to download a udemy course if using a paid proxy, but without proxy only 20~KB/s <img alt="ghe-emoji" title=":_onion_head_bad_atmosphere:" src="https://cloud.githubusercontent.com/assets/136959/13371081/63a959a6-dce3-11e5-9745-58f839297a5b.gif">
