### ISSUE TITLE
URLError : either your internet connection is not working or server aborted the request

### ISSUE THREAD

**Issue by Carlosx7** [r0oth3x49/udemy-dl#415]
Why I have these problem , I try to change my IP and redownload the application but didn't work.
<img width="740" alt="屏幕快照 2019-07-28 上午9 32 35" src="https://user-images.githubusercontent.com/3402621/62001117-38ff4e80-b11b-11e9-9924-b19adda82806.png">

**Comment by leoalipazaga** [comment]
same error :( 
![image](https://user-images.githubusercontent.com/10076586/62001709-07a36600-b0bc-11e9-9dd5-256eef9dcc12.png)

**Comment by r0oth3x49** [comment]
trying to figure out whats wrong with udemy's guys they always do such silly things which takes time to investigate, i 'm facing the same issue from yesterday, hopefully will fix the issue soon.
PR are also welcome :)

**Comment by kaisbe** [comment]
@r0oth3x49  There is a ready PR for this :)

**Comment by r0oth3x49** [comment]
> 
> 
> @r0oth3x49 There is a ready PR for this :)

i saw your reply and commented my thoughts on that, thanks for that,

btw some for me the same code working fine now don't know what's wrong with udemy servers

**Comment by stephenwithav** [comment]
Same error here this morning, unfortunately.

**Comment by elain** [comment]
The real problem may be in the Python version you use. Please use Python 3.

**Comment by ricardoalcantara** [comment]
I tried both python:2 and python:3, I can actually list the course and the topics, but cannot actually download any file, I suspect that it's missing some OS dependency I just don't know what it is.

**Comment by rodolfoap** [comment]
[compat_urlerr].reason is: SSLError(1, u'[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:727)'))

**Comment by jkapusi** [comment]
I was able to fix the issue with "CipherString = DEFAULT@SECLEVEL=1" openssl settings. Until its not handled by the code the following Dockerfile will work.

```
FROM python:3
RUN git clone https://github.com/r0oth3x49/udemy-dl.git
RUN pip install -r /opt/udemy-dl/requirements.txt
RUN sed -i -e 's/^CipherString.*/CipherString = DEFAULT@SECLEVEL=1/g' /etc/ssl/openssl.cnf
```
