### ISSUE TITLE
ZeroDivisionError : it seems, lecture has malfunction or is zero byte(s) ..

### ISSUE THREAD

**Issue by Gexur** [r0oth3x49/udemy-dl#417]
I have this error in this parts:

`[*] : Lecture(s) : (11 of 20)
[*] : Downloading (081 Realm - Creating layout list view)
[*] : Lecture : '081 Realm - Creating layout list view' (download skipped).
[-] : ZeroDivisionError : it seems, lecture has malfunction or is zero byte(s) ..`

`[*] : Lecture(s) : (13 of 20)
[*] : Downloading (083 Realm - Mostrar registros en list view)
[*] : Lecture : '083 Realm - Mostrar registros en list view' (download skipped).
[-] : ZeroDivisionError : it seems, lecture has malfunction or is zero byte(s) ..`

`[*] : Lecture(s) : (19 of 20)
[*] : Downloading (089 Test y Fichero BD)
[*] : Lecture : '089 Test y Fichero BD' (download skipped).
[-] : ZeroDivisionError : it seems, lecture has malfunction or is zero byte(s) ..`

`[*] : Lecture(s) : (2 of 9)
[*] : Downloading (117 Creando layout para Navigation Drawer)
[*] : Lecture : '117 Creando layout para Navigation Drawer' (download skipped).
[-] : ZeroDivisionError : it seems, lecture has malfunction or is zero byte(s) ..`

`[*] : Lecture(s) : (8 of 18)
[*] : Downloading (132 Controlando Rotacion)
[*] : Lecture : '132 Controlando Rotacion' (download skipped).
[-] : ZeroDivisionError : it seems, lecture has malfunction or is zero byte(s) ..`

`[*] : Lecture(s) : (4 of 42)
[*] : Downloading (197 Como ejecutar LibGDX en el telefono)
[*] : Lecture : '197 Como ejecutar LibGDX en el telefono' (download skipped).
[-] : ZeroDivisionError : it seems, lecture has malfunction or is zero byte(s) ..`

`Lecture(s) : (25 of 49)
[*] : Downloading (260 Tres comandos utiles para la terminal)
[*] : Lecture : '260 Tres comandos utiles para la terminal' (download skipped).
[-] : ZeroDivisionError : it seems, lecture has malfunction or is zero byte(s) ..`

course: [https://www.udemy.com/programacion-de-android-desde-cero/](url)

**Comment by JordyCuan** [comment]
# ZeroDivisionError : it seems, lecture has malfunction or is zero byte(s)

I am having the same issue trying to download the next course https://www.udemy.com/grpc-golang/ on a Mac OSX with Mojave

## Steps to reproduce the bug:

On terminal:
`python udemy-dl.py https://www.udemy.com/grpc-golang/ --username MyUsername --password MyPassword --skip-sub --chapter 4 --lecture 3`

**Comment by r0oth3x49** [comment]
will try to reproduce, btw it should not be the case as i already have handled this error

**Comment by r0oth3x49** [comment]
would be great if you guys can share your creds for reproduce & fix, email:- `nasir251292@gmail.com`
