### ISSUE TITLE
Error 403 when downloading course

### ISSUE THREAD

**Issue by 4ngeluxpunk** [r0oth3x49/udemy-dl#419]
Good estimates I have the following error, do not let me download the courses.

**[-] : Udemy Says : 403 Forbidden You should use cookie base method to authenticate or try again in few minutes ...**

![kyMUK71PQVqTfJoOYOdN6w](https://user-images.githubusercontent.com/22511504/63112951-1e203d00-bf57-11e9-8f01-ab7af16f30d4.png)

**Comment by AshishDhama** [comment]
I am also having the same issue and when I tried the cookies method getting the following error"Cookies error, unable to find access_token, proper cookies required
<img width="965" alt="Screenshot 2019-08-15 at 11 06 32 PM" src="https://user-images.githubusercontent.com/16203333/63113993-581e2d00-bfb1-11e9-94ac-df166349ecc2.png">
"

**Comment by AshishDhama** [comment]
@4ngeluxpunk try cookies method it works, you just have to follow these instructions https://github.com/r0oth3x49/udemy-dl/issues/389#issuecomment-492569372
