### ISSUE TITLE
Download is stopping

### ISSUE THREAD

**Issue by salytwo** [r0oth3x49/udemy-dl#423]
It being stopped after a while of download, in other words it ranges between 2 to 7 MB of download then it stop, I tried to logout to change the token  but it no benefit. same issue even if I changed the token value by re-login again.

**Comment by Pathetic-Moses** [comment]
The python file has errors

**Comment by r0oth3x49** [comment]
> 
> 
> It being stopped after a while of download, in other words it ranges between 2 to 7 MB of download then it stop, I tried to logout to change the token but it no benefit. same issue even if I changed the token value by re-login again.

it's not related to token that's is some other issue,

can you follow the issue reporting guideline.

and would be great if you can share your creds and link to the course so that i can reproduce and fix.
