### ISSUE TITLE
Incomplete downloads 

### ISSUE THREAD

**Issue by swebdevaf** [r0oth3x49/udemy-dl#424]
After attempting to login, with cookie.txt/username-password, the script starts to download the lecture, half, and move on to downloading another without completing the first lecture, e.g downloads first lecture 30mb, lecture size 100mb, or downloads 20% moves to another lecture. 

I don't know what the problem is... 

I'm downloading **udemy** course Bootcamp for web developer by colt Steele. 
its purchase, and lectures download is enabled by the lecturer. 

can you please, help me out?

thanks, Used cmd/powershell, I'm running windows10. and everything is uptodate.

**Comment by ronkiwest** [comment]
It has happened to me before 3/4 times , I guess this is something to do with your internet connection not stable enough  at that time.
