### ISSUE TITLE
File length is too long for create

### ISSUE THREAD

**Issue by skeetinec** [r0oth3x49/udemy-dl#425]
Hello, friend, you make a great script for downloading from Udemy.
But have one problem: if name of lecture file is too long (maybe author specifically did it), than we have a trouble: "File length is too long for create".
Can you make, that script automatically cut names of files or key for command line for cutting names of files?

**Comment by skeetinec** [comment]
![screen](https://user-images.githubusercontent.com/5354232/64069267-b5d09b80-cc78-11e9-92d1-0eee67f987f5.JPG)

**Comment by r0oth3x49** [comment]
@skeetinec you should try downloading with `--unsafe`?

**Comment by skeetinec** [comment]
I try  --unsafe, but problem is not resolved: names of videofiles too long for win file system. For example:
079 105610771079110210841077 10821091108810891072 105510861102109710801077 1095107210961080 107610831103 1074108910771093 1041107210791086107410991081 1082109110881089 10631072108910901100 2
And i get message:
[*] : Lecture : '079 105610771079110210841077 10821091108810891072 105510861102109710801077 1095107210961080 107610831103 1074108910771093 1041107210791086107410991081 1082109110881089 10631072108910901100 2' (download skipped).
[-] : Reason : [Errno 22] Invalid argument: 'E:" -c 18 --unsafe\\singingbowls\\18 105610771079110210841077 10821091108810891072 105510861102109710801077 1095107210961080 107610831103 1074108910771093 1041107210791086107410991081 1082109110881089.part'

**Comment by skeetinec** [comment]
Sorry, i understand, yes, it's russian text of files, sorry :)

**Comment by r0oth3x49** [comment]
> 
> 
> Sorry, i understand, yes, it's russian text of files, sorry :)

you should use --unsafe switch with that.

`python -k COOKIE_FILE --unsafe COURSE_URL`

this should work fine if not let me know

**Comment by skeetinec** [comment]
Yes, so thanks, you are genious! Thank you so much for script, friend!
