### ISSUE TITLE
course name and chapter name is numbers  (in Arabic Language)

### ISSUE THREAD

**Issue by mabdulkadr** [r0oth3x49/udemy-dl#43]
hi r0oth3x49,

 It's a great job, but i have a problem (in Arabic Language )in course name and chapter name it's numbers.
- in English course it's ok.
- when i use youtube-dl it's ok.  

https://www.udemy.com/linuxubuntu/learn/v4/content

[*] : Downloading chapter : (1 of 4)
[+] : Chapter (01 16051602158316051577)
[+] : Found ('3') lecture(s).

[*] : Downloading lecture : (1 of 3)
[*] : Downloading (001 1606159215851577 1593157516051577 159316041609 1606159215751605 1575160416041610160616031587 1576158816031604 159315751605)
[*] : 55.90MB/4.11MB  7.35% |###-------------------------------------| 131.56kB/s  06:43s ETA

**I hope to fix this error quickly.**

**Comment by r0oth3x49** [comment]
@mabdulkadr thanks for the report. will have a look & fix ASAP
