### ISSUE TITLE
How to fix "file length is too long to create"?

### ISSUE THREAD

**Issue by Aragorn5534** [r0oth3x49/udemy-dl#436]
**Describe the bug**
Can't download course, because file length is too long to create.

**To Reproduce**
1. udemy course url: https://www.udemy.com/course/phpmasterwfs/
2. Run the following command to reproduce the error.
3. See error

**Expected behavior**
I think download just started.
**Screenshots**
![howfix](https://user-images.githubusercontent.com/55978006/65865883-fb21df00-e384-11e9-8145-3128f8e74e00.png)

**Python Environment (please complete the following information):**
 - OS Platform: Windows 10
 - Python Version 3.7.4

**Additional context**

**Comment by r0oth3x49** [comment]
@Aragorn5534 you should be using `--unsafe` switch in front it will solve your problem

**Comment by Aragorn5534** [comment]
It helps. Thank you.
