### ISSUE TITLE
Polish sings are incorrect

### ISSUE THREAD

**Issue by Xapixowy** [r0oth3x49/udemy-dl#437]
Folders and files names are incorrect, example:

Folder:
01 Wstęp czego i jak się nauczysz -> 01 Wst281p  czego i jak si281 nauczysz

File:
001 Jak będziesz uczyć się w tym kursie -> 001 Jak b281dziesz uczy263 si281 w tym kursie

**Comment by r0oth3x49** [comment]
> 
> 
> Folders and files names are incorrect, example:
> 
> Folder:
> 01 Wstęp czego i jak się nauczysz -> 01 Wst281p czego i jak si281 nauczysz
> 
> File:
> 001 Jak będziesz uczyć się w tym kursie -> 001 Jak b281dziesz uczy263 si281 w tym kursie

you should use `--unsafe` switch that will solve your problem
