### ISSUE TITLE
subtitle download skipped. Reason : [('system library', 'fopen', 'Too many open files')]

### ISSUE THREAD

**Issue by ForeverDreamer** [r0oth3x49/udemy-dl#438]
**Describe the bug**
    Both Courses "after-effects-kinetic-typography" and "adobe-premiere-pro-video-editing" only 
    downloaded part of them, before the error happens.

**To Reproduce**
1. udemy course url: [e.g `https://www.udemy.com/machinelearning/`] '...'
    https://www.udemy.com/course/after-effects-kinetic-typography/
2. Run the following command to reproduce the error.
    python udemy-dl.py https://www.udemy.com/course/after-effects-kinetic-typography/ -q 480
3. See error
    After normaly downloading several chapters, error happens: [*] : Downloading subtitle(s) [*] : Downloading (173 Practice Activity Challenge-tr) [*] : Subtitle : '173 Practice Activity Challenge-tr' (download skipped). [-] : Reason : [('system library', 'fopen', 'Too many open files'), ('BIO routines', 'BIO_new_file', 'system lib'), ('x509 certificate routines', 'X509_load_cert_crl_file', 'system lib')]

**Expected behavior**
    All course downloaded completely
    

**Screenshots**
   Don't see where I can upload a image, sorry!

**Python Environment (please complete the following information):**
 - OS Platform: [e.g. Windows 10, Ubuntu 16.04, macOS Sierra]
    Aws ec2 linux image
 - Python Version [e.g. 3.x.x]
    anaconda python 3.7
**Additional context**

**Comment by r0oth3x49** [comment]
the issue seems more related to system then udemy-dl

**Comment by ForeverDreamer** [comment]
Are you sure?  I mean, 1-9 chapters is downloaded successfully, It fails from 10th chapter and after.

**Comment by r0oth3x49** [comment]
> 
> 
> Are you sure? I mean, 1-9 chapters is downloaded successfully, It fails from 10th chapter and after.

yes because the server you are using to download courses might have open file limits, i will handle that on my side too, but it seems the server don't allow opening files more then some number,

i can't reproduce the error i have downloaded a way long course then this which has almost 21 chapters.

another alternative could be to use `--chapter-start` and `--chapter-end` switch or just `--chapter-start`.

example.

`python udemy-dl.py -u USER -p PASS COURSE_URL --chapter-start 10`

**Comment by ForeverDreamer** [comment]
It works, thanks.

**Comment by alan1world** [comment]
Yes, this looks like it is a platform issue for Linux / Mac.
See this StackOverflow question: https://stackoverflow.com/questions/16526783/python-subprocess-too-many-open-files

I have the same issue on Arch Linux, my max open file limit is 1024.
