### ISSUE TITLE
Error download - Reason : __enter__

### ISSUE THREAD

**Issue by Ianito** [r0oth3x49/udemy-dl#444]
**Describe the bug**
Im' trying to download a course, but this error happens:
```
[*] : Trying to login using cookies ...
[+] : Logged in successfully.
[*] : Downloaded course information .. (done)
[*] : Trying to logout now...
[+] : Logged out successfully.
[*] : Course 'typescript-na-pratica-criando-aplicacoes-web-com-typescript'.
[+] : Chapter(s) (18).
[*] : Lecture(s) (138).

[*] : Downloading chapter : (1 of 18)
[+] : Chapter (01 Introduc227o)
[*] : Found (6) lectures ...

[*] : Lecture(s) : (1 of 6)
[*] : Downloading (001 Vis227o Geral e Objetivo do Curso)
[*] : Lecture : '001 Vis227o Geral e Objetivo do Curso' (download skipped).
[-] : Reason : __enter__
```

**To Reproduce**
1. udemy course url: https://www.udemy.com/course/typescript-na-pratica-criando-aplicacoes-web-com-typescript/
2. I'm using cookies but i tried with email and password
3. See error

Screenshots:
![image](https://user-images.githubusercontent.com/14864646/67590600-daee0180-f731-11e9-90e6-f3ef84726086.png)

**Python Environment (please complete the following information):**
 - Windows 10 - 64 Bits - Last update
 - Python 3.7.4

**Additional**
All the courses I tried to download are like this ...

**Comment by VladimiPutin** [comment]
I have a similar issue
Steps to reproduce the behavior:

1. https://www.udemy.com/course/graphql-angular-de-0-a-experto-jwt-socket-mongodb-heroku-anartz-mugika/
2. I'm using cookies
3. error: 
 ![image](https://user-images.githubusercontent.com/5619504/67707257-27327f00-f988-11e9-98f7-6436ccc52159.png)

**Python Environment**
- Windows 10 - 64 Bits
- Python 2.7.15
