### ISSUE TITLE
Error 503 Backend fetch failed...

### ISSUE THREAD

**Issue by VladimiPutin** [r0oth3x49/udemy-dl#448]
**Describe the bug**
I can download other courses, but not this one.

**To Reproduce**
1. udemy course url: https://www.udemy.com/course/react-redux/`
2. im using cookie.
3. error capture
![image](https://user-images.githubusercontent.com/5619504/68128047-036dbc80-fee5-11e9-9df9-94031ef1c83e.png)

**Python Environment:
 - Windows 10
 - Python Version [2.7.15]

**Additional context**
Is it possible that my IP has been banned?

**Comment by abhinavpanse** [comment]
I am also having the same issue... I am using python 3.7...
![image](https://user-images.githubusercontent.com/20023085/68270916-01dafa80-0085-11ea-9d84-b4dadd73af40.png)

**Comment by jessequinn** [comment]
same error. python 3 with cookies

**Comment by EDAriR** [comment]
I have same issue yesterday, but it can work to day , I use same code same cookie

**Comment by jessequinn** [comment]
refreshing the access_token sometimes works and using login sometimes works. However, in general, i receive the 503 error.

**Comment by roleed** [comment]
Having the same issue @r0oth3x49 I can provide a URL with cookies for you to reproduce the error, how is best to get in contact with you?
