### ISSUE TITLE
Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

### ISSUE THREAD

**Issue by xxhaithamxx** [r0oth3x49/udemy-dl#45]
i don't know what's wrong i do i installed python and it's work fine and pip work fine just tested with pip install youtube-dl

is there a doc or video thanks

**Comment by r0oth3x49** [comment]
@xxhaithamxx verify first if there is `requirements.txt` file available inside `udemy-dl` directory. you can also see the [README](https://github.com/r0oth3x49/udemy-dl/blob/master/README.md) doc where usage and installation both are already mention.
