### ISSUE TITLE
-k prevents use of config

### ISSUE THREAD

**Issue by teamcrisis** [r0oth3x49/udemy-dl#451]
**Describe the bug**
Using `-k` results in the `config` file not being used for other specifications like `output`

**Steps to reproduce the behavior:**
1. Use `-k` option
2. Have a config file where `output` is specified
3. You should see downloads are not saved in the specified path

**Expected behavior**
When cookie option is given, other settings should be used from the config.
Ideally, cookie could be specified in the config, and if so, it would take precedence over username

**Python Environment:**
OS Platform: MacOS 10.14.6
Python Version: 2.7.17

**Comment by r0oth3x49** [comment]
@teamcrisis will implement reading config file along with `-k` switch but cookies will not be added to config file or else it's ruing the purpose `-k` switch so you should always specify cookies in a separate file then config, config was only meant to be used for logging in using user/pass,filepath,quality.
