### ISSUE TITLE
Udemy Says : 403 Forbidden You should use cookie base ...

### ISSUE THREAD

**Issue by eidiear** [r0oth3x49/udemy-dl#454]
Recently using both username+password and cookies return error:

Udemy Says : 403 Forbidden You should use cookie base method to authenticate or try again in few minutes ...

**Comment by r0oth3x49** [comment]
This is not an issue. It guides you to use cookie based method instead. [take a look at how to extract cookies](https://github.com/r0oth3x49/udemy-dl#how-to-login-with-cookie)

after that simply use `-k` switch.

**Comment by eidiear** [comment]
I have successfully use the code many many times with cookies (-k switch),
until today the error occured. The cookies logged my udemy account in, but
failed on _session._get something in the proces of getting some infos about
the course.

I tried using my username and password instead, but it just the same thing
occured.

I think maybe udemy has modified their code recently.
Thanks for your respond anyway, your code is awesome!

Regards.

**Comment by gs-shahid** [comment]
You will get this error if access-token is expired. In this case you need to get new access_token from your browser and try again after updating your file
