### ISSUE TITLE
Error loading the course (determining the size of files, etc.) 

### ISSUE THREAD

**Issue by Moroz812** [r0oth3x49/udemy-dl#455]
**Describe the bug**
With the --info flag, it displays an error code below, if without sections, sections are skipped, empty directories for sections are created, some files are attached to the course, the videos themselves are not ...

Maybe I'm doing something wrong, I do not exclude this, I apologize in advance.

**To Reproduce**
1. udemy course url: [e.g `https://www.udemy.com/machinelearning/`] '...'
https://www.udemy.com/course/android_sumin/
2. Run the following command to reproduce the error.
C:\Python27\udemy-dl-master>C:\Python27\python.exe udemy-dl.py https://www.udemy
.com/course/android_sumin/ -k cookies.txt --info
3. See error
[*] : Lecture(s) (2).
     - duration   : 02:38.
     - Lecture id : 11772542.
Traceback (most recent call last):
  File "udemy-dl.py", line 1453, in <module>
    main()
  File "udemy-dl.py", line 968, in main
    udemy.course_list_down(chapter_number=options.chapter, lecture_number=option
s.lecture, unsafe=options.unsafe)
  File "udemy-dl.py", line 280, in course_list_down
    content_length = stream.get_filesize()
  File "C:\Python27\udemy-dl-master\udemy\_shared.py", line 547, in get_filesize

    with requests.get(self.url, stream=True, headers=headers) as resp:
AttributeError: __exit__

**Expected behavior**

I would like to download the course, and if there are attachments to the section, they too ...

**Screenshots**

**Python Environment (please complete the following information):**
 - OS Platform: [Windows XP] - Could it be the OS version?
 - Python Version [2.7.17]

**Additional context**

Installed Modules:
Python pip
Python module requests
Python module colorama
Python module unidecode
Python module six
Python module requests[security] or pyOpenSSL - sort of like both options

**Comment by Moroz812** [comment]
https://github.com/r0oth3x49/udemy-dl/issues/443

I understand that I have a similar problem ...
But I can not upgrade Python to version 3, because it does not support OS Win XP

Pain...

**Comment by r0oth3x49** [comment]
@Moroz812 you still using Win XP, the next version which i will release i will remove support of python2 so i 'm closing this issue as won't resolve, you should upgrade to python 3 latest version and try again if the error still occurs feel free to re-open this issue.
