### ISSUE TITLE
Can't connect to udemy

### ISSUE THREAD

**Issue by RealMcFly01** [r0oth3x49/udemy-dl#46]
[https://i.imgur.com/EEaLhlC.png?1](url)
Cannot get udemy-dl to connect to website to begin downloading course. Says I need user/pass/link but all 3 are typed correct. Can anyone help me figure out what is wrong and how to fix it?

**Comment by r0oth3x49** [comment]
@RealMcFly01 link you shared is not working. can you explain a bit more.
what command are you using?

**Comment by RealMcFly01** [comment]
Not sure what I did but I was able to get it to work and got the course DL. sorry about the broken link in op, Thank you for writing up this code, you're awesome.
