### ISSUE TITLE
"Downloading course information, course id not found .. (failed)"

### ISSUE THREAD

**Issue by RR00200** [r0oth3x49/udemy-dl#460]
**Describe the bug**
I have the course bought with my account, and have participated in several lectures on web page. But when I tried to download them, it failed.

**To Reproduce**
1. udemy course url: https://www.udemy.com/course/machinelearning/
2. Run the following command: python udemy-dl.py -u ACCOUNT -p PASSWORD https://www.udemy.com/course/machinelearning/ -q 1080 -o DIRECTORY
3. See error: 
Downloading course information, course id not found .. (failed)
[i] : It seems either you are not enrolled or you have to visit the course at least once while you are logged in.

**Expected behavior**
Able to download all of them.

**Python Environment (please complete the following information):**
 - OS Platform: macOS High Sierra
 - Python Version: 3.7.3

Thanks in advance.

**Comment by RR00200** [comment]
Succeeded to download another course.

**Comment by r0oth3x49** [comment]
if login with email/pass don't work there is alternative you can use cookie based login as well. closing the issue.

**Comment by ademianfight** [comment]
> if login with email/pass don't work there is alternative you can use cookie based login as well. closing the issue.

can you give me the sample of cookie ?

**Comment by r0oth3x49** [comment]
[see this section](https://github.com/r0oth3x49/udemy-dl#how-to-login-with-cookie)
