### ISSUE TITLE
Russian symbols in names

### ISSUE THREAD

**Issue by gorshkov-leonid** [r0oth3x49/udemy-dl#463]
**Screenshots**
![image](https://user-images.githubusercontent.com/2270831/72149617-fd9cc780-33bc-11ea-97da-93dd3597b04d.png)

**Python Environment (please complete the following information):**
 - OS Platform: Ubuntu WSL 18.04 / Windows
 - Python Version 2.7.1 / Python for Windows 3.8.x

**To reproduce get free course and try to download some video:**
`python udemy-dl.py https://www.udemy.com/course/intensive-js -o . --chapter-start 1 --chapter-end 1 --lecture-start 1 --lecture-end 1`

**Comment by gorshkov-leonid** [comment]
Типы данных и взаимодействие с пользователем   
 
105510861083108510861094107710851085107O03 10871088107210821090108010821072 10871086 108510721087108010891072108510801102 10821086108810791080108010851099 1090108610741072108810861074

**Comment by gorshkov-leonid** [comment]
I do not not know python, but the experiment shows that problem in code
`  _temp   = ''.join([str(ord(i)) if ord(i) > 128 else i for i in title])`

**Comment by r0oth3x49** [comment]
you shoudl use `--unsafe` switch
