### ISSUE TITLE
Connection Error - HTTPSConnectionPool Max retries exceeded

### ISSUE THREAD

**Issue by floriankasper** [r0oth3x49/udemy-dl#465]
**Describe the bug**
The bug is literally the same like #430 - excepting that it happens on all tested courses after some time. 

**To Reproduce**
1. udemy course url:
`https://www.udemy.com/course/react-the-complete-guide-incl-redux/`
2. Run the following command to reproduce the error: 
`python udemy-dl.py https://www.udemy.com/course/react-the-complete-guide-incl-redux/ --cache --skip-sub --unsafe` 
3. See error:
` ConnectionError: HTTPSConnectionPool(host='a2.udemycdn.com', port=443): Max retries exceeded with url: /2017-[...]HD_720p.mp4?nva=[...]020ede2 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10c2e5190>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))`

**Expected behavior**
The expected behavior would be a smooth download of all assets and video files from the course.

**Screenshots**
![error](https://user-images.githubusercontent.com/10350653/72477954-1b20c580-37f1-11ea-8eab-ca02dd184d45.png)

I tried with and without `--unsafe` - same result both times

**Python Environment (please complete the following information):**
 - OS Platform: macOS Catalina 10.15.2 (19C57)
 - Python Version 3.7.6
 - Pip Version: 19.3.1 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)
 - Requirements:
    colorama     0.4.3
    pyOpenSSL    19.1.0
    requests     2.22.0
    six          1.14.0
    Unidecode    1.1.1
    urllib3      1.25.7
    wheel        0.33.6

**Comment by r0oth3x49** [comment]
the error is more specific to requests/urllib then udemy-dl, but will look for solution, most of the time it happens in Mac only not any other OS.

**Comment by Eliteneet** [comment]
I'm still having this happen on the latest version of udemy-dl

**Comment by Deviad** [comment]
I have this too. 
Could it be because of some kind of throttling?

**Comment by ronnicek** [comment]
Just hit it as well.. on CentOS 7 in virtualenv

**Comment by r0oth3x49** [comment]
@ronnicek wait for some time and then try again there is no way i can fix this but urllib3/requests

**Comment by ronnicek** [comment]
@r0oth3x49 I actually had it yesterday a lot.. now it looks ok (there are errors time to time, but only single ones, not half of the course) :) Thanks! :)

**Comment by r0oth3x49** [comment]
great so the solution is to wait at least a day :P .
