### ISSUE TITLE
"Failed to login "

### ISSUE THREAD

**Issue by drokbers** [r0oth3x49/udemy-dl#468]
Windows 10
Python 3.8.1
latest udemy-dl as of  31.01.2020 (0.5)

udemy course url:https://www.udemy.com/course/sifirdan-ileri-seviyeye-python/learn/lecture 

![Screenshot 31 01 2020 01_52_48_LI](https://user-images.githubusercontent.com/6474580/73497833-c07c9180-43cc-11ea-845f-19759b75ed8d.jpg)

**Comment by bonjovi27** [comment]
Check your anti-virus. In my case, it was Kaspersky blocking it.

**Comment by r0oth3x49** [comment]
use cookie based method instead if user/pass not working

**Comment by drokbers** [comment]
> use cookie based method instead if user/pass not working

Thanks for answer. I tried  cookie method but It wasnt clear for me. I found my access code and I put a txt but Idk what I must do after that.. guide is hard to understand for me.  Can you help me?

**Comment by r0oth3x49** [comment]
did you tried directly using?

-u email -p pass COURSE

**Comment by r0oth3x49** [comment]
when you extract your access token donot logout from browser when you logout the session gets destroyed which expires the access token
