### ISSUE TITLE
Downloading course inforamtion, course id not found .. (failed)

### ISSUE THREAD

**Issue by riplotus** [r0oth3x49/udemy-dl#469]
**Describe the bug**
For purchased and enrolled Udemy courses.
The download failed in every course which contains non-English characters in the course name. However, it works fine when the name of the course is only English and or German. 

**To Reproduce**
1. udemy course url: [e.g `https://www.udemy.com/course/android-android-u/`] '...'
2. Run the following command to reproduce the error. (windows command prompt)
>python udemy-dl.py https://www.udemy.com/course/android-android-u/ -q 720
3. See error
... 
[*] : Logged in successfully.
[-] : Downloading course information, course id not found .. (failed)
[i] : It seems either you are not enrolled or you have to visit the course atleast once while you are logged in.
[*] : Trying to logout now...
[+] : Logged out successfully.
**Expected behavior**

**Python Environment (please complete the following information):**
 - OS Platform: [e.g. Windows 10]
 - Python Version [e.g. 3.6]

**Comment by r0oth3x49** [comment]
for non english course did you treid using `--unsafe`?
you can only download course if you have subscribed/enrolled, the tool will download courses if it is paid otherwise it will not download.

**Comment by riplotus** [comment]
> for non english course did you treid using `--unsafe`?
> you can only download course if you have subscribed/enrolled, the tool will download courses if it is paid otherwise it will not download.

Thank you. Yep, for purchased and enrolled courses. I do not have video-friendly internet connection at home, therefore searching for offline choice.
I tried '--unsafe', it does not work still.

**Comment by r0oth3x49** [comment]
no response from you as of yet so i 'm closing the issue.

**Comment by ioanvapi** [comment]
Hi. I get the same error trying to download with command: python.exe udemy-dl.py -u <myuser> -p <mypass> https://www.udemy.com/course/hmtl5-training/ --unsafe
I have accessed the course before. It is enrolled in my udemy account.
I can provide username/pass by email if it can help. The git repo is also updated. I don't know what else to try.

**Comment by ghost** [comment]
The id of the course can be found on this site. Can we tell udemy-dl that it should use this id?
https://www.infognu.com/udemy-course-date-finder
