### ISSUE TITLE
Can't download content after successful login (SSLError(SSLError("bad handshake")

### ISSUE THREAD

**Issue by yassinesabri** [r0oth3x49/udemy-dl#471]
**Describe the bug**
I keep getting (download skipped) error and I can't download any content from the course, I've tried both methods, login with username/password and Cookies.

**To Reproduce**
1. udemy course url: https://www.udemy.com/course/flutter-dart-the-complete-flutter-app-development-course/
2. Run the following command to reproduce the error.

- python udemy-dl.py -k access_token https://www.udemy.com/course/flutter-dart-the-complete-flutter-app-development-course/
Or

- python udemy-dl.py -u xxxxx@gmail.com -p xxxxx https://www.udemy.com/course/flutter-dart-the-complete-flutter-app-development-course/ (--unsafe)

3. See error

ConnectionError: HTTPSConnectionPool(host='a.udemycdn.com', port=443): Max retries exceeded with url: /2018-03-18_21-34-35-b48af2dfe540607aeca3364afe89f030/WebHD_720p.mp4?nva=20200209142843&token=090d4692eebf1a4e26ca2 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls12_check_peer_sigalg', 'wrong signature type')],)",),))

**Expected behavior**
Be able to download the course content

**Screenshots**
<a href="https://imgur.com/FfqMaf7.png">
  <img src="https://imgur.com/FfqMaf7.png" />
</a>

**Python Environment (please complete the following information):**
 - OS Platform: Kali Linux Rolling
 - Python Version 3.7

**Comment by r0oth3x49** [comment]
try to upgrade the dependencies, the error is more specific to requests not udemy-dl i can't solve this error but have handle the exception, you can wait and download the course, or try downloading on some other os like ubuntu. closing the issue.
