### ISSUE TITLE
Downloading course information, course id not found .. (failed) as #469

### ISSUE THREAD

**Issue by ioanvapi** [r0oth3x49/udemy-dl#472]
Hi. 
I get the same error as issue #469 trying to download with command: python.exe udemy-dl.py -u myuser -p mypass https://www.udemy.com/course/hmtl5-training
Also, tried with cookies and unsafe but got exactly the same error.

I have accessed the course before. It is enrolled (**it's a free course**) in my udemy account.
I can provide username/pass by email if it can help. The git repo is also updated. I don't know what else to try.
Also, I can download other courses but not this one. Thanks.

**Comment by r0oth3x49** [comment]
@ioanvapi i will check :)

**Comment by ioanvapi** [comment]
Any update?! At least, were you able to reproduce it?

**Comment by simplerethink** [comment]
@ioanvapi I'm able to reproduce the issue. I don't seem to have the issue with other courses.

**Comment by r0oth3x49** [comment]
![Capture](https://user-images.githubusercontent.com/11024397/75105638-93bc4280-5637-11ea-94e1-32f8ab4d79d0.PNG)
 issue is fixed, thanks for reporting .
