### ISSUE TITLE
Courses stop downloading

### ISSUE THREAD

**Issue by teamcrisis** [r0oth3x49/udemy-dl#475]
**Describe the bug**
Similar to #411 I have come across several courses that suddenly stop downloading. 

**To Reproduce**
1. Download course `digital-marketing-guide`
2. Watch as several chapters and lectures are successfully downloaded
3. Watch as suddenly download stops
4. Restart download, course stops downloading at some location

**Screenshots**
![image](https://user-images.githubusercontent.com/4693056/75594387-91525200-5a56-11ea-928f-d929650e4c75.png)

**Python Environment:**
 - OS Platform: MacOS 10.14.6 Mojave
 - Python Version 3.7.6

**Comment by teamcrisis** [comment]
In screenshot, you will see that lecture 67 is skipped. Not sure why.

**Comment by r0oth3x49** [comment]
it must be some sort of external files which are not logged.

**Comment by simplerethink** [comment]
I'm fairly certain that is not the case but I will check. How might I tell udemy-dl to ignore such situations? As of now, no other lectures can be downloaded because it hangs at this point, which was the point of this issue.

**Comment by teamcrisis** [comment]
I'm fairly certain that is not the case but I will check. How might I tell udemy-dl to ignore such situations? As of now, no other lectures can be downloaded because it hangs at this point, which was the point of this issue.

**Comment by r0oth3x49** [comment]
you can directly start downloading from specifc chapter number as well can you try?

python udemy-dl -U USER -p PASS URL --chapter-start CHAPTER_NUMBER

if it still hangs on that particular lecture then i might need your creds to reproduce and fix
