### ISSUE TITLE
Course download finishes without reporting error at the end

### ISSUE THREAD

**Issue by geffchang** [r0oth3x49/udemy-dl#477]
**Describe the bug**
This is a feature request, rather than a bug. When you download a course, and there is an error downloading one of the courses in between, but the course finishes successfully, you are not informed at the end that there was an error. If the course download is large (i.e. has many videos / chapters), you may miss this error if you don't scroll up or check the previous progress.

NOTE: There are 2 cases of error: (1) An error happens in between, but the last course finishes successfully. In this case, it's difficult to know there was an error, (2) An error happens in between, and the course also finishes with an error. In this case, you know immediately there is an error.

**To Reproduce**
1. It will not be easy to replicate this issue. Download a large course, get an error in between, and finish a course.

**Expected behavior**
At the end of the course download, report any failed downloads (video, subtitle, document, etc). A note that an error occurred may be enough. Optional to add: Number of errors.

**Screenshots**
Subtitle skipped: https://imgur.com/AYnDkIW
Lecture skipped: https://imgur.com/ASkqUxq

**Python Environment (please complete the following information):**
 - OS Platform: Windows 10
 - Python Version 3.8.0

**Additional context**

**Comment by r0oth3x49** [comment]
hmm that is most of the time case with subtitles as the direct url gets expired for some reason, will add some mechanism to show the total of errors at the end of course

**Comment by geffchang** [comment]
@r0oth3x49 It can also happen with a lecture. I updated the screenshot; I got it just a while ago.

**Comment by r0oth3x49** [comment]
@geffchang in the next version i already have added a proper session management, so this issue will be resolved with next major update.

**Comment by geffchang** [comment]
> @geffchang in the next version i already have added a proper session management, so this issue will be resolved with next major update.

That sounds great. Looking forward to it! :)
