### ISSUE TITLE
Possible suggestion.

### ISSUE THREAD

**Issue by Wea1thRS** [r0oth3x49/udemy-dl#478]
Any chance to add the ability to download all courses currently enrolled in on a specific account? I have over 1,000 courses I would like to download that would be extremely tedious to do with current methods.

**Comment by teamcrisis** [comment]
I would love this as well. I currently use a bash script, but even this is very tedious.

```
#!/bin/bash
courses=(
	https://www.udemy.com/course/jam-stack/learn/lecture/17665758#overview
	https://www.udemy.com/course/hands-on-web-development-with-react-and-gatsbyjs/learn/lecture/16798080#overview
)

for c in "${courses[@]}"
do
	echo "\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n START DOWNLOADING $c"
	python ~/udemy-dl/udemy-dl.py $c --skip-sub -k ~/udemy-dl-cookie.txt
    echo "END DOWNLOADING $c \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n"
done
```

**Comment by r0oth3x49** [comment]
@Wea1thRS i don't have plan for getting all courses subscribed, but i do have plan to add support to download courses in file. i 'm closing the issue as duplicate as this was already discuss and requested by some one else.
