### ISSUE TITLE
No JSON object could be decoded

### ISSUE THREAD

**Issue by fyz** [r0oth3x49/udemy-dl#479]
**Describe the bug**
No JSON object could be decoded.

**To Reproduce**
1. udemy course url: [e.g `https://www.udemy.com/course/build-olx-clone-with-python-django` or `https://www.udemy.com/course/microsoft-azure-fundamentals-training-bootcamp`] '...'

**Screenshots**
![05](https://user-images.githubusercontent.com/195547/77193530-b0388700-6ade-11ea-964f-0a75910b629d.png)

**Python Environment (please complete the following information):**
 - Windows 7
 - Python 2.7.13

**Additional**
I returned to check udemy-dl 0.4 and it says that Udemy Says: You don't have permision

**Comment by r0oth3x49** [comment]
@fyz i will remove python2 support in next update please check if the error occurs with python3.

**Comment by fyz** [comment]
@r0oth3x49 working with python 3.7, thanks
