### ISSUE TITLE
All video downloads are "skipped"

### ISSUE THREAD

**Issue by bvrulez** [r0oth3x49/udemy-dl#481]
**Describe the bug**
After `python3 udemy-dl.py -u MYUSER -p MYPASS https://www.udemy.com/course/git-complete` I get logged in successfully and all of the courses videos are skipped. I get a directory full of directories of the course sections and occationally, there is some .txt file in it for external resources or an html-file. But apart from that the directories are empty. No video file is downloaded.

**To Reproduce**
1. udemy course url: 
https://www.udemy.com/course/git-complete
2. Run the following command to reproduce the error.
python3 udemy-dl.py -u MYUSER -p MYPASS https://www.udemy.com/course/git-complete
3. See error
[*] : Downloading subtitle(s)
[*] : Downloading (001 Welcome and Course Goals-it)
[*] : Subtitle : '001 Welcome and Course Goals-it' (download skipped).
[-] : Reason : __ exit __

**Expected behavior**
I was expection all video files to download.

**Screenshots**
no screenshots 

**Python Environment (please complete the following information):**
 - OS Platform: Lubuntu 16.04
 - Python Version: 3

**Additional context**
I am logged into the server that should do the download via ssh.

This is probably the same issue as: https://github.com/r0oth3x49/udemy-dl/issues/473
I see this was reported several times already, e.g. in: https://github.com/r0oth3x49/udemy-dl/issues/458

Maybe this is because my operating system Lubuntu 16.04 is out of date.

**Comment by r0oth3x49** [comment]
can't reproduce on ubuntu works fine for me
![Capture](https://user-images.githubusercontent.com/11024397/77614450-c9ae5880-6f4e-11ea-9202-98a8b1ce5590.PNG)

**Comment by bvrulez** [comment]
As I said I suspect the problem is due to my Lubuntu 16.04 beeing outdated. I cannot upgrade it because 18.04 has a totally different desktop environment and I want to keep the system running as long as possbile without interference. Maybe I will try and run 18 in a VM on the server. 

But if you think it has nothing to do with this and you can test it on 16.04 then email me at ben AT bviertel.de and I will provide you with my login credentials.

**Comment by r0oth3x49** [comment]
@bvrulez have tested with ubuntu 18 LTS, will test and on 16 as well but i 'm sure it should work there too.

**Comment by bvrulez** [comment]
works well. awesome guy! i am looking forward to becoming someone like you. have a nice evening!

**Comment by r0oth3x49** [comment]
> 
> 
> works well. awesome guy! i am looking forward to becoming someone like you. have a nice evening!

good luck bro.
