### ISSUE TITLE
Improve shebang for python

### ISSUE THREAD

**Issue by dragetd** [r0oth3x49/udemy-dl#483]
The shebang currently has an absolute path to python.

According to https://www.python.org/dev/peps/pep-0394/#recommendation the recommended way is:

/bin/env python3

PR incoming.

**Comment by r0oth3x49** [comment]
@dragetd in next version all PEP rules will handled properly. so i 'm closing the PR and issue both thanks for that anyway.

**Comment by dragetd** [comment]
Ah, okay. Did not find any branch or info about the planned updates. Looking forward to the next version! :-)
