### ISSUE TITLE
Too many console outputs slow down the whole process

### ISSUE THREAD

**Issue by dragetd** [r0oth3x49/udemy-dl#486]
Try downloading a course. Then, downloading it again, it will skip over all chapters.

Then try the same thing, but redirecting stdout to /dev/null. The whole process is significantly faster. Even when downloading, the console is updated very often which slows down things.

I suggest only one update per second, this will speed up things.

**Comment by r0oth3x49** [comment]
i would like continue with the current status. will think about it in future version.

**Comment by dragetd** [comment]
Okay, why are you closing this issue then?

**Comment by r0oth3x49** [comment]
because i said i will think about it in future versions i didn't i 'm planing to add.
