### ISSUE TITLE
Cannot do anything, receiving same error

### ISSUE THREAD

**Issue by Utkarsh-Sinha75** [r0oth3x49/udemy-dl#491]
TypeError:cannot unpack non-iterable NoneType object
Please help
![Capture](https://user-images.githubusercontent.com/50379193/79562762-2a9dfc00-80c9-11ea-9b00-226a8575d7c9.PNG)

**Comment by r0oth3x49** [comment]
@Utkarsh-Sinha75 you should use proper url, the URL you are using is missing the *www* which is why you are facing the error.

url should be.

https://www.udemy.com/...
https://BUSINESS_NAME.udemy.com/...
