### ISSUE TITLE
Downloads only in 720p

### ISSUE THREAD

**Issue by ArKay74** [r0oth3x49/udemy-dl#493]
**Describe the bug**
All of my downloads are stored in 720p even when they are available in 1080. 

**To Reproduce**
1. https://www.udemy.com/course/unitycourse/
2. udemy-dl.py -q 1080 -k \Udemy-DL\cookie --sub-lang en https://www.udemy.com/course/unitycourse/
3. All files are in 720p

**Expected behavior**
Files downloaded in 1080p. I can save them in 1080p through IDM from the page.
Happens with all of the other courses as well.

**Screenshots**

**Python Environment (please complete the following information):**
 - Windows 10 current
 - Python 3.7.4

**Additional context**

**Comment by ArKay74** [comment]
It doesn't list 1080p even though it's available.

`     - duration   : 02:38.
     - Lecture id : 10614272.
        - video:mp4@1280x720     720p    52.68MB (Best)
        - video:mp4@854x480      480p    26.51MB
        - video:mp4@640x360      360p    14.88MB
        - video:mp4@256x144      144p    5.01MB
        - subtitle:en@vtt        vtt     3.89KB
        - subtitle:id@vtt        vtt     4.21KB
        - subtitle:th@vtt        vtt     7.58KB
        - subtitle:fr@vtt        vtt     4.30KB
        - subtitle:de@vtt        vtt     4.07KB
        - subtitle:es@vtt        vtt     4.09KB
        - subtitle:it@vtt        vtt     4.09KB
        - subtitle:ja@vtt        vtt     4.80KB
        - subtitle:pt@vtt        vtt     4.11KB
        - subtitle:tr@vtt        vtt     4.00KB`

**Comment by ArKay74** [comment]
![image](https://user-images.githubusercontent.com/12251023/79693382-98cdf480-826a-11ea-9c91-14d03331937b.png)

Streams downloadable through IDM.

**Comment by r0oth3x49** [comment]
@ArKay74 you could have checked older issues, this is feature request, udemy-dl don't support hls stream downloading, closing the issue as duplicate.

**Comment by ArKay74** [comment]
Could be mentioned in the docs as well so that people aren't surprised by it and think it's a bug since there is a qualty switch.
