### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by abban270** [r0oth3x49/udemy-dl#495]
Unable to login with mmy account
![Capture](https://user-images.githubusercontent.com/50278545/80214368-fed7c480-863a-11ea-89ac-f7f2669e4c32.PNG)

**Comment by abban270** [comment]
i have try this commands
    pip install requests --upgrade
    pip install unidecode --upgrade
    pip install requests[security] --upgrade
    pip install pyOpenSSL --upgrade
My version (Python 3.7.4)

but the same probleme

**Comment by darkRaspberry** [comment]
try login with cookie
Login with password is having error

**Comment by abban270** [comment]
![Capture](https://user-images.githubusercontent.com/50278545/80226884-3bacb700-864d-11ea-8f68-0ef463922610.PNG)

**Comment by r0oth3x49** [comment]
@abban270 you are not giving the cookies right way, can you follow the guideline on how you should extract the cookies, see the readme file.

**Comment by abban270** [comment]
yes i have see all instruction
and i get the right value
![Capture](https://user-images.githubusercontent.com/50278545/80251327-b8ec2200-8675-11ea-854a-43f8ba85ced7.PNG)
