### ISSUE TITLE
having speed issue

### ISSUE THREAD

**Issue by darkRaspberry** [r0oth3x49/udemy-dl#496]
**Describe the bug**
The Speed get decreased too low upto 65 KB/S only
 
**To Reproduce**
1. udemy course url: https://www.udemy.com/course/nodejs-express-mongodb-bootcamp-with-real-projects
2. python udemy-dl.py https://www.udemy.com/course/nodejs-express-mongodb-bootcamp-with-real-projects/ -k cookie.txt --chapter-start 10
3. The speed in starting is good but after lecture 40 speed get down

**Expected behavior**
Speed should go up to 1-2 MB/s

**Screenshots**
![Screenshot (8)](https://user-images.githubusercontent.com/56693429/80225461-ba631d80-8668-11ea-925c-3cf53fc4d1a2.png)

**Python Environment (please complete the following information):**
 - OS Platform: Windows 10 PRO Insider Preview BUILD-19613
 - Python Version: 2.7.17 (LATEST)

**Additional context**
NOPE

**Comment by r0oth3x49** [comment]
@darkRaspberry i can't reproduce this, but i will add external download utility support in up comming version i 'm working on. May be some thing else is eating up your bandwidth.

**Comment by darkRaspberry** [comment]
i don't think soo that my bandwidth is eaten up.
But restarting several time have **partially** solved my issue.

Thanks
