### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by Guizmo24** [r0oth3x49/udemy-dl#497]
Hello there,

_I downloaded a few of my courses a few days ago, and wanted to resume and finish my downloads. But today, every time I try to log in to access my courses, I get this 403 Forbidden error, which keeps me from downloading._ 

**To Reproduce**
1. udemy course url: [e.g `https://www.udemy.com/machinelearning/`] 
_**https://www.udemy.com/course/mixing-masterclass/**_
2. Run the following command to reproduce the error: 
_**I typed python udemy-dl.py course_url, which worked perfectly fine a few days ago**_
3. See error

**Expected behavior**
_**I expected the download to start.**_

**Screenshots**
![error](https://user-images.githubusercontent.com/64291450/80266386-e77cf380-869b-11ea-92a7-262699733668.PNG)

**Python Environment (please complete the following information):**
 - OS Platform: _**Windows 10**_
 - Python Version _**3.8.2**_

**Additional context**
**_As mentioned before, worked perfectly fine a few days ago. I figured either Udemy changed something on their side, or they noticed suspicious activity on my account and blacklisted my IP, so I went back to the website on my browser and could access the courses altogether (might not be an IP issue?)._**

**Comment by ZevFung** [comment]
me too

**Comment by ZevFung** [comment]
#389
