### ISSUE TITLE
ImportError: No module named udemy

### ISSUE THREAD

**Issue by iPhoNewsRO** [r0oth3x49/udemy-dl#5]
hello, after cloning this repo, installing the requirements and so, i get this:

```
Radus-MBP-2016:Downloads radu$ python udemy-dl.py -u user@domain.com -p p4ssw0rd https://www.udemy.com/COURSE_NAME
Traceback (most recent call last):
  File "udemy-dl.py", line 7, in <module>
    import udemy
ImportError: No module named udemy
```

any help?

**Comment by r0oth3x49** [comment]
@iPhoNewsRO  Can you explain a bit more with screenshots. and which OS r u using? And can you please explain why you referenced an Issue that is not related to this repo?

**Comment by iPhoNewsRO** [comment]
i am running macOS 10.12.6 (16G29) and this issue is happening on your project.

**Comment by r0oth3x49** [comment]
@iPhoNewsRO i have updated and tested on macOS it is working fine now. try it and let me know if you still face the same problem.
