### ISSUE TITLE
What is default resolution?

### ISSUE THREAD

**Issue by SalihKARAHAN** [r0oth3x49/udemy-dl#50]
Hi @r0oth3x49,

First thanks for the 'udemy-dl' app. I have a wonder, if we don't pass the "-r" arg as "720", what is your app default behaviour? Will the app list the exist resolution and select max or select first? I wonder it because I ran with "-l" videos don't order by resolution. 

Thanks.

**Comment by r0oth3x49** [comment]
@SalihKARAHAN default is 720 if its available. i think its already written in a description of `--help` option as well. BTW does it really matters `list down order by resolution`?
