### ISSUE TITLE
Downloading asset files(.py)

### ISSUE THREAD

**Issue by Redlava60** [r0oth3x49/udemy-dl#501]
Course: https://www.udemy.com/course/python-training/

Description: It downloaded the course well, but since the course has some .py files attached, it wasn't able to download them and was showing the error, as shown below
https://i.imgur.com/q8pdfMF.png

Error output:
> [*] : Downloading asset(s)
> [*] : Downloading (file:py@py)
> [*] : Asset : 'file:py@py' (download skipped).
> [-] : Udemy returned HTTP Code 416: Requested Range Not Satisfiable
> 
> [*] : Downloading asset(s)
> [*] : Downloading (file:py@py)
> [*] : Asset : 'file:py@py' (download skipped).
> [-] : Udemy returned HTTP Code 416: Requested Range Not Satisfiable
> 
> [*] : Downloading asset(s)
> [*] : Downloading (file:py@py)
> [*] : Asset : 'file:py@py' (download skipped).
> [-] : Udemy returned HTTP Code 416: Requested Range Not Satisfiable
> 
> [*] : Downloading asset(s)
> [*] : Downloading (file:py@py)
> [*] : Asset : 'file:py@py' (download skipped).
> [-] : Udemy returned HTTP Code 416: Requested Range Not Satisfiable
> 
> [*] : Downloading asset(s)
> [*] : Downloading (file:py@py)
> [*] : Asset : 'file:py@py' (download skipped).
> [-] : Udemy returned HTTP Code 416: Requested Range Not Satisfiable

**Comment by Nightreaver** [comment]
I have the 'complete-python-developer-zero-to-mastery' and it downloaded .py files well.
So it might be another issue?

**Comment by r0oth3x49** [comment]
> 
> 
> I have the 'complete-python-developer-zero-to-mastery' and it downloaded .py files well.
> So it might be another issue?

Awesome it means i 'm not the only one who can't reproduce for me it downloads any sort of file if the link is not expired. so i 'm closing the issue as invalid because no response from @Redlava60 .

**Comment by Nightreaver** [comment]
So, coming back to this, its not totally invalid.
It does not specifically happen on .py file, but any resource I just found myself that this happens to me as well. too a specific course and all containing files in a chapter

be it .json, .ps1 or .txt

the question is, if this is related to udemy (like 503 error) or the downloader

**Comment by r0oth3x49** [comment]
> 
> 
> So, coming back to this, its not totally invalid.
> It does not specifically happen on .py file, but any resource I just found myself that this happens to me as well. too a specific course and all containing files in a chapter
> 
> be it .json, .ps1 or .txt
> 
> technically, the files are getting downloaded and saved as .part, but they wont be renamed.
> when you run the downloader again, you are requesting the missing range/byte offset from the server, which is obviously "not in range" so you will get an 416 because the file is already downloaded completely.
> 
> @r0oth3x49 try deleteing some of your asset files and try re-downloading them, they might come up as .part first, then failing in second run

awesome i will check and fix

**Comment by Nightreaver** [comment]
The exact issue is, that the amount of data that is downloaded is technically more than the size of the file itself
![image](https://user-images.githubusercontent.com/3270156/81598178-dc4af700-9401-11ea-8f99-315cee136a14.png)
