### ISSUE TITLE
Slow download speed

### ISSUE THREAD

**Issue by AdityaJaiswal1** [r0oth3x49/udemy-dl#502]
**Describe the bug**
I have a 100MBps connection and usually, I get around 8-10MBps speed when downloading. But when I am downloading using the tool it hardly touches the 2MBps mark. It usually downloads at 1.25MBps at max. I tried downloading a course using IDM and I got around the speed I was expecting which was 9-10MBps. So, can anyone tell what's is wrong I am doing or is it just me or, others also getting the same issue?

**Comment by dillagr** [comment]
same here.. that's rate limiting at the other end of the pipe.
(you really can't realistically watch 720p videos at 9MBps, when it is supposed to be streaming)
