### ISSUE TITLE
asset download skipped

### ISSUE THREAD

**Issue by bibekme** [r0oth3x49/udemy-dl#504]
**Describe the bug**
When downloading the downloadable resources from course, I get the error that is printed in my prompt saying "None" and the download of that file is skipped. The course comes with a text file that includes the source code of the tutorial. Udemy-dl fails to download the file.  I have attached the screenshot of the error.

**To Reproduce**
1. udemy course URL: https://gale.udemy.com/course/build-an-app-with-aspnet-core-and-angular-from-scratch/
2. Run the following command to reproduce the error:
python udemy-dl.py https://gale.udemy.com/course/build-an-app-with-aspnet-core-and-angular-from-scratch/ --sub-lang en -k [cookies text file]
3. See error

**Expected behavior**
I wanted to download those assets without any error.

**Screenshots**
![Screenshot (16)](https://user-images.githubusercontent.com/55137095/81529076-c1cf3a00-937d-11ea-9469-217ba8516221.png)

**Python Environment (please complete the following information):**
 - OS Platform: Windows 10
 - Python Version: Python 3.8.3rc1

**Comment by Nightreaver** [comment]
Can you check if the target folder contains the asset file with .part file extension ?

**Comment by Bibekkhatriii** [comment]
Yes, it has .part file

**Comment by Nightreaver** [comment]
I think it then relates to #501 

a quick and probably **unclean** workaround is to edit line #L222 in file udemy\_shared.py 
and change 
```if total_bytes_done == bytes_to_be_downloaded:```
to
```if total_bytes_done>= bytes_to_be_downloaded:```
(greater equal)

tho this might have other unexpected results - tho for me its currently working this way.
Try at your own risk

**Comment by Bibekkhatriii** [comment]
Thanks. I will try it

**Comment by r0oth3x49** [comment]
> 
> 
> I think it then relates to #501
> 
> a quick and probably **unclean** workaround is to edit line #L222 in file udemy_shared.py
> and change
> `if total_bytes_done == bytes_to_be_downloaded:`
> to
> `if total_bytes_done>= bytes_to_be_downloaded:`
> (greater equal)
> 
> tho this might have other unexpected results - tho for me its currently working this way.
> Try at your own risk

not a good fix, the file bytes shouldn't be greater then the total

**Comment by r0oth3x49** [comment]
![Capture](https://user-images.githubusercontent.com/11024397/81882049-2d4a1f00-95ab-11ea-8dc7-5bcff60aa842.PNG)
i can't reproduce the error with courses i have in my account take a look at above SS. I might need an account to reproduce and fix

**Comment by Nightreaver** [comment]
My idea was, that they started using gzip/deflate for compressing the asset files, so these data that was downloaded is less than the file afterwards.
I checked the files contents from manual udemy download and dem the downloader and they are equal. So something has to cause the difference, I just didn't notice anything bad from having downloaded more yet.

**Comment by r0oth3x49** [comment]
@Nightreaver requests also sends the header by default `Accept-Encoding: gzip/deflate`

**Comment by r0oth3x49** [comment]
i don't see any other reports and can't even reproduce with retries and the suggestions as well, so i 'm considering that this is resolved, or you guys share your creds on my email to check with that course causing the error.

`nasir251292@gmail.com`
