### ISSUE TITLE
-] : Udemy Says : 403 Forbidden You should use cookie base method to authenticate or try again in few minutes ...

### ISSUE THREAD

**Issue by ahmadsb101** [r0oth3x49/udemy-dl#505]

**Comment by ioanvapi** [comment]
The same error I got too. The error text is; "Udemy Says : 403 Forbidden You should use cookie base method to authenticate or try again in few minutes ...".

After trying download with cookies I got the error; "Cookies error, unable to find access_token, proper cookies required."

**Comment by ahmadsb101** [comment]
Yes, I used cookie option and it worked completely. The username/password approach is not working right now. 
I think we should close this issue. shall we?
