### ISSUE TITLE
Download skipped error with message: "Reason : Could not find a suitable TLS CA certificate bundle, invalid path: /<path>/lib/python3.6/site-packages/certifi/cacert.pem

### ISSUE THREAD

**Issue by kutkin54** [r0oth3x49/udemy-dl#509]
Hi udemy-dl programmers, and users.

I encountered this Error: 
Download skipped.  "Reason : Could not find a suitable TLS CA certificate bundle, invalid path: /<papth>/lib/python3.6/site-packages/certifi/cacert.pem

I observed that all the HTML files are not able to be downloaded. 
I am using Ubuntu 16.04.

**Comment by r0oth3x49** [comment]
more related to openssl/certs, try upgrading requests[security] requests. i can't reproduce.
