### ISSUE TITLE
Turkish character problem

### ISSUE THREAD

**Issue by SalihKARAHAN** [r0oth3x49/udemy-dl#51]
Hi @r0oth3x49,

I downloaded some Turkish course and I saw video numbers instead of Turkish characters on downloaded videos and texts, I putted some samples to below: 

<img width="331" alt="screen shot 2017-12-19 at 10 14 10" src="https://user-images.githubusercontent.com/5853234/34145097-84572b9e-e4a5-11e7-94d6-bb64e149f4fd.png">
<img width="61" alt="screen shot 2017-12-19 at 10 19 07" src="https://user-images.githubusercontent.com/5853234/34145233-19115f52-e4a6-11e7-9e6d-e0d74cad6411.png">
<img width="285" alt="screen shot 2017-12-19 at 10 18 56 1" src="https://user-images.githubusercontent.com/5853234/34145248-31e1eeca-e4a6-11e7-9cd4-a73479b6aebd.png">

Can you support this issue?

Thanks.

**Comment by r0oth3x49** [comment]
@SalihKARAHAN i can add support for turkish chars as well but i might need a list of chars of turkish which can be convert into english. see issue [#24](https://github.com/r0oth3x49/udemy-dl/issues/24)
