### ISSUE TITLE
Cookies to authenticate with

### ISSUE THREAD

**Issue by IGLOU-EU** [r0oth3x49/udemy-dl#511]
Hi,
for cookies usage, why didn't use Netscape standard format ?
No miss understand and usable with all export cookies addon.

Unfortunately i'm not a Py dev, so i can't make it my self , sorry :(

**Comment by r0oth3x49** [comment]
> 
> 
> Hi,
> for cookies usage, why didn't use Netscape standard format ?
> No miss understand and usable with all export cookies addon.
> 
> Unfortunately i'm not a Py dev, so i can't make it my self , sorry :(

i 'm not familiar with Netscape will check that.
