### ISSUE TITLE
Show course contents but not download

### ISSUE THREAD

**Issue by nakarin** [r0oth3x49/udemy-dl#514]
Hi, Udemy-dl team. I try to download my course but show only contents list now download like this.
How do i to solve this issue.
Thanks you

![Annotation 2020-06-02 051937](https://user-images.githubusercontent.com/5127052/83460514-ca082a00-a490-11ea-805c-00fa1183a4ab.png)

**Comment by r0oth3x49** [comment]
you much be using `--info` switch don't use that if you want to download.
see the [Usage](https://github.com/r0oth3x49/udemy-dl#usage) hope this helps.
