### ISSUE TITLE
ModuleNotFoundError: No module named 'udemy._colorized'

### ISSUE THREAD

**Issue by SnuppeDeluxe** [r0oth3x49/udemy-dl#515]
**Describe the bug**
Traceback (most recent call last):
  File "udemy-dl.py", line 12, in <module>
    from udemy._colorized import *
ModuleNotFoundError: No module named 'udemy._colorized'

**To Reproduce**
1. Downloaded the newest version of the program
2. run "sudo pip3 install --upgrade -r requirements.txt"
3. run "python3 udemy-dl.py https://www.udemy.com/course/github-tutorial-deutsch/learn/lecture/5856174?start=0#overview -u my@mail.com -p my_password"

**Expected behavior**
I expected, that all moduls would be fine and the program will start.

**Python Environment (please complete the following information):**
 - OS: Debian 10 buster (Kernel: x86_64 Linux 4.19.0-9-amd64)
 - Python 3.7.3 (default, Dec 20 2019, 18:57:59) [GCC 8.3.0] on linux

****
I hope, thats all informations you need.
Thank you for your help.

**Comment by r0oth3x49** [comment]
i can't reproduce, are you sure you downloaded it properly? the files should be there
