### ISSUE TITLE
Trying to login gives 403 forbidden error. 

### ISSUE THREAD

**Issue by Sarfarazsajjad** [r0oth3x49/udemy-dl#516]
when trying to download a tutorial with its url

python udemy-dl.py https://...

it asks for username,password then returns error

`[-] : Udemy Says : 403 Forbidden You should use cookie base method to authenticate or try again in few minutes ...`

**Comment by Sarfarazsajjad** [comment]
open udemy website on your browser login -> open developer console -> application tab -> cookies -> find access_token and copy value.

create a file for example accesstoken.txt and save text

access_token=accesstokenvaluehere

now run command 

python udemy-dl.py udemyurl -k accesstoken.txt

**Comment by r0oth3x49** [comment]
> 
> 
> open udemy website on your browser login -> open developer console -> application tab -> cookies -> find access_token and copy value.
> 
> create a file for example accesstoken.txt and save text
> 
> access_token=accesstokenvaluehere
> 
> now run command
> 
> python udemy-dl.py udemyurl -k accesstoken.txt

glad to know that you solve the issue. though in error message it also says use the cookie based method instead.
