### ISSUE TITLE
Udemy Says : 403 Forbidden You should use cookie base method to authenticate or try again in few minutes ...

### ISSUE THREAD

**Issue by rus4u** [r0oth3x49/udemy-dl#517]
Hello,

when I use command: python udemy-dl.py https://www.udemy.com/course/crowdtesting/
to download the course I get this error: Udemy Says : 403 Forbidden You should use cookie base method to authenticate or try again in few minutes ...

Could you please help me to download this course?
![python](https://user-images.githubusercontent.com/66890463/84581599-e2563e00-adda-11ea-8ea0-ffe94f0e0f5f.jpg)

**Comment by r0oth3x49** [comment]
@rus4u this issue is created so many times and the error is clearly saying either use cookie based method or wait, so use the cookie based method you can take a look at readme file.
