### ISSUE TITLE
Using --save option results in getting all links in a single row

### ISSUE THREAD

**Issue by HyperNovaVY** [r0oth3x49/udemy-dl#518]
**Describe the bug**
When using --save option to get specific chapter's links it saves the whole course in the .txt file, no matter if I use --chapter-start/end options.

**To Reproduce**
1. Tried `py -3.8 udemy-dl.py https://www.udemy.com/course... -k token.txt --save --chapter-start 64 --chapter-end 65` both with --save first and at the end.
2. Got `[+] : Chapter(s) (77).
[*] : Lecture(s) (290).
[*] : Writing course content(s) to 'links.txt'`

**Expected behavior**
I expected to get links from chapter 64 to 65

**Python Environment (please complete the following information):**
- OS Platform: Windows 10
- Python Version 3.8.3

**Comment by r0oth3x49** [comment]
@HyperNovaVY `--save` switch only works for whole course links not part of the course.
