### ISSUE TITLE
Can't download

### ISSUE THREAD

**Issue by SuSSan143** [r0oth3x49/udemy-dl#519]
![Screenshot_20200622-124717](https://user-images.githubusercontent.com/62052673/85259516-d6c3e080-b486-11ea-8d1a-079875e5f048.png)
I am not getting what is the problem

**Comment by ambi1997** [comment]
Use Cookie, to login.

**Comment by SuSSan143** [comment]
I found how to login using cookies in Firefox and Chrome. I am using termux
in mobile to download. Pls say how to do it

**Comment by ambi1997** [comment]
Do as you did on pc, make a txt file for cookies in the udemy-dl directory, and type/paste your cookie over there.

**Comment by r0oth3x49** [comment]
> 
> 
> ![Screenshot_20200622-124717](https://user-images.githubusercontent.com/62052673/85259516-d6c3e080-b486-11ea-8d1a-079875e5f048.png)
> I am not getting what is the problem

this repository is not install able from pypi, either use this or report to the author of pypi. there is no csrf token fetching code in this repo.
