### ISSUE TITLE
 [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by hsgeorgian2532** [r0oth3x49/udemy-dl#521]
**Describe the bug**

error appeared only when downloading chapter number 2 and with this particular course only. rest all courses are getting downloaded.

**To Reproduce**

1. udemy course url: https://www.udemy.com/course/build-professional-gui-apps-with-vba-excel-zero-to-mastery/learn/lecture/18385180?start=0#overview

2. Run the following command to reproduce the error.
python udemy-dl.py https://www.udemy.com/course/build-professional-gui-apps-with-vba-excel-zero-to-mastery/learn/lecture/18385180?start=0#overview -c2 -k cookie.txt

3. See error
Reason : [Errno 2] No such file or directory: 'C:\\Users\\Georgian\\Desktop\\udemy-dl\\build-professional-gui-apps-with-vba-excel-zero-to-mastery\\02 Practical excercices \\010 VBA Crud operations  ( Add  Delete  Modify rows )  - Build Your first GUI app.mp4.part'

**Expected behavior**
the chapter should be downloaded like all other chapters

**Screenshots**
screenshot attached

**Python Environment (please complete the following information):**
 - OS Platform:  Windows 10,
 - Python Version 3.8.3

![errno2](https://user-images.githubusercontent.com/67404297/85652995-e717cd80-b6c9-11ea-8152-02be9003c5f5.jpg)

              __                               ____
   __  ______/ /__  ____ ___  __  __      ____/ / /
  / / / / __  / _ \/ __ `__ \/ / / /_____/ __  / /
 / /_/ / /_/ /  __/ / / / / / /_/ /_____/ /_/ / /
 \__,_/\__,_/\___/_/ /_/ /_/\__, /      \__,_/_/
                           /____/
                                 Version : 0.5
                                 Author  : Nasir Khan (r0ot h3x49)
                                 Github  : https://github.com/r0oth3x49

[*] : Trying to login using cookies ...
[+] : Logged in successfully.
[*] : Downloaded course information .. (done)
[*] : Trying to logout now...
[+] : Logged out successfully.
[*] : Course 'build-professional-gui-apps-with-vba-excel-zero-to-mastery'.
[+] : Chapter(s) (3).
[*] : Lecture(s) (21).

[*] : Downloading chapter : (2)
[+] : Chapter (02 Practical excercices )
[*] : Found (9) lectures ...

[*] : Lecture(s) : (1 of 9)
[*] : Downloading (010 VBA Crud operations  ( Add  Delete  Modify rows )  - Build Your first GUI app)
[*] : Lecture : '010 VBA Crud operations  ( Add  Delete  Modify rows )  - Build Your first GUI app' (download skipped).
[-] : Reason : [Errno 2] No such file or directory: 'C:\\Users\\Georgian\\Desktop\\udemy-dl\\build-professional-gui-apps-with-vba-excel-zero-to-mastery\\02 Practical excercices \\010 VBA Crud operations  ( Add  Delete  Modify rows )  - Build Your first GUI app.mp4.part'

**Additional context**
please give possible solutions to this problem.

**Comment by r0oth3x49** [comment]
@hsgeorgian2532 if you specify any other path does that work for you?

example:
`python udemy-dl.py -k cookies.txt COURSE_URL -o "E:/tuts"`

try this it should solve the issue i guess. though the file length doesn't seems much which should break windows naming conventions.

**Comment by hsgeorgian2532** [comment]
I've tried this one before sending you the query. If you wish to try for
yourself then I can send you the cookies.txt file for testing at your end.

Regards
