### ISSUE TITLE
Digits instead of cyrillic symbols in filenames

### ISSUE THREAD

**Issue by Zeddex** [r0oth3x49/udemy-dl#523]
For example the filename is "10 Разные Продвинутые Темы" and I got filename like this "10 105610721079108510991077 10551088108610761074108010851091109010991077 1058107710841099"

**Comment by r0oth3x49** [comment]
> 
> 
> For example the filename is "10 Разные Продвинутые Темы" and I got filename like this "10 105610721079108510991077 10551088108610761074108010851091109010991077 1058107710841099"

you should use `--unsafe` switch to avoid such issues.
