### ISSUE TITLE
Download assets skipped

### ISSUE THREAD

**Issue by pratiksawant026** [r0oth3x49/udemy-dl#526]
please fix my download assets are being skipped while downloading
![Capture](https://user-images.githubusercontent.com/56512158/87534697-021ba300-c6b4-11ea-95ab-13e66c9968ab.PNG)

**Comment by Laiteux** [comment]
I'm experiencing the same issue with all txt assets.

Course: https://www.udemy.com/course/di-ioc-dotnet/

Logs: https://haste.laiteux.dev/zkkspfpr

**Comment by pratiksawant026** [comment]
so how can we get help from udemy or software ? any fixes ?

**Comment by r0oth3x49** [comment]
duplicate of #524
