### ISSUE TITLE
Some weird connection errors happening only with certain courses

### ISSUE THREAD

**Issue by Laiteux** [r0oth3x49/udemy-dl#527]
**Describe the bug**
When trying to download courses (I use cookies), some of them actually throw some errors.
I can't really say what this is due to as I'm using a VPS to download (not a connection issue) and it only happens on certain courses.
Some courses are totally fine, but some will keep throwing errors there and there when trying to download them, even after restarting the download process from the beginning.

**To Reproduce**
1. udemy course url: https://www.udemy.com/course/how-to-write-multi-threaded-csharp-code/
2. Run the following command to reproduce the error: `py udemy-dl.py https://www.udemy.com/course/how-to-write-multi-threaded-csharp-code/ -k cookies.txt`
3. See errors

**Screenshots**
![](https://share.laiteux.dev/mrejxbks)

**Python Environment (please complete the following information):**
 - OS Platform: Windows Server 2016 x64
 - Python Version 3.8.2

**Comment by Laiteux** [comment]
Update:

So I tried restarting this course download once again, and noticed the errors are only happening on the lectures, not the assets or subtitles: https://haste.laiteux.dev/doyzhyln

**Comment by r0oth3x49** [comment]
try upgrading requirements.

**Comment by Laiteux** [comment]
They are up to date.

**Comment by r0oth3x49** [comment]
hmm, i can't reproduce the issue, the error seems more related to some sort of ssl issue, if you are okay sharing your creds i can try reproduce with the same course and fix ASAP

**Comment by Laiteux** [comment]
Hello,

I got this course refunded for some reason but will let you know if this ever happen again.

Closing this, for now.
