### ISSUE TITLE
Can not able to download asset folder 

### ISSUE THREAD

**Issue by pratiksawant026** [r0oth3x49/udemy-dl#528]
i can not able to download asset folder so as you told i tried from Linux Ubuntu Desktop OS but still getting error while downloading see the screen shot that i shot below:
![Screenshot from 2020-07-18 14-41-24](https://user-images.githubusercontent.com/56512158/87849294-fc68cc00-c904-11ea-934d-b394a186ae0b.png)

**Comment by xd003** [comment]
its the same issue i guess - https://github.com/r0oth3x49/udemy-dl/issues/524

you guys are lucky , mine is not not even getting authenticated :-:
