### ISSUE TITLE
i Can not able to authenticate with udemy account

### ISSUE THREAD

**Issue by pratiksawant026** [r0oth3x49/udemy-dl#530]
**Describe the bug**

**To Reproduce**
1. udemy course url: [e.g `https://www.udemy.com/machinelearning/`] '...'
2. Run the following command to reproduce the error.
3. See error

**Expected behavior**

**Screenshots**

**Python Environment (please complete the following information):**
 - OS Platform: [e.g. Windows 10, Ubuntu 16.04, macOS Sierra]
 - Python Version [e.g. 3.x.x]

**Additional context**

**Comment by r0oth3x49** [comment]
use cookie based method and extracting cookies is already listed in readme
