### ISSUE TITLE
Can not able to authenticate with my udemy account 

### ISSUE THREAD

**Issue by pratiksawant026** [r0oth3x49/udemy-dl#531]
![Capture](https://user-images.githubusercontent.com/56512158/87867918-635aa500-c946-11ea-8c86-b55bc0a41dd3.PNG)
**Describe the bug**

**To Reproduce**
1. udemy course url: [e.g `https://www.udemy.com/machinelearning/`] '...'
2. Run the following command to reproduce the error.
3. See error

**Expected behavior**

**Screenshots**

**Python Environment (please complete the following information):**
 - OS Platform: [e.g. Windows 10, Ubuntu 16.04, macOS Sierra]
 - Python Version [e.g. 3.x.x]

**Additional context**

**Comment by r0oth3x49** [comment]
@pratiksawant026 did you even take a look at features, or other issues, please don't spam the repository with issues that already have alternatives.
