### ISSUE TITLE
Russian titles of chapters and lectures

### ISSUE THREAD

**Issue by karankevich-aleksey** [r0oth3x49/udemy-dl#534]
**Describe the bug**
When course has russian title of chapret or lecture, the name a folder or file looks like string of codes of unicode characters as numbers. 

It would be nice to change 127 line in _sanitize.py something like this: 
`_temp   = ''.join([str(ord(i)) if (ord(i) > 128 and not(ord(i) > 1039 or ord(i) < 1104)) else i for i in title])`

i suppose the same problem may be with another languages.

**Python Environment (please complete the following information):**
 - OS Platform: Windows 10
 - Python Version 3.8

**Comment by r0oth3x49** [comment]
@karankevich-aleksey there is switch `--unsafe` if you have had time to look at the readme file.
