### ISSUE TITLE
SUGGESTION: Option to download all courses from an account

### ISSUE THREAD

**Issue by TarcisioCaetano** [r0oth3x49/udemy-dl#535]
Not a bug, just a suggestion.
maybe download it in order or something, or even list options as numbers and gave the user a choice between those numbers.

**Comment by r0oth3x49** [comment]
@TarcisioCaetano i don't have any plan to include such feature, as it would require a lots of requests to server which showing more then 100 course names on cli, I don't think so is good idea, So i 'm closing this issue or feature request.
