### ISSUE TITLE
I can not able to autheticate with udemy even through cookies

### ISSUE THREAD

**Issue by pratiksawant026** [r0oth3x49/udemy-dl#536]
I can not able to autheticate with u
![Capture](https://user-images.githubusercontent.com/56512158/88366857-e006dc80-cda7-11ea-8191-348d422d75d1.PNG)
demy even through cookies please see below screenshot :

**Comment by xd003** [comment]
Firstly this is not cookies authentication error

Secondly , its already reported and the issue is open - https://github.com/r0oth3x49/udemy-dl/issues/529

Please do check existing issues before reporting new issues
I remember you have spammed false issues way too many times

**Comment by pratiksawant026** [comment]
sir how to fix it please help i want to download course from udemy
