### ISSUE TITLE
Skip automatically generated subtiles

### ISSUE THREAD

**Issue by ipkpjersi** [r0oth3x49/udemy-dl#54]
Hello,

I think it would be great if there was a way to skip automatically generated subtitles. This is a super necessary feature IMO and if you could find a way to do that, that would be amazing. I'm hoping that this should be simple enough to do since you already have the code for downloading and skipping subtitles.

Also, while I'm here, what happens if I have the resolution parameter set to 1080p but then a course only offers 720p, would it download the next highest resolution (so 720p)?

Great program, by the way!

**Comment by r0oth3x49** [comment]
@ipkpjersi thank you for the appreciation and using this program. 

it already skips the `automatically generated subtitles`. when you set the resolution param to `1080p` it will try to find that resolution if its not there it will show you a prompt asking that `this quality is not available would you like to download the default one?`. BTW you should set resolution param to `1080` instead `1080p` which is already mention in `README`.
**Example:**
```
python udemy-dl.py -u user@domain.com -p p4ssw0rd https://www.udemy.com/COURSE_NAME -s -r 1080
```  
 the other option is you set `-d` (default option) with `-r` (resolution option) which checks for the requested resolution and if its not there it will automatically download the default one and will not ask you that question again and again.

**Example**
```
python udemy-dl.py -u user@domain.com -p p4ssw0rd https://www.udemy.com/COURSE_NAME -r 1080 -d
```

**Comment by ipkpjersi** [comment]
Hello,

In that case, it's a bug. When I downloaded from this course: https://www.udemy.com/webdevelopercourse/learn/v4/ that has automatically generated subs, it still downloaded the subs.

Thank you for the information about resolution, that is good to know.

**Comment by r0oth3x49** [comment]
@ipkpjersi thanks i'll have a look and try to fix that as well.  BTW is there any thing annoying about auto gen subs jusy asking, coz people wanna to download subs and you want to skip those caption.

**Comment by ipkpjersi** [comment]
Automatically generated subs are often very inaccurate for uncommon programming words/technologies and can be distracting so it would be nice to only have the manually generated subtitles which are known to be correct and skip the automatically generated subtitles.

**Comment by ipkpjersi** [comment]
Sorry for the double post but I am thinking that maybe if you are able to make it skip auto generated subs, perhaps you could make it as a flag/argument that way people who want auto generated subs can have them and people who don't can skip them.

**Comment by r0oth3x49** [comment]
@ipkpjersi i just checked the course with `--skip-subs` options it does not download the captions so this is not the bug. either i am not getting your point what do you want to or you are not getting my point.

have i look i don't see any subs on this video although according to you it has auto gen subs.
![capture](https://user-images.githubusercontent.com/11024397/34270277-6db980c0-e6a9-11e7-93d4-33c8131eb2db.PNG)
there are two flags already available for subs.

- `--sub-only` which will download subtitles only.
- `--skip-sub` which will skip subtitles and download course lectures etc. 

i will close this by tomorrow as invalid .

**Comment by ipkpjersi** [comment]
It's not invalid, I showed you my screenshot that has subtitles. Here is proof of the subtitles in-browser: https://i.imgur.com/TbarG0P.jpg

Here is proof that this program is downloading subtitles: https://i.imgur.com/nS9QUer.png

**Comment by ipkpjersi** [comment]
Sorry for the double post, but I just realized I am not explaining myself well. I want an enhancement to this program that skips ONLY automatically generated subtitles, while still downloading manual subtitles. I am not sure if this is even possible.

**Comment by r0oth3x49** [comment]
@ipkpjersi i got your point & tested on ubuntu  latest available version with a simple command, here is a simple way you can skip subs (either it is auto gen or created by author or course). there is no special way available right. 
```
python3 udemy-dl.py -u USER -p PASS COURSE_URL --skip-sub
```
again i'll say this not the bug this is invalid.

**Comment by ipkpjersi** [comment]
I'm not quite sure you are getting my point. My point is I would like to skip automatically generated subs whilst downloading manually generated subs without having to specific course-by-course to skip all subs or not, but instead have a "--skip-automatic-sub" that checks if the subs are automatically generated and if so skips them for that course, otherwise it downloads them. Is this not possible?

**Comment by r0oth3x49** [comment]
@ipkpjersi i got your point and also checked some courses having auto-gen subs but either of these courses have auto gen subs or custom created subs i cannot find both in a single course. find me a course which has both `auto gen subs` & `author's created subs` so i can test the utility properly otherwise i will consider this option as future update.

**Comment by ipkpjersi** [comment]
Hello,

Yeah it's not possible for a course to have both automatically generated and manually created subs since automatically generated subs are only created if an author has not manually created subs.

Thanks.

**Comment by r0oth3x49** [comment]
@ipkpjersi always welcome and thanks for using this utility. now i assume you are clear about subtitles and also you are satisfied with the available options for skipping/downloading subs as you said `it is not possible for a course to have both auto subs & custom one as well`.

- ***Skip captions***
```
python3 ./udemy-dl.py https://www.udemy.com/webdevelopercourse/learn/v4/overview --skip-sub
```
- ***Download captions only***
```
python3 ./udemy-dl.py https://www.udemy.com/webdevelopercourse/learn/v4/overview --sub-only
```

if you still have any suggestions do suggest i will consider that as future enhancement.

**Comment by ipkpjersi** [comment]
Yeah I would still like the ability to automatically skip only automatically generated subs while still downloading manually created subs (without having to check on a course-by-course basis, but having this program check automatically). I think that would be a good future enhancement.

**Comment by r0oth3x49** [comment]
@ipkpjersi okay i 'm considering this as future enhancement and also will wait for other to suggest the same. now i 'm closing this issue as future enhancement. BTW this is nothing but just another check on subs.
