### ISSUE TITLE
Downloading course aborts due to error "TypeError: 'encoding' is an invalid keyword argument for this function"

### ISSUE THREAD

**Issue by EnoqueEsteves** [r0oth3x49/udemy-dl#541]
**Describe the bug**
When downloading some courses the  `udemy-dl.py` utility abandons the download process leaving the downloaded course incomplete.  

**To Reproduce**
1. udemy course url: [e.g `https://www.udemy.com/machinelearning/`] '...'
2. Run the following command to reproduce the error. 
    ```shell
    udemy-dl.py "https://www.udemy.com/course/terraform-fast-track" -k authcookie.txt --skip-sub -q 1080 -o ../downloads/udemy 
    ```
3. See error
    ```text
    Traceback (most recent call last):
      File "./udemy-dl/udemy-dl.py", line 1453, in <module>
        main()
      File "./udemy-dl/udemy-dl.py", line 1108, in main
        udemy.course_download(skip_captions=options.skip_captions, path=options.output, quality=options.quality, unsafe=options.unsafe)
      File "./udemy-dl/udemy-dl.py", line 490, in course_download
        self.download_lectures_only(lecture_best=lecture_best, lecture_title=lecture_title, inner_index=inner_index, lectures_count=lectures_count, lecture_assets=lecture_assets, filepath=filepath, unsafe=unsafe)
      File "./udemy-dl/udemy-dl.py", line 414, in download_lectures_only
        self.download_assets(lecture_assets=lecture_assets, filepath=filepath, unsafe=unsafe)
      File "./udemy-dl/udemy-dl.py", line 327, in download_assets
        assets.download(filepath=filepath, unsafe=unsafe, quiet=True, callback=self.show_progress)
      File "/mnt/e/utilities/udemy-dl/udemy/_shared.py", line 126, in download
        return self._write_external_links(filepath, unsafe)
      File "/mnt/e/utilities/udemy-dl/udemy/_shared.py", line 92, in _write_external_links
        file_data = [i.strip().lower() for i in open(filename, encoding='utf-8') if i]
    TypeError: 'encoding' is an invalid keyword argument for this function
    ```

**Expected behavior**
Expect the application to download the full coarse or the new deltas (changes compared to previously downloaded) successfully

**Screenshots**
![image](https://user-images.githubusercontent.com/7204353/88921913-3ae87a00-d267-11ea-98c9-2ad186a3a822.png)

**Python Environment (please complete the following information):**
 - OS Platform: Ubuntu 18.04.4 LTS running on Windows 10 WSL 2
 - Python Version Python 2.7.17 and Python 3.6.9

**Additional context**
I believe this might be related to #540

**Comment by r0oth3x49** [comment]
@EnoqueEsteves use `python3` instead, python2 will be removed completely in next version.

**Comment by EnoqueEsteves** [comment]
That did indeed resolve the issue - thank you
