### ISSUE TITLE
Connection error : make sure your internet connection is working.

### ISSUE THREAD

**Issue by tech-vin** [r0oth3x49/udemy-dl#546]
**Describe the bug**
It was working fine till yesterday. But today I am getting this error Connection error : make sure your internet connection is working. Yes, I did went through the previous post but still, the issue is not resolved.

**To Reproduce**
python udemy-dl.py https://www.udemy.com/course/complete-machine-learning-and-data-science-zero-to-mastery/learn/lecture/16451328#overview -k cookies.txt

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/54138655/90335261-45d63500-dff1-11ea-92ff-02b2df4ae7dd.png)

**Python Environment (please complete the following information):**
 - OS Platform: . Windows 10
 - Python Version [e.g. 3.x.x]

**Comment by skkuraki** [comment]
same for me

**Comment by jcs1910** [comment]
Encountered the same issue. Wt is a solution?

**Comment by skkuraki** [comment]
looks like error comes out of auth phrase, something change on udemy may be

**Comment by jcs1910** [comment]
any solution?

**Comment by r0oth3x49** [comment]
if you guys are using cookie based authentication then auth phase shouldn't be a problem. may be session got expired did you manage to update the cookies file? plus showing on error is not that appropriate you should at least show the where the error occur in screenshot, like when you were trying to login or some where between in course download.
