### ISSUE TITLE
Authentification

### ISSUE THREAD

**Issue by virat-pa** [r0oth3x49/udemy-dl#549]
I used to download course directly to gdrive,now its asking username and password, before its used to ask only token, now its asking credential, pls undo this one, because mine is organization account, I cant give username and password...

**Comment by r0oth3x49** [comment]
@virat-pa nothing is changed in authentication you can still authenticate using cookies, so i 'm closing it as invalid.
![Capture](https://user-images.githubusercontent.com/11024397/93003427-094a1a80-f558-11ea-8960-08a072b6cd8a.PNG)
