### ISSUE TITLE
Error with python

### ISSUE THREAD

**Issue by halveen** [r0oth3x49/udemy-dl#550]
parrot]─[~/udemy-dl]
└──╼ $python udemy-dl.py https://www.udemy.com/course/learn-complete-wordpress-for-beginners/learn/
  File "udemy-dl.py", line 62
    logger.info(msg=f"Downloading ({title})", new_line=True)
                                           ^
SyntaxError: invalid syntax

i get this error anytime i try to run the program

**Comment by r0oth3x49** [comment]
@halveen i have removed python2 support now udemy-dl will only work with python3 so use python3 instead
