### ISSUE TITLE
course id not found

### ISSUE THREAD

**Issue by jaan143** [r0oth3x49/udemy-dl#553]
hello
i some courses are giving error in downloading but i checked in browser courses are showing fine there and evan i play lectures also in browser its streaming fine but these courses are not downloading using your script

 Trying to login using cookies ...
 Logged in successfully.
 Downloading course information, course id not found .. (failed)
 It seems either you are not enrolled or you have to visit the course atleast once while you are logged in.
 Trying to logout now...
 Logged out successfully.

**Comment by r0oth3x49** [comment]
@jaan143 you should upgrad to latest version you are using older version.
