### ISSUE TITLE
Error downloading assets and some videos

### ISSUE THREAD

**Issue by lokaimoma** [r0oth3x49/udemy-dl#554]
Most of the videos  and assets give the error 
int() argument must be a string, a bytes-like object or a number, not 'NoneType'

But the previous release(ver 0.5) didn't have those errors.

I just checkout to that version and everything is fine again.

**Comment by r0oth3x49** [comment]
the course which is facing the error should contain udemy-dl.log file can you please attach that file after removing anything which is sensitive though their shouldn't be any. plus i can't reproduce the error for me videos and everything works fine. so provide proper details and do follow issue reporting guideline.
