### ISSUE TITLE
Error downloading videos and assets

### ISSUE THREAD

**Issue by lokaimoma** [r0oth3x49/udemy-dl#555]
Most of the videos were skipped and assets give the error 
int() argument must be a string, a bytes-like object or a number, not 'NoneType'

But the previous release(ver 0.5) didn't have those errors.

I just checkout to that version and everything is fine again.

Below is the log to the problem i had
[udemy-dl.log](https://github.com/r0oth3x49/udemy-dl/files/5241348/udemy-dl.log)

And a sample screen shot
![udemy-dl_bug](https://user-images.githubusercontent.com/46226886/93516299-b61cf280-f8de-11ea-8f57-147462c7a6d0.png)

**Comment by r0oth3x49** [comment]
can you just download the assets? --assets-only? most of the time links also gets expired which causes that error, otherwise i would need account creds or cookies atleast to reproduce and fix with the same course.

**Comment by r0oth3x49** [comment]
okay found the issue, will be resolved with next commit

**Comment by lokaimoma** [comment]
> can you just download the assets? --assets-only? most of the time links also gets expired which causes that error, otherwise i would need account creds or cookies atleast to reproduce and fix with the same course.

**Comment by lokaimoma** [comment]
> okay found the issue, will be resolved with next commit

👌

**Comment by r0oth3x49** [comment]
can you confirm that it now works fine for you?

**Comment by lokaimoma** [comment]
It's now working, all is ok now
