### ISSUE TITLE
Download failure - AttributeError: 'NoneType' object has no attribute 'get_quality' 

### ISSUE THREAD

**Issue by EnoqueEsteves** [r0oth3x49/udemy-dl#556]
**Describe the bug**
When trying to download a course from Udemy it fails. This occurs on previously downloaded courses as well as if you clear the previously downloaded course and try to download it from scratch again.

**To Reproduce**
1. Run the download (see additional context). 
2. Error occurs
    ```text
    Traceback (most recent call last):
      File "./udemy-dl/udemy-dl.py", line 607, in <module>
        main()
      File "./udemy-dl/udemy-dl.py", line 591, in main
        skip_hls_stream=args.skip_hls_stream,
      File "./udemy-dl/udemy-dl.py", line 354, in course_download
        quality,
      File "./udemy-dl/udemy-dl.py", line 81, in download_lecture
        lecture = lecture.get_quality(quality)
    AttributeError: 'NoneType' object has no attribute 'get_quality'
    ```

**Expected behavior**
Download course video and/or assets correctly with out errors

**Screenshots**
Example error out put to screen
![image](https://user-images.githubusercontent.com/7204353/93522056-d7a2cc00-f928-11ea-8a1b-c3571e2fc9ce.png)

**Python Environment (please complete the following information):**
 - OS Platform: Ubuntu 18.04.5 LTS & Ubuntu 20.04 (both running in Windows 10 WSL2)
 - Python Version 3.6.9

**Additional context**

Tried running it in the following combinations
```bash
./udemy-dl/udemy-dl.py "$i" -k ./udemy_authcookie.txt --skip-sub -q 1080 -o ../Manuals/udemy 
./udemy-dl/udemy-dl.py "$i" -k ./udemy_authcookie.txt --skip-sub -q 1080 -o ../Manuals/udemy --skip-assets
./udemy-dl/udemy-dl.py "$i" -k ./udemy_authcookie.txt --skip-sub -q 1080 -o ../Manuals/udemy --skip-assets --skip-hls
```
"$i" can be replaced with the following course url's which I have tried and fail.

-  "https://www.udemy.com/course/70533-azure"
-  "https://www.udemy.com/course/advanced-css-and-sass"
-  "https://www.udemy.com/course/angular-advanced-masterclass"

**Comment by EnoqueEsteves** [comment]
What was the cause?

**Comment by r0oth3x49** [comment]
the lecture type was not video which cause the issue
