### ISSUE TITLE
Does not work in Parrot OS.

### ISSUE THREAD

**Issue by kaptX** [r0oth3x49/udemy-dl#558]
─[✗]─[0000000@00000000]─[~/udemy-dl]
└──╼ $python udemy-dl.py https://www.udemy.com/course/xcxcxcxxc/
  File "udemy-dl.py", line 62
    logger.info(msg=f"Downloading ({title})", new_line=True)
                                           ^
SyntaxError: invalid syntax

**Comment by r0oth3x49** [comment]
@kaptX please do read readme file before creating issues it is clearly mention there that udemy-dl now only supports python3 so you should be running it with python3 instead python2 support is removed.

**Comment by kaptX** [comment]
My apologies. I realized I never ran pip3 install -r requirements.txt. I did this and now it's doing it's magic on macOS Catalina and Parrot. Great work brother.

Best,

~Me.

Confidentiality Notice:

This transmission may contain information that is privileged, confidential, legally privileged, and/or exempt from disclosure under applicable law. If you are not the intended recipient, you are hereby notified that any disclosure, copying, distribution, or use of the information contained herein (including any reliance thereon) is STRICTLY PROHIBITED. Although this transmission and any attachments are believed to be free of any virus or other defect that might affect any computer system into which it is received and opened, it is the responsibility of the recipient to ensure that it is virus free and no responsibility is accepted by the sender, as applicable, for any loss or damage arising in any way from its use. If you received this transmission in error, please immediately contact the sender at psiaccounts@protonmail.com and destroy the material in its entirety, whether in electronic or hard copy format. Thank you.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
