### ISSUE TITLE
Download subtitles

### ISSUE THREAD

**Issue by gbrlb** [r0oth3x49/udemy-dl#559]
**Describe the bug**
Download subtitles by default only download the first language listed in subtitles.

**To Reproduce**
1. udemy course url: https://www.udemy.com/course/ros-essentials/
2. python udemy-dl.py --sub-only -s en -k cookie.txt https://www.udemy.com/course/ros-essentials/
3. Download language Italian

**Expected behavior**
Download language English

**Screenshots**
--info
![image](https://user-images.githubusercontent.com/71607280/93719742-e375d480-fb5a-11ea-95b4-8e711daa0302.png)

**Python Environment (please complete the following information):**
 - OS Platform: Windows 10
 - Python Version 3.7.9

**Additional context**

**Comment by r0oth3x49** [comment]
The default language it checks for en if not then downloads all instead to this is intentional behavior, The expected behavior you described is actually in build in this utility the default language for subtitle is set to en, if you want language other than that you can pass it as argument using -s.

**Comment by gbrlb** [comment]
When run the following command:
>python udemy-dl.py --sub-only -s **en -k** cookie.txt https://www.udemy.com/course/ros-essentials/

It download Italian not English.

When run the following command: 
>python udemy-dl.py --sub-only -k cookie.txt https://www.udemy.com/course/ros-essentials/

Also download only Italian, not all the languages.

It seems to only download the first language in the list.

![image](https://user-images.githubusercontent.com/71607280/93782116-8f253000-fc00-11ea-9d3a-4ba4c571cd1e.png)

**Comment by edvjacek** [comment]
First of all, a great tool but I can confirm the problem: I try to download the [https://www.udemy.com/course/the-complete-guide-to-angular-2/](url) course. If I use the --info parameter I see English seven others languages. But downloading I see all languages but the English.

Regards,
Jacek
