### ISSUE TITLE
Not Found (failed)

### ISSUE THREAD

**Issue by kRaLL-Turko** [r0oth3x49/udemy-dl#566]
**Describe the bug**
https://ibb.co/9yBX8Wp

**To Reproduce**
https://www.udemy.com/course/hamitmizrak_javafullstackdeveloper/

**Screenshots**
https://ibb.co/9yBX8Wp

**Python Environment (please complete the following information):**
 - OS Platform: [e.g. Windows 7 x64]
 - Python Version [last version]

**Comment by kRaLL-Turko** [comment]
https://ibb.co/5sGsJp5

**Comment by vikasnewports** [comment]
@kRaLL-Turko  please check that your subscribed course is not **archived**

**Comment by r0oth3x49** [comment]
@kRaLL-Turko it will only download courses in which you are already registered won't work on others.
