### ISSUE TITLE
unable to download course Traceback (most recent call last):on ..File "udemy-dl.py", line 1453, in <module> 

### ISSUE THREAD

**Issue by iamgovindthakur** [r0oth3x49/udemy-dl#574]
i have downloaded almost 70% of the course but now when i was trying today morning i got this error. Any help will be appreciated Once again i have alreday downloaded 70 % of course and i have using latest cookie acces_token and other course is downloading smoothly.
 Error screenshot:

![Screenshot (26)](https://user-images.githubusercontent.com/32303373/95645759-e91e6480-0adf-11eb-86e7-c9a73e5866b9.png)

**Comment by mylinttrap** [comment]
try deleting/moving .udemy-dl.conf

**Comment by xsirvent** [comment]
Hello,

I have the exact same call stack.

It's working for some courses (https://xxxxx.udemy.com/course/ios-13-app-development-bootcamp) and it's not working for some others (https://xxxxx.udemy.com/course/nodejs-the-complete-guide)

Deleting .udemy-dl.conf did nothing.

**Comment by iamgovindthakur** [comment]
> Hello,
> 
> I have the exact same call stack.
> 
> It's working for some courses (https://xxxxx.udemy.com/course/ios-13-app-development-bootcamp) and it's not working for some others (https://xxxxx.udemy.com/course/nodejs-the-complete-guide)
> 
> Deleting .udemy-dl.conf did nothing.

yeah for that course it's not working may be udemy-dl team need to reconfigure their logics in udemy-dl project.

**Comment by iamgovindthakur** [comment]
> try deleting/moving .udemy-dl.conf

cant find  **.udemy-dl.conf** can you please help me in locating  

![Screenshot (27)](https://user-images.githubusercontent.com/32303373/95673361-58ba4f80-0bc5-11eb-984d-8c0ba5be27ca.png)

**Comment by r0oth3x49** [comment]
> 
> 
> try deleting/moving .udemy-dl.conf

bro the issue don't have any relation with .udemy-dl.conf this file is to manage udemy-dl session that's it.
