### ISSUE TITLE
ModuleNotFoundError: No module named 'm3u8' in Ubuntu 16.04

### ISSUE THREAD

**Issue by kutkin54** [r0oth3x49/udemy-dl#575]
I am running udemy-dl under virtual environment in Ubuntu 16.04. All this while, it is working well. Until today session, a new eror occurs. Despite having the required dependencies installed, the module m3u8 is not detected when the udemy-dl.py is executed. Is there any solution to solve it? I have tried manual installed it, but the same error occurs. 
Required m3u8 has been installed: 
![image](https://user-images.githubusercontent.com/25189239/95686057-9ea50100-0c21-11eb-9920-228be9b144b5.png)
Error message: 
![image](https://user-images.githubusercontent.com/25189239/95686142-1ecb6680-0c22-11eb-924c-02a94bbe6cb7.png)

**Comment by r0oth3x49** [comment]
@kutkin54 are you sure you are installing module and running the udemy-dl with same python version?
try `python3 -m pip install -r requirements.txt --upgrade` and then try `python3 udemy-dl.py --help`.
