### ISSUE TITLE
Can't download programs

### ISSUE THREAD

**Issue by MazenElzanaty** [r0oth3x49/udemy-dl#578]
python3 udemy-dl.py https://www.udemy.com/program/az-900-microsoft-azure-fundamentals/learn/2394982/ -q 1080 --cookies cookies

              __                               ____
   __  ______/ /__  ____ ___  __  __      ____/ / /
  / / / / __  / _ \/ __ `__ \/ / / /_____/ __  / /
 / /_/ / /_/ /  __/ / / / / / /_/ /_____/ /_/ / /
 \__,_/\__,_/\___/_/ /_/ /_/\__, /      \__,_/_/
                           /____/
                                 Version : 1.0
                                 Author  : Nasir Khan (r0ot h3x49)
                                 Github  : https://github.com/r0oth3x49

[i] : Trying to login using session cookie
[i] : Logged in successfully.
[-] : Downloading course information, course id not found ..  (failed)
[i] : It seems either you are not enrolled or you have to visit the course atleast once while you are logged in.
[i] : Trying to logout now...
[i] : Logged out successfully.

**Comment by r0oth3x49** [comment]
@MazenElzanaty are you enrolled in that course? did you followed the step udemy-dl suggests in error?

*It seems either you are not enrolled or **you have to visit the course atleast once while you are logged in**.*

you can't download courses without enrollment.

**Comment by MazenElzanaty** [comment]
It's a program, not a course. i can access it from udemy normally.

**Comment by r0oth3x49** [comment]
hmm no support for program download as of yet i need to check whats there.

**Comment by MazenElzanaty** [comment]
Okay, let me know if there's any updates

**Comment by r0oth3x49** [comment]
would you mind sharing cookies so that i can take a look how program behaves and how it can be downloaded.
it's ok if you don't share. plus i don't see any documentation on API as well that's why requesting cookies so that i can take a look and see if it can be implemented or not.

**Comment by MazenElzanaty** [comment]
The programs section appear when you're pro. https://www.udemy.com/pro/
I'm sorry i can't share this cookies.

**Comment by r0oth3x49** [comment]
> 
> 
> The programs section appear when you're pro. https://www.udemy.com/pro/
> I'm sorry i can't share this cookies.

:+1:  np.
