### ISSUE TITLE
ASCII Problem

### ISSUE THREAD

**Issue by wecarrasco** [r0oth3x49/udemy-dl#58]
I was downloading this course: https://www.udemy.com/the-complete-react-native-and-redux-course/ and for some reason it gives a error when trying to download lecture 33 from the 7th Section.

Here is the error:

`Traceback (most recent call last):
  File "udemy-dl.py", line 924, in <module>
    main()
  File "udemy-dl.py", line 856, in main
    udemy.ExtractAndDownload(path=outto, quality=res)
  File "udemy-dl.py", line 413, in ExtractAndDownload
    _is_converted = vtt2srt.convert(lecture_name)
  File "/home/wecarrasco/Descargas/UdemyDl/udemy/_utils.py", line 246, in convert
    _textcontainer   = '{}'.format(line)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 44: ordinal not in range(128)
`

**Comment by r0oth3x49** [comment]
@wecarrasco thanks for the report will fix this ASAP.
