### ISSUE TITLE
Whats wrong

### ISSUE THREAD

**Issue by 7oka** [r0oth3x49/udemy-dl#581]
**python udemy-dl.py https://www.udemy.com/course/fluttercourse/
  File "udemy-dl.py", line 62
    logger.info(msg=f"Downloading ({title})", new_line=True)
                                           ^
SyntaxError: invalid syntax**

**Comment by 7oka** [comment]
can you edit you command to python3 in your tutorial ?!

**Comment by DanMarqz** [comment]
> can you edit you command to python3 in your tutorial ?!

Hi, how did you solve it? I'm trying to do it with python3 and it keeps telling me syntax error
