### ISSUE TITLE
Are you thinking to move gitlab?

### ISSUE THREAD

**Issue by SalihKARAHAN** [r0oth3x49/udemy-dl#582]
Hi @r0oth3x49 

Did you hear youtube-dl removed from github. Event any situation can appear for this repository too. Are you thinking to put a gitlab link to here for move the project to gitlab?

**Comment by r0oth3x49** [comment]
@SalihKARAHAN yes i have seen thing going on about that on twitter, i already have moved the project to gitlab thanks for suggestion. i will be maintaining code on both places in case it happens which i think shouldn't. 

I will put the link in readme file as well.
here is link:- https://gitlab.com/r0oth3x49/udemy-dl
