### ISSUE TITLE
Segmentation fault (core dumped) while installing.

### ISSUE THREAD

**Issue by Rajssss** [r0oth3x49/udemy-dl#583]
So today, I have accidentally nuked the udemy-dl dir. So I have cloned it again and ran:
`~/udemy-dl$ pip3 install -r requirements.txt`

`Collecting six (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.
0-py2.py3-none-any.whl
Collecting m3u8 (from -r requirements.txt (line 2))
Collecting colorama (from -r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/44/98/5b86278fbbf250d239ae0ecb724f8572af1c91f4a11edf4d36a206189440/colorama-
0.4.4-py2.py3-none-any.whl
Collecting requests (from -r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/45/1e/0c169c6a5381e241ba7404532c16a21d86ab872c9bed8bdcd4c423954103/requests-
2.24.0-py2.py3-none-any.whl
Collecting unidecode (from -r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/d0/42/d9edfed04228bacea2d824904cae367ee9efd05e6cce7ceaaedd0b0ad964/Unidecode
-1.1.1-py2.py3-none-any.whl
Collecting pyOpenSSL (from -r requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/9e/de/f8342b68fa9e981d348039954657bdf681b2ab93de27443be51865ffa310/pyOpenSSL
-19.1.0-py2.py3-none-any.whl
Collecting cloudscraper (from -r requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/83/e4/f1d3872ce822f52f4133cc04960185f64676ca5ec87f05a5350fc0c0a92f/cloudscra
per-1.2.48-py2.py3-none-any.whl
Collecting iso8601 (from m3u8->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/f5/c7/06b5938e79a09112a256f26a1ae0551b04bc6aafcb71fd7ee2390c2c54c6/iso8601-0
.1.13-py2.py3-none-any.whl
Collecting idna<3,>=2.5 (from requests->-r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/a2/38/928ddce2273eaa564f6f50de919327bf3a00f091b5baba8dfa9460f3a8a8/idna-2.10-py2.py3-none-any.whl
Collecting chardet<4,>=3.0.2 (from requests->-r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 (from requests->-r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/56/aa/4ef5aa67a9a62505db124a5cb5262332d1d4153462eb8fd89c9fa41e5d92/urllib3-1.25.11-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests->-r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/5e/c4/6c4fe722df5343c33226f0b4e0bb042e4dc13483228b4718baf286f86d87/certifi-2020.6.20-py2.py3-none-any.whl
Collecting cryptography>=2.8 (from pyOpenSSL->-r requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/08/31/c43f1e45b4a5ebac13ff038a3f167ba3c7432f6dc8683ea504f5af9265eb/cryptography-3.2.1-cp35-abi3-manylinux1_x86_64.whl
Collecting pyparsing>=2.4.7 (from cloudscraper->-r requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/8a/bb/488841f56197b13700afd5658fc279a2025a39e22449b7cf29864669b15d/pyparsing-2.4.7-py2.py3-none-any.whl
Collecting requests-toolbelt>=0.9.1 (from cloudscraper->-r requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/60/ef/7681134338fc097acef8d9b2f8abe0458e4d87559c689a8c306d0957ece5/requests_toolbelt-0.9.1-py2.py3-none-any.whl
Collecting cffi!=1.11.3,>=1.8 (from cryptography>=2.8->pyOpenSSL->-r requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/50/ca/bbca0fd95b24a1d4f0d2e016f09f35ae68d4fe72bf34cc538d0a0d2d3e10/cffi-1.14.3-cp36-cp36m-manylinux1_x86_64.whl
Collecting pycparser (from cffi!=1.11.3,>=1.8->cryptography>=2.8->pyOpenSSL->-r requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/ae/e7/d9c3a176ca4b02024debf82342dab36efadfc5776f9c8db077e8f6e71821/pycparser-2.20-py2.py3-none-any.whl
Installing collected packages: six, iso8601, m3u8, colorama, idna, chardet, urllib3, certifi, requests, unidecode, pycparser, cffi, cryptography, pyOpenSSL, pyparsing, requests-toolbelt, cloudscraper
Successfully installed certifi-2020.6.20 cffi-1.14.3 chardet-3.0.4 cloudscraper-1.2.48 colorama-0.4.4 cryptography-3.2.1 idna-2.10 iso8601-0.1.13 m3u8-0.7.1 pyOpenSSL-19.1.0 pycparser-2.20 pyparsing-2.4.7 requests-2.24.0 requests-toolbelt-0.9.1 six-1.15.0 unidecode-1.1.1 urllib3-1.25.11
Segmentation fault (core dumped)`

I don't know whats wrong.

**Comment by Rajssss** [comment]
Sorry looks like I don't really need to install it again, it's working fine.

**Comment by adeelmichael** [comment]
Facing this error while want to download a tutorial from udemy


![error](https://user-images.githubusercontent.com/34165428/97676406-6c652180-1ab2-11eb-8d86-d8a2d5762703.JPG)

**Comment by eddiebeltran33** [comment]
I've had a similar issue and I just installed dependencies (after installing ffmpeg) again with pip3 install requirements.txt (i'm using mac os and python3.8)

**Comment by Mizerka** [comment]
> Facing this error while want to download a tutorial from udemy
> 
> ![error](https://user-images.githubusercontent.com/34165428/97676406-6c652180-1ab2-11eb-8d86-d8a2d5762703.JPG)

pip install m3u8
pip install cloudscraper

then try again.

**Comment by r0oth3x49** [comment]
@Mizerka it should work with latest python as well, i have already fixed that html parsing issue.

plus @all you guys should install all the requirements then use the udemy-dl.

**Comment by r0oth3x49** [comment]
> 
> 
> Anyways, I have tried to download a course using a cookie method, and it stuck on Downloading Course information..

can't reproduce this issue is that course too big?

**Comment by r0oth3x49** [comment]
> 
> 
> So today, I have accidentally nuked the udemy-dl dir. So I have cloned it again and ran:
> `~/udemy-dl$ pip3 install -r requirements.txt`
> 
> `Collecting six (from -r requirements.txt (line 1)) Using cached https://files.pythonhosted.org/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15. 0-py2.py3-none-any.whl Collecting m3u8 (from -r requirements.txt (line 2)) Collecting colorama (from -r requirements.txt (line 3)) Using cached https://files.pythonhosted.org/packages/44/98/5b86278fbbf250d239ae0ecb724f8572af1c91f4a11edf4d36a206189440/colorama- 0.4.4-py2.py3-none-any.whl Collecting requests (from -r requirements.txt (line 4)) Using cached https://files.pythonhosted.org/packages/45/1e/0c169c6a5381e241ba7404532c16a21d86ab872c9bed8bdcd4c423954103/requests- 2.24.0-py2.py3-none-any.whl Collecting unidecode (from -r requirements.txt (line 5)) Using cached https://files.pythonhosted.org/packages/d0/42/d9edfed04228bacea2d824904cae367ee9efd05e6cce7ceaaedd0b0ad964/Unidecode -1.1.1-py2.py3-none-any.whl Collecting pyOpenSSL (from -r requirements.txt (line 6)) Using cached https://files.pythonhosted.org/packages/9e/de/f8342b68fa9e981d348039954657bdf681b2ab93de27443be51865ffa310/pyOpenSSL -19.1.0-py2.py3-none-any.whl Collecting cloudscraper (from -r requirements.txt (line 7)) Using cached https://files.pythonhosted.org/packages/83/e4/f1d3872ce822f52f4133cc04960185f64676ca5ec87f05a5350fc0c0a92f/cloudscra per-1.2.48-py2.py3-none-any.whl Collecting iso8601 (from m3u8->-r requirements.txt (line 2)) Using cached https://files.pythonhosted.org/packages/f5/c7/06b5938e79a09112a256f26a1ae0551b04bc6aafcb71fd7ee2390c2c54c6/iso8601-0 .1.13-py2.py3-none-any.whl Collecting idna<3,>=2.5 (from requests->-r requirements.txt (line 4)) Using cached https://files.pythonhosted.org/packages/a2/38/928ddce2273eaa564f6f50de919327bf3a00f091b5baba8dfa9460f3a8a8/idna-2.10-py2.py3-none-any.whl Collecting chardet<4,>=3.0.2 (from requests->-r requirements.txt (line 4)) Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 (from requests->-r requirements.txt (line 4)) Using cached https://files.pythonhosted.org/packages/56/aa/4ef5aa67a9a62505db124a5cb5262332d1d4153462eb8fd89c9fa41e5d92/urllib3-1.25.11-py2.py3-none-any.whl Collecting certifi>=2017.4.17 (from requests->-r requirements.txt (line 4)) Using cached https://files.pythonhosted.org/packages/5e/c4/6c4fe722df5343c33226f0b4e0bb042e4dc13483228b4718baf286f86d87/certifi-2020.6.20-py2.py3-none-any.whl Collecting cryptography>=2.8 (from pyOpenSSL->-r requirements.txt (line 6)) Using cached https://files.pythonhosted.org/packages/08/31/c43f1e45b4a5ebac13ff038a3f167ba3c7432f6dc8683ea504f5af9265eb/cryptography-3.2.1-cp35-abi3-manylinux1_x86_64.whl Collecting pyparsing>=2.4.7 (from cloudscraper->-r requirements.txt (line 7)) Using cached https://files.pythonhosted.org/packages/8a/bb/488841f56197b13700afd5658fc279a2025a39e22449b7cf29864669b15d/pyparsing-2.4.7-py2.py3-none-any.whl Collecting requests-toolbelt>=0.9.1 (from cloudscraper->-r requirements.txt (line 7)) Using cached https://files.pythonhosted.org/packages/60/ef/7681134338fc097acef8d9b2f8abe0458e4d87559c689a8c306d0957ece5/requests_toolbelt-0.9.1-py2.py3-none-any.whl Collecting cffi!=1.11.3,>=1.8 (from cryptography>=2.8->pyOpenSSL->-r requirements.txt (line 6)) Using cached https://files.pythonhosted.org/packages/50/ca/bbca0fd95b24a1d4f0d2e016f09f35ae68d4fe72bf34cc538d0a0d2d3e10/cffi-1.14.3-cp36-cp36m-manylinux1_x86_64.whl Collecting pycparser (from cffi!=1.11.3,>=1.8->cryptography>=2.8->pyOpenSSL->-r requirements.txt (line 6)) Using cached https://files.pythonhosted.org/packages/ae/e7/d9c3a176ca4b02024debf82342dab36efadfc5776f9c8db077e8f6e71821/pycparser-2.20-py2.py3-none-any.whl Installing collected packages: six, iso8601, m3u8, colorama, idna, chardet, urllib3, certifi, requests, unidecode, pycparser, cffi, cryptography, pyOpenSSL, pyparsing, requests-toolbelt, cloudscraper Successfully installed certifi-2020.6.20 cffi-1.14.3 chardet-3.0.4 cloudscraper-1.2.48 colorama-0.4.4 cryptography-3.2.1 idna-2.10 iso8601-0.1.13 m3u8-0.7.1 pyOpenSSL-19.1.0 pycparser-2.20 pyparsing-2.4.7 requests-2.24.0 requests-toolbelt-0.9.1 six-1.15.0 unidecode-1.1.1 urllib3-1.25.11 Segmentation fault (core dumped)`
> 
> I don't know whats wrong.

the issue seems more related to libraries installation then actual udemy-dl error.

**Comment by Mizerka** [comment]
I used release 1.0 rather than gitclone to be fair;

I tried with 3.9 latest and it wasn't working until I downgraded 
and requirements was missing m3u8 and cloudparser whatever those do.
Not sure if relevant but I've also stuck ffmpeg into top dir.

works fine for me, looking at commits since, gitclone should work probably.

**Comment by Rajssss** [comment]
> 
> 
> > Anyways, I have tried to download a course using a cookie method, and it stuck on Downloading Course information..
> 
> can't reproduce this issue is that course too big?

don't think so.

**Comment by r0oth3x49** [comment]
> 
> 
> > > Anyways, I have tried to download a course using a cookie method, and it stuck on Downloading Course information..
> > 
> > 
> > can't reproduce this issue is that course too big?
> 
> don't think so.

so are you still facing the same issue? try using --skip-hls switch

**Comment by Rajssss** [comment]
> 
> 
> > > > Anyways, I have tried to download a course using a cookie method, and it stuck on Downloading Course information..
> > > 
> > > 
> > > can't reproduce this issue is that course too big?
> > 
> > 
> > don't think so.
> 
> so are you still facing the same issue? try using --skip-hls switch

It's working fine now actually, I have cloned again and then installed it.
