### ISSUE TITLE
Did not download Assignments - Found (0) lecture(s). 

### ISSUE THREAD

**Issue by ds2k5** [r0oth3x49/udemy-dl#586]
**Describe the bug**

Course: 100 Days of Code - The Complete Python Pro Bootcamp for 2021
after Chapter: 80 did not download.

**To Reproduce**
1. ./udemy-dl.py https://www.udemy.com/course/100-days-of-code/learn
2. Run the following command to reproduce the error.
3. See error

[i] : Downloading chapter : (80 of 100)
[i] : Chapter (80 Day 80 - Advanced - Capstone Project  - Predict House Prices)
[i] : Found (2) lecture(s).
                                                                                                                                                       
[i] : Downloading asset(s)
[i] : Downloading (655 Multivariable-Regression-Start.zip)
[+] : Asset : '655 Multivariable-Regression-Start.zip' (already downloaded)
                                                                                                                                                       
[i] : Downloading asset(s)
[i] : Downloading (656 Multivariable-Regression-Complete.zip)
[+] : Asset : '656 Multivariable-Regression-Complete.zip' (already downloaded)
                                                                                                                                                       
[i] : Downloading chapter : (81 of 100)
[i] : Chapter (81 Day 81 - Professional Portfolio Project - [Python Scripting])
[i] : Found (1) lecture(s).
                                                                                                                                                       
[i] : Downloading chapter : (82 of 100)
[i] : Chapter (82 Day 82 - Professional Portfolio Project - [Python Web Development])
[i] : Found (0) lecture(s).
                                                                                                                                                       
[i] : Downloading chapter : (83 of 100)
[i] : Chapter (83 Day 83 - Professional Portfolio Project - [Python Scripting])
[i] : Found (0) lecture(s).
                                                                                                                                                       
[i] : Downloading chapter : (84 of 100)
[i] : Chapter (84 Day 84 - Professional Portfolio Project - [GUI])
[i] : Found (0) lecture(s).
                                                                                                                                                       
[i] : Downloading chapter : (85 of 100)
[i] : Chapter (85 Day 85 - Professional Portfolio Project - [GUI])
[i] : Found (0) lecture(s).
                                                                                                                                                       
[i] : Downloading chapter : (86 of 100)
[i] : Chapter (86 Day 86 - Professional Portfolio Project - [Game])
[i] : Found (0) lecture(s).
                                                                                                                                                       
[i] : Downloading chapter : (87 of 100)
[i] : Chapter (87 Day 87 - Professional Portfolio Project - [Web Development])
[i] : Found (0) lecture(s).
                                                                                                                                                       
[i] : Downloading chapter : (88 of 100)
[i] : Chapter (88 Day 88 - Professional Portfolio Project - [Web Development])
[i] : Found (0) lecture(s).
                                                                                                                                                       
[i] : Downloading chapter : (89 of 100)
[i] : Chapter (89 Day 89 - Professional Portfolio Project - [GUI Desktop App])
[i] : Found (0) lecture(s).
                                                                                                                                                       
[i] : Downloading chapter : (90 of 100)
[i] : Chapter (90 Day 90 - Professional Portfolio Project - [HTTP Requests & APIs])
[i] : Found (0) lecture(s).
                                                                                                                                                       
[i] : Downloading chapter : (91 of 100)
[i] : Chapter (91 Day 91 - Professional Portfolio Project - [Image Processing & Data Science])
[i] : Found (0) lecture(s).
                                                                                                                                                       
[i] : Downloading chapter : (92 of 100)
[i] : Chapter (92 Day 92 - Professional Portfolio Project - [Web Scraping])
[i] : Found (0) lecture(s).
                                                                                                                                                       
[i] : Downloading chapter : (93 of 100)
[i] : Chapter (93 Day 93 - Professional Portfolio Project - [GUI Automation])
[i] : Found (0) lecture(s).
                                                                                                                                                       
[i] : Downloading chapter : (94 of 100)
[i] : Chapter (94 Day 94 - Professional Portfolio Project - [Game])
[i] : Found (0) lecture(s).
                                                                                                                                                       
[i] : Downloading chapter : (95 of 100)
[i] : Chapter (95 Day 95 - Professional Portfolio Project - [HTTP Requests & APIs])
[i] : Found (0) lecture(s).
                                                                                                                                                       
[i] : Downloading chapter : (96 of 100)
[i] : Chapter (96 Day 96 - Professional Portfolio Project - [Web Development])
[i] : Found (0) lecture(s).
                                                                                                                                                       
[i] : Downloading chapter : (97 of 100)
[i] : Chapter (97 Day 97 - Professional Portfolio Project - [Python Automation])
[i] : Found (0) lecture(s).
                                                                                                                                                       
[i] : Downloading chapter : (98 of 100)
[i] : Chapter (98 Day 98 - Professional Portfolio Project - [Data Science])
[i] : Found (0) lecture(s).
                                                                                                                                                       
[i] : Downloading chapter : (99 of 100)
[i] : Chapter (99 Day 99 - Professional Portfolio Project - [Data Science])
[i] : Found (0) lecture(s).
                                                                                                                                                       
[i] : Downloading chapter : (100 of 100)
[i] : Chapter (100 Day 100 - Professional Portfolio Project - [Data Science])
[i] : Found (0) lecture(s).

this are: Assignments

**Expected behavior**

that all 100 parts are downloaded

**Screenshots**

**Python Environment (please complete the following information):**
 - OS Platform: Manjaro Linux
 - Python Version 3.8.6
 - udemy-dl Version : 1.0

**Comment by r0oth3x49** [comment]
hmm assignments download currently not supported.

**Comment by r0oth3x49** [comment]
i 'm closing this issue as currently i don't have any plan to support downloading assignments. i will reopen once i decided to include this feature as well.
