### ISSUE TITLE
Traceback errors

### ISSUE THREAD

**Issue by TCVinNYC** [r0oth3x49/udemy-dl#587]
I'm using Windows 10, tried both Python 3.8 and 3.9

Ran these commands:
git clone https://github.com/r0oth3x49/udemy-dl.git
cd udemy-dl
pip install -r requirements.txt
python3 udemy-dl.py https://www.udemy.com/course/master-the-concepts-of-digital-circuit-design/ -k cookies.txt

did it in CMD, already bought the course and found the access_token for my account

get these errors:
`Traceback (most recent call last):
  File "udemy-dl.py", line 31, in <module>
    import udemy
  File "C:\Users\Prince\udemy-dl\udemy\__init__.py", line 32, in <module>
    from udemy.udemy import course, fetch_enrolled_courses
  File "C:\Users\Prince\udemy-dl\udemy\udemy.py", line 27, in <module>
    from udemy.internal import InternUdemyCourse as Udemy
  File "C:\Users\Prince\udemy-dl\udemy\internal.py", line 26, in <module>
    from udemy.compat import time, sys
  File "C:\Users\Prince\udemy-dl\udemy\compat.py", line 33, in <module>
    import m3u8
ModuleNotFoundError: No module named 'm3u8'`

and i doubled checked with pip install -r requirements.txt and got:
`Requirement already satisfied: six in c:\users\prince\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from -r requirements.txt (line 1)) (1.15.0)
Requirement already satisfied: m3u8 in c:\users\prince\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from -r requirements.txt (line 2)) (0.7.1)
Requirement already satisfied: colorama in c:\users\prince\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from -r requirements.txt (line 3)) (0.4.4)
Requirement already satisfied: requests in c:\users\prince\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from -r requirements.txt (line 4)) (2.24.0)
Requirement already satisfied: unidecode in c:\users\prince\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from -r requirements.txt (line 5)) (1.1.1)
Requirement already satisfied: pyOpenSSL in c:\users\prince\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from -r requirements.txt (line 6)) (19.1.0)
Requirement already satisfied: cloudscraper in c:\users\prince\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from -r requirements.txt (line 7)) (1.2.48)
Requirement already satisfied: iso8601 in c:\users\prince\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from m3u8->-r requirements.txt (line 2)) (0.1.13)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\prince\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from requests->-r requirements.txt (line 4)) (2020.6.20)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\prince\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from requests->-r requirements.txt (line 4)) (1.25.11)
Requirement already satisfied: chardet<4,>=3.0.2 in c:\users\prince\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from requests->-r requirements.txt (line 4)) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in c:\users\prince\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from requests->-r requirements.txt (line 4)) (2.10)
Requirement already satisfied: cryptography>=2.8 in c:\users\prince\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from pyOpenSSL->-r requirements.txt (line 6)) (3.2.1)
Requirement already satisfied: pyparsing>=2.4.7 in c:\users\prince\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from cloudscraper->-r requirements.txt (line 7)) (2.4.7)
Requirement already satisfied: requests-toolbelt>=0.9.1 in c:\users\prince\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from cloudscraper->-r requirements.txt (line 7)) (0.9.1)
Requirement already satisfied: cffi!=1.11.3,>=1.8 in c:\users\prince\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from cryptography>=2.8->pyOpenSSL->-r requirements.txt (line 6)) (1.14.3)
Requirement already satisfied: pycparser in c:\users\prince\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from cffi!=1.11.3,>=1.8->cryptography>=2.8->pyOpenSSL->-r requirements.txt (line 6)) (2.20)
`

**Comment by r0oth3x49** [comment]
@TCVinNYC it's more related to module and not udemy-dl, try installing that module using pip and then let me know if the error still there.

I tried with python3.8 and python3.9 both can't reproduce the issue.

*Install module using pip*
- `python -m pip install m3u8 --upgrade` or
- `pip install m3u8 --upgrade`

remember module should be installed for the version of python you are using to run udemy-dl.

if you have multiple installation in your system and one of that is added to ENV let say python2 then pip install will install the module for python2 instead if actual python version, So double check when trying to install the modules.

**Comment by TCVinNYC** [comment]
Ohh that makes a lot more sense, thank you haha :)
