### ISSUE TITLE
Version 1.0 - Cloudflare Captcha error - no download

### ISSUE THREAD

**Issue by ds2k5** [r0oth3x49/udemy-dl#590]
Download did not work. Error: cloudscraper.exceptions.CloudflareChallengeError: Detected a Cloudflare version 2 Captcha challenge, This feature is not available in the opensource (free) version.

It is on every course download I tryed, looks like a general issue.

1. udemy course url: https://www.udemy.com/course/network-socket-programming-in-python-3-practical-way/learn
2. Run the following command to reproduce the error.
./udemy-dl.py https://www.udemy.com/course/network-socket-programming-in-python-3-practical-way/learn

3. See error
cloudscraper.exceptions.CloudflareChallengeError: Detected a Cloudflare version 2 Captcha challenge, This feature is not available in the opensource (free) version.

**Python Environment (please complete the following information):**
 - OS Platform: Linux Debian
 - Python Version 3.8.6

**Comment by ds2k5** [comment]
Solution was:

sudo pip3 install -r requirements.txt

had the python packages only in the user context this did not work.

**Comment by r0oth3x49** [comment]
only workaround to this exception is to provide cookies by your self.
