### ISSUE TITLE
Cloudflare/cookie expiration issue, (cloudscraper.exceptions.CloudflareChallengeError: Detected a Cloudflare version 2 Captcha challenge, This feature is not available in the opensource (free) version.)

### ISSUE THREAD

**Issue by scapman2k** [r0oth3x49/udemy-dl#591]
[i] : Trying to login using session cookie
[-] : Udemy Says: 403 Forbidden session cookie seems to be expired...
[i] : Updating session cookie..
cloudscraper.exceptions.CloudflareChallengeError: Detected a Cloudflare version 2 Captcha challenge, This feature is not available in the opensource (free) version.

This gets fixed when I completely log out and log in to generate a new access token and replace it within the cookies.txt. However sometimes during the downloading session, it gives me this error. Is there a workaround?

**Comment by r0oth3x49** [comment]
unfortunately the only workaround is already implemented, so you would need to provide new cookie by yourself if that happens.
