### ISSUE TITLE
error No module named 'm3u8'

### ISSUE THREAD

**Issue by mdashif43** [r0oth3x49/udemy-dl#592]
File "C:\..,\Desktop\ud\udemy-dl-1.0\udemy\compat.py", line 33, in <module>
    import m3u8
ModuleNotFoundError: No module named 'm3u8'

**Comment by eliassoares** [comment]
Did you run `pip install -r requirements.txt`?

**Comment by mdashif43** [comment]
Yes. Requirement already satisfied

**Comment by johnnybaloney** [comment]
Is this package a dependency of some other package listed in `requirements.txt`? Because [what's listed in 1.0](https://github.com/r0oth3x49/udemy-dl/blob/v1.0/requirements.txt) doesn't seem to be pulling it. I had to manually add `m3u8` and `cloudscraper`.

**Comment by gayansanjeewa** [comment]
```shell
python3.9 -m pip install -r requirements.txt --upgrade
```
worked for me as mentioned in https://github.com/r0oth3x49/udemy-dl/issues/575#issuecomment-706756081
