### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by mgiay** [r0oth3x49/udemy-dl#593]
root@ns536903:/opt/temp/udemy/udemy-dl# cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"
root@ns536903:/opt/temp/udemy/udemy-dl# 

**python udemy-dl.py https://www.udemy.com/course/certified-kubernetes-administrator-with-practice-tests/ -k cookies.txt
  File "udemy-dl.py", line 62
    logger.info(msg=f"Downloading ({title})", new_line=True)
                                           ^
SyntaxError: invalid syntax**

Screenshot: https://photos.app.goo.gl/yNWpcdk3KfibW2WS7

**Comment by mohitjain** [comment]
Are you using Python3?

**Comment by r0oth3x49** [comment]
@mgiay you should use python3 instead python2 is not supported anymore.
