### ISSUE TITLE
Cyrillic characters disappear in file names (not videos) and links

### ISSUE THREAD

**Issue by Harosatchi** [r0oth3x49/udemy-dl#594]
Hello. Cyrillic characters disappear in file names (not videos) and links.

Examples:
1) Instead of the file name **«001 Задание.txt»** -> **«001 .txt»**.
2) In the file *external-assets-links.txt* instead of the link **«001 Ссылка на статью про Udemy»** -> **«001 -Udemy»** or instead of **«002 Ссылка»** -> **«002 -»**.

The `--unsafe` command you suggested earlier doesn't work:
**udemy-dl.py: error: unrecognized arguments**

***
**Python Environment:**
 - OS Platform: macOS Big Sur
 - Python Version: 3.9

**Comment by r0oth3x49** [comment]
is there any free course if you can refer to try reproducing and fixing the issue.

**Comment by Harosatchi** [comment]
Ok, here's an example. Free course - `https://www.udemy.com/course/adobe-illustrator-designer/`.

> Chapter 1.

- Attached file to video 1. Instead Of **"001 Illustrator".zip" -> "001 .zip"**.

- Attached link to video 2. Instead of **"002 Adobe.com -website for downloading the program" - > "002 Adobe.com-"**.

***

**_Screenshots:_**

<img width="294" alt="Снимок экрана 2020-12-04 в 11 39 54" src="https://user-images.githubusercontent.com/51264528/101143236-ab454480-3627-11eb-92dd-f256a97b36e9.png">

<img width="294" alt="Снимок экрана 2020-12-04 в 11 40 03" src="https://user-images.githubusercontent.com/51264528/101143239-ac767180-3627-11eb-830d-e81466530d09.png">

<img width="362" alt="Снимок экрана 2020-12-04 в 11 47 40" src="https://user-images.githubusercontent.com/51264528/101143242-ac767180-3627-11eb-9f6e-31f6a5512d06.png">

**Comment by r0oth3x49** [comment]
will check and try to fix ASAP :)

**Comment by Harosatchi** [comment]
did i understand correctly that you fixed the problem? If so, when will the new version be released? or do i need to update somehow?

**Comment by r0oth3x49** [comment]
@Harosatchi yes the issue is fixed, If you have clone the repo using git then simply `git pull` command will get you the latest code otherwise download the latest master zip file and use it.
