### ISSUE TITLE
Unable to download subtitles from every language

### ISSUE THREAD

**Issue by Bigemul** [r0oth3x49/udemy-dl#595]
**Describe the bug**

I get:
udemy-dl.py: error: argument -s/--sub-lang: expected one argument.

While downloading, I used `--sub-lang` but it also works with `-s` without argument.

**To Reproduce**

`python3 udemy-dl.py my_course_url --chapter-start 1 --chapter-end 5 -k cookies.txt --sub-lang`

**Expected behavior**
I would like to download every subtitle.

**Python Environment (please complete the following information):**
I just manually updated everything in the requirements.txt file.
I didn't update python since I already have 3.8.3 and I saw someone with m3u8 issue (solved?) with an updated version of Python.

**Comment by r0oth3x49** [comment]
@Bigemul you can now use `-s all` as switch to download all subtitles.

**Comment by RiseT** [comment]
@r0oth3x49 I guess the docs should get adjusted then, as they don't mention "all":

> Download specific subtite by using language code such as (en, es) if lang switch is not specified then default will be all subtitles
