### ISSUE TITLE
A windows commnd line helper for the udemy-dl project

### ISSUE THREAD

**Issue by Kambaa** [r0oth3x49/udemy-dl#596]
Hello, 
I just wrote a command line helper tool for me to use it via cookies on windows. Just wanted to ask if it is ok for you to be in the project.

![see it in action gif](https://github.com/Kambaa/udemy-dl-helper/blob/main/ezgif.com-video-to-gif.gif?raw=true)

You can check it out here : 
https://github.com/Kambaa/udemy-dl-helper

Have a nice day, 
Kambaa

**Comment by r0oth3x49** [comment]
seems good specially for those users not very much familiar with how to use command line. Good luck with that.
