### ISSUE TITLE
Downloading course information, course id not found

### ISSUE THREAD

**Issue by EinfachnurMomo** [r0oth3x49/udemy-dl#597]
[-] : Downloading course information, course id not found ..  (failed)
[i] : It seems either you are not enrolled or you have to visit the course atleast once while you are logged in.

I got ths course for one year now and worked on it already.

Used Course URL:  https://www.udemy.com/course/learn-html-css-clone-amazon-netflix-spotify/learn/v4/overview

python udemy-dl.py https://www.udemy.com/course/learn-html-css-clone-amazon-netflix-spotify/learn/v4/overview -u EMAIL -p PASSWORD

**Comment by streamington** [comment]
try https://www.udemy.com/learn-html-css-clone-amazon-netflix-spotify/ as url

**Comment by EinfachnurMomo** [comment]
> try https://www.udemy.com/learn-html-css-clone-amazon-netflix-spotify/ as url

Thank you! That worked.
