### ISSUE TITLE
NOT an issue, but a small improvement

### ISSUE THREAD

**Issue by iahim** [r0oth3x49/udemy-dl#598]
Sometimes UDEMY can mark your connection as a bot (if you download too much/too fast).
In the udemy-dl.py   i have done this to put some delays between downloads:

`import time, random`

Then :
`
    def download_lecture(self, lecture, filepath, current, total, quality):

        """This function will simply download the lectures.."""

        rndInt = random.randint(5, 10)

        logger.info(msg="Sleep for {} sec".format(rndInt), new_line=True, before=True)

        time.sleep(rndInt)
`

**Comment by r0oth3x49** [comment]
this seems a good idea though the download the sequential one after another, so it has i guess enough seconds to download the next video but i will check if this think is needed.

**Comment by iahim** [comment]
It has happened to me before that Udemy blocked my download due to "bot detection". To solve it i have used a delay. I used before the youtube-dl. Again - amazing work with this project !
