### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode character

### ISSUE THREAD

**Issue by godomainz** [r0oth3x49/udemy-dl#60]
it seems there are issues with subtitle downloads. some gets downloaded some doesn`t.
Tried to download subs from this 
python udemy-dl.py -u mymail@gmail.com -p mypassword https://www.udemy.com/scrapy-tutorial-web-scraping-with-python/ --sub-only

 Logged in successfully.
[*] : Downloading course information webpages ..
[*] : Found (73) lectures ...
[*] : Extracting (73/73) |========================================| 100.00%
[*] : Downloaded course information webpages successfully..
[*] : Trying to logout now...
[+] : Logged out successfully.
[*] : Counting no of chapters..
[+] : Found ('24') chapter(s).

[*] : Downloading chapter : (1 of 24)
[+] : Chapter (01 Scrapy vs_ Other Python Web Scraping Frameworks)
[+] : Found ('4') lecture(s).

[*] : Downloading subtitle ..
[*] : Downloading (001 Scrapy vs_ Beautiful Soup vs_ Selenium-subtitle-en.vtt)
[*] : Lecture : '001 Scrapy vs_ Beautiful Soup vs_ Selenium-subtitle-en.vtt' (already downloaded).

[*] : Downloading subtitle ..
[*] : Downloading (001 Scrapy vs_ Beautiful Soup vs_ Selenium-subtitle-pt.vtt)
[*] : Lecture : '001 Scrapy vs_ Beautiful Soup vs_ Selenium-subtitle-pt.vtt' (already downloaded).

[*] : Lecture : (002 Course Tips (Must Read))
[*] : Lecture : '002 Course Tips (Must Read)' (already downloaded).

[*] : Downloading chapter : (2 of 24)
[+] : Chapter (02 Scrapy Installation)
[+] : Found ('13') lecture(s).

[*] : Downloading subtitle ..
[*] : Downloading (003 Linux Scrapy Installation-subtitle-en.vtt)
[*] : Lecture : '003 Linux Scrapy Installation-subtitle-en.vtt' (already downloaded).

[*] : Downloading subtitle ..
[*] : Downloading (003 Linux Scrapy Installation-subtitle-pt.vtt)
[*] : Lecture : '003 Linux Scrapy Installation-subtitle-pt.vtt' (already downloaded).

[*] : Downloading subtitle ..
[*] : Downloading (004 Mac Scrapy Installation-subtitle-en.vtt)
[*] : Lecture : '004 Mac Scrapy Installation-subtitle-en.vtt' (already downloaded).

[*] : Downloading subtitle ..
[*] : Downloading (004 Mac Scrapy Installation-subtitle-pt.vtt)
[*] : Lecture : '004 Mac Scrapy Installation-subtitle-pt.vtt' (already downloaded).

[*] : Downloading subtitle ..
[*] : Downloading (005 Windows Scrapy Installation-subtitle-en.vtt)
[*] : Lecture : '005 Windows Scrapy Installation-subtitle-en.vtt' (already downloaded).
Traceback (most recent call last):
  File "udemy-dl.py", line 924, in <module>
    main()
  File "udemy-dl.py", line 831, in main
    udemy.ExtractAndDownload(caption_only=True)
  File "udemy-dl.py", line 382, in ExtractAndDownload
    _is_converted = vtt2srt.convert(lecture_name)
  File "H:\Lynda\scrapy-tutorial-web-scraping-with-python\udemy-dl-master\udemy-dl-master\udemy\_utils.py", line 253, in convert
    sub.write('{}'.format(_srtcontent))
  File "C:\Users\Akila Mendis\AppData\Local\Programs\Python\Python36-32\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u0648' in position 1587: character maps to <undefined>

**Comment by r0oth3x49** [comment]
@godomainz thanks for using this utility. I will check & fix ASAP.
