### ISSUE TITLE
udemy-dl stuck and get error in the middle of downloading

### ISSUE THREAD

**Issue by ademianfight** [r0oth3x49/udemy-dl#601]
**Describe the bug**
udemy-dl stuck and get error in the middle of downloading

**To Reproduce**
1. udemy course url: https://www.udemy.com/course/scrum-master-training/learn/lecture/
2. Run the following command to reproduce the error
3. See error

**Expected behavior**
can't continue to download after some section downloaded, I attached the screenshot bellow

**Screenshots**
![udemy_error](https://user-images.githubusercontent.com/16543823/103667298-51c69180-4fa8-11eb-9e3a-2f033931ed95.JPG)

**Python Environment (please complete the following information):**
 - OS Platform:  Windows 10
 - Python Version 3.8

**Additional context**

**Comment by SpecieX** [comment]
### **I'm having something similar.**

**Describe the bug:**
udemy-dl stop downloading and get errors (shown on screenshot)

**To Reproduce:**
C:\udemy-dl>python udemy-dl.py -k cookie.txt https://www.udemy.com/course/curso-definitivo-para-aprender-a-programar-en-android/

**Screenshot**
![Captura de pantalla 2021-01-11 193244](https://user-images.githubusercontent.com/5661134/104257968-3cd47d00-5444-11eb-9858-7bb93610b604.png)

**Python Environment (please complete the following information):**

- OS Platform: Windows 10 Pro x64 Version 20H2
- Python Version: 3.9.1

**Comment by r0oth3x49** [comment]
> 
> ### **EDIT:**
> 
> I have cloned the main branch version and it is working properly. Without any errors so far.
> 
> > **I'm having something similar.**
> > **Describe the bug:**
> > udemy-dl stop downloading and get errors (shown on screenshot)
> > **To Reproduce:**
> > C:\udemy-dl>python udemy-dl.py -k cookie.txt https://www.udemy.com/course/curso-definitivo-para-aprender-a-programar-en-android/
> > **Screenshot**
> > ![Captura de pantalla 2021-01-11 193244](https://user-images.githubusercontent.com/5661134/104257968-3cd47d00-5444-11eb-9858-7bb93610b604.png)
> > **Python Environment (please complete the following information):**
> > 
> > * OS Platform: Windows 10 Pro x64 Version 20H2
> > * Python Version: 3.9.1

you should pull the latest master this error is already fixed you are using the old code.

**Comment by r0oth3x49** [comment]
> 
> 
> **Describe the bug**
> udemy-dl stuck and get error in the middle of downloading
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
>     1. udemy course url: https://www.udemy.com/course/scrum-master-training/learn/lecture/
> 
>     2. Run the following command to reproduce the error
> 
>     3. See error
> 
> 
> **Expected behavior**
> can't continue to download after some section downloaded, I attached the screenshot bellow
> 
> **Screenshots**
> ![udemy_error](https://user-images.githubusercontent.com/16543823/103667298-51c69180-4fa8-11eb-9e3a-2f033931ed95.JPG)
> 
> **Python Environment (please complete the following information):**
> 
>     * OS Platform:  Windows 10
> 
>     * Python Version 3.8
> 
> 
> **Additional context**

try with `--skip-hls` switch, should work
