### ISSUE TITLE
Udemy pro courses supported?

### ISSUE THREAD

**Issue by DoesN0tCompute** [r0oth3x49/udemy-dl#603]
Both of these fail with same error:

[i] : Trying to login using session cookie
[i] : Logged in successfully.
[-] : Downloading course information, course id not found ..  (failed)
[i] : It seems either you are not enrolled or you have to visit the course atleast once while you are logged in.
[i] : Trying to logout now...
[i] : Logged out successfully.

python3 udemy-dl.py https://www.udemy.com/program-taking/UHJvZ3JhbToxMjk0/learn/1348924/lecture/10103522 -k cookie.txt

python3 udemy-dl.py  https://www.udemy.com/course/cissp-domain-1-2 -k cookie.txt

Only thing I can think of is that the course is part of Udemy Pro, is that supported?  It is part of "My Learnings"

**Comment by r0oth3x49** [comment]
yes it does support udemy pro. but you have to provide a full url of course instead of learning path.

**Comment by retardedloozer** [comment]
> yes it does support udemy pro. but you have to provide a full url of course instead of learning path.

Can you provide an example of a full url of a course instead of the learning path?
