### ISSUE TITLE
download udemy with error: cloudscraper.exceptions.CloudflareChallengeError: Detected a Cloudflare version 2 Captcha challenge, This feature is not available in the opensource (free) version.

### ISSUE THREAD

**Issue by yi-liu9** [r0oth3x49/udemy-dl#604]
**Describe the bug**

**To Reproduce**
1. udemy course url: [e.g `https://www.udemy.com/machinelearning/`] '...'
2. Run the following command to reproduce the error.
3. See error

**Expected behavior**

**Screenshots**

**Python Environment (please complete the following information):**
 - OS Platform: [e.g. Windows 10, Ubuntu 16.04, macOS Sierra]
 - Python Version [e.g. 3.x.x]

**Additional context**

**Comment by yi-liu9** [comment]
cloudscraper.exceptions.CloudflareChallengeError: Detected a Cloudflare version 2 Captcha challenge, This feature is not available in the opensource (free) version.

**Comment by r0oth3x49** [comment]
the error is related to 3rd party you should use cookie based method instead.

**Comment by wayneferns** [comment]
> the error is related to 3rd party you should use cookie based method instead.

how to do that
