### ISSUE TITLE
Stop downloading

### ISSUE THREAD

**Issue by AnthonyIp** [r0oth3x49/udemy-dl#605]
Tried to download the course with this cmd: 

python udemy-dl.py -u https://www.udemy.com/course/complete-ethical-hacking-bootcamp-zero-to-mastery/ -q 1080 -k cookie.txt --sub-lang en

But the download stuck at chapter 83....

There is no error log...

**Comment by r0oth3x49** [comment]
@AnthonyIp did you tried using `--chapter-start` switch to start download from chapter 83?

**Comment by AnthonyIp** [comment]
My bad it was lecture 83 and I tried to start it from there but it restarts to lecture 1.
![image](https://user-images.githubusercontent.com/19600839/105608018-be5fcf80-5da1-11eb-8744-0ab48ed7ff66.png)

**Comment by r0oth3x49** [comment]
the indexing is different for lectures in udemy-dl. it always starts from one for a chapter.
so the command should be `--chapter-start 11 --lecture-start 1 --skip-hls` or just `--chapter-start 11 --skip-hls`

**Comment by AnthonyIp** [comment]
@r0oth3x49 what does --skip-hls do ?

it skips a big part of the chapter
