### ISSUE TITLE
It does not work any more

### ISSUE THREAD

**Issue by hkillp** [r0oth3x49/udemy-dl#609]
**Describe the bug**

**To Reproduce**
1. udemy course url: [e.g `https://www.udemy.com/machinelearning/`] '...'
2. Run the following command to reproduce the error.
3. See error

**Expected behavior**

**Screenshots**

**Python Environment (please complete the following information):**
 - OS Platform: [e.g. Windows 10, Ubuntu 16.04, macOS Sierra]
 - Python Version [e.g. 3.x.x]

**Additional context**

**Comment by alternistom** [comment]
What error do you get?
It is working fine for me.

**Comment by r0oth3x49** [comment]
> 
> 
> **Describe the bug**
> A clear and concise description of what the bug is.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
>     1. udemy course url: [e.g `https://www.udemy.com/machinelearning/`] '...'
> 
>     2. Run the following command to reproduce the error.
> 
>     3. See error
> 
> 
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> **Python Environment (please complete the following information):**
> 
>     * OS Platform: [e.g. Windows 10, Ubuntu 16.04, macOS Sierra]
> 
>     * Python Version [e.g. 3.x.x]
> 
> 
> **Additional context**
> Add any other context about the problem here.

Issue reporting template is created to describe the issue properly instead of copy pasting the same template.
