### ISSUE TITLE
Downloading course information, course id not found ..  (failed)

### ISSUE THREAD

**Issue by Bross9132** [r0oth3x49/udemy-dl#610]
I have tried both user/pass and cookie authentication but I am still receiving the error "Downloading course information, course id not found ..  (failed)". I have a Udemy Subscription and I can watch courses fine. Please assist and also confirm the proper way to get a course URL.

**Comment by KingLehon** [comment]
Also getting this as well
Error is 
[i] : Trying to login using session cookie
[i] : Logged in successfully.
[-] : Downloading course information, course id not found ..  (failed)
[i] : It seems either you are not enrolled or you have to visit the course atleast once while you are logged in.
[i] : Trying to logout now...
[i] : Logged out successfully.

https://www.udemy.com/course/jazz-piano-the-ultimate-beginners-course/learn/lecture/14972102?start=0#overview
Course being used.
![firefox_CY7kb5g2OH](https://user-images.githubusercontent.com/29807845/107128488-1d3a4400-688c-11eb-8be9-2deaac01000b.png)
You can see I have visited the course and I am enrolled in it.

**Comment by r0oth3x49** [comment]
You guys might be doing something wrong because i can't reproduce the issue in anyway.

try using only this course url `https://www.udemy.com/course/jazz-piano-the-ultimate-beginners-course/`

**Comment by KingLehon** [comment]
> You guys might be doing something wrong because i can't reproduce the issue in anyway.
> 
> try using only this course url `https://www.udemy.com/course/jazz-piano-the-ultimate-beginners-course/`

I will try this later when I’m home again. I’ve emailed you an offer to let you use the account for this course if trouble persists

**Comment by KingLehon** [comment]
> 
> 
> You guys might be doing something wrong because i can't reproduce the issue in anyway.
> 
> try using only this course url `https://www.udemy.com/course/jazz-piano-the-ultimate-beginners-course/`

![image](https://user-images.githubusercontent.com/29807845/107585296-f8b3d400-6bcb-11eb-8934-458910b5a2ec.png)

**Comment by r0oth3x49** [comment]
> 
> 
> > You guys might be doing something wrong because i can't reproduce the issue in anyway.
> > try using only this course url `https://www.udemy.com/course/jazz-piano-the-ultimate-beginners-course/`
> 
> I will try this later when I’m home again. I’ve emailed you an offer to let you use the account for this course if trouble persists

let me check my email and see what's the issue.
