### ISSUE TITLE
Help with some adjustments

### ISSUE THREAD

**Issue by SumitK27** [r0oth3x49/udemy-dl#612]
By default, this script downloads all the content in a folder named after its slug. So can we make it as saving with the course title instead of the slug?

Secondly, is there any way to reset the number for every video to new modules. Like this:

```
1. Some Module Title
    1. Title A
    2. Title B
2. Some Other Module
    1. Title C
    2. Title D
```

**Comment by r0oth3x49** [comment]
I 'm already thinking of implementing that. will consider this for next update :).

**Comment by magheralex** [comment]
Do you know how  can i fix this issue? I am trying to use the cookie auth method.


                           /____/
                                 Version : 0.5
                                 Author  : Nasir Khan (r0ot h3x49)
                                 Github  : https://github.com/r0oth3x49

[*] : Trying to login using cookies ...
[+] : Logged in successfully.
[-] : Udemy Says : 403 Forbidden You should use cookie base method to authenticate or try again in few minutes ...

**Comment by SumitK27** [comment]
> Do you know how can i fix this issue? I am trying to use the cookie auth method.
> 
> ```
>                        /____/
>                              Version : 0.5
>                              Author  : Nasir Khan (r0ot h3x49)
>                              Github  : https://github.com/r0oth3x49
> ```
> 
> [*] : Trying to login using cookies ...
> [+] : Logged in successfully.
> [-] : Udemy Says : 403 Forbidden You should use cookie base method to authenticate or try again in few minutes ...

You must be trying to download course that isn't subscribe by your Udemy ID

**Comment by magheralex** [comment]
@SumitK27 thank you but I am not subscribed to this course. I have tried with different ones. I am logged in and double check the access_token from cookie.txt
![image](https://user-images.githubusercontent.com/30143275/108078398-4fab2480-7076-11eb-99d5-48c97b65cc9f.png)

**Comment by SumitK27** [comment]
> @SumitK27 thank you but I am not subscribed to this course. I have tried with different ones. I am logged in and double check the access_token from cookie.txt
> ![image](https://user-images.githubusercontent.com/30143275/108078398-4fab2480-7076-11eb-99d5-48c97b65cc9f.png)
> 
> Can you give me an example to try? Thank you in advance for your help!

You can't download a course that you haven't subscribed. So don't try them, only try what you have enrolled
