### ISSUE TITLE
403 Forbidden session cookie seems to be expired

### ISSUE THREAD

**Issue by Dionisos94** [r0oth3x49/udemy-dl#613]
**Describe the bug**
I tried many times over few months to download Udemy courses from my company's Udemy.
However, it never worked and always displays to me the message "403 Forbidden session cookie seems to be expired."

I checked many times and my cookie is always ok and valid.
I even log out and log in again to change it and it does the same.

**To Reproduce**
1. udemy course url: https://xxxxxx.udemy.com/course/complete-cfa-level-i/
2. Run the following command to reproduce the error.
python udemy-dl.py https://xxxxxx.udemy.com/course/complete-cfa-level-i/learn/v4/content -k cookie.txt
(sorry I cannot provide my company name in public)
3. See error

**Expected behavior**
I expected the course to download itself.

**Screenshots**
I modified the code to show me the cookie (self.cookies), to be sure it is correctly read from the file.
It even fails the same way if I change the url to remove "learn/v4/content".
![image](https://user-images.githubusercontent.com/15048957/107251848-b2743e80-6a2c-11eb-9394-0c196c46aef2.png)

**Python Environment (please complete the following information):**
 - OS Platform:  Windows 10
 - Python Version : 3.8.7

**Additional context**
I can provide the cookie file if needed and the url but only in private.

**Comment by r0oth3x49** [comment]
@Dionisos94 thanks for reporting the issue, actually i can't reproduce the issue on my end would be great if are okay to share the cookie on my email: `nasir251292@gmail.com`. You can email me course url and the cookie file on this weekend and i will take a look into it and try fix it ASAP.

**Comment by r0oth3x49** [comment]
no response, going to close the issue.
