### ISSUE TITLE
Can't download .py resource

### ISSUE THREAD

**Issue by ReneMario** [r0oth3x49/udemy-dl#614]
Course https://www.udemy.com/course/universidad-python-desde-cero-hasta-experto-django-flask-rest-web/

[ * ] : Downloading asset(s)
[ * ] : Downloading (102 cursor-del-pool.py)
[ * ] : Asset : '102 cursor-del-pool.py' (download skipped).
[ - ] : Reason : int() argument must be a string or a number, not 'NoneType'

**Comment by ReneMario** [comment]
Same error on .txt resources

[ * ] : Downloading asset(s)
[ * ] : Downloading (133 03-UsoLoggingFlask.txt)
[ * ] : Asset : '133 03-UsoLoggingFlask.txt' (download skipped).
[ - ] : Reason : int() argument must be a string or a number, not 'NoneType'

**Comment by r0oth3x49** [comment]
you should use the latest version it's already fixed.
