### ISSUE TITLE
int() argument must be a string, a bytes-like object or a number, not 'NoneType'

### ISSUE THREAD

**Issue by coffeebeantraining** [r0oth3x49/udemy-dl#615]
**Describe the bug**

While downloading course content from udemy i get the following error:

**Downloading asset(s)
Downloading (047 6-SafariDriverMac.txt)
Asset : '047 6-SafariDriverMac.txt'  (download skipped)
Reason : int() argument must be a string, a bytes-like object or a number, not 'NoneType'**

This error: **Reason : int() argument must be a string, a bytes-like object or a number, not 'NoneType'**
seems to be repeating over and over for various files while downloading.

**To Reproduce**
1. udemy course url: [e.g `https://www.udemy.com/machinelearning/`] '...'
https://www.udemy.com/course/selenium-webdriver-with-java-testng-and-log4j
2. Run the following command to reproduce the error.: 
python udemy-dl.py https://www.udemy.com/course/selenium-webdriver-with-java-testng-and-log4j/ -k cookies.txt
3. See error
Image attached.

**Expected behavior**
No error, but instead if the content is not supposed to be downloaded then assure the user it's expected.

**Screenshots**
Attached.

**Python Environment (please complete the following information):**
 - OS Platform: [e.g. Windows 10, Ubuntu 16.04, macOS Sierra]
 Windows 7 Ultimate, x64
 - Python Version [e.g. 3.x.x]
 Python version 3.7.4
![Snap20210214144907](https://user-images.githubusercontent.com/59173960/107891682-125b6100-6ed5-11eb-8aa8-a2699990bf36.png)

**Additional context**

**Comment by r0oth3x49** [comment]
use latest master. it's already fixed
