### ISSUE TITLE
Error after Course information downloaded

### ISSUE THREAD

**Issue by MHC-1** [r0oth3x49/udemy-dl#616]
Got following Error after Course information downloaded.

![pyerror](https://user-images.githubusercontent.com/63932822/107929306-c1517880-6f79-11eb-9b49-e8d96c387147.png)

translating last sentence: "The system cannot find the associated file."

all packages are already upgraded.

**Comment by r0oth3x49** [comment]
you should use `--skip-hls` switch in this case or install ffmpeg, please do read the readme.md for requirements for downloading hls based streams
