### ISSUE TITLE
Udemy quizzes don't get exported

### ISSUE THREAD

**Issue by overthetop** [r0oth3x49/udemy-dl#619]
Great tool! 
In my case it doesn't work because I'm preparing for a certification and I'd like to have the quizzes downloaded as well. :(
It's a great material for learning and further researching on the subjects. Is it possible to have them downloaded as a .html files even without the answers? That will greatly help...

**Comment by r0oth3x49** [comment]
@overthetop for now downloading quizzes is out of scope but i will may be think about it in future releases.
