### ISSUE TITLE
Traceback error

### ISSUE THREAD

**Issue by Drovosek01** [r0oth3x49/udemy-dl#62]
I was on the loading rate. I changed my Wi-Fi network, and then returned to the previous Wi-Fi network. The downloading of the course was interrupted. I restarted the command prompt and re-entered the command the download and got the error. Then I tried to download other courses and received the same error.

`Traceback (most recent call last):
  File "udemy-dl.py", line 7, in <module>
    import udemy
ModuleNotFoundError: No module named 'udemy'`

![image](https://user-images.githubusercontent.com/29478700/34440792-b477c380-ecc8-11e7-81df-f3b256e74a77.png)

**Comment by r0oth3x49** [comment]
@Drovosek01 looks weird how can i reproduce this error. there is no fix for this kind of error but a simple suggestion. Which is : download udemy-dl again, place to some where choice of your directory and then try to download the course again.

**Comment by Drovosek01** [comment]
Sorry, bro, that's my fault. I accidentally deleted the udemy folder that was near the udemy-dl.py file. Thank you for your work, happy new year!

**Comment by r0oth3x49** [comment]
@Drovosek01 thanks for appreciation & Happy new year.
