### ISSUE TITLE
403 forbidden error

### ISSUE THREAD

**Issue by ambi1997** [r0oth3x49/udemy-dl#620]
![Issue1 - Copy](https://user-images.githubusercontent.com/47357080/110110535-fc0a3c00-7dd4-11eb-83cb-bb1c04325a20.jpg)

**Comment by ambi1997** [comment]
Resolved.

**Comment by yybdegithub** [comment]
> Resolved.

Hello!I just met the same problem, what should I do to resolve this?Thank You!

**Comment by ambi1997** [comment]
> > Resolved.
> 
> Hello!I just met the same problem, what should I do to resolve this?Thank You!

Hi,
1. Logout and Login (udemy account). 
2. A new Access Token will be generated. Try using that.

Thanks!

**Comment by yybdegithub** [comment]
> > > Resolved.
> > 
> > 
> > Hello!I just met the same problem, what should I do to resolve this?Thank You!
> 
> Hi,
> 
> 1. Logout and Login (udemy account).
> 2. A new Access Token will be generated. Try using that.
> 
> Thanks!

It seems does not work for me.
But Thank you for helping me anyway!
