### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by starm7md** [r0oth3x49/udemy-dl#623]
i have an issue with cookie.txt , no matter how much i try to fix it i can't , after creating cookie.txt file with the access token and start using this command python udemy-dl.py <url> -k cookie.txt , i get this error **FileNotFoundError: [Errno 2] No such file or directory: 'cookie.txt'**

please Any help is appreciated @r0oth3x49  beside of that one more thing d**o i need to purchase the course in order to download it ??** 

![issue 2](https://user-images.githubusercontent.com/65809932/113480089-e3a04680-9492-11eb-8049-109ff7746533.png)
![issue 3](https://user-images.githubusercontent.com/65809932/113480090-e438dd00-9492-11eb-814a-60ffac6b67fa.png)
![issue](https://user-images.githubusercontent.com/65809932/113480091-e438dd00-9492-11eb-9be9-5b44f82d4af8.png)

Python 3.6

**Comment by ghana7989** [comment]
`python udemy-dl.py <COURSE_URL> -k cookie.txt`
Insert course url without <>.
Coming to the second question YES you need to purchase the course to download.
