### ISSUE TITLE
Stuck at "Downloading course information ..."

### ISSUE THREAD

**Issue by KoichaDev** [r0oth3x49/udemy-dl#629]
It seems there Udemy has been doing some sort of changes where you can't download videos like you should anymore. I get the `Downloading course information .. |` that is stucked. 

Please fix this!

**Comment by r0oth3x49** [comment]
you should use `--skip-hls` switch to avoid fetching hls based streams

**Comment by r0oth3x49** [comment]
hope the above solution solved your problem going to close.
