### ISSUE TITLE
Course not found

### ISSUE THREAD

**Issue by ipkpjersi** [r0oth3x49/udemy-dl#63]
Hello,

Some of my courses (I THINK I used to be able to previously download them) are not downloadable now. I am not sure why. Here is an example of the error: https://i.imgur.com/eBQVH2P.png

I would appreciate if you could give me some tips on how to possibly debug this better. 

I have verified the course still exists and I can still access the contents in my web browser.

Thanks.

**Comment by r0oth3x49** [comment]
@ipkpjersi this is not the error of script but the server, This is actually a handle to error i also face the same problem many times with my courses.

this is an additional check on course request if some how server don't respond with course information then it shows this error one thing i can do is to change the error message for better understanding.

**Comment by skarpetauuuu** [comment]
Is there any way to download not enrolled courses @r0oth3x49 ?

**Comment by ipkpjersi** [comment]
So there's nothing that can be done about the error? I find it very odd that this only happens sometimes, other times the course seems to download fine? I guess it's not a huge deal.

**Comment by r0oth3x49** [comment]
@skarpetauuuu i don't think so you have to enroll first to download the course either it is paid or free.

**Comment by r0oth3x49** [comment]
@ipkpjersi yes currently there's no solution as i said this is not the Bug but the server response which the script show you nicely and you can also see in the above comment that happens with me as well. so currently the simple solution to this error is to use a complete course URL with `/learn/v4/*` and try again if the error occurs.

**Comment by r0oth3x49** [comment]
@ipkpjersi i am closing this issue as this is not an issue with the script but a simple server response.
