### ISSUE TITLE
Error plz help

### ISSUE THREAD

**Issue by m7amad-nem** [r0oth3x49/udemy-dl#633]
$ python udemy-dl.py https://www.udemy.com/course/learn-python-and-ethical-hacking-from-scratch/ -q 1080 -o "~/Python & Ethical Hacking/"  

  File "udemy-dl.py", line 65
    logger.info(msg=f"Downloading ({title})", new_line=True)
                                                                 ^
SyntaxError: invalid syntax

**Comment by r0oth3x49** [comment]
python3 only it's already written in read, do read before creating an issue

**Comment by m7amad-nem** [comment]
srry my bad i didnt pay attention
