### ISSUE TITLE
A lot of videos not downloaded

### ISSUE THREAD

**Issue by xsirvent** [r0oth3x49/udemy-dl#635]
Hi,

I pulled the last version 2 days ago (version 1.1)

I tried to reload a course because some new chapters was added.
Then, I compared the old and the new folder and the new one contained a way less files than the old one.

The course I tried is:
https://sdsglobal.udemy.com/course/swiftui-masterclass-course-ios-development-with-swift

The command I used was:
python udemy-dl.py -u USER -p PASSWORD -s en -q 720 --skip-hls https://sdsglobal.udemy.com/course/swiftui-masterclass-course-ios-development-with-swift

I attached the view of chapter 2 as displayed by udemy web site and the traces given by udemy-dl.

![SwiftUI_Cpater2_Web](https://user-images.githubusercontent.com/44020322/116192760-92504380-a72e-11eb-9db7-9dfe3cdf2d05.png)

![SwiftUI_Cpater2_Udemy](https://user-images.githubusercontent.com/44020322/116192865-c166b500-a72e-11eb-8854-73699fdc1ca3.png)

as you can see, a lot of files are missing and the file numbering on disk is also wrong.

I'll send you the credentials in private messages.

Have a good day.
Xavier

**Comment by xsirvent** [comment]
Sorry, it seems this issue is a duplicate of a recent one. I saw the problem before the recent one was loggued, but not when I created my issue.

**Comment by r0oth3x49** [comment]
that's why i leaved it open once fixed will be closed, closing this issue as dup
