### ISSUE TITLE
ModuleNotFoundError: No module named 'm3u8'

### ISSUE THREAD

**Issue by zaidisyed1991** [r0oth3x49/udemy-dl#636]
I am trying to run udemy-dl but I encounter this error.

![Prob](https://user-images.githubusercontent.com/60362508/116337557-4c37c600-a7a8-11eb-8167-5f4ad5774ee4.jpg)

I want to mention I manually typed in FFmpeg and ran pip install -r requirements.txt to move forward but still the same issue remains.

Please can someone guide me step by step how to fix this as everything else to my knowledge is updated (i.e. acess_token).

___________________________________________________________________________________________________________

Update:

I upgraded to pip3 and Python3 but the error still persists overtime I run python3 udemy-dl.py COURSE_URL

I get this error

<img width="786" alt="Screen Shot 2021-04-28 at 2 10 38 AM" src="https://user-images.githubusercontent.com/60362508/116354809-f292c400-a7c6-11eb-9cf2-64564705c4e5.png">

Not sure how to go about this as the url is accurate.
____________________________________________________________________________________________________________

Update part 2:

I got it to work using
python udemy-dl.py  COURSE_URL -k cookies.txt

But this error persists

[Change 2.pdf](https://github.com/r0oth3x49/udemy-dl/files/6402706/Change.2.pdf)

**Comment by OdinVex** [comment]
> ...

I would recommend closing the Issue then?

**Comment by OdinVex** [comment]
> ...

A simple jpg/png is usually enough. Uploading PDFs of images is just...weird. Either way, your issue belongs in a new Issue. On a side note, you may need to view the course at least once and then try. If it isn't working then, you may need to double-check your URL. An example: `python ./udemy-dl.py https://www.udemy.com/course/COURSE_NAME/learn/lecture/COURSE_ID`

**Comment by zaidisyed1991** [comment]
My bad I have no idea how that PDF happen total mistake on my end for not checking.

I will try it the way you mentioned of going through the entire course and then doing it. 

Note: I also tried doing the same thing reverting back to 3.7 python and same issue of only scrapping the free content.

**Comment by OdinVex** [comment]
> My bad I have no idea how that PDF happen total mistake on my end for not checking.
> 
> I will try it the way you mentioned of going through the entire course and then doing it.
> 
> Note: I also tried doing the same thing reverting back to 3.7 python and same issue of only scrapping the free content.

You can only rip what you own. udemy-dl doesn't rip unpaid-for stuff.

**Comment by zaidisyed1991** [comment]
Yes I understand I own it, I've already paid for it but this issue isn't going away for me.

**Comment by OdinVex** [comment]
> Yes I understand I own it, I've already paid for it but this issue isn't going away for me.

There may be a new DRM involved. Check issue #627. I don't think it is "just downloading free stuff" but rather that the non-free has a new DRM. I'm not sure, just speculating. It's still a different issue from your m3u8, which should never have been created to begin with, you merely needed to install a dependency. You should mark this closed and see issue #627, it may apply.
