### ISSUE TITLE
403 Error

### ISSUE THREAD

**Issue by kaptX** [r0oth3x49/udemy-dl#639]
**Describe the bug**
python3 udemy-dl.py https://www.udemy.com/courseURL -k token.txt

Result:

[i] : Trying to login using session cookie
[i] : Logged in successfully.
[-] : Udemy Says: 403 Forbidden on https://www.udemy.com/courseURL

**Comment by amm834** [comment]
I am facing this issue too.
```
[i] : Trying to login as (user@gmail.com)
[i] : Logged in successfully.
[-] : Udemy Says: 403 Forbidden on https://www.udemy.com/api-2.0/users/me/subscribed-courses?fields[course]=id,url,title,published_title&page=1&page_size=1000&ordering=-last_accessed,-access_time&search=fast-track-red-hat-enterprise-linux-rhcsa-with-vms
```

**Comment by r0oth3x49** [comment]
wait for a good amount of time and then run the script it should work, Don't behave like robots

**Comment by amm834** [comment]
Yes , I wait too many time and try it again.
`403` error is still showing.
This issue should not close until course downloading is working well.
