### ISSUE TITLE
Lectures not download

### ISSUE THREAD

**Issue by sarankumar20** [r0oth3x49/udemy-dl#640]
**Description the bug**
Json data from udemy api return stream_urls object None

**To Reproduce**
1. udemy course url: "https://www.udemy.com/course/javascript-beginners-complete-tutorial/"
2. udemy-dl.py -k cookies.txt -q 720 https://www.udemy.com/course/javascript-beginners-complete-tutorial/
3. Not downloading full course. Some videos are skipped and download only assets.

**Expected behavior**
Expected to download full course with subtitles and assets

**Python Environment:**
 - OS Platform: Windows 10
 - Python Version [3.9.4]

**Comment by sdcluisanaya** [comment]
> **Description the bug**
> Json data from udemy api return stream_urls object None
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. udemy course url: "https://www.udemy.com/course/javascript-beginners-complete-tutorial/"
> 2. udemy-dl.py -k cookies.txt -q 720 https://www.udemy.com/course/javascript-beginners-complete-tutorial/
> 3. Not downloading full course. Some videos are skipped and download only assets.
> 
> **Expected behavior**
> Expected to download full course with subtitles and assets
> 
> **Python Environment:**
> 
> * OS Platform: Windows 10
> * Python Version [3.9.4]

I´ve been facing the same issue from the last week, really frustrating.

**Comment by OdinVex** [comment]
Myself as well, but it is mostly random (but repeatable). The same course can be downloaded but only the same files are downloaded. For some sections it is the first video(s) and no more, sometimes middle videos, sometimes last videos, but always consistent. Wondering if DRM is in play.

**Comment by haldog79** [comment]
I am having the same problem

For the command below, you'll see that it reports there are 3 lectures for the first chapter. However it only returns video information for the first 2. It doesn't recognize any of the resources or videos for lecture 3. I am having this happening on multiple courses.

python udemy-dl.py  https://www.udemy.com/course/friendlyinvitationtocsharp --cookies cookies.txt --keep-vtt --chapter 1 --info

**Comment by chrissierra** [comment]
I am having the same problem

**Comment by vadaliya** [comment]
I am having the same problem

**Comment by mahdisky** [comment]
I am having the same problem

**Comment by Manfrad** [comment]
Hi there

may I add what I have discovered for consideration and further analysis by supporters.

This is what is received in the json for the items missing in the downloads
------------------------------------------------------------------------
'asset': 
...
'asset_type': 'Video', 
'stream_urls': None, 
...
------------------------------------------------------------------------

Whereas 'asset_type': 'stream_urls' should contain the
------------------------------------------------------------------------
'label'  = video resolution
'file' = "address" in udemy content management system
'type' = media type
------------------------------------------------------------------------

I found the following "errors" in the browser
------------------------------------------------------------------------
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
....
Tracking Prevention blocked access to storage for https:......
....
Failed to load resource: the server responded with a status of 403 ()
------------------------------------------------------------------------

It seems individual  items are somewhat blocked by the server side.

Maybe this helps to resolve the issue.

**Comment by OdinVex** [comment]
I noticed that the videos not being played all have an index.mpd being HEAD-ed instead of GET-ed, in browser. Forcing it to GET on my own end makes them play.

**Comment by ndbagal** [comment]
what is the solution to this issue?

**Comment by javierguzman** [comment]
Having the same problem
