### ISSUE TITLE
Some folders empty after downloading course.

### ISSUE THREAD

**Issue by asdfmonster261** [r0oth3x49/udemy-dl#641]
**Describe the bug**

**To Reproduce**
1. url: `https://www.udemy.com/course/thecompletewebdeveloper/`
2. command: `python .\udemy-dl.py -k .\cookies.txt https://www.udemy.com/course/thecompletewebdeveloper/`
3. No errors, udemy-dl.log is empty

**Expected behavior**
Expected behavior is for the entire course to download. 
After downloading however, some chapter folders are empty. 
udemy-dl.log is empty

**Python Environment**
 - OS Platform: Windows 10
 - Python Version: 3.9.5

Forwarding cookie to your email as well, will link this issue in the email.

**Comment by oneskeleton** [comment]
Same issue here,
Chapters are considered as downloaded but folders are empty.
Also some chapters have partial lectures ( lecture 3 and 5 is present and the rest are not there)

**Comment by SreecharanShroff** [comment]
I can reproduce it as well

**Comment by joaobrasil65** [comment]
Same issue. I get a few videos downloaded on a course I have paid for but unexplainably the videos quit downloading.
![Capture](https://user-images.githubusercontent.com/11778985/118202075-1725a780-b427-11eb-8c54-2d799d7e37af.JPG)
