### ISSUE TITLE
Skipping Lectures

### ISSUE THREAD

**Issue by imtariksaeed** [r0oth3x49/udemy-dl#645]
udemy-dl is not downloading all lectures from a chapter. It is only downloading one lecture

![image](https://user-images.githubusercontent.com/78796901/119253055-bfc2cc80-bbc8-11eb-8d84-1b9b635ad548.png)

**Comment by niravsikotaria** [comment]
Yes Same Issue With Me Also

**Comment by joaobrasil65** [comment]
Just wondering how it gets any video with the license issue being
discussed? How can it work correctly at all?
