### ISSUE TITLE
Skipping Lectures

### ISSUE THREAD

**Issue by niravsikotaria** [r0oth3x49/udemy-dl#646]
![Screenshot (370)](https://user-images.githubusercontent.com/5881266/119262288-5195fe00-bbf8-11eb-8909-cb4597082ca7.png)

Hello, admin Please solve this issue as soon as possible.

**Comment by Brown-Boi-Nash** [comment]
It's not that easy. Udemy has added DRM so probably there may not be a fix or it may take a whole lot of time.Be patient is what I can say.
