### ISSUE TITLE
Only the whole first chapter, plus few lectures are downloaded

### ISSUE THREAD

**Issue by ashrav** [r0oth3x49/udemy-dl#649]
**Describe the bug**
When I try to download a course, the first chapter is completely downloaded and only 1 lecture of two or three other chapters is downloaded as well.

**To Reproduce**
1. On ubuntu, run the following command
2. python3 udemy-dl.py https://www.udemy.com/course/java-8-and-beyond-for-testers -k cookies.txt -q 720

**Expected behavior**
All lectures should be downloaded

example of running with --info switch. as you see, many chapters don't provide any info.
**Screenshots**
![image](https://user-images.githubusercontent.com/14939305/119477301-81a7e300-bd57-11eb-8111-d5517b02c5c4.png)

**Python Environment (please complete the following information):**
 - OS Platform: ubuntu
 - Python Version : 3.8.5

**Comment by DailyIncome** [comment]
It's seem Udemy update, we need wait for Udemy-dl Author update too.
Thanks bro
