### ISSUE TITLE
By running the following code "udemy-dl.py https://udemy_course_url", some of the video lectures are being skipped during download. 

### ISSUE THREAD

**Issue by Suman-98** [r0oth3x49/udemy-dl#651]
**Describe the bug**

**To Reproduce**
1. udemy course url: [e.g `https://www.udemy.com/machinelearning/`] '...'
2. Run the following command to reproduce the error.
3. See error

**Expected behavior**

**Screenshots**

**Python Environment (please complete the following information):**
 - OS Platform: [e.g. Windows 10, Ubuntu 16.04, macOS Sierra]
 - Python Version [e.g. 3.x.x]

**Additional context**

**Comment by Puyodead1** [comment]
you barely filled out the template, but probably related to #627
