### ISSUE TITLE
Collect Enrolled Course's URLs

### ISSUE THREAD

**Issue by t4nnyyy** [r0oth3x49/udemy-dl#652]
**Describe the bug**
Currently, we have to log in udemy account to the browser and collect URLs of each course, but if we can able to collect the all enrolled courses' URL from an account automatically then it will be very easy t download the course in a flash.

**To Reproduce**
I created a simple bash script to collect all URLs from the HTML page, so we can use that script to collect all course's URL, however, I don't know python much but if anyone can convert my idea to python and merge it with this code then it will be great

**Additional context**
code of my bash script below: 

```
cat *.html | tr '"' '\n' | tr "'" '\n' | grep -e '^https://www.udemy.com/course' | sort | uniq > links.txt

python3 udemy-dl.py links.txt -k access_token.txt
```

**Comment by r0oth3x49** [comment]
this feature is already in queue so closing this as dup.
