### ISSUE TITLE
Downloading course information, course I'd not found (failed!)

### ISSUE THREAD

**Issue by smmsa1912** [r0oth3x49/udemy-dl#653]
**Describe the bug**

**To Reproduce**
1. udemy course url: [e.g `https://www.udemy.com/machinelearning/`] '...'
2. Run the following command to reproduce the error.
3. See error

**Expected behavior**

**Screenshots**

**Python Environment (please complete the following information):**
 - OS Platform: [e.g. Windows 10, Ubuntu 16.04, macOS Sierra]
 - Python Version [e.g. 3.x.x]

**Additional context**
[issue pic](https://github.com/riazXrazor/udemy-dl-gui/issues/20#issue-906524929)

**Comment by ElwoodHogan** [comment]
im getting this same issue.  After logging in and attempting the URL https://www.udemy.com/course/learn-how-to-create-a-2d-tower-defense-game-in-unity-2020/
using: python udemy-dl.py https://www.udemy.com/course/learn-how-to-create-a-2d-tower-defense-game-in-unity-2020/
Th error appears:
[-] : Downloading course information, course id not found ..  (failed)
[i] : It seems either you are not enrolled or you have to visit the course atleast once while you are logged in.

**Comment by sak1620** [comment]
Please clone latest from the repo. And try again.
Hope you will be able to download.

**Comment by victorfz40** [comment]
I have the same problem

C:\udemy-dl>udemy-dl.py https://www.udemy.com/course/universidad-spring-framework-springboot-java-security-rest-webservices/learn/lecture/18217012?start=105#overview -k cookie.txt

              __                               ____
   __  ______/ /__  ____ ___  __  __      ____/ / /
  / / / / __  / _ \/ __ `__ \/ / / /_____/ __  / /
 / /_/ / /_/ /  __/ / / / / / /_/ /_____/ /_/ / /
 \__,_/\__,_/\___/_/ /_/ /_/\__, /      \__,_/_/
                           /____/
                                 Version : 1.1
                                 Author  : Nasir Khan (r0ot h3x49)
                                 Github  : https://github.com/r0oth3x49

[i] : Trying to login using session cookie
[i] : Updating session cookie..

Access Token : xxxxxxxxxxxxxxxxxxxxxxxxxxxxx


[i] : Logged in successfully.
[i] : Downloading course information .. \
[-] : User Interrupted..
...
...

**Comment by smmsa1912** [comment]
Thank You I will let you know did it downloaded or not 😊

**Comment by victorfz40** [comment]
Hello,
   Delete my post because then it downloaded successfully.
   Thanks and regards

**Comment by smmsa1912** [comment]
Sry I can't Understand which Post?

**Comment by victorfz40** [comment]
Nothing, he had written by mistake, sorry.

**Comment by smmsa1912** [comment]
Okok 👌

**Comment by smmsa1912** [comment]
No it didn't worked it show the same errors I want to download this course

https://www.udemy.com/course/tally-erp-9-step-by-step-guide-to-accounting-with-tally/
Kindly help me 😔
