### ISSUE TITLE
Incomplete Downloads

### ISSUE THREAD

**Issue by majordaniel** [r0oth3x49/udemy-dl#654]
**Describe the bug**
The Script shows the number of files in the Tutorials but it downloads just few of them and mostly leaves out the video files and downloads only other file types

**To Reproduce**
1. I am using this H:\udemy-dl-master> python udemy-dl.py    https://**xxxxxxx**.udemy.com/course/software-architecture-case-studies/learn/lecture/18222008#overview         -k cookie.txt

**Expected behavior**
I Expected to get everything downloaded but it is not so (eg) Found 8 files but downloads only 1

**Screenshots**
![image](https://user-images.githubusercontent.com/30798025/120141910-45500900-c1d5-11eb-8e51-a459207e183e.png)

**Python Environment (please complete the following information):**
 - OS Platform: Windows 10
 - Python Version 385

**Additional context**

**Comment by r0oth3x49** [comment]
did you even checked the issue reporting guidline?
