### ISSUE TITLE
Udemy-dl doesn't find the course videos - only the "public videos" 

### ISSUE THREAD

**Issue by luizconrado** [r0oth3x49/udemy-dl#655]
Hi, 

I have tried to copy to my local machine a Udemy Course I have purchased.
Udemy-dl was able to log in, find the course and download some things, however, the videos of the course were not downloaded (besides a handful of videos that are opened to the public to see them).

Do you know why this is happening?
I do have a Udemy account, I do own the course I was trying to download.

Thank you in advance.

**Comment by mytchmason** [comment]
This is an issue right now with udemy. I don't remember the exact reason, but  I believe someone mentioned DRM issues in an earlier issues thread. Check out the other open issues, but this is happening to everyone.
