### ISSUE TITLE
Videos are not down loading only assets zip files are downloading

### ISSUE THREAD

**Issue by RishikantSri** [r0oth3x49/udemy-dl#656]
Hi there
Videos are not down loading only assets zip files are downloading

Traceback (most recent call last):
  File "udemy-dl.py", line 660, in <module>
    main()
  File "udemy-dl.py", line 630, in main
    udemy_obj.course_download(
  File "udemy-dl.py", line 381, in course_download
    self.download_subtitles(
  File "udemy-dl.py", line 132, in download_subtitles
    self.convert(filename=filename, keep_vtt=keep_vtt)
  File "D:\udemy-dl-master\udemy\vtt2srt.py", line 109, in convert
    self._write_srtcontent(fname, timecode)
  File "D:\udemy-dl-master\udemy\vtt2srt.py", line 51, in _write_srtcontent
    with open(fname, mode="a", encoding="utf-8", errors="ignore") as fd:
PermissionError: [Errno 13] Permission denied: 'D:\\udemy-dl-master\\laravel-fra
mework-build-professional-ecommerce\\02 Laravel 8 A-Z Basic Fandamentals with Co
mplete Dynamic Web Project\\001 Essential Enviroment Setup.en.srt'

some times this error occoured
[i] : Logged in successfully.
[-] : Udemy Says : '524 ' while fetching hls streams..
[-] : Udemy Says : '('Connection aborted.', ConnectionResetError(10054, 'An exis
ting connection was forcibly closed by the remote host', None, 10054, None))' wh
ile fetching hls streams..
[i] : Downloading course information .. |

**Comment by saurabh9813** [comment]
This indeed is an issue. Just wondering whether we are going to get a workaround to this issue or not?
I am also facing the same issue. Videos being skipped while downloading. In few situations, entire course is getting skipped.
Ex: https://wipro.udemy.com/course/progressive-web-app-pwa-the-complete-guide/
Plz lets find a fix to this issue at the earliest, or at least a workaround

**Comment by ashrav** [comment]
it's been reported many times before during this and last week. I expect your issue will get closed as duplicate soon

**Comment by RishikantSri** [comment]
> it's been reported many times before during this and last week. I expect your issue will get closed as duplicate soon

so, what is the solution?
