### ISSUE TITLE
Incomplete Download

### ISSUE THREAD

**Issue by UTK7994** [r0oth3x49/udemy-dl#658]
**Describe the bug**

While downloading any chapter, only few lectures are downloaded and downloading of next chapter starts

**To Reproduce**
1. udemy course url: [e.g `https://www.udemy.com/machinelearning/`] '...'
2. Run the following command to reproduce the error. : >python udemy-dl.py  https://www.udemy.com/course/{course_name} -k cookie.txt
3. See error

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/7688962/120593122-a5a4ac00-c45c-11eb-80f1-d2a525f94497.png)

**Python Environment (please complete the following information):**
 - OS Platform: [e.g. Windows 10, Ubuntu 16.04, macOS Sierra]
 - Python Version [e.g. 3.x.x]

**Additional context**

**Comment by saurabh9813** [comment]
Yes, randomly lectures are getting skipped, without any errors. Now its happening almost in 9 out of 10 courses we are trying to download.

**Comment by ashlynblack** [comment]
Also getting this issue, it sees how many lectures there are in a chapter, but doesn't download them all.

**Comment by reachrishav** [comment]
Yes, even I am facing the same issue since few days. Lectures are being randomly skipped for no obvious reason. @r0oth3x49 Please look into this

**Comment by UTK7994** [comment]
@r0oth3x49 please add the link of duplicate thread to follow.

**Comment by r0oth3x49** [comment]
#627
