### ISSUE TITLE
Download multiple course in once command feature?

### ISSUE THREAD

**Issue by vinhloc1996** [r0oth3x49/udemy-dl#66]
Hi, I'm just using this tool recently. It's a useful tool, but I'm confusing that is there any way to download multiple courses with one command? Something like put all course url to one text file and input the path of the text file instead of the url course.

**Comment by r0oth3x49** [comment]
@vinhloc1996 currently there is no way but may be in future if i get more requests to add this feature.
the other solution is.
you can create a batch file in windows/bash file in unix based systems to automate your stuff.
