### ISSUE TITLE
FileNotFound Error:

### ISSUE THREAD

**Issue by sgaechter** [r0oth3x49/udemy-dl#660]
Error during Downloading Course:

`                                 
Version : 1.1
Author  : Nasir Khan (r0ot h3x49)
Github  : https://github.com/r0oth3x49

[i] : Trying to login using session cookie
[i] : Logged in successfully.
[+] : Downloaded course information ..  (done)
[i] : Trying to logout now...
[i] : Logged out successfully.
[+] : Course 'affinity-designer-deutsch'
[i] : Chapter(s) (6)
[i] : Lecture(s) (35)

[i] : Downloading chapter : (1 of 6)
[i] : Chapter (01 Einleitung)
[i] : Found (2) lecture(s).

[i] : Lecture(s) : (1 of 2)
[i] : Downloading (001 Grundlagen)
[+] : Lecture : '001 Grundlagen' (already downloaded)

[i] : Downloading asset(s)
[i] : Downloading (001 Shortcuts AD.pdf)
[+] : Asset : '001 Shortcuts AD.pdf' (already downloaded)

[i] : Lecture(s) : (2 of 2)
[i] : Downloading (002 Unterschied Vektor & Pixel)
[+] : Lecture : '002 Unterschied Vektor & Pixel' (already downloaded)

[i] : Downloading chapter : (2 of 6)
[i] : Chapter (02 Werkzeuge)
[i] : Found (11) lecture(s).

[i] : Lecture(s) : (1 of 11)
[i] : Downloading (001 Zeichenstift)
[+] : Lecture : '001 Zeichenstift' (already downloaded)

[i] : Lecture(s) : (2 of 11)
[i] : Downloading (002 Grafiktext)
[+] : Lecture : '002 Grafiktext' (already downloaded)

[i] : Lecture(s) : (3 of 11)
[i] : Downloading (003 Ebenen)
[+] : Lecture : '003 Ebenen' (already downloaded)

[i] : Lecture(s) : (4 of 11)
[i] : Downloading (004 Farbauswahl)
[+] : Lecture : '004 Farbauswahl' (already downloaded)

[i] : Lecture(s) : (5 of 11)
[i] : Downloading (005 Bleistift)
[+] : Lecture : '005 Bleistift' (already downloaded)

[i] : Lecture(s) : (6 of 11)
[i] : Downloading (006 Pinsel)
[+] : Lecture : '006 Pinsel' (already downloaded)

[i] : Lecture(s) : (7 of 11)
[i] : Downloading (007 Farbverlauf mit dem Füllungswerkzeug)
[+] : Lecture : '007 Farbverlauf mit dem Füllungswerkzeug' (already downloaded)

[i] : Lecture(s) : (8 of 11)
[i] : Downloading (008 Transparenzwerkzeug)
[+] : Lecture : '008 Transparenzwerkzeug' (already downloaded)

[i] : Lecture(s) : (9 of 11)
[i] : Downloading (009 Übung_ Zeichenstift, Knotenwerkzeug & Füllung)
[+] : Lecture : '009 Übung_ Zeichenstift, Knotenwerkzeug & Füllung' (already downloaded)

[i] : Lecture(s) : (10 of 11)
[i] : Downloading (010 Eckenwerkzeug)
[+] : Lecture : '010 Eckenwerkzeug' (already downloaded)

[i] : Lecture(s) : (11 of 11)
[i] : Downloading (011 Auswahlpinsel)
[+] : Lecture : '011 Auswahlpinsel' (already downloaded)

[i] : Downloading asset(s)
[i] : Downloading (013 Trinkbecher.jpg)
[+] : Asset : '013 Trinkbecher.jpg' (already downloaded)

[i] : Downloading chapter : (3 of 6)
[i] : Chapter (03 Weitere Funktionen)
[i] : Found (4) lecture(s).

[i] : Lecture(s) : (1 of 4)
[i] : Downloading (001 Maskierungsebene)
[+] : Lecture : '001 Maskierungsebene' (already downloaded)

[i] : Lecture(s) : (2 of 4)
[i] : Downloading (002 Effekte & Stile)
[+] : Lecture : '002 Effekte & Stile' (already downloaded)

[i] : Lecture(s) : (3 of 4)
[i] : Downloading (003 Texte biegen & formen)
Traceback (most recent call last):
  File "D:\APP\udemy-dl\udemy-dl.py", line 660, in <module>
    main()
  File "D:\APP\udemy-dl\udemy-dl.py", line 630, in main
    udemy_obj.course_download(
  File "D:\APP\udemy-dl\udemy-dl.py", line 371, in course_download
    self.download_lecture(
  File "D:\APP\udemy-dl\udemy-dl.py", line 94, in download_lecture
    retval = lecture.download(
  File "D:\APP\udemy-dl\udemy\shared.py", line 140, in download
    retVal = FFMPeg(None, self.url, self.token, temp_filepath).download()
  File "D:\APP\udemy-dl\udemy\ffmpeg.py", line 174, in download
    with subprocess.Popen(
  File "C:\python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden
`

Environment: Windows 10, Python 3.9 x64

**Comment by r0oth3x49** [comment]
You should install ffmpeg before downloading any streams or use `--skip-hls`
