### ISSUE TITLE
Output folder setting does not work correctly.

### ISSUE THREAD

**Issue by b68h4** [r0oth3x49/udemy-dl#661]
**Describe the bug**
The download is done by opening a folder with the name of the course.

**To Reproduce**
1. Set output path.
2. Download any course.
3. The course will be downloaded to the folder inside the output folder.

**Expected behavior**
The course should download directly to the output folder without opening a folder with its name.
Is there a setting for this?

**Python Environment (please complete the following information):**
 - OS Platform: Centos 7
 - Python Version: 3.9

**Additional context**
A setting needs to be added for this.

**Comment by r0oth3x49** [comment]
This is intentional behavior not a bug or issue. by output it means you can download the course to any other location not the course content.

by course means the course name included.
