### ISSUE TITLE
Cannot download some lectures' video file

### ISSUE THREAD

**Issue by leonkaihao** [r0oth3x49/udemy-dl#662]
**Describe the bug**
When I tried to download a full course, I found that some video lectures within the course were missing.
Also, the log didn't show any download process info. Like:
```
[i] : Downloading chapter : (2)
[i] : Chapter (02 Kubernetes Overview)
[i] : Found (4) lecture(s).
```
without any download info.
If I tried to download the missing video lecture, it still bypassed the video download.
 
**To Reproduce**
1. udemy course url: [e.g `https://www.udemy.com/course/learn-kubernetes`] 
2. Run the following command to reproduce the error.
```
python udemy-dl.py https://www.udemy.com/course/learn-kubernetes -c 2 -u <user email> -p <user password> -l 3
```
3. See error
```
[i] : Logged in successfully.
[+] : Downloaded course information ..  (done)
[i] : Trying to logout now...
[i] : Logged out successfully.
[+] : Course 'learn-kubernetes'
[i] : Chapter(s) (12)
[i] : Lecture(s) (60)

[i] : Downloading chapter : (2)
[i] : Chapter (02 Kubernetes Overview)
[i] : Found (4) lecture(s).

➜  udemy-dl git:(master) 
```
**Expected behavior**
Show a progress bar to download the video file.

**Python Environment (please complete the following information):**
 - OS Platform: [macOS bigsur]
 - Python Version [3.9.5]

**Additional context**
Seems like some lectures adopt a different video encoding approach(dash?)
![image](https://user-images.githubusercontent.com/5800222/122148063-510e2180-ce9d-11eb-8e11-45c9f20cd381.png)

**Comment by mayanklalwani** [comment]
facing same issue

**Comment by reidemeister94** [comment]
Same issue here

**Comment by Lordwales** [comment]
same here also
