### ISSUE TITLE
Please add support of sub-domain

### ISSUE THREAD

**Issue by undeinf** [r0oth3x49/udemy-dl#663]
**New Feature Request**
Kindly add support for subdomain, for ex:

https://lg.udemy.com
https://samsung.udemy.com

**Current Scenario**
After successful login, getting below error:

[i] : Trying to login using session cookie
[i] : Logged in successfully.
[-] : Udemy Says: Connection error, HTTPSConnectionPool(host='SUB-DOMAIN.udemy.com', port=443): Max retries exceeded with url: /api-2.0/users/me/subscribed-courses?fields%5Bcourse%5D=id,url,title,published_title&page=1&page_size=1000&ordering=-last_accessed,-access_time&search=adobe-photoshop-cc-principal-essential-course-for-beginners (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001A365202430>: Failed to establish a new connection: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions'))

**Comment by r0oth3x49** [comment]
It is already supported,
