### ISSUE TITLE
python-dl.py is not working..."syntax error"

### ISSUE THREAD

**Issue by DevHanza** [r0oth3x49/udemy-dl#665]
what can i do for this?  ☹️

Error Output -:

_File "udemy-dl.py", line 65
    logger.info(msg=f"Downloading ({title})", new_line=True)
                                           ^
SyntaxError: invalid syntax_

Screenshot Of Error -: <a href="https://ibb.co/1nbzgnq"><img src="https://i.ibb.co/qnxJSns/Screenshot-8.png" alt="Screenshot-8" border="0"></a>

**Comment by k3tzor** [comment]
Having the same problem here.

**Comment by r0oth3x49** [comment]
python3 only.

**Comment by jcn50** [comment]
More than 3 people have posted similar "issues" with no other help than "python3"...
If you don't want users to use your script: you might as well unpublish it all together?...
