### ISSUE TITLE
Skipped expected quality not found. 

### ISSUE THREAD

**Issue by aerobo1** [r0oth3x49/udemy-dl#68]
Don't know what to say, I have looked and cloned the package and installed dependencies as to which it still doesn't work after installing aria2. Good grief this is frustrating. Trying to download courrses. Any help? Thanks

**Comment by r0oth3x49** [comment]
@aerobo1 you might want to try take a look at this bro. [Skipped. Expected quality not found! #30](https://github.com/r0oth3x49/udemy-dl/issues/30)

**Comment by aerobo1** [comment]
I have already looked at that before making this post and that solution does not work, I have already downloaded the correct version and installed aria with the same result. I am not able to download anything whatsoever because of this.

**Comment by aerobo1** [comment]
I have already looked at that before making this post and that solution does not work, I have already downloaded the correct version and installed aria with the same result. I am not able to download anything whatsoever because of this.

**Comment by aerobo1** [comment]
@r0oth3x49 I have already looked at that before making this post and that solution does not work, I have already downloaded the correct version and installed aria with the same result. I am not able to download anything whatsoever because of this.

**Comment by r0oth3x49** [comment]
@aerobo1 this utility is not depended on any kind of aria so there is no way to solve your problem and this issue does not belongs to this utility. a simple suggestion is to uninstall udemy or remove udemy entirely  and then clone from this repository again and download.

**Comment by aerobo1** [comment]
@r0oth3x49 Ok, I will give it a shot. Thank you for your time and contribution to the github community.
