### ISSUE TITLE
Can not complete download file

### ISSUE THREAD

**Issue by mabdulkadr** [r0oth3x49/udemy-dl#72]
can not complete downloads file like this and when i try to re-download he sow files as already downloaded 

[*] : Downloading lecture : (10 of 39)
[*] : Downloading (004 What Does ITIL Provide_)
[*] : 34.88MB/3.36MB  9.63% |####------------------------------------| 22.16kB/s  24:16s ETA
[+] : Downloaded  (004 What Does ITIL Provide_)

**Comment by r0oth3x49** [comment]
@mabdulkadr how can i reproduce this error?
