### ISSUE TITLE
Downloading Lectures from halfway

### ISSUE THREAD

**Issue by yashsati29** [r0oth3x49/udemy-dl#74]
@r0oth3x49 Actually i downloaded half of my lectures from other software and now that software is blocked here so could you please tell me can i download my course from where i stopped my downloading..? REPLY ASAP 👍 

P.S. by downloading i meant, can the software download lectures from the course from where i want to download..?

**Comment by r0oth3x49** [comment]
@yashsati29 no currently there is no option to download from the user define point. i will add this in new release ASAP.
