### ISSUE TITLE
General question

### ISSUE THREAD

**Issue by aerobo1** [r0oth3x49/udemy-dl#75]
How can you run this on a windows machine? I can't find any instruction on how to.

**Comment by r0oth3x49** [comment]
@aerobo1 all the commands mention in `README` file is same for each platform. here it is ( [Usage](https://github.com/r0oth3x49/udemy-dl#usage) ) if can't find it in README.

**Comment by Drovosek01** [comment]
@aerobo1, if you can understantd russian text, you can look my tutorial about this application: https://www.youtube.com/watch?v=stiCY8UqZD8

**Comment by aerobo1** [comment]
Spacebo brata
