### ISSUE TITLE
How get list enrolled courses?

### ISSUE THREAD

**Issue by Drovosek01** [r0oth3x49/udemy-dl#77]
Hi.
Is there a way to get the list of courses (which I signed) from my udemy account?

**Comment by r0oth3x49** [comment]
@Drovosek01 currently this utility don't have this feature but may be in future updates i will add. BTW i don't find it useful as this might be a bunch of requests to udemy which is not good.

**Comment by Drovosek01** [comment]
@r0oth3x49, And the udemy app on Android also sends a lot of requests to the site when smartphone open the "My courses"?
By the way, they seem to have a function in the API to get a list of all courses account.
https://www.udemy.com/developers/methods/get-courses-list/

**Comment by r0oth3x49** [comment]
@Drovosek01 yes i already checked this, it is good when you have less than 100 courses in your account if you have more, then the requests will increase. i will wait for more requests on this feature.
