### ISSUE TITLE
download problem on Apple Bash

### ISSUE THREAD

**Issue by Gh02t** [r0oth3x49/udemy-dl#78]
I have some problem with download my courses content, the error code is [CRITICAL-238] Skipped. Expected quality not found!

Can someone have had the same problem?
I already try to download in low quality(via Shell) bun the same problem happen

Tnk
![bashscreen](https://user-images.githubusercontent.com/30687712/35049254-aa372e3e-fb9f-11e7-8030-594070f31216.jpg)

**Comment by r0oth3x49** [comment]
@Gh02t see issue [#68](https://github.com/r0oth3x49/udemy-dl/issues/68)
