### ISSUE TITLE
problem with pip install

### ISSUE THREAD

**Issue by channimol** [r0oth3x49/udemy-dl#8]
when I type:
>pip install -r requirements.txt

I got this message:

>Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

and I have already install all the requirements.
What's wrong with that?

**Comment by r0oth3x49** [comment]
@channimol first make sure that you have clone/downloaded the complete repo, then open terminal in the same directory where **udemy-dl.py** is, check if requirements.txt exists then use pip command to install. 

**Alternative**
You can also install the requirements by using separate  commands for both dependencies.
Example (Linux if running as other than root) make sure python-pip is installed in linux:

   `sudo pip install requests`
   `sudo pip install colorama`
     
Example (windows) make sure pip is in you env, or change to directory under Python2**/3** "Scripts" and use pip:

    `pip install requests`
    `pip install colorama`
