### ISSUE TITLE
New rule aiming at file renaming in certain conditions

### ISSUE THREAD

**Issue by dvisan** [r0oth3x49/udemy-dl#80]
I encountered the following issue while grabbing a course:

```
[*] : Lecture : (013 Practice Activity: User Interface Customizations)
Traceback (most recent call last):
  File "udemy-dl.py", line 924, in <module>
    main()
  File "udemy-dl.py", line 840, in main
    udemy.ExtractAndDownload(path=outto)
  File "udemy-dl.py", line 448, in ExtractAndDownload
    with open(filename, 'wb') as f:
IOError: [Errno 22] invalid mode ('wb') or filename: '013 Practice Activity: User Interface Customizations.html'
```

After searching for _'IOError: [Errno 22] invalid mode ('wb') or filename: '_ I stumbled upon this:
https://stackoverflow.com/questions/22620965/ioerror-errno-22-invalid-mode-wb-or-filename

And learnt that `:` cannot be used for naming files in windows, alongside `<, >, ", /, \, |, ?, *` because these characters are system reserved. If you read the aforementioned error again, you'll see the course the script stopped at has `:` in its name.
I don't have the coding knowledge to cook a fix for this issue, but I believe it can be solved by adding a rule to replace any of the previously mentioned illegal characters with a dash or something else.

Looking forward to an update when you get the chance.

Thanks man!

btw: I was running the script from WSL in windows, in a mounted windows folder. The script works and downloads the whole course when I add no path from outside the WSL environment, but for the machine I am currently using (company owned) I have no acces to the `/user/appdata/local/lxss` folder in which WSL stores the virtual `home` folder.

**Comment by r0oth3x49** [comment]
@dvisan good catch will fix it ASAP thanks for the report.

**Comment by UMUTBAYGUT** [comment]
I think it is same error with me. 
Traceback (most recent call last):
  File "udemy-dl.py", line 924, in <module>
    main()
  File "udemy-dl.py", line 829, in main
    udemy.ExtractAndDownload()
  File "udemy-dl.py", line 409, in ExtractAndDownload
    msg = self.Downloader(_url, lecture_name, chapter_path)
  File "udemy-dl.py", line 89, in Downloader
    out = course_dl.download(url, title, filepath=path, quiet=True, callback=self.Download)
  File "/mnt/c/udemy/udemy-dl/udemy/_downloader.py", line 101, in download
    outfh = open(temp_filepath, fmode)
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/c/udemy/udemy-dl/uctan-uca-sql-server-egitimi/02 SQL Server Kurulum/002 SQL Server E4 Kurulumu 1| Kurulum menuleri.mp4.part'

**Comment by dvisan** [comment]
@UMUTBAYGUT yes it is. You course has a `|` in its name. As I see in the path, you're using WSL in Windows too, in a mounted folder - so it's exactly my issue.

**Comment by Wayne-Mather** [comment]
@UMUTBAYGUT @dvisan Please note that while the special chars fix will solve one problem, some courses do use filenames that violate the NTFS standards. I had issues running under WSL so I have moved to a Linux Platform to do the downloads. 

Then I use mkisofs -udf .... to make a UDF compliant image that can be mounted in Windows to watch videos as needed.
