### ISSUE TITLE
Username, Password and course url is required [Python2 Issue - Workaround Found (use v3)]

### ISSUE THREAD

**Issue by Wayne-Mather** [r0oth3x49/udemy-dl#81]
**Update**

I installed python3 and pip3 for fedora server 27 and the issue no longer exists. There must be something in the python2 runtime that causes the script to throw the error.

I keep getting this error now: Username, Password and course url is required

Command is: python ./udemy-dl/udemy-dl.py -u user@here -p some_password https://www.udemy.com/somewhere

This is Fedora Server 27. Anything I can do to get the script to accept to not fail on correct arguments? Does not matter if I quote or not quote the user and password values.

python ./udemy-dl/udemy-dl.py -h returns:

||BANNER||
                                 Version : 0.3
                                 Author  : Nasir khan(r0ot h3x49)
                                 Visit   : https://github.com/r0oth3x49

Usage: udemy-dl.py [-h] [-u "username"] [-p "password"] COURSE_URL
                   [-s] [-l] [-r "resolution"] [-o "/path/to/directory/"]
                   [-d] [-c/--configs] [--sub-only] [--skip-sub]

A cross-platform python based utility to download courses from udemy for
personal offline use.

Options:
  General:
    -h, --help         Shows the help.
    -v, --version      Shows the version.

  Advance:
    -u, --username     Username in udemy.
    -p, --password     Password of your account.
    -c, --configs      Cache your credentials to use it later.
    -s, --save-links   Do not download but save links to a file.
    -l, --list-infos   List all lectures with available resolution.
    -r, --resolution   Download video resolution, default resolution is 720p.
    -d, --get-default  Download default resolution if requested not there.
    -o, --output       Output directory where the videos will be saved,
                       default is current directory.

  Others:
    --sub-only         Download captions/subtitle only.
    --skip-sub         Download course but skip captions/subtitle.

**Comment by r0oth3x49** [comment]
@Wayne-Mather did you used the most recent `udemy-dl` or the old cloned one, because the error that you are  facing existed due to my mistake because i was not checking properly for arguments. 
have a look a issue [#46](https://github.com/r0oth3x49/udemy-dl/issues/46). did you faced the same? if yes please clone the most recent one & try, if still the error occurs i will check & try to fix it ASAP.

**Comment by Wayne-Mather** [comment]
@r0oth3x49 It was the latest cloned branch. I don't think it was your code because python3 executes correctly, but running against python2 failed..

By default Fedora Server 27 ships with python 2. I then found it has python 3 so I just installed that:

dnf install python3 python3-pip
pip3 install -r requirements.txt
python3 udemy-dl....

And it just worked as expected.

**Comment by r0oth3x49** [comment]
@Wayne-Mather glade to know that this works for you fine with py3.  I will download the `fedora Server 27` & try to reproduce the error with py2 against some free courses.

**Comment by Wayne-Mather** [comment]
@r0oth3x49 I am actually a programmer for a living, just never got around to learning python (or ruby, or Go, or any of the other million languages that exist that I don't use daily - I am a .NET developer that came from a C/C++ background.

Will try to understand more how to actually debug a python application so I can either supply a PR or more information.

**Comment by itsroby** [comment]
@Wayne-Mather @r0oth3x49  Not working for me, I used Ubuntu 16.04 and Python 3.5.1.

![udemy-dl-2](https://user-images.githubusercontent.com/31939641/35374429-68bf5378-01d5-11e8-8534-6568e6a874cb.png)

![udemy-dl](https://user-images.githubusercontent.com/31939641/35374434-70cbe176-01d5-11e8-91a2-44c421226e96.png)

Do you have other solution?
Thanks

**Comment by itsroby** [comment]
Do you mean like this?

![udemy-dl-3](https://user-images.githubusercontent.com/31939641/35376819-4d0f9f70-01df-11e8-91ed-6814677b5170.png)

What should I do?

**Comment by Wayne-Mather** [comment]
Just installing 16.04.3 desktop now to understand. However, I am not a python programmer at this time :)

**Comment by itsroby** [comment]
@Wayne-Mather no problem mate, thank you very much 👍 
But if someday you found the solution, please share.

**Comment by r0oth3x49** [comment]
@itsroby  i have downloaded `Ubuntu 16.04.3 LTS 64-bit` and tested against a free course in my account it worked for me i cannot reproduce the error. have a look below.
![picture](https://user-images.githubusercontent.com/11024397/34041139-b4fe5370-e1b8-11e7-85fe-05818bbd3c29.png)

**Comment by r0oth3x49** [comment]
@Wayne-Mather   i have downloaded `Fedora Server 27 64-bit` and tested against a free course in my account with default py2 & it worked fine. have a look below.
![capture](https://user-images.githubusercontent.com/11024397/35401979-f58fa658-021c-11e8-8851-a283df8677b1.PNG)

**Comment by Wayne-Mather** [comment]
@r0oth3x49 What is the course you use? Over this weekend (I am in Australia, so public holiday today [26 Jan]) I am going to setup several VM's and try to understand what the cause is.

@itsroby Will paste a comment here if I get it working

**Comment by Wayne-Mather** [comment]
@r0oth3x49 Can we modify line 929 and tell the user they have an exception and save the exception details somehow? I think this is what our problem is and that the printed error message makes you think the options are invalid, when it maybe an array boundary issue somewhere.

@itsroby using vanilla install of Ubuntu 16.0.4.3LTS desktop version of ubuntu with only sudo apt-get install git.

Python 2.7 and udemy-dl is just working. I even installed pycharm and debugged the application first to get a better handle on what is happening. The only thing that I can think of at the moment is that it was an IndexError exception being thrown (network issue or the parsing of the course information)

I would need to investigate the code as to what happens to generate the IndexError exception that prints out that text. I must admit, the code that handles command-line arguments does not adhere to DRY (Dont Repeat Yourself) patterns and the enter main() function needs to be refactored so that the code is less complex and easier to understand.

**Comment by r0oth3x49** [comment]
@Wayne-Mather course url is -> `https://www.udemy.com/learn-ruby-on-rails-from-scratch/` & about line 929 i will take a look.

**Comment by itsroby** [comment]
@Wayne-Mather @r0oth3x49 My bad, typo mistake on my email address. 
Thank you for your support :+1:
