### ISSUE TITLE
Download gets stuck in between downlaoding 

### ISSUE THREAD

**Issue by rsa2418** [r0oth3x49/udemy-dl#84]
Downloading stucks in between every time i download course. Please check everything else works(internet) but downloading gets stuck. Is there any work around to again get started.

PS:
I have found a work around if download gets stuck in between.(But before doing this work around please be sure check during downloading which file it got stuck. Delete that file dont worry it will get downloaded after applying below steps)
1)Open another cmd window.
2)Run same command with same destination do not change anything.

It will skip files which were already downloaded and start from where it left.

**Comment by r0oth3x49** [comment]
@rsa2418 how can i reproduce this error,  if i can't, i will not be able to add a fix. BTW never faced this problem.

**Comment by rsa2418** [comment]
i have figured out a way for this issue

**Comment by Wayne-Mather** [comment]
@rsa2418 This sounds more like an OS/Hardware issue. Can you supply details about:

Operating System & Version?
Hardware information about where the files are being saved?

I must note that some courses use filenames that go beyond the NTFS limit if you are on a Windows platform and downloads can fail or have issues when the underlying filesystem does not like that filename or directory hierarchy.
