### ISSUE TITLE
"You are not enrolled in this course..."

### ISSUE THREAD

**Issue by Drovosek01** [r0oth3x49/udemy-dl#86]
![image](https://user-images.githubusercontent.com/29478700/35455262-4a9c88ee-02e2-11e8-87c1-67cce1ee6e82.png)
Often appear the error message, as if I am not enrolled in the course, but I signed up for the course. You have to repeatedly activate the same command line. To download starts with or 3 times. This does not always happen.

**Comment by r0oth3x49** [comment]
@Drovosek01 you should clone the recent version and also have a look at issue [#63](https://github.com/r0oth3x49/udemy-dl/issues/63). 

i m closing this with duplicate as i have already discussed this in above issue.
