### ISSUE TITLE
No module named unidecode

### ISSUE THREAD

**Issue by itsroby** [r0oth3x49/udemy-dl#88]
I found error when trial on my server, server configuration as bellow : 

![udemy-dl-7](https://user-images.githubusercontent.com/31939641/35605697-09a3dde4-067d-11e8-8786-6e54bcf6ce3d.png)

Error message "No module named unidecode"

![udemy-dl-4](https://user-images.githubusercontent.com/31939641/35605667-cef5ee94-067c-11e8-945a-bdc1a2172194.png)

To solve this problem we have to install the unidecode module `pip install unidecode`

Running smoothly :smiley: 
![udemy-dl-6](https://user-images.githubusercontent.com/31939641/35605778-96827cf2-067d-11e8-8570-e5e29c5eca9b.png)

Please add `unidecode` on requirements.txt for next modification.
Thanks

**Comment by r0oth3x49** [comment]
@itsroby updated `requirements.txt`

**Comment by UsernameOfUtkarsh** [comment]
@itsroby Found the simplest solution. Just copy the "unicode" folder to the repo folder. Solved for me.
