### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory:

### ISSUE THREAD

**Issue by avadnc** [r0oth3x49/udemy-dl#93]
PS G:\udemy-dl-master> python .\udemy-dl.py -u in*******@gmail.com -p ********** https://www.udemy.com/creando-restful-services-php-mysql -r 720

              __                               ____
   __  ______/ /__  ____ ___  __  __      ____/ / /
  / / / / __  / _ \/ __ `__ \/ / / /_____/ __  / /
 / /_/ / /_/ /  __/ / / / / / /_/ /_____/ /_/ / /
 \__,_/\__,_/\___/_/ /_/ /_/\__, /      \__,_/_/
                           /____/
                                 Version : 0.3
                                 Author  : Nasir khan(r0ot h3x49)
                                 Visit   : https://github.com/r0oth3x49

[*] : Downloading webpage..
[*] : Extracting course information..
[*] : Downloading 'creando restful services php mysql'.
[*] : Trying to login as (in*******@gmail.com)...
[+] : Logged in successfully.
[*] : Downloading course information webpages ..
[*] : Found (32) lectures ...
[*] : Extracting (32/32) |========================================| 100.00%
[*] : Downloaded course information webpages successfully..
[*] : Trying to logout now...
[+] : Logged out successfully.
[*] : Counting no of chapters..
[+] : Found ('6') chapter(s).

[*] : Downloading chapter : (1 of 6)
[+] : Chapter (01 Empezar aqu )
[+] : Found ('3') lecture(s).

[*] : Downloading lecture : (1 of 3)
[*] : Downloading (001 Introducci n al curso)
Traceback (most recent call last):
  File ".\udemy-dl.py", line 924, in <module>
    main()
  File ".\udemy-dl.py", line 879, in main
    udemy.ExtractAndDownload(quality=res)
  File ".\udemy-dl.py", line 409, in ExtractAndDownload
    msg = self.Downloader(_url, lecture_name, chapter_path)
  File ".\udemy-dl.py", line 89, in Downloader
    out = course_dl.download(url, title, filepath=path, quiet=True, callback=self.Download)
  File "G:\udemy-dl-master\udemy\_downloader.py", line 101, in download
    outfh = open(temp_filepath, fmode)
FileNotFoundError: [Errno 2] No such file or directory: 'G:\\udemy-dl-master\\creando-restful-services-php-mysql\\01 Empezar aqu \\001 Introducci n al curso.mp4.part'

**Comment by r0oth3x49** [comment]
@avadnc have a look at  issue [#32](https://github.com/r0oth3x49/udemy-dl/issues/32)
