### ISSUE TITLE
variable resolution and output, not working

### ISSUE THREAD

**Issue by adfenor** [r0oth3x49/udemy-dl#94]
Hi, it does not work when I insert the resolution or output variable.
It only works if I put my username and password. But the above does not. what's going on?

Inside configuration Nº 1 [Not working]
	
	{
		"username" 		: "myuser@gmail.com",
		"password" 		: "p4ssw0rd",
		"output" 		: "path/to/directory/",
		"resolution" 		: "1080"
	}

Output on terminal:
```

[*] : Loading configs.. (done)
[-] : Username, Password and course url is required..
```
Inside configuration Nº 2 [Working]
```
	{
		"username" 		: "myuser@gmail.com",
		"password" 		: "p4ssw0rd"
	}
```
output on terminal:
```
[*] : Loading configs.. (done)
[*] : Downloading webpage..
[*] : Extracting course information..

```

**Comment by r0oth3x49** [comment]
@adfenor thanks for your report i will try to reproduce & fix it ASAP. thanks for using this utility
