### ISSUE TITLE
Aria2c cant download.

### ISSUE THREAD

**Issue by RuthlessRuler** [r0oth3x49/udemy-dl#96]
I tried downloading the course from the saved links with captions using Arai2c but it wasn't able to download. 
If possible please tell me which downloader supports this type of files. 

Also, would it possible to directly save all of these files in google drive in proper folder manner.(cause i get higher down speed bcoz of peering through which i am able to download at 900 kbps and only 125 kbps normally). please help me if possible cause i am new to all this. 

Thanks for your time in advance.

**Comment by r0oth3x49** [comment]
@RuthlessRuler i have never used aria2c downloader against save links. you can use IDM for that simply give a text file to idm it will download all the links.

with this script this is not possible to download directly to google drive. it will only download the course into your local system in folder manner & about getting higher speed of downloading the script uses the maximum downloading speed available.
