### ISSUE TITLE
Downt Downloads the Content Sometimes

### ISSUE THREAD

**Issue by RuthlessRuler** [r0oth3x49/udemy-dl#97]
Sometimes it give sthe error: Udemy Says : Resource not found. either you are not enrolled in course or server didn't respond with course information webpages. but after trying again with same command it starts downloading. (In this 3rd time).  FYI- i have changed my id, password and username

C:\Users\USERANME\Downloads\udemy-dl-master>python udemy-dl.py -u EMAIL@mail.com -p password https://www.udemy.com/learn-c-plus-plus-from-beginner-to-advanced/learn/v4/overview -r 480

[*] : Downloading webpage..
[*] : Extracting course information..
[*] : Downloading 'learn c plus plus from beginner to advanced'.
[*] : Trying to login as (EMAIL@mail.com)...
[+] : Logged in successfully.
[*] : Downloading course information webpages ..
[-] : Udemy Says : Resource not found. either you are not enrolled in course or server didn't respond with course information webpages.
[*] : Re-run udemy-dl against full course url (e.g :- https://www.udemy.com/course/learn/v4/overview)
[*] : Trying to logout now...
[+] : Logged out successfully.

C:\Users\USERANME\Downloads\udemy-dl-master>python udemy-dl.py -u EMAIL@mail.com -p password https://www.udemy.com/learn-c-plus-plus-from-beginner-to-advanced/learn/v4/overview -r 480

[*] : Downloading webpage..
[*] : Extracting course information..
[*] : Downloading 'learn c plus plus from beginner to advanced'.
[*] : Trying to login as (EMAIL@mail.com)...
[+] : Logged in successfully.
[*] : Downloading course information webpages ..
[-] : Udemy Says : Resource not found. either you are not enrolled in course or server didn't respond with course information webpages.
[*] : Re-run udemy-dl against full course url (e.g :- https://www.udemy.com/course/learn/v4/overview)
[*] : Trying to logout now...
[+] : Logged out successfully.

C:\Users\USERANME\Downloads\udemy-dl-master>python udemy-dl.py -u EMAIL@mail.com -p password https://www.udemy.com/learn-c-plus-plus-from-beginner-to-advanced/learn/v4/overview -r 480

[*] : Downloading webpage..
[*] : Extracting course information..
[*] : Downloading 'learn c plus plus from beginner to advanced'.
[*] : Trying to login as (EMAIL@mail.com)...
[+] : Logged in successfully.
[*] : Downloading course information webpages ..
[*] : Found (76) lectures ...
[*] : Extracting (76/76) |========================================| 100.00%
[*] : Downloaded course information webpages successfully..
[*] : Trying to logout now...
[+] : Logged out successfully.
[*] : Counting no of chapters..
[+] : Found ('19') chapter(s).

**Comment by r0oth3x49** [comment]
@RuthlessRuler this is not the problem but a simple handle to to server response. see issue #63 , i already have discussed this in details there so i 'm closing the issue.
