### ISSUE TITLE
bug when trying to download

### ISSUE THREAD

**Issue by thesalah1212** [r0oth3x49/udemy-dl#98]
Traceback (most recent call last):
  File "udemy-dl.py", line 924, in <module>
    main()
  File "udemy-dl.py", line 879, in main
    udemy.ExtractAndDownload(quality=res)
  File "udemy-dl.py", line 291, in ExtractAndDownload
    self.login()
  File "udemy-dl.py", line 40, in login
    extract_info.login(self.username, self.password)
  File "/home/thesalah1212/udemy-dl-master/udemy/_extractor.py", line 147, in login
    login_form      = self._fill_login_form(login_popup, username, password)
  File "/home/thesalah1212/udemy-dl-master/udemy/_extractor.py", line 98, in _fill_login_form
    login_form = self._form_hidden_inputs('login-form', webpage)
  File "/home/thesalah1212/udemy-dl-master/udemy/_extractor.py", line 88, in _form_hidden_inputs
    return _hidden_inputs(form)
  File "/home/thesalah1212/udemy-dl-master/udemy/_utils.py", line 80, in _hidden_inputs
    html = re.sub(r'', '', html)
  File "/usr/lib/python3.5/re.py", line 182, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
thesalah1212@thesalah1212-pc:~/udemy-dl-master$

**Comment by ejose19** [comment]
I'm also getting this, upon inspecting the source code I found udemy is detecting this tool as automation, any way to hide this?

**Comment by YaNgO15** [comment]
Ami also I get that error, and I started thinking that maybe we should update the python ?, I would like you to answer r0oth3x49

**Comment by coder797** [comment]
yup same here .. time to update the tool

**Comment by r0oth3x49** [comment]
@thesalah1212 the error is causing with python3 only will fix it ASAP. with python2 it works fine for me.
have a look.
![untitled](https://user-images.githubusercontent.com/11024397/36087724-a82f418e-0ff5-11e8-9259-fd6a23cf1a73.png)

**Comment by gangadharparde** [comment]
![error](https://user-images.githubusercontent.com/7418840/36088232-4366d7d8-0ffc-11e8-9f52-fa2c528cfec5.PNG)

**Comment by gangadharparde** [comment]
![error](https://user-images.githubusercontent.com/7418840/36088263-711fad08-0ffc-11e8-8167-b1b86a40bb5f.PNG)

**Comment by gangadharparde** [comment]
Need solution for this error

**Comment by r0oth3x49** [comment]
@ gangadharparde which python version are you using?

**Comment by r0oth3x49** [comment]
@thesalah1212 @ejose19 @YaNgO15 @coder797 
here is a simple workaround for both python version (py2 & py3)

- upgrade all the packages
- install requests[security]

then try to download and let me know if still the error occurs.

i have done the above steps and tested against py2 & py3 both, for me works fine now.
python3
![py3](https://user-images.githubusercontent.com/11024397/36089053-c565d848-0ffb-11e8-8bc7-1833d74ccf76.PNG)
python2
![py2](https://user-images.githubusercontent.com/11024397/36089061-ce8f195c-0ffb-11e8-978f-6464bd23c9d3.PNG)

**Comment by yashjit** [comment]
From cffi callback <function _verify_callback at 0x1083d7d70>:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/OpenSSL/SSL.py", line 313, in wrapper
    _lib.X509_up_ref(x509)
AttributeError: 'module' object has no attribute 'X509_up_ref'
[-] : Connection error : make sure your internet connection is working.

**Comment by igizm0** [comment]
Python 3.6.4
macOS High Sierra 10.13.3
Last version not work.

**Comment by gangadharparde** [comment]
@r0oth3x49: 
Python3.6 
32 bit Windows 7

**Comment by jaan143** [comment]
i have a question 
is it download pdf and all other project files of course ?

**Comment by ejose19** [comment]
I still get the error after downloading the new version and upgrading the packages.

**Comment by r0oth3x49** [comment]
@gangadharparde you should check this issue #56

**Comment by DazzaB73** [comment]
I have tried python 2.712, 2.714, v3.5.2, v3.6.4 - all as fresh installs and downloading all the requirements and ensuring they are all up-to-date and I am using the latest version of udemy-dl.   I am still getting the error mentioned by thesalah1212 at the start of this post.

**Comment by thesalah1212** [comment]
I still get the error after updating the packages

**Comment by thesalah1212** [comment]
@DazzaB73  it works fine after doing this command `pip install requests[security]`

**Comment by yashjit** [comment]
Resolve after uninstall openssl pyhton package and reinstall it.

**Comment by abravodeb** [comment]
pip install pyOpenSSL, its works! I'm using python3.6.2

**Comment by seanwhe** [comment]
I can confirm that on Ubuntu Linux 16.04 installation of pyOpenSSL works.

# pip install pyOpenSSL
